RetroPie/RetroPie-Setup

scriptmodules/libretrocores/lr-nestopia.sh

Nestopia doesn't need an external `NstDatabase.xml` file anymore, it's been added to the core source file in [this commit](https://github.com/libretro/nestopia/commit/354fa2f0f3bb9884988b05a6bc0e60dae961bec4).

nestopia: remove the board database file from the package installation

---

scriptmodules/supplementary/skyscraper.sh

Rename the `$md_conf_dir` variable, `md_` names are reserved for built-in module/helpers variables.

skyscraper: don't use predefined variable names for the config dir

---

scriptmodules/packages.sh

Small spelling error - should be `md_id`. Noticed it during source installs, because the `build` phase tries to write the `.pkg` info file without the install folder being present.

packages: fix spelling error

---

scriptmodules/admin/stats/pkgflags/app.js

After https://github.com/RetroPie/RetroPie-Setup/pull/3000, the logic for calculating the Video category for a package has changed with the introduction of the `!all` flag. The modification updates the `pkgflags` page to better match a package to the corresponding video section (Mali/DRM&KMD/VideoCore/X11).
I also added a title (which should be visible as a tool tip on a desktop browser) on each package row entry to show the script flags, just to make it easier to spot errors.

stats: modify the pkgflags stats logic after the flags reorganization

---

scriptmodules/helpers.sh
scriptmodules/packages.sh
scriptmodules/supplementary/sdl1.sh
scriptmodules/supplementary/sdl2.sh

* create a rp_getBinaryUrl function to get the binary url of a package
* if a module has a __binary_url and it returns an empty string, treat this as no binary available - this allows removing hardcoded logic for sdl1/sdl2 from getDepends
* if a module doesn't have this function but it has its own install_bin don't test for a binary and assume it's ok

sdl1 / sdl2 - add __binary_url functions and rework packaging logic

---

scriptmodules/libretrocores/lr-hatari.sh
scriptmodules/libretrocores/lr-hatari/01_libcapsimage.diff

(reported in https://retropie.org.uk/forum/topic/25181/) `lr-hatari` fails building with a linker error on gcc 7.x, due to not finding the `capsimage` functions.
Re-arranged the linking order so `libcapsimage.so.5` is picked up last and removed an extra include in the module `.diff`.

lr-hatari: fix linkage on Ubuntu 18.04 & friends (gcc7)

---

scriptmodules/supplementary/splashscreen.sh
scriptmodules/supplementary/splashscreen/asplashscreen.sh

This prevents resetting of the configuration when upgrading, since now the user configuration is kept in the scriptmodule itself.
Has been reported a few times in the forum - just didn't get around to fix it.
EDIT: Besides the randomization option, the splashscreen duration is now configurable (default: 12 sec, min: 10 sec, max 100 sec).

splashscreen: add a configuration file for user settings

---

scriptmodules/supplementary/splashscreen.sh

Without it, the service would not be properly configured unless the user has chosen one of the _raondomize_ options from the configuration screen.

splashscreen: create user config on install/upgrade

---

scriptmodules/admin/setup.sh
scriptmodules/packages.sh
scriptmodules/supplementary/golang.sh
scriptmodules/supplementary/mesa-drm.sh
scriptmodules/supplementary/omxiv.sh
scriptmodules/supplementary/sdl1.sh
scriptmodules/supplementary/sdl2.sh

setup - show install origin in manage package sections for overview
* useful to get an overview - used bold markup but shows as grey from framebuffer - but is easier to read when differently styled imho
Wanted to get an opinion on this before I commit.
Also added a dependency section to setup also as now packages remember how they were installed it is useful to be able to switch between binary / source.

Packaging / setup tweaks

---

scriptmodules/ports/solarus.sh

* added missing libglm-dev dependency
* make sure libraspberrypi-dev is installed in videocore platform
* added switch to disable debugging Lua console
* added preloading of legacy videocore GLES2 drivers (if necessary)
* use exec to run the binary in the wrapper shell script
I saw the second point done in other scriptmodules so decided to play safe here too.
As discussed, this method does not require any changes to SDL2 :)
Tested on RPI3B with Stretch and Buster + Legacy Drivers.

solarus - fix segfault on exit with videocore and other updates

---

scriptmodules/supplementary/runcommand.sh
scriptmodules/supplementary/runcommand/joy2key.py
scriptmodules/system.sh

* Ubuntu 20.04 will no longer include python-pyudev
* Use stderr for /dev/tty opening error msg
* Use python3 in runcommand module for compilation
* Open with 'append' which was added in f614804 fails with python3 on rpi4 console. Use lower level os.open and O_WRONLY to avoid possible buffer issues. Could not reproduce the ghost inputs the append was added for

joy2key - convert to python3 and use python3-pyudev dependency

---

scriptmodules/libretrocores/lr-mupen64plus-next.sh

* fixed upstream in https://github.com/libretro/mupen64plus-libretro-nx/commit/d32dea1
* removed unneeded dependencies (tested building without them)
* minor cosmetic tweaks
Tested this on RPI3B with Buster + Legacy Drivers. Does not affect other platforms.
Marked as *Draft* until branch `v2.0.5-RC1` upstream (containing the fix) gets merged into `develop`.
I wanted to leave this PR prepared and just wait for upstream to update.

lr-mupen64plus-next - revert workaround for crash in videocore platform

---

scriptmodules/ports/love-0.10.2.sh
scriptmodules/ports/love.sh

* updated the license, since it's actually ZLIB and not GPL(3).
* the project has moved the source and development to Github (see https://love2d.org/wiki/Building_L%C3%96VE). 
* adjusted the dependencies to remove `mercurial` (since we're using `git` to download the sources) and `devil`, not used since [2014](https://github.com/love2d/love/commit/eca8c17a693e85635b043353e431dcb9d5012e75).
* updated the included Mari0 game to 1.6.2, compatible with the 11.2.

love: updated license and download links, updated 'mari0' game

---

scriptmodules/emulators/dosbox.sh

2 very small changes to improve a bit the Dosbox experience.
* larger C drive is required to install games like Fallout, M.A.X, KKND, etc. I went with 1GB to be absolutely sure but 768GB should be fine too.
* relying on the elegant method described [in the doc](http://dosonthepi.blogspot.com/2015/02/dosbox-configuration-for-individual.html) - which has you populate the **[autoexec]** section at the bottom of the .conf file (one .conf file = one game) - works great with Retropie. This allows for a single extension type (.conf) to be registered. Yet Dosbox default config file is also called anytime and along the user's own config file for the game. This comes with side effects like Mount points declared twice, sound card parameters mess and even preventing games to run. I've fixed that …

dosbox - allows for larger C drive

---

scriptmodules/emulators/retroarch.sh

* `video_smooth` defaults to `false` since RetroArch 1.8.5
Ref: https://github.com/libretro/RetroArch/pull/9710

retroarch - setting `video_smooth` is no longer necessary

---

scriptmodules/supplementary/skyscraper.sh

I've updated the skyscraper.sh script to use the `--flags FLAG1,FLAG2` format. I've also added version checks for at least 3.5 to the gathering and generating functions that will display a message in case the user needs to update. Lastly I've updated all the places where the old flags were mentioned in the help texts so they now show the new `--flags` versions.

Updates the script to conform with the new '--flags FLAG1,FLAG2' flags

---

scriptmodules/system.sh

Noticed some messages right after calling retropie_setup.sh and before the dialog:
```
/home/meleu/RetroPie-Setup/scriptmodules/system.sh: linha 49: "8078788" / 1024 : erro de sintaxe: operando esperado (token com erro é ""8078788" / 1024 ")
```
It happens because the bash version on the computer I'm running it is 4.3, and it doesn't accept quotes inside the arithmetic expansion `$((...))` (it was [fixed in bash-4.4](http://git.savannah.gnu.org/cgit/bash.git/tree/CHANGES?h=bash-4.4-testing#n3433))
For consistency, I also removed the `$` prefix for variables inside the arithmetic expansion (same style used on line 56).

system.sh: arithmetic expansion smallfix

---

scriptmodules/emulators/mupen64plus.sh

Currently we're getting slowdowns on mupen64plus-GLideN64 with default settings. See https://retropie.org.uk/forum/topic/25112/getting-the-best-n64-experience-on-a-pi-4/44

N64: Disabled hybrid upscaling filter (causes slowdown on RPI4)

---

scriptmodules/supplementary/customhidsony.sh
scriptmodules/supplementary/customhidsony/0001-hidsony-gasiafix.diff
scriptmodules/supplementary/sixaxis.sh

Mark "libbluetooth3" for installation in sixaxis module (with service stack reload if necessary).
Just a thought, but perhaps we could consider adding "sixaxis" to the default package list for image builds? The package shouldn't really cause any issues for users that will never use a DualShock, and the messy third-party driver is split off (and not installed by default until the user selects via the gui option of the driver).
I would also like to rip out the "custombluez" module completely, but perhaps we can leave that until stretch support is fully dropped.

Sixaxis fixes for bare installation

---

scriptmodules/libretrocores/lr-mesen.sh

Runs ok on the PI4, but is too slow for a stock Pi 3B. I enabled it for the `xu4` , I don't think it would run well on a Tinkboard.
The upstream maintains the libretro port and is quite active.

add lr-mesen: Mesen NES/Famicom emulator, libretro core

---

scriptmodules/ports/solarus.sh

* when not in videocore, the script fails due to missing "false" case
Shameful bug from my previous PR :disappointed:
Tested by a user running RetroPie on RPI4.

solarus - fix missing "false" case in wrapper script

---

platforms.cfg
scriptmodules/libretrocores/lr-theodore.sh

Adds support for Thomson MO/TO, a line of 8bit computers produced during 1982 and 1989 (TO7, TO7/70, TO8, TO8D, TO9, TO9+, MO5, MO6) and used mainly in France.
The Libretro [core](https://docs.libretro.com/library/theodore/) is based on the [DCMOTO](http://dcmoto.free.fr/) emulator. 
The system has a medium library of games and application/educational software - 515 entries on [ScreenScraper](https://screenscraper.fr/gamesinfos.php?plateforme=141&alpha=0&numpage=0), more in the associated Libretro DB.

added theodore: libretro core for Thomson MO/TO emulation

---

scriptmodules/libretrocores/lr-bsnes.sh

Updated `lr-bsnes` to the latest BSNES version.
The libretro fork of the current/latest version has a different repo, the previous `bsnes` core fork has been renamed to `bsnes2014` [^1][^2] and hasn't been updated since last year.
The (new) [BSNES](https://github.com/bsnes-emu/bsnes) seems to work reasonably well on the Pi4. It requires a C++17 compiler, this means at least GCC 7 (no Raspbian/Debian Stretch).
[1] - BSNES2014 https://github.com/libretro/bsnes-libretro/commit/feb8c10c672094e689ed057a278c2b354e113f32
[2] https://forums.libretro.com/t/deprecate-the-bsnes-higan-snes-forks/24732/3.

lr-bsnes: update to the current BSNES version of the libretro fork

---

scriptmodules/libretrocores/lr-mame2010.sh

Should address https://github.com/libretro/mame2010-libretro/issues/130
and be a (hopefully working) alternative to
https://github.com/RetroPie/RetroPie-Setup/pull/2773

Add rpi platform to lr-mame2010

---

scriptmodules/libretrocores/lr-theodore.sh

Fixes the repository source, replacing the libretro fork with the [upstream repo](https://github.com/Zlika/theodore).
Seems like the libretro fork is used only for PR submitted upstream, the buildbot uses the same upstream repository (https://retropie.org.uk/forum/topic/3049/thomson-computers-emulator/29).

lr-theodore: switch to upstream repository

---

scriptmodules/supplementary/audiosettings.sh

Modified to support the 2nd HDMI port on the Pi4 and for supporting the new upstream defaults, which use discrete ALSA cards. Handle the case when on-board audio is disabled.
On-board audio support is enabled via the `snd_bcm2835` module. Depending on the `enable_compat_alsa` parameter value (0/1), loading the module creates 1 or ~~3~~ 2/3 sound devices. 
The default so far has been `enable_compat_alsa=1`, but this will change in the new 5.4 LTS kernel (see https://github.com/raspberrypi/firmware/commit/7449540e3787cc14e9ee7f63690d6569943bce26 and the discussion in the [RPF Forums](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=269769&start=200#p1659490)). `raspi-config` already handles this since [January](https://github.com/RPi-Distro/raspi-config/commit/629699ff9b2e73c92bafe452 …

audiosettings: updates for Pi4 and support for discrete internal ALSA devices

---

scriptmodules/supplementary/usbromservice.sh

Mounting ext3/ext4 and other native filesystems was broken due to having uid=X,gid=X in the default mount options.
Now we just set these options on a per filesystem basis via FS_MOUNTOPTIONS
This is not yet tested.

usbromservice - fix mounting ext3/ext4 partitions

---

scriptmodules/admin/image.sh

Latest Buster Raspberry Pi OS image has changed location. Previous URL returns older (Feb 2020) release.

image: update the URL for latest Buster image

---

scriptmodules/emulators/retroarch.sh
scriptmodules/emulators/retroarch/01_hotkey_hack.diff
scriptmodules/emulators/retroarch/02_disable_search.diff
scriptmodules/emulators/retroarch/03_shader_path_config_enable.diff

Rebased RetroPie patched for 1.8.8 and added - for now - the option to keep the global core options in a single file.
NOTE: tested on Pi4 only at the moment.

retroarch: version 1.8.8 update

---

platforms.cfg

As documented on the wiki, .mdf is a valid extension for the Saturn emulators. Tested that the change allows loading these files on my local installation.

Add .mdf to Saturn extensions

---

scriptmodules/libretrocores/lr-np2kai.sh

Looks like upstream renamed the build folder (`sdl2` renamed to `sdl`), so the build instructions have been updated. 
Similar upstream change at https://github.com/libretro/libretro-super/commit/0c7dde6c4d3ffff3fe1fcb5af5a9813319254a67.

lr-np2kai: update build instructions

---

scriptmodules/supplementary/runcommand/runcommand.sh

The mode id is a hex, so it can contain (multiple) `[a-f]` apart from `[0-9]`.
Reported in the forums a couple of times ([here](https://retropie.org.uk/forum/topic/26683/) and [here](https://retropie.org.uk/forum/topic/26362/)). 
`xrandr` code for printing the mode id looks to be [here](https://gitlab.freedesktop.org/xorg/app/xrandr/-/blob/master/xrandr.c#L618).

runcommand: improve 'xrandr' output parsing for mode id

---

platforms.cfg
scriptmodules/emulators/mame.sh

See https://retropie.org.uk/forum/topic/19303/installation-of-mamedev-mame/81 for full conversation/history of script development.
This pull request is for a scriptmodule that will compile and install the latest MAMEdev version of MAME. It has been tested with the latest RetroPie on Raspberry Pi 3, Intel based Ubuntu systems, as well as cross-compiling for RPi3 on an Intel based machine. It has also been tested on a Raspberry Pi 0, but due to slow performance (on compiling and execution), it is removed via the rp_module_flags.
Big thanks to @cmitu and @joolswills for their help and guidance during the development of this scriptmodule.

MAMEdev MAME installation script

---

scriptmodules/libretrocores/lr-gearsystem.sh
scriptmodules/libretrocores/lr-smsplus-gx.sh

SMSPlus-GX and Gearsystem are Sega 8 bit emulator cores, with better compatibility for Master System games than existing cores in RetroPie.
Both have been tested on a RPi3B+.

add lr-smsplus-gx and lr-gearsystem

---

scriptmodules/ports/cgenius.sh

2.3.6 had a bug where the controller configuration menu wouldn't show up, the latest fixes this and other bugs:
https://github.com/gerstrong/Commander-Genius/blob/master/changelog.txt

Update cgenius  from 2.3.6 to 2.4.4.1

---

scriptmodules/supplementary/bluetooth.sh
scriptmodules/supplementary/bluetooth/connect.sh

bluetooth - use bt-device from bluez-tools over old python code
* added bluez-tools dependency
* use bt-device for Trusting / Connecting / Removing of devices
bluetooth - split out boot bluetooth connect script from main code
* running RetroPie-Setup on boot isn't efficient / it should work without RetroPie-Setup present.
* running it as root on boot causes /opt/retropie/configs/all to be chowned to root due to setupDirectories call
@psyke83 
This needs some testing - but works ok here. I did touch a bit of the Playstation pairing code with the first commit - perhaps I should have split out the second commit - I can do that if there's issues
the code relating to the platstation code was the following
```diff
-       $(get_script_bluetooth bluez-test-device) disconnect "$mac_address" 2>&1 …
```

Bluetooth updates

---

scriptmodules/ports/gemrb.sh

* updated the dependency list to include the Vorbis and VLC libraries.
* choose explicitly the SDL1 backend at build time.
* added the `dispmanx` flag to enable proper scaling on FKMS (Pi4) platforms (untested though).
* explicitly depend on `python2-dev` since python3 port is not complete.

gemrb: update to latest stable version and refresh deps

---

scriptmodules/helpers.sh
scriptmodules/system.sh

I am building an image based on RPi 0/1 4.5.1 utilizing systemd-nspawn.  The existing logic to determine chroot environments doesn't seem to hold true when utilizing systemd-nspawn container instead of the traditional chroot command.
I also ran into an issue when updating/compiling the xpad kernel driver.  I believe there is no reason to modprobe the kernel driver in a chroot environment.

Fix systemd-nspawn detection

---

scriptmodules/ports/gemrb.sh

GemRB supports both SDL1 and SDL2 for graphic rendering, SDL2 being now the preferred one.
This commit adds a `-sdl2` version for `gemrb` that builds the port with SDL2 and modifies the original scriptmodule so we can build both versions using the same functions.

gemrb: switch to SDL2 for rendering

---

scriptmodules/supplementary/attractmode.sh

Added 'attractmode' for the 'kms' platform, since it now includes support for DRM/KMS.
The 'sfml-pi' branch on https://github.com/mickelson/sfml-pi/ can be built with OpenGL or GLES support, by default it uses OpenGL.
~~Because the 'drmSetMaster'/'drmDropMaster' calls need 'root' privileges, a separate setuid helper is installed, which runs these privileged calls. It's needed by AttractMode to background itself when launching a game/emulator.~~
Added 2 corrections:
- don't remove an empty system name (can happen when `delEmulator` is used for a Port)
- really replace `/` in the system's full name (when adding/deleting a system)
When using KMS, `attractmode` starts with 'preferred' video mode, as reported by the display's EDID. This could be different than the current video mode set via …

attractmode: enable for KMS/DRM

---

scriptmodules/libretrocores/lr-prboom.sh
scriptmodules/ports/lzdoom.sh

* This was announced as the final lzdoom release to support GL2 rendering.
* Update Freedoom to v0.12.1 with checksum check to update older versions.
---
Tested on RPI4.

lzdoom: update to 3.86a

---

scriptmodules/emulators/ti99sim.sh

Updated the emulator to the latest version, which is using SDL2, so `dispmanx` is not necessary mandatory.
Modified the installation to include some utilities (might be useful for disc/cartridge manipulation) and to include the docs and license.

ti99sim: update to version 0.16.0, switch to SDL2

---

scriptmodules/emulators/reicast.sh

I did a quick test and the reicast-joyconfig seemed to work with python3. A deprecated warning but I only did a quick test.
We may need to revisit using the other upstream branch - but last I checked some of the code paths were not wired in. But something to look into.

reicast - use python3 for reicast-joyconfig

---

scriptmodules/libretrocores/lr-nestopia.sh

The `NstDatabase.xml` is not bundled anymore, it's built-in and it's not part of the binary install since 372c7cf7f1.

nestopia: don't try to copy the NstDatabase.xml on configuration.

---

scriptmodules/supplementary/runcommand/runcommand.sh

Before setting the SDL2 env variables that configure the modesetting for DRM/KMS, validate the CrtcId/ModeId tuple against the current list reported by `modetest`. Changes in the kernel DRM driver could make the existing modesetting configuration (stored in `videomodes.cfg`) invalid because of different CrtcId and/or ModeId in new versions of the driver.

runcommand: validate the CrtcId/ModeId values for SDL2 env vars

---

scriptmodules/emulators/gpsp.sh
scriptmodules/libretrocores/lr-gpsp.sh

lr-gpsp:
cpu_threaded.c built with -O2 on gcc 8 produces a non working binary. This source already had
a different optimisation level from the rest of the code (O2 vs O3). However, on gcc-8 it causes
a non working binary when built with anything other than O0, but this could have some performance
issues (would need testing on a rpi1).
I compared all the different optimisation flags enabled by O1 and also with any changes from gcc-6,
but not all GCC optimisations are controllable from flags. It was not possible to produce a working
binary with O1 - even disabling all the configurable optimisations enabled by O1.
The issue is most likely undefined behaviour in this file (which has a lot of large macros), and it
probably needs some fixes. However it could be a bug in the gcc-8 optimiser …

gpsp / lr-gpsp - use gcc-6 to workaround segfault with gcc-8 on buster

---

scriptmodules/libretrocores/lr-flycast.sh
scriptmodules/libretrocores/lr-flycast/01_flags_fix.diff

* makefile patch is still needed for our compiler flags
* CPU_FLAGS isn't used so not sure what happened here - mistake or I missed out something.
* use CXXFLAGS for the additional videocore flags, to override makefile logic
* re-add make clean

lr-flycast - restore makefile patch and fix logic

---

scriptmodules/emulators/sdltrs.sh

Switched SDLTRS to be built from https://gitlab.com/jengun/sdltrs, which is an active fork of the original SDLTRS emulator.
* use the SDL2 branch, which should be more portable (KMS/Odroid/etc.)
* set a minimum of configuration dir in the default configuration file ($HOME/.sdltrs.t8c)
* although not explicitely specified, the main license seems to be BSD-2-Clause (https://opensource.org/licenses/BSD-2-Clause)

sdltrs: switch to an active fork, build with SDL2

---

scriptmodules/emulators/uae4arm/uae4arm.sh

* use "--config " instead of "-config=" and "--autoload "
* may adjust this further and split out amiberry launch to its own code rather than sharing the uae4arm launch code

amiberry - adjust amiberry launch script for argument changes

---

scriptmodules/supplementary/runcommand/runcommand.sh
scriptmodules/supplementary/sdl1.sh

Added sdl1 patch to allow overriding of graphics_get_display_size as it returns 0 on fkms for width and height,
which skips the scaling code and ability to adjust aspect ratio.
New ENV vars are SDL_DISPMANX_WIDTH and SDL_DISPMANX_HEIGHT which we now set manually in runcommand on fkms
when a dispmanx backend is used with sdl1.
This should resolve aspect ratio issues rpi4 users were having with some sdl1 emulators that worked with the dispmanx
backend, but always stretched to fill the entire screen.
This also enables the use of SDL_DISPMANX_RATIO to tweak the ratio when scaling - from 0.2 to 6 - currently
unused in any RetroPie modules by default, but used to be used for tweaking the vice scaling, to more accurately
produce a correct aspect ratio for the C64. But can be used by users …

runcommand - fix aspect ratio using dispmanx backend with sdl1 on fkms

---

scriptmodules/emulators/ti99sim-sdl1.sh
scriptmodules/emulators/ti99sim.sh

Added back the `dispmanx` flag for the - older - SDL1 version.
Uses the[0.15.0](https://www.mrousseau.org/programs/ti99sim/archives/ti99sim-0.15.0.src.tar.xz) version when compiled with SDL1, which needs to be copied to the RetroPie archive web server.

ti99sim: use an older version for Debian Stretch

---

scriptmodules/system.sh

* by user request - not officially supported

system - added recognition for Jetson Nano and Tegra X1

---

scriptmodules/libretrocores/lr-mupen64plus-next.sh

Parity with the defaults for mupen64plus-GLideN64 standalone.

Default Core Options for lr-mupen64plus-next

---

scriptmodules/emulators/xroar.sh

The changes in 25d6710f9275e49 lead to a crash when the emulator starts in fulscreen,
when using the RPI driver in SDL2. Looks like repeated calls to create/destroy the SDL renderer,
when resizing the window, lead to a VC driver error:
failed to add service - already in use?
The RPI driver already starts the window in fulscreen, so there's no visible difference without the parameter removed.

xroar: add a workaround for the crash on VC platforms

---

README.md

Update the `README` to be in-sync with the official documentation from RaspberryPi [1]
> Raspberry Pi OS (previously called Raspbian) is the Foundation’s official supported operating system.
[1] https://www.raspberrypi.org/downloads/raspberry-pi-os/

Replace Raspbian with Raspberry Pi OS

---

scriptmodules/emulators/mame.sh

Should fix the situation when there is not default 'python', but python3
is installed, like default installation of Ubuntu 20.04 LTS.
Fixes #3228.

mame: use python3 to build, when available

---

scriptmodules/admin/builder.sh
scriptmodules/helpers.sh
scriptmodules/packages.sh
scriptmodules/supplementary/sdl1.sh
scriptmodules/supplementary/sdl2.sh
scriptmodules/system.sh

* default signing key can be overridden with __gpg_signing_key
* added gpg dependency by default
* download retropie key from ubuntu keyserver if it doesn't exist in keyring
* added download helper function
* rework logic for rp_installBin and rp_createBin
* copy secret key to chroots for package building
All core/opt bins are now signed. Some experimental packages are still being built still but all bins will be signed soon.
After this is included I may switch away from wget to curl due to wget limitations with its use of  stderr (see download function).
But first will reduce number of modules handling downloads themselves to use the download function. Also the download and extract function will be reworked etc.
But the main premise behind this is to reduce the risk of installing …

system / packages - added signing of binary packages

---

scriptmodules/ports/cannonball.sh

This commit: https://github.com/djyt/cannonball/commit/ffac08c25c2937d046e376ed59a5f0154c38d969 broke the build and installation process for the cannonball engine as designed in RetroPie-Setup. By updating the arguments to gitPullOrClone to lock the version at a previously-buildable version, cannonball is now able to build and install correctly.
A better solution would be to update the build process here to work with the new cmake files in the master version of their repository, but this fix will at least allow the engine to function.

Recent change in cannonball cmake files makes RetroPie build/installation process no longer function

---

scriptmodules/libretrocores/lr-hatari/01_libcapsimage.diff

Build broke because of upstream commit 05c7f4e9f399c2 (Makefile update).

lr-hatari: update local patch to fix build

---

scriptmodules/libretrocores/lr-vecx.sh

The core now uses GPU rendering and it needs additional parameters for compilation.
Not sure  how it works on other GLES platforms (Odroid/Tinker/etc), it assumes that `libGLESv2` is the name of the GLES lib. Would be useful to test at least on Odroid.

lr-vecx: update build for GPU rendering support

---

scriptmodules/supplementary/esthemes.sh

This adds a new theme I made for my retro cabinet based on a fork/variation of es-theme-angular by lilbud.
The theme repository is here: https://github.com/Elratauru/es-theme-angular-artwork
It's mostly for 5:4 screens, as the cabinet I'm using has one of these, but 4:3 support could probably be added if requested later down the line.
I updated the readme of the theme repo with more detailed information along with screenshot of how it looks since I was at it. 
Is there anything else I should do besides the modification on this file to point to the repository?
Thanks!

Adds new Angular Artwork theme

---

scriptmodules/emulators/retroarch.sh
scriptmodules/emulators/retroarch/04_config_save_fix.diff

If we have a custom config with
```
#include "/opt/retropie/configs/all/retroarch.cfg"
```
Changing an option that is set in the config above in RGUI and using "Save current configuration" from RGUI will not save that option. No options that exist in the include will be saved.
This is a revert of upstream change https://github.com/libretro/RetroArch/pull/10524/commits/9eb84728

retroarch - fix saving configuration when config keys exists in an include - #3249

---

scriptmodules/emulators/mame.sh
scriptmodules/libretrocores/lr-mame.sh

The change impacts `lr-mame`,`lr-mess`,`lr-mame2016`,`lr-mess2016` and `mame`.
It should fix building on new Ubuntu 20.04+ installations, which don't have a default `python` executable.
Since `python3` is automatically needed by the installation (via `python3-pyudev` for `joy2key`), no explicit dependency for `python3` was added.

lr-mame, mame: use python3 to build recent mame versions

---

scriptmodules/supplementary/runcommand/runcommand.sh

Ok, small change of which you can actually see.
using {exit} on awk is equivalent to a | head -n1. So it exits at the first /connected/. thus filling the array with only one output.
Also why does grep -o even have {1,}, that's what + is for

runcommand.sh: Fixes x11 multiple output/display error

---

scriptmodules/emulators/drastic.sh

After the changes in #3121, starting `drastic` on a Pi4 shows the X11 cursor.
Since there's no way to remove it for users that don't have a mouse/touchpad available and `drastic` has its own input stylus handling for those input devices, disable the cursor via the WM.

drastic: disable cursor under KMS

---

scriptmodules/supplementary/audiosettings.sh

When PulseAudio is installed and active, it takes over as the default ALSA device.
Remove any `.asoundrc` when it's enabled and configure the PulseAudio default output sink instead.
Added the option to enable/disable PulseAudio, depending on the running configuration.

audiosettings: add PulseAudio configuration support.

---

scriptmodules/emulators/ppsspp-1.5.4.sh
scriptmodules/emulators/ppsspp.sh
scriptmodules/libretrocores/lr-ppsspp.sh

Users reported that this version runs faster on videocore on the rpi1/2/3
Adjusted ppsspp sources to allow branch parameter and fixed build subfolder to ppsspp
so that paths are the same for md_ret_files, including adjusting lr-ppsspp in the same way.
Older code builds ok with our current ppsspp module script on rpi1/2/3 + videocore gles2,
but not rpi4, which it isn't needed on anyway. This may need changing if we have to update
ppsspp further in the future.

ppsspp / ppsspp-1.5.4 - added ppsspp 1.5.4 using parent ppsspp module

---

scriptmodules/supplementary/bluetooth.sh

I made some changes before to hide previously registered devices from the connect menu, to make it
easier when dealing with multiple devices of the same name. However due to the way bluetoothctl works,
previously "seen" devices are added to the system, meaning devices that are not paired are registered and cached,
and then won't be shown again.
This changeset addresses the following:
Only actually paired devices will be hidden from the register and connect menu
New functions list_paired and list_connected have been added
Switched to use bt-device to check for connected devices for consistency. Private function handles
grepping for Paired or Connected via bt-device --info
display_active_and_registered function renamed to simpler status and reworked to use the new functions.
It outputs to …

bluetooth - registered / paired device logic rework

---

scriptmodules/admin/setup.sh
scriptmodules/system.sh

Disable binaries for Raspbian Stretch and adjust warning message accordingly.

system / setup - Raspbian Stretch is no longer supported

---

scriptmodules/emulators/openmsx.sh
scriptmodules/emulators/openmsx/retropie-init.tcl
scriptmodules/supplementary/emulationstation/configscripts/openmsx.sh

* added a joystick auto-configuration for Emulationstation. Joypad mappings:
* A: MSX controller A; OSD menu: Back/Cancel
* B: MSX controller B; OSD menu: Action (toggle/execute menu item)
* D-Pad/Left Analog: MSX controller joystick; OSD Menu: Up/Down/Left/Right
* Start - Toggle the openMSX OSD menu
* Select - Show on-screen keyboard
* Y - MSX F1
* X - MSX F2
* Left Trigger - MSX F3
* Right Trigger - MSX F4
The joystick's A/B/D-Pad are functional in the openMSX menu, however B is action and A is cancel/back for some reason.
The joystick is loaded using the `retropie-init.tcl` script, automatically loaded and executed during startup. Per-game overrides are possible, as long as the correct configuration script for a gamepad is found (needs some documentation).
* created a minimal …

openmsx: added joystick autoconfiguration, config tweaks and enabled for 'mali'

---

platforms.cfg
scriptmodules/emulators/dolphin.sh
scriptmodules/emulators/openmsx.sh
scriptmodules/libretrocores/lr-bluemsx.sh
scriptmodules/libretrocores/lr-opera.sh
scriptmodules/libretrocores/lr-quasi88.sh
scriptmodules/libretrocores/lr-vice.sh

* Amiga - new extensions supported by `lr-puae`
* C64 - new extensions supported by `lr-vice`
* 3DO - added `.chd`, supported by the Opera Libretro core; updated license URL for the core.
* GC/Wii - added `.rvz`, supported by Dolphin
* MSX - added `.cas`, supported by both `lr-bluesmsx` and `openmsx`
Should fix #3261.

platform updates - add new supported extensions

---

scriptmodules/supplementary/esthemes.sh

This would enable installation of themes where the default branch is named `main`, instead of `master`.
Github changed this a while back, see the [renaming repo](https://github.com/github/renaming).
One such theme is @lipebello's new theme (https://github.com/lipebello/es-theme-retrorama-turbo).
**Note**: this is a re-worked version of #3278. While `gitPullOrClone` could be modified to detect the default main branch of a repo, its main usage is in the `_source` scriptmodules function - where the branch can be specified, so default branch detection is not strictly necessary.
`esthemes` doesn't have the ability to specify a branch when cloning a theme. Since a theme repository isn't usually multi-branched (so there's no need to add branch name support in the selection list), I added the …

esthemes: enable default branch detection for themes repositories.

---

scriptmodules/supplementary/moonlight.sh

There are open-source implementations of NVIDIA's GFE server which
expands Moonlight compatibility to other GPU manufacturers on both
Linux and Windows:
1. https://github.com/loki-47-6F-64/sunshine
(original project with CPU and NVIDIA HW encoder support)
2. https://github.com/LS3solutions/openstream-server
(forked project focused on Windows support with partial AMD HW encoding)
Unfortunately, moonlight-embedded does not work out of the box, so
provide a new host menu to assist in configuring the options needed
to attain full compatibility with these servers.

moonlight: add support for open-source GFE servers

---

scriptmodules/admin/builder.sh
scriptmodules/admin/setup.sh
scriptmodules/admin/stats.sh
scriptmodules/packages.sh
scriptmodules/supplementary/attractmode.sh
scriptmodules/supplementary/dispmanx.sh
scriptmodules/supplementary/emulationstation.sh
scriptmodules/supplementary/mehstation.sh
scriptmodules/supplementary/retropiemenu.sh
scriptmodules/supplementary/runcommand.sh
scriptmodules/supplementary/splashscreen.sh
scriptmodules/supplementary/usbromservice.sh

This reworks a lot of internal package logic and simplifies a lot of functions.
It was something I had in mind a long time ago, and the longer I left it, the messier it got.
Previously all the module data was in indexed arrays with matching offsets. Each scriptmodule folder had an initial index and it was incremented per module.
Many package functions expected an index. Indexes were never unique and could change depending on added modules etc. We also had to convert between them and module IDs.
This caused a lot of issues to extend package organisation. Eg. The idea to allow external repos with additional packages would have been messy to try and arrange the order.
Now it's all done by module id. There is a numbered index of all modules found, which increments which is used in the GUI …

Move to associative arrays for module data

---

scriptmodules/emulators/hatari.sh

Upstream `hatari` has dropped support for CAPS4, so it's not looking for `caps5`, but the libretro core still looks for [`caps5`](https://github.com/libretro/hatari/blob/c05015c395a17af12e1eb7e9e4fb876f74b00122/src/uae-cpu/newcpu.c#L166).

lr-hatari: fix building with the capsimage libs

---

scriptmodules/admin/image.sh
scriptmodules/admin/setup.sh
scriptmodules/emulators/ags.sh
scriptmodules/emulators/frotz.sh
scriptmodules/emulators/fs-uae.sh
scriptmodules/emulators/mame.sh
scriptmodules/helpers.sh
scriptmodules/libretrocores/lr-prboom.sh
scriptmodules/packages.sh
scriptmodules/ports/dxx-rebirth.sh
scriptmodules/ports/eduke32.sh
scriptmodules/ports/kodi.sh
scriptmodules/ports/openpht.sh
scriptmodules/ports/steamlink.sh
scriptmodules/ports/uqm.sh
scriptmodules/supplementary/customhidsony.sh
scriptmodules/supplementary/pegasus-fe.sh
scriptmodules/supplementary/raspbiantools.sh
scriptmodules/supplementary/retronetplay.sh
scriptmodules/supplementary/scraper.sh
scriptmodules/supplementary/skyscraper.sh
scriptmodules/system.sh

Move RetroPie to use curl rather than wget.
This changeset switches the helpers download function to use curl (including some function enhancements such as stdout support) and makes downloadAndExtract also use the core download function.
In addition almost all module code using wget has been switched to use the download or downloadAndExtract function excluding one case where wget was used in an external script which has been switched to curl.
Packaging and setup functions have been adjusted to curl also.
This is left as draft as there's a few things I want to look at still, such as the stderr output capturing and some additional tweaks here and there perhaps. But feel free to test.

Wget to curl

---

ext/README.txt
scriptmodules/packages.sh

The structure should be such that you have
ext/REPOSITORY/scriptmodules
modules are only read from the following subfolders of scriptmodules
emulators
libretrocores
ports
supplementary
admin
Tagging: @zerojay and @hiulit
This should make things easier and keep your repos separate etc. Needs testing.

packages - allow adding of 3rd party module repos

---

scriptmodules/admin/builder.sh
scriptmodules/admin/setup.sh
scriptmodules/admin/stats.sh
scriptmodules/packages.sh
scriptmodules/supplementary/dispmanx.sh

rather than multiple arrays for each module info we now use a single array with
__mod_info(ID/KEY) where key is type/desc/help/licence/flags etc
we still keep __mod_id() - a standard indexed array with every module id (used for setup menus etc) and
__mod_idx() which references the index # from the id
this will make it easier to extend in the future

Merge module arrays and include all modules in setup

---

scriptmodules/admin/setup.sh

On the Raspberry Pi console, bold text results in a lighter colour, rather than actually being bold.
One user (it may not be a common issue) reported on their terminal that they couldn't see installed packages. This was due to our "bold white" for installed applications which ended up being bold grey on a grey background - so they couldn't see what was installed without hovering over it.
I have switched the colours around here, so the section heading is just "bold" which will be a light
grey on the Raspberry Pi, and blue for installed apps, and red for unavailable packages.
I'm not completely happy with this, as it's more colourful than before, and perhaps too busy. However, this should work on terminals that decode it as 7 colours + bold rather than 15 colours etc.
--
Thoughts welcome. I …

setup - change colours around to work with other terminals

---

scriptmodules/emulators/openmsx.sh

Alternatively, we could install `gcc-8` on Ubuntu and compile with it - seems to work.

openmsx: fix building on Ubuntu 18.04/GCC 7

---

scriptmodules/emulators/dolphin.sh

After recent modification of dolphin.sh, build from source failed, because 2 branches are set in git command.

dolphin - correct build from source script

---

scriptmodules/ports/lzdoom.sh

Looks like GL2 compatibility has been kept for LZDoom versions post 3.86, so we can update to the latest 3.x release tag.
Other:
* Removed the CFLAGS manipulation, since the math optimizations have been removed in c3751a4f0ee37451991b775e0bea8ba3df424a20, but left the warning for building with `-funsafe-math-optimizations`
* Use the direct link to the license page

lzdoom: update to 3.87c

---

scriptmodules/admin/setup.sh
scriptmodules/helpers.sh
scriptmodules/packages.sh

Create a new function isConnected in helpers.sh which calls getIPAddress, but also sets a new global __NET_ERRMSG if not connected. This is used in setup.sh and packages.sh so we don't duplicate the same message between files.
Split out a new function runCurl from the download function, to do lower level curl calls, but capture any errors into __NET_ERRMSG for display in setup.sh or via the packaging functions. Use a connect timeout of 10 in the download function rather than 60 which is quite long, but keep the 60 second limit on no data transfer.
Adjust rp_remoteFileExists to use runCurl, so we can capture any error when checking a remote file, and use this value for display in setup and in logs etc. Switch to using long versions of curl options for readability, and add --show-error so …

Rework the checks and error messages displayed on network error

---

scriptmodules/emulators/openmsx.sh

Turns out `-m` is not a shorthand for `-machine`.
Changed the names emulators shown in runcommand selection, `+` may be problematic when storing the entry in emulators.cfg

openmsx: fix the wrong emulator parameter for model

---

scriptmodules/supplementary/sdl2.sh

Have forked https://github.com/libsdl-org/SDL to https://github.com/RetroPie/SDL and have applied
our patches against the upstream release-2.0.10 tag in the retropie-2.0.10 branch.

sdl2 - switch sdl2 to use our fork of the new upstream repository

---

scriptmodules/libretrocores/lr-fbneo.sh

remove version from description, i think the previous 0.2.97.44 description is still causing misunderstandings for ppl who didn't update their retropie-setup script yet, and we'll probably change version more regularily from now on.

lr-fbneo.sh: be less specific about version

---

scriptmodules/supplementary/audiosettings.sh

`mawk` (default AWK on Debian) doesn't know about `gensub`, so use a Posix ERE instead.
Fix also the options index when choosing the PulseAudio sink so the correct audio output is chosen.

audiosettings: fix PA options display when using mawk

---

scriptmodules/emulators/mame.sh

The suffix was removed in 0.229 (https://github.com/mamedev/mame/commit/adc23f3f74f64afa3a1258539a4f8ae2f7ae76c9)

mame: remove binary name, not needed anymore

---

scriptmodules/supplementary/xpadneo.sh

0.9.1 is a maintenance release:
"The highlights of this release are better compatibility with current Proton versions, fixes to Xbox One S|X controller support, removal of old dead configuration options, updated and improved documentation, better integration with DKMS, improved logging to aid issue resolving, future proofing the systemd and udev integration, and deprecating support for directional rumble which never properly worked."
The install script has slightly changed, so the build step was updated to accommodate that.

xpadneo: update to 0.9.1

---

scriptmodules/emulators/mame.sh

installing `lib-pulsedev` doesn't appear to have any effect on general sound, nor install `pulseaudio` (the purging of which is sometimes recommended to fix the ALSA vs Pulse audio issues)

MAME Pulse dependency

---

scriptmodules/libretrocores/lr-quicknes.sh

As per https://docs.libretro.com/guides/retroachievements/#nes, lr-fceumm (default NES emulator for >armv6) now supports RetroAchievements, so I can't think of a reason to keep lr-quicknes in main packages for anything other than pi1/0 (where it's currently the default as it's the fastest).

lr-quicknes in main packages only for armv6 (pi1/0)

---

scriptmodules/libretrocores/lr-theodore.sh

Hello.
The current LICENSE path points to the old libretro clone of the upstream repository. The libretro clone does not exist anymore, the upstream repository must be used instead.

lr-theodore: Update LICENSE file path

---

scriptmodules/libretrocores/lr-gpsp.sh

The dynarec crash on ARM with GCC7+ have been solved in 6254bbb1d, building with GCC6 is no longer necessary.

lr-gpsp: remove the build workaround added in #3456036

---

scriptmodules/emulators/ppsspp.sh

Reported initially in https://retropie.org.uk/forum/topic/30620/, it looks like recent versions don't detect correctly the binary folder at runtime and they're unable to find the `assets` folder correctly.
Running from the emulator's folder fixes it, since `cwd` is added to the search path by the emulator.
Needs further investigation to find the cause and - possibly - a proper fix.

ppsspp: add a workaround for assets folder detection issues

---

scriptmodules/helpers.sh

The `__curl_opts` environment variable is currently always ignored due to the inverse logic being used when determining whether the variable is present.  It currently uses the bash `-z` check when it should use `-n`.
Current logic:
```sh
function runCurl() {
local params=("$@")
[[ -z "$__curl_opts" ]] && params+=($__curl_opts)
echo "${params[@]}"
}
unset __curl_opts
runCurl --max-time 10 --silent --show-error --fail --head "https://retropie.org.uk/"
__curl_opts='-L'
runCurl --max-time 10 --silent --show-error --fail --head "https://retropie.org.uk/"
```
Output:
```
--max-time 10 --silent --show-error --fail --head https://retropie.org.uk/
--max-time 10 --silent --show-error --fail --head https://retropie.org.uk/
```
New logic:
```sh
function runCurl() {
local params=("$@")
[[ -n …
```

Fix __curl_opts environment variable being ignored when present

---

scriptmodules/libretrocores/lr-duckstation.sh

Tested on Pi 4, arm32, gles 3.1. Should be compatible with aarch64 and x64, gles2 (ie pi2/3 - not sure about performance) and vulkan.
Libretro core is not released as source - binary is hosted by dev, under NC-type license. see https://www.duckstation.org/libretro/

Added experimental PSX emulator lr-duckstation.

---

scriptmodules/emulators/retroarch/02_shader_path_config_enable.diff

Looks like the v1.9.1 original patch didn't apply cleanly to v1.9.4 and the patch was incomplete.

retroarch: fix the patch enabling `video_shader`

---

scriptmodules/packages.sh

Custom binary URLs provided by __binary_url_* scriptmodule functions were ignored for platforms we don't host general binary builds for. This meant that lr-duckstation wouldn't show binary install options on aarch64 / x86_64.
Moved the rp_hasBinaries check logic to rp_getBinaryUrl, so we only set a URL by default when we have binaries for that system. This is overridden as needed by install_bin_* / __binary_url_* scriptmodule functions. The rp_hasBinary function will check for a binary if the URL is set, so we allow overriding of our own binaries, as well as having the ability to install 3rd party binaries for systems we don't host binaries for.

packages - allow custom binary installs when we don't host binaries

---

scriptmodules/emulators/redream.sh

Fix `redream` being installable on `aarch64`, now that #3357 fixed the issue of packages with custom binary url set.

redream: not available on aarch64 yet

---

scriptmodules/supplementary/runcommand/runcommand.sh

As discussed here initially: https://retropie.org.uk/forum/topic/30662/intellivision-jzintv-for-sdl2-proposed-scriptmodule/3
Added some escape sequences for doxygen to keep `%` char in HTML output.

runcommand.sh: updated doc for %XRES%, %YRES%

---

scriptmodules/emulators/jzintv.sh

As initially sketched here: https://retropie.org.uk/forum/topic/30662/intellivision-jzintv-for-sdl2-proposed-scriptmodule
Note for early adapters trying this before it is merged upstream: If the download fails replace `$__archive_url/jzintv-20200712-src.zip` with `file http://spatula-city.org/%7Eim14u2c/intv/dl/jzintv-20200712-src.zip`

scriptmodule: jzIntv release 2020-07-12, SDL2 build

---

scriptmodules/helpers.sh
scriptmodules/supplementary/runcommand.sh
scriptmodules/supplementary/runcommand/joy2key_sdl.py
scriptmodules/supplementary/runcommand/runcommand.sh
scriptmodules/system.sh

Added a new `joy2key` implementation, using PySDL2 for joystick event handling.
PySDL2 is a python module that wraps SDL2 (and other SDL libraries) using the built-in `ctypes` module.
Pros:
* event handling is simplified a bit, using SDL's event loop.
* (subjective) the code is a bit more structured and easy to follow.
* joystick handling is rewritten based on EmulationStation code, movement is smoother and scrolling is improved.
* support for input repeat to improve scrolling, just keep the input pressed and scrolling continues
Cons:
* module is a bit larger (296 LOC vs 224 in current joy2key.py)
* needs PySDL2 (which might not be packaged, see the notes below) and SDL2
* arguably, device conf. to keyboard event mapping is more complex (abstracted as InputDev)
Notes:
* availability of …

joy2key: new version using PySDL2

---

scriptmodules/emulators/dosbox-staging.sh
scriptmodules/emulators/dosbox.sh

PR to include DOSBox Staging to Retropie. This fork is an attempt to revitalize DOSBox's development process. It's not a rewrite, but a continuation and improvement on the existing DOSBox codebase while leveraging modern development tools and practices. This fork is in very active development. 
Besides code modernization and refinements, Staging brings the following features - documented on the [Wiki](https://github.com/dosbox-staging/dosbox-staging/wiki):
* SDL 2.0
* General MIDI via Fluidsynth (2.x built-in statically)
* MT-32 via Munt (2.x built-in statically)
* Major [improvements](https://github.com/dosbox-staging/dosbox-staging/wiki/Gravis-UltraSound-Enhancements) to Gravis Ultrasound playback
* Support FLAC, Opus, Vorbis, and MP3 CD-DA tracks
* …

add dosbox staging - an enhanced modernized dosbox fork

---

scriptmodules/supplementary/runcommand/joy2key_sdl.py

`python3.8(+)` throws a warning for using 'is/is not' with with certain literal types [1].
Simplifying the debug message that shows the `python3-sdl2` wrapper version gets rid of this warning, the end result is the same.
[1] https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior
Reported in https://retropie.org.uk/forum/topic/30876.

joy2key: simplify debug message; fix python warning

---

scriptmodules/supplementary/runcommand/joy2key_sdl.py

Added 2 fixes:
* reject malformed hat values for an input in the joystick auto-config file(s).
If it's not one of `h<X>up`, `h<X>right`, `h<X>down`, `h<X>left`, reject the input value.
* fix `SDL_GetError` not being properly shown because of the wrong f-string.
1st fix should fix the error reported by @mth75 in https://retropie.org.uk/forum/topic/30882/.

joy2key: guard against malformed hat values

---

scriptmodules/ports/wolf4sdl.sh

Changes in Wolf4SDL:
* ported to SDL2
* added PC speaker sound emulation
* support for the Japanese version
* added the OPL emulation from DOSBOX, as an alternative MAME's emulation code. This allows re-licensing under GPL
* various bugfixes
Module changes:
* re-license under GPL by excluding the MAME OPL emulation
* update dependencies with SDL2 and enable for Mali platforms
* update the upstream repository (used now by the project at http://wolf3d.net/wolf4sdl)

wolf4sdl: update to 2.0

---

scriptmodules/supplementary/runcommand/runcommand.sh

Split out runcommand.info creation to a function and call it again after menu is used in case any emulator settings are changed
Added additional runcommand-onlaunch.sh user script support which is run just before launching. This was requested in #2779 and #2810

Runcommand tweaks

---

scriptmodules/ports/wolf4sdl.sh

Looks like the new version doesn't have a default `DATADIR` to search for files.
Modified the launcher to start from the `ports/wolf3d` port folder so data files are found.

wolf4sdl: fix game launching

---

scriptmodules/emulators/dosbox-staging.sh

Not sure what I've done here hence I'm sorry for that. The `.git` extension has been restored as I wrongly removed it from previous PR. Should be good this time. _Note to self_: never rush a commit...
The main reason to switch from traditional [master branch](https://github.com/dosbox-staging/dosbox-staging) to a fixed version ([tag](https://github.com/dosbox-staging/dosbox-staging/tags)) is all about stability. Heavy changes are to be worked on shortly on DOSBox Staging (scaling method, better shader integration, input handling, etc just to name a few). Therefore the master branch is likely to break at some point. 
In order to not overwhelm [Github](https://github.com/dosbox-staging/dosbox-staging/issues) with tickets (or Retropie forum) when build is broken, let's stick to a fixed …

Dosbox Staging - move to fixed version instead of master/main

---

scriptmodules/supplementary/runcommand/runcommand.sh

Switch to letters for items rather than numerical values to avoid gaps and to make it easier to add items to the
menu without having to renumber items etc, which has happened previously (hence most menus excluding
generated lists don't use number ids in RetroPie).
Remove the "Remove emulator/video mode choice" items and replace with an option in the sub-menu for clearing / removing.
Previously when choosing a default emulator for a rom, (or a default video mode for emulator, emulator + rom etc),
an additional menu item was added below to remove the setting. Although this enabled quick access to remove options
from the main menu, it wasn't that intuitive and doesn't match the way menus work elsewhere in RetroPie.
Now when choosing a default emulator / video mode, there is an option to …

Runcommand menu rework

---

scriptmodules/emulators/atari800.sh
scriptmodules/helpers.sh
scriptmodules/supplementary/backends.sh

This allows choosing of sdl1 backend for atari800 and changes default to dispmanx for fkms.
More details in the commits.

Atari800 backends

---

scriptmodules/system.sh

sorry about the mess I made here.
https://github.com/RetroPie/RetroPie-Setup/pull/3365
As I said in one of my messages there, the previous implementation is not stable as model can be configured quite easily in the dts (and it often done so on custom carrier board).
Checking the dts filename is also not stable as this will change whenever a new board layout is made.
the SOCFamily is only changed when a new chip is created (all tegrax1 chips use tegra210 as an example but the tegrax2 has its own socfamily)

Add the missing Nvidia Jetsons (update)

---

scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh

When a hat is mapped to another set of inputs other than D-Pad's up/down/left/right in EmulationStation, the resulting RetroArch mapping can be incorrect.
As an example, the following ES input mapping (obtained by probably mapping the physical D-Pad to the left analog stick inputs in EmulationStation):
<input name="leftanalogdown" type="hat" id="0" value="4"/>
<input name="leftanalogright" type="hat" id="0" value="2"/>
<input name="leftanalogleft" type="hat" id="0" value="8"/>
<input name="leftanalogup" type="hat" id="0" value="1"/>
results in the following incorrect RetroArch input configuration:
input_l_y_plus_btn = "h0leftanalogdown"
input_l_x_plus_btn = "h0leftanalogright"
input_l_x_minus_btn = "h0leftanalogleft"
input_l_y_minus_btn = "h0leftanalogup"
Rather than use `input_name`, map …

emulationstation: fix an input mapping corner case bug

---

scriptmodules/helpers.sh

When the release of the remote repository is changed, `apt-get` will not update its packages without
`--allow-releaseinfo-change`, so fix that.
This has become problematic due to last week's Debian Bullseye release, which changed the <raspbian.raspberrypi.org> suite from 'stable' to 'oldstable' and prevents `apt` to refresh its index. Upgrading from 4.7.1 (image) to the current version is no longer possible because of this, since `subversion` is not installed on 4.7.1, but it's required now and due to it being updated in the repo, it's not installable.
In the future, we might switch to just using `apt update` (which doesn't have this problem), but there are several other places where `apt-get` is still used, so this change is meant just as a quick fix for the recent suite changes.

helpers: teach `aptUpdate` to hop releases

---

scriptmodules/system.sh

tegra 2 is armv7 and doesn't support NEON and is unlikely to ever be used
tegra 3 (and maybe 4?) only support gles (up to 2.0) not gl (in L4T linux at least)

remove tegra 2 and change tegra 3/4 to gles

---

scriptmodules/libretrocores/lr-vice.sh

The options changed are similar to the configuration used for the standalone VICE:
* Set the SID implementation to FastSID
* Decrease the sound sample rate to 22050

lr-vice: preset a couple of SID options on ARMv6

---

scriptmodules/emulators/retroarch.sh
scriptmodules/supplementary/configedit.sh

-Add mesa vulkan drivers if retroarch is build with vulkan support. 
-Remove cg toolkit because cg to glsl conversion is no longer necessary. Libretro has an own repo with up to date glsl shaders.
-Configuration editor: Add a more precise description which shader presets can be used with different video drivers.

Add some minor improvements

---

scriptmodules/supplementary/skyscraper.sh

qt5 has been removed in all modern versions of Debian and Ubuntu, and the skyscraper script will not work at all without these changes - this dependency change should not break older versions of these operating systems and the package should install fine.
https://askubuntu.com/a/1335187

Skyscraper - fix critical dependency error (Debian 11+, Ubuntu 21.04+)

---

scriptmodules/emulators/retroarch.sh
scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh

Whilst using Libretro's [RetroArch joypad autoconfigs](https://github.com/libretro/retroarch-joypad-autoconfig/) has proven problematic, we can still leverage this database in some interesting ways. This PR uses it to apply meaningful button labels across the Retroarch menus, rather than the retropad abstract/button numbers.
Eg, for a DualShock 4:
Only tested with UDEV devices - one with labels in the matched preset in the repo (pictured), one with none (but will have after https://github.com/libretro/retroarch-joypad-autoconfig/pull/767). When there's no labels, they appear as previously:

Use Libretro's RetroArch joypad autoconfig presets to generate button labels

---

scriptmodules/ports/uqm.sh

This avoids the messy logic for missing Raspberry Pi Buster packages, and simplifies future updates.

uqm - rework module to build from source (and update to 0.8.0)

---

platforms.cfg
scriptmodules/libretrocores/lr-tic80.sh

This script was developed with assistance from mods and forum users on Retropie, full forum thread at https://retropie.org.uk/forum/topic/31366/tic-80-retroarch-lr-tic80-core-installation-script?_=1632144270795
The script is easy to install, the emulator runs well, and .tic/.zip files work without issues.

Add libretro module script for TIC-80

---

scriptmodules/supplementary/configedit.sh

Since v1.9.6 RetroArch changes the way the "analog to digital" works and since then the "forced mode" is need for some cores (eg. lr-vice, lr-puae).
#https://github.com/libretro/RetroArch/pull/12562

add forced modes to analog_dpad_mode

---

scriptmodules/libretrocores/lr-duckstation.sh

Set the Memcard 1 save as "Save Ram (libretro .srm)" instead of the native "<game>_1.mcd" file. Should make easier consistent with other libretro cores behavior.
License link updated, taken from https://github.com/stenzek/duckstation#libretro-core.

duckstation: preset an extra option, added license link

---

scriptmodules/admin/joy2key/joy2key_sdl.py

Added a couple of fixes for issues discovered tracking the errors reported in a forum post [1].
* When a device is disconnected, its events were not cleared. 
This was problematic for joystick/d-pad movement tracking, which keeps the last move event in the event queue. Disconnecting a device while the movement is active would keep this last move in the event queue forever, so clear all events associated with a device when it disconnects
*  For certain joysticks (axis), SDL will generate spurious axis movement events during initialization.
It seems that for axis where `absmin` and `absmax` are asymmetrical (ex. 0-255 instead of -255 - 255), SDL generates extra events which are not user generated. This can causes issues - i.e. automatically trigger the `runcommand` menu without user …

joy2key: fix a couple of bugs in the SDL version

---

scriptmodules/emulators/mupen64plus.sh

Massively improves framerate at cost of accuracy.
Tested on Pi 4, GoldenEye menu:
True = 47 FPS
False = 33 FPS
The accuracy cost is essentially the last few months of texture handling improvements. These do fix some long standing display/accuracy bugs, but the framerate cost is so prohibitive on Pi that I doubt there would be cause to use them. Certainly not by default.

mupen64plus: enable GLideN64 plugin option EnableInaccurateTextureCoordinates for rpi.

---

scriptmodules/supplementary/bluetooth.sh
scriptmodules/supplementary/bluetooth/bluez-simple-agent
scriptmodules/supplementary/bluetooth/bluez-test-device
scriptmodules/supplementary/bluetooth/bluezutils.py

Updated the dependencies and scripts for python3:
* `python-dbus` no longer exists in Debian 11 'bullseye' or Ubuntu > 20.04, installl the `python3` version
* `python-gobject` has been superseeded by `python(3)-gi`, the current package is just a transitional package that pulls
`python-gi` and the old `python-gobject-2` (deprecated). Update the dependencies and the scripts to use the new package.
* set python3 as interpreter for the helper scripts. Fixed the dict syntax for getting items.

bluetooth: update python scripts and deps for python3

---

scriptmodules/helpers.sh

Couple of changes:
When env __persistent_repos is 1, we do full checkouts of repositories. This allows users with diskspace to spare to speed up source updates, by avoiding doing a shallow clone everytime.
However, it was not working for cases where a module switched to a newer tag/branch as remote changes were not fetched first. This is now fixed.
Also fixed errors thrown when calling gitPullOrClone on an existing repository when doing git pull, when HEAD is detached (for tags) or there is no tracking branch.
And
When doing a shallow clone, also add --shallow-submodules which will do a shallow clone of submodules with depth 1.
This significantly speeds up checkouts of repositories with a lot of submodules (eg lr-tic80).

gitPullOrClone improvements

---

scriptmodules/admin/joy2key.sh
scriptmodules/admin/joy2key/osk.py
scriptmodules/supplementary/wifi.sh

(Inspired by https://github.com/RetroPie/RetroPie-Setup/pull/3429)
Currently, the WiFi configuration from RetroPie menu needs a keyboard for configuring a connection.
Added a `python` script to display on-screen keyboard which can be operated with `joy2key` and the gamepad, which allows entering the WiFi network/key/password without a keyboard. The script accepts keyboard input, so it's suited for both keyboard and joystick input. It's using the `urwid` library (https://urwid.org).
The WiFi scriptmodule was modified to use the new OSK script instead of the `dialog` based inputboxes.
Additional modifications to the WiFi module:
- added a confirmation step before removing the WiFi config and stopping the WiFi
- added an info message during the WiFi scanning (instead of having a black …

joy2key,wifi: add an on-screen keyboard dialog

---

scriptmodules/ports/openblok.sh

Tried to install RetroPie on a clean minimal Kubuntu installation.
Had to add gettext to the list of dependencies.

added missing gettext dependency

---

scriptmodules/emulators/advmame-0.94.sh
scriptmodules/emulators/advmame-1.4.sh
scriptmodules/emulators/advmame.sh
scriptmodules/emulators/advmame/02_fix_extern_globals_0_94.diff
scriptmodules/emulators/advmame/02_fix_extern_globals_1_4.diff

(Following up on #3440).
1. Build fixes for older `advmame` versions:
With gcc10 and newer, the `-fno-common` option is the default, causing
issues for global variables with multiple declarations that are missing the `external` initializer.
See https://wiki.gentoo.org/wiki/Project:Toolchain/Gcc_10_porting_notes/fno_common for a summary.
Added a couple of patches to fix building for older `advmame` versions:
* for `advmame-1.4`, pick amadvance/advancemame@f8688ca
* for `advmame-0.94`, created a separate patch
Added a minor modification to use the scriptmodule's `md_path` variable to calculate the patch folder location.
2. For `advmame`, fixed the SDL1 enable/disable flag, it was incorrect.

advmame: build fixes when using a newer `gcc`

---

scriptmodules/emulators/pcsx2.sh

seems like the binary was changed to lower-case in the recent package:
pcsx2-unstable 3:1.7.0~git202112312251+202201010334~ubuntu21.10.1

lower-case required for recent ubuntu package

---

scriptmodules/emulators/hypseus.sh
scriptmodules/emulators/hypseus/hypinput.ini

This is to automate: https://github.com/DirtBagXon/hypseus-singe/blob/master/src/3rdparty/retropie/RETROPIE.md
This plugin is not restricted in arcitecture like the previous SDL1 version.
Supports Pi (inc. aarch64), ODroid & PC (i386/AMD64).
Standing Forum discussions:
https://retropie.org.uk/forum/topic/18505/new-hypseus-and-lr-daphne-to-add-on-retropie-setup
https://retropie.org.uk/forum/topic/27426/request-add-daphne-singe-emulator
https://retropie.org.uk/forum/topic/31155/integrate-daphne-emulator-back-into-the-retropie-script-for-ubuntu
This setup follows the existing Daphne plugin installation as closely as possible.
I have mirrored the included config file to the existing plugin where appropriate.
This is my first pull request for RetroPie, please let me know if anything else is …

Add Hypseus Singe (Daphne) SDL2 Laserdisc emulator.

---

scriptmodules/supplementary/xpad.sh
scriptmodules/supplementary/xpad/02_dkms_updates_folder.diff

Changed from `extra` to `updates` to work-around some kernel upgrades (RPI) disabling the RetroPie `xpad` driver.
Upstream `xpad` repo installs the kernel in `/lib/modules/$KERN_VER/extra`, deleting the built-in module:
``` sh
$ modinfo xpad | head -n 5
filename:       /lib/modules/5.10.63-v7l+/extra/xpad.ko
license:        GPL
description:    X-Box pad driver
author:         Marko Friedemann <mfr@bmx-chemnitz.de>
srcversion:     849EA3FE68A31D6FA00FD40
```
During a kernel upgrade, **when** `$KERN_VER` does not change (happened with RPI provided kernels), then `dkms` gets confused about where the module resides:
* the pre-install hook deletes the module in `extra`, but restores the original module in the same location (!)
* the post-install hook sees the module in `extra` and assumes is …

xpad: change install folder in the kernel tree

---

scriptmodules/emulators/xroar.sh

Changes:
* Added support for Tandy Color Computer 3 (NTSC/PAL).
* Added support for Tandy MC-10
* Emulator tries multiple SDL video renderers in order
* Tape play/pause function
* New snapshot format to support CoCo 3, MC-10
* Add Control+Shift+D to flush disk images
* RACE Computer Expansion Cage support (-cart mpi-race)
* Support leading "~/" in filenames, not just path element
* IDE, NX32, MOOH now all require user to specify an image
Scriptmodule changes:
* Added explicit dependencies for ALSA and ZLIB. PulseAudio dependency added for `x11` platforms
* Added emulator entries for CoCo3 models (PAL/NTSC)
* Removed OSS support explicitely during build

xroar: update to 1.0.7

---

scriptmodules/libretrocores/lr-flycast.sh
scriptmodules/libretrocores/lr-flycast/01_flags_fix.diff

This reverts commit 9b271b2bfd96e703e49f23fce82e4f26ee0f2b9b.
Due to `gcc` seemingly mis-compiling the SH4 interpreter and crashing Naomi games.

Revert "lr-flycast: update to switch to upstream project"

---

scriptmodules/libretrocores/lr-freeintv.sh

License changed upstream with commit [e8d7ff7ae0d048055e7b0da0de78ed92eb0173a0](https://github.com/libretro/FreeIntv/commit/e8d7ff7ae0d048055e7b0da0de78ed92eb0173a0).

lr-freeintv: synchronise license with upstream

---

scriptmodules/libretrocores/lr-mess.sh

Fixes the binary installation, which didn't include the `hash` folder.

lr-mess: add hash folder to install location

---

scriptmodules/supplementary/golang.sh

I can change this to https://golang.org/dl/go1.8.linux-$arch.tar.gz if that would be preferable. Comments left in as a reference if anyone ever wants to change it back to Google's servers

update golang to v1.8.7 and include arm64 version to fix arm64 compatibility

---

scriptmodules/emulators/scummvm.sh

Version 2.5.1 incorporated the OpenGL based scalers by default and this causes a runtime error on GLES platforms.
Update to a post-2.5.1 commit which changes the OpenGL loader from GLEW to GLAD and fixes this problem.
Minor - upstream license changed to GPL3+.

scummvm: update to fix GL runtime detection

---

scriptmodules/emulators/mupen64plus.sh

This var is not set locally, it is inheriting wrong value "main packages" from ../admin/setup.sh#L380, resulting in:
mupen64plus-gles2ricemain packages = "...

Fix gles2rice plugin entry.

---

scriptmodules/emulators/mupen64plus.sh

mupen64plus: (QOL) Link config dir for network access to saves, etc.

---

scriptmodules/emulators/ags.sh

ags3 development branch has switched to an SDL2 backend, but also has build issues on my Ubuntu 21.10 system.
The module will need updating to support this, but it's better to wait until the next version is released and tested working.

ags - switch to to release-3.5.1 branch

---

scriptmodules/libretrocores/lr-stella.sh

I put this together rather quickly (and it needs testing), based on the lr-stella2014 script module and referencing the post on https://retropie.org.uk/forum/topic/32067/installing-lr-stella-upstream-on-raspberry-pi-4b/3?_=1643005126251 - which was similar.
If it's useful, it's an easy addition.

Added upstream / current stella libretro core - lr-stella

---

scriptmodules/supplementary/sdl2.sh

Added libsamplerate0-dev dependency to module.
Branch includes reworking the patch for kms modesetting via env variables, some minor changes to our Mali and RPI patches,
and some removal of no longer needed changes. It also includes removal of some debian/control build dependencies which were
added to upstream to align with Debian's packaging. The addition causes dependencies like libwayland-dev and libpulse-dev to
be required for all platforms. As we handle adding dependencies in our sdl module code, these have been removed in our
retropie-2.0.16+ sdl2 branch.

sdl2 - updated to retropie-2.0.20 branch

---

scriptmodules/supplementary/sdl2.sh

Reverts RetroPie/RetroPie-Setup#3390
Seems to have some issues with (some) OpenGL software on the RPI4. eg Darkplaces quake, alephone.

Revert "sdl2 - updated to retropie-2.0.20 branch"

---

scriptmodules/ports/alephone.sh

The different Marathon games are each launched with a unique emulator config, each one configured to launch only that particular game with the executable and game data directory hardcoded into the emulator command.
This change combines them into one "alephone" emulator config, with just the executable in the command, and splits the game data dir out into the "%ROM%" parameter. This allows easy user integration of additional alephone engine games simply by adding their game data and a launch script such as:
"/opt/retropie/supplementary/runcommand/runcommand.sh" 0 _PORT_ "alephone" "/path/to/game/dir/"
Pros:
- cleaner "configs" folder with only one shared emulator instead of a different one for each game
- easy user integration of additional alephone engine games
Cons:
- none that I can …

alephone: (QOL) improve/combine emulator configs

---

scriptmodules/emulators/xroar.sh

Fixes from 1.0.7: 
* Fix WASM audio for non-Firefox [Greg Dionne]
* Fix crash reading zero-length CAS file
* Fix joystick reads for Pacdude Monster Maze
* Close file after serialisation

xroar: update to 1.0.9 (bugfix release)

---

scriptmodules/supplementary/controlblock.sh

Added `libgpiod` dependency, introduced in https://github.com/petrockblog/ControlBlockService2/commit/1d3492c545ea4db99d7e9425e3b2d0f58d51487c.

controlblock: update dependencies

---

scriptmodules/libretrocores/lr-ppsspp.sh

`lr-ppsspp` uses the `savefile_directory` path in order to create its own save structure.
Game saves are not regular `.srm` files, but they're saved in a `PSP/SAVEDATA/<GAME_ID>` folder structure.
Without setting a `savefile_directory`, the core will try to save to `/PSP/SAVEDATA/<GAME_ID>`, which obviously fails.
Setting this to `$HOME/.config/ppsspp` makes it possible to share the savedata with the standalone emulator.

lr-ppsspp: preset a save directory

---

scriptmodules/emulators/ppsspp.sh

PPSSPP CMakeLists.txt adds -latomic for android targets, but this is also needed on armv6 on RaspberryPi OS Buster.
This commit sets the variable ATOMIC_LIB to "atomic" for videocore / armv6 so that -latomic is added.

ppsspp - Fix linking on rpi1 / armv6

---

scriptmodules/libretrocores/lr-fbneo.sh

We were missing ensureSystemretroconfig calls for FBNeo's console subsystems that are needed to populate a default retroarch.cfg
Move the systems into an array to avoid listing them twice.

lr-fbneo - add ensureSystemretroconfig calls for all fbneo subsystems

---

scriptmodules/supplementary/retropiemenu.sh

Due to the recent addition of the GameMode support, RetroArch needs access to the user's DBUS session socket.
When starting RetroArch from the RetroPie menu, `su` is used to launch it as the install user, but the DBUS socket path is not preserved (`DBUS_SESSION_BUS_ADDRESS`), leading to a en error and then a crash.
Prevent the crash by setting the XDG_RUNTIME_DIR when RetroArch is started with `su`.
NOTE: this primarily affects X11/PC users, where GameMode is part of the desktop install.

retropiemenu: fix launching RetroArch from the menu

---

scriptmodules/emulators/redream.sh

Hello As you know, a zip  build has been released  about 5 days that  in same link   for arm32-bit and  arm64 64-bit.
It doesn't change much else since the Redream script takes care of loading aarch32.elf or aarch64.elf if you are under 32bits or 64bits. 
Only supported on boards the GPU driver can run context  opengl 3.1 up to 4.5  (some extensions optional) or Opengl es 3.1 context.

Update Redream to Universal arm (32/64bits)

---

scriptmodules/supplementary/runcommand/runcommand.sh

When mutiple displays are connected, some of them may be disabled - skip them when considering the available video modes.
Fixes: #3496 .

runcommand: check only active displays on X11

---

scriptmodules/supplementary/attractmode.sh

`libavresample-dev` has been obsoleted by `libswresample-dev` on recent (21.10 and later) Ubuntu versions and Debian Testing.
Also explicitely add the dependency on curl's libs.

attractmode: dependency update

---

scriptmodules/emulators/zesarux.sh

See: https://github.com/chernandezba/zesarux/tags
Latest Tag is: ZEsarUX-10.0
Deprecated Unavailable Tag is: 9.1

Branch / Tag 9.1 no longer available.

---

scriptmodules/supplementary/attractmode.sh

Upstream project changed the `makefile` in [1] and `EXTRA_CFLAGS` was removed.
Use the new `EXTRA_CXXFLAGS` instead, so our compiler flags and directives to find the locally compiled `sfml-pi` are passed on.
[1] https://github.com/mickelson/attract/commit/502f5d71e5f3c97d3d1a6def440e1462c1f6ba0c

attractmode: fix build on videocore/kms platforms

---

scriptmodules/libretrocores/lr-pcsx-rearmed.sh

should be safe to run on armhf systems as well, though having someone test that for me would be nice

lr-pcsx-rearmed: fix fatal build error on aarch64

---

scriptmodules/admin/setup.sh

Git reports
fatal: unsafe repository ('$HOME/RetroPie-Setup' is owned by someone else)
This is due to us running `git log` under root on a repo owned by the user it was installed for.
This commit also switches from su to sudo in setup.sh for consistency with other code.

setup - fix up warnings with git 2.34.1 in retropie-setup

---

platforms.cfg
scriptmodules/emulators/amiberry.sh
scriptmodules/emulators/amiberry/01_preserve_env.diff
scriptmodules/emulators/uae4all.sh
scriptmodules/emulators/uae4arm.sh
scriptmodules/emulators/uae4arm/uae4arm.sh

[](https://github.com/RetroPie/RetroPie-Setup/commits?author=joolswills)Update amiberry version to v5.1 tag
Remove no longer needed libxml2-dev dependency
Add patch for amiberry Makefile so it doesn't override our CFLAGS/CPPFLAGS/LDFLAGS
Remove -O3 from Makefile so it uses our default optimisation level. Previously this was -Ofast but from my own testing -O2 with our compiler flags works best.
Modify build_amiberry with updated paths for caps bootstrap/configure. Override CPUFLAGS for amiberry, so our flags are used, rather than the ones hard-coded into the Makefile.
Include abr and kickstarts folder in install_amiberry. The kickstarts folder includes a freely distributable AROS rom, so let's include it.
Symlink cd32.nvr from "$md_inst/data" to "$md_conf_root/amiga/amiberry" so it's …

Update amiberry version to v5.1

---

scriptmodules/emulators/amiberry.sh

* New:
- Added new CD32 config with 8MB Fast, use that with --autoload option
- Enable RTC automatically if enabled expansions have RTC
- Support for Cycle-Exact mode from XML options (#959)
- Ability to set default soundcard (#963)
* Bugs fixed
- Hotkey mappings didn't work with controller buttons (#949)
- Only check for hotkey buttons if they have been mapped (#949)
- When using Auto-crop and virtual mouse driver, the pointer would not reach the edges of the screen (#962)
- Launch Amiberry binary directly in macOS app bundle (#970)
* Improvements
- Updated bundled AROS ROMs to latest version
- Updated WHDBooter XML and WHDLoad to latest versions
- Picasso96 new features are now optional. DACSWITCH fix.

amiberry: update to version 5.2

---

platforms.cfg
scriptmodules/emulators/pcsx2.sh

Supported by `pcsx2` since https://github.com/PCSX2/pcsx2/pull/4314.

ps2: add support for CHD disc images

---

scriptmodules/system.sh

system - use architecture for __platform instead of x86
For architectures not handled by custom logic, we previously checked `uname -m` for i686/x86_64/amd64 and then set __platform=x86.
This change switches to using the actual output of `uname -m` as the `__platform` variable. If a`platform_$__platform` function exists, we will call it, otherwise we call platform_native (which used to be platform_x86).
In platform_native we check if the platform is i386/i686/x86_64 and then set an x86 flag.
This seems more logical and allows us to more easily check for x86_86 in scriptmodule flags. It also resolves redream incorrectly having x86_64 added to the flags in d877a81 (which work after this change).
The error: fatalError "Unknown platform - please manually set the __platform variable to one of …

system - use architecture for __platform instead of x86

---

scriptmodules/supplementary/emulationstation.sh

Starting with RaspiOS 'bullseye', the `omxplayer` RPI video player is no longer supported.
Use the new EmulationStation build option (`OMX`) to enable the `omxplayer` bits only for `dispmanx` platforms. The new options is added in https://github.com/RetroPie/EmulationStation/pull/792. The `RPI` build option is used only for pre-setting some program settings on the Raspberry Pi platforms (audio/video memory).
Complements https://github.com/RetroPie/EmulationStation/pull/792.

emulationstation: build omxplayer only on dispmanx platforms

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/libretrocores/lr-ppsspp.sh

Stand-alone already does this with this (shared) dir, but if you only use the lr-core, it doesn't link it.

ppsspp/lr-ppsspp: (QOL) link save file dir for libretro core, and (BUG) resolve conflicts on removal

---

scriptmodules/supplementary/xpadneo.sh

New stable version:
* improved compatibility with the new BLE enabled controller firmware
* better compatibility with kernels 5.12 or later and latest DKMS versions. On kernels 5.12 or later should no longer Bluetooth ERTM is not unconditionally disabled anymore. For better stability, it's generally recommended to upgrade controllers to the new BLE firmware variant (version 5.x and above) for improved connection stability
* fixed rumble throttling for modern (BLE enabled) firmware
* fixed an issue conforming to the Linux input spec better which improves compatibility with jinput
* improved documentation

xpadneo: upgrade to v0.9.2

---

scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh

Forum post: https://retropie.org.uk/forum/topic/32790/retroarch-keyboard-hotkeys
Currently, LS / RS buttons enable the `input_load_state` / `input_save_state` hotkeys in RetoArch for joystick inputs: https://github.com/RetroPie/RetroPie-Setup/blob/b2012749de22b1c5c1a55bc9ce8d39191ec928a3/scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh#L178-L183
This is not the case for keyboard inputs: https://github.com/RetroPie/RetroPie-Setup/blob/b2012749de22b1c5c1a55bc9ce8d39191ec928a3/scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh#L327-L332
All other hotkeys, however, are handled consistently between the two including:
* `input_state_slot_decrease`
* `input_state_slot_increase`
* `input_reset`
* `input_menu_toggle`
* `input_exit_emulator`
This change …

Add input_load_state / input_save_state keyboard hotkeys for RetroArch during input configuration

---

scriptmodules/supplementary/runcommand/runcommand.sh

Added 2 new parameters for the runtime-generated `retroarch.cfg`:
* `libretro_log_level` will add more debug messages from the libretro core, in addition to the frontend debugging messages.
Cand be useful to diagnose core issues, since `--verbose` activates just the frontend logging.
* `libretro_directory` is set to the core file folder (i.e. `/opt/retropie/libretrocores/lr-<core>`).
It is used by during netplay, as a client, when RetroArch attempts to re-load the core used during netplay.
Basically, when connecting to a remote netplay host, RetroArch will try to locate a `core.info` file and then try to re-load the core file. If any of them is missing, the connection fails with "Couldn't find a suitable core or content file".
The netplay issue was reported and diagnosed in #3161. Rather …

runcommand: add more parameters for RetroArch

---

scriptmodules/emulators/amiberry.sh

Changed the license file link and updated the upstream project location.
Changelog (taken from upstream https://github.com/BlitterStudio/amiberry/releases/tag/v5.3):
New:
* statusline resync indicator, merged from latest WinUAE
Fixes:
* AmiQuit was missing from boot-data.zip file
* Fixed P96 not working anymore in some environments
* Navigation in Custom controls when using SDL2 versions older than 2.0.14 wasn't correct
* input options were not properly parsed when using default.uae on startup, until the GUI was opened once
* don't overwrite all of changed_prefs when enabling autoheight in DMX
* Reverted CIA changes until upstream bug is fixed (fixes Mega Typhoon,Cruise for a corpse, probably more, see https://github.com/BlitterStudio/amiberry/issues/985)
Improvements:
* updated WHDLoad …

amiberry: upgrade to version 5.3

---

scriptmodules/emulators/amiberry.sh

Amiberry uses it to download the WHDLoad and GamesControllerDB updates.
Since we switched to `curl` for downloads, `wget` may not be installed and updates would fail.

amiberry: add wget dependency

---

scriptmodules/libretrocores/lr-desmume.sh

platform var needs the additional 'unix' keyword since the changes in https://github.com/libretro/desmume/commit/3af49d8d5d851a512d1be34a4ff369b813f57313 or else the wrong target platform is used (it tries to include x86 specific code)

lr-desmume - fix building on arm

---

scriptmodules/emulators/hatari.sh
scriptmodules/libretrocores/lr-hatari.sh

https://github.com/libretro/hatari/commit/245e1a126f8920cc7f6fbb582fdc9fd110de7a30 changes the include paths for CapsLibAll.h which breaks our build script.
This change adds the include path for the caps headers ($md_build/src/includes/caps) to CFLAGS which resolves it.
Also remove the symlink creation in hatari.sh for the caps5 include path that is no longer used.

lr-hatari - fix build failing due to CapsLibAll.h include path change

---

scriptmodules/supplementary/scraper.sh

One of the depedencies updates has broke the `scraper` build [1].
Until the compatibility is restored (could happen) or scraper is updated (unlikely), just use a previous version of the dependent Go library.
[1] https://github.com/J-Swift/thegamesdb-swagger-client-go/commit/06967c20ca1d18e7fbba5929d1b4bf930052956d#commitcomment-75241057

scraper: fix building the package

---

scriptmodules/libretrocores/lr-pcsx-rearmed.sh

Upstream introduced recently an ASM optimized path for NEON platforms, enabled with a new `define`.
Added the new define for NEON platforms, otherwise the build fails because it picks the wrong ASM path.
Introduced in https://github.com/libretro/pcsx_rearmed/commit/047899a4f30d4a11e467e6b5aa0ba4cbf94c3f6b
NB: standalone doesn't seem affected, since the `makefile` is created properly by `configure`.

lr-pcsx-rearmed: fix build for NEON platforms

---

scriptmodules/libretrocores/lr-mess.sh

Recent changes in upstream MAME changed the resulting target filename, consequently the libretro core file needs to be renamed.
Fixes: #3571

lr-mess: update the binary core target result

---

scriptmodules/emulators/retroarch.sh
scriptmodules/emulators/retroarch/mamemess_libretro.info
scriptmodules/emulators/retroarch/mess2016_libretro.info
scriptmodules/emulators/retroarch/mupen64plus_libretro.info

Upstream core info repository doesn't contain core info files for:
* Mupen64Plus (obsolete upstream, the Plus/Next variant is the only one that has core info). Based on Mupen64Plus-Next core info file
* Mess (upstream doesn't build/distribute it). Based on the Mame core info file
* Mess2016 (upstream doesn't build/distribute it). Based on the Mame2016 core info file
This should complement 55aab04a6bb220e001bb0f5cbbafab0a62ecee08, where core info files have been added to RetroPie's RetroArch installation.
In the end, I think the `retroarch` package is the place to add the extra info, since they're only consumed by the front-end, plus it's less files needed to be modified.

retroarch: add extra core info files for missing upstream files

---

scriptmodules/supplementary/emulationstation.sh

Added `mesa-utils` for `glxinfo`, used during build to detect the OpenGL version.

emulationstation: add mesa-utils dependency on X11

---

scriptmodules/libretrocores/lr-pcsx-rearmed.sh

The libretro/pcsx_rearmed NEON gpu plugin now can also run on arm64 and x86, and it's makefile should be able to detect when to enable those things. Remove the 'else' case and let it do the detection.
libretro/pcsx_rearmed#690

lr-pcsx-rearmed: trust the project's makefile to detect defaults

---

scriptmodules/ports/alephone.sh

The autogen.sh script has been removed upstream in favour of using autoreconf -i
Switch to checking for autogen.sh and use it if present, otherwise use autoreconf -iv (--install --verbose).
Add required autoconf-archive as a dependency.

alephone - fix building due to removal of autogen.sh

---

scriptmodules/system.sh

This allowed the emulator compilations to work for me using Bunsen Linux on a fairly old PC which is unable to run Ubuntu.

Add Bunsen Linux to supported flavours

---

scriptmodules/system.sh

Pretty much what it says on the tin -- add a minimal definition to enable support for the RockPro64.
Tested under vanilla Debian 11 (bullseye) with stella and mame2003 cores.

Add support for Pine64 RockPro64 board.

---

scriptmodules/emulators/dosbox-staging.sh

Full changelogs: 
* major release: https://dosbox-staging.github.io/v0-79-0/
* minor release: https://dosbox-staging.github.io/v0-79-1/
TL;DR: many improvements done on the audio front where the SB16 will now sound exactly as it's supposed to, compressor to prevent clipping, etc. Inclusion of a nice mouse driver for Windows 3.1. Performance improvement for low-spec devices (eg. RPi) and other graphical improvements (CGA, shaders, etc). Localization improvements. xbox-compatible controller mapperfiles for 180+ games.
**All credits to DOSBox' community and of course to the many excellent contributors of Staging.**
Script updated to include new required files and better default values for RPi3/4 devices. 
* `libspeexdsp-dev` has been added as a new dependency. 
* New required files (shaders, …

DOSBox Staging 0.79 update 

---

scriptmodules/admin/image.sh
scriptmodules/emulators/dosbox-staging.sh
scriptmodules/emulators/dosbox-staging/speexdsp_simd_disable.diff

The speexdsp meson wrap enables armv7/neon instructions when building for armv6 (Raspberry Pi 1). This causes compilation to fail.
Patch meson.build to disable the simd option for older arm platforms (that don't have the neon platform flag).

dosbox-staging - fix building for armv6

---

scriptmodules/system.sh

crc and simd and enable by default in all versions of gcc so would be redundant to add here.
Cortex-A57 armv8.0 has optional crypto extensions so they are not enabled by default. TX1 and TX2 have these extensions available in hardware.

enable crypto extensions for TX1 and TX2

---

scriptmodules/emulators/retroarch.sh

Current patched tree is at https://github.com/cmitu/retroarch/tree/retropie-v1.12.0
**NOTE**: it includes one post-v1.12.0 change (https://github.com/libretro/RetroArch/pull/14537) which solves an issue with shader presents affecting configurations using the `glcore` video driver.
Scriptmodule changes:
1. Added a few more default options to the main config:
- `remap_save_on_exit` set to false (new option), since by default any changes will be auto-saved on exit. Prevents users accidentally messing their controls and keeps the behavior similar to the previous versions.
- `menu_disable_search_button`  set to `true` (new option) instead of using our patch for disabling the Search action.
- (cosmetic) disabled some Quick Menu items (Overlay and Favorites).
2. Removed `rgui_show_start_screen`, …

retroarch: update to v1.12.0

---

scriptmodules/ports/kodi.sh

The Kodi PPA for Jammy (22.04) and later doesn't include `kodi-inputstream-rtmp` anymore. Trying to install the version from the Ubuntu repositories will produce a conflict due to mismatched dependencies with the versions from the PPA, so  don't try to install the package.
NOTE: the addon can be later installed from inside Kodi, which is also recommended in its installation page: https://kodi.tv/addons/matrix/inputstream.rtmp

kodi: fix installation on Ubuntu 22.04 and later

---

scriptmodules/ports/lzdoom.sh

Updated to 3.88b (released on Feb 2022) to include recent fixes, should fix building with recent `gcc` (Ubuntu 22.04, Debian testing).
Changed the license URL to the location on the main branch and removed the extra quotes around the `snd_mididevice` parameter.

lzdoom: update to 3.88b

---

scriptmodules/ports/yquake2.sh

This version came out in May, and improves controller support, adding better handling of menus and the possibility to use a `gamecontrollerdb.txt` file, instead of setting an environment variable to set up the SDL2 game controller.

Update Yamagi Quake 2 to version 8.10

---

scriptmodules/system.sh

Add the Debian version for the Debian Edition of Linux Mint.
- version 4 is based on Debian 10 'buster
- version 5 is based on Debian 11 'bullseye'
Older versions (1 to 3) are no longer supported upstream.

systems: add support Linux Mint LMDE

---

scriptmodules/emulators/retroarch.sh
scriptmodules/helpers.sh
scriptmodules/ports/alephone.sh
scriptmodules/ports/srb2.sh
scriptmodules/supplementary/emulationstation.sh
scriptmodules/supplementary/runcommand.sh
scriptmodules/supplementary/sdl1.sh
scriptmodules/system.sh

There was a mix of compareVersions "$__os_debian_ver" OP $arg and [[ "$__os_debian_ver OP $arg ]] around the code.
As $__os_debian_ver is always an integer, use the bash built in operators for performance.
The compareVersions call is significantly slower as it uses an external command (dpkg).

Use bash operators instead of compareVersions for __os_debian_ver

---

scriptmodules/ports/yquake2.sh

I know you've just updated to the 8.10 version, but today is Quake II's 25th anniversary, and Yamagi released 8.20, which adds even more improvements to controllers. Now, you can even change sticks layout and deadzone sizes from the menu. Playing on a RPi 3 B+, no performance lost from previous versions.
To make this PR have a little more value, I've also let the expansions' source clone from a certain tag, instead of doing it from "master". This let the expansion take into account a certain version, just like the main repository.

Update Yamagi Quake 2 to version 8.20

---

scriptmodules/ports/lzdoom.sh
scriptmodules/ports/lzdoom/01_remove_cmake_arm_options.diff
scriptmodules/ports/lzdoom/02_lzma_sdk_dont_force_arm_crc32.diff

The changes added enable `lzdoom` to build (and run) on RPI1/RPI0:
- remove the `ARMV8` build option, since it used upstream as a toggle between RPI2 or RPI3 CPU parameters. Since we're passing the platform CPU flags to `gcc` ourselves, they're not really needed and they'll add the wrong options for other ARM platforms
- patch the included LZMA SDK CRC calculation to not assume every ARM platform supports hardware-assistet CRC (i.e. ARMv8). This will fix the build for RPI1/ARMv6 platforms

lzdoom: fix the build for RPI1/ARMv6 platforms

---

scriptmodules/supplementary/xboxdrv.sh

Python3 is the default in current Debian & friends distros (and `python2` was also recently [removed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027108) from Debian _sid_), but the current fork from zerojay/xboxdrv.git doesn't support it.
Upstream has moved back to Github [1] and added the necessary fixes for building with `python3`, so merge the upstream code with the various fixes added in zerojay/xboxdrv under retropie/xboxdrv.git. This fixes building under RaspiOS _bullseye_.
Since the new Sconsfile doesn't build with `python2` anymore, make the `python3` usage explicit for the `deps` and `build` phases.
[1] https://github.com/xboxdrv/xboxdrv

xboxdrv: upgrade the build process to python3

---

scriptmodules/emulators/amiberry.sh

- Reverted CD32 autoloader to normal config
- Fixed uaegfx overlay bounds check
- added linefeed in logging errors from CDDA init
- CDDA and AHI wouldn't respect the selected SDL2 audio device
- CDDA audio would fail to init in some cases
- Controller axes inverted status was not respected when reading their input 
- CD32 mode wasn't properly applied when using WHDLoad booter
- fixed passing string to write_log in Panel Paths
- Enumeration of Recording devices would write into sound device ID
- NVRAM path wasn't used in CD32/CDTV configs
- uaegfx blitter was accidentally disabled
- uaegfx masked and overlapping blit fix
- gfx_top_windowed/gfx_left_windowed replacement config entries
- When using Alt-Tab, the keys were not released when returning control
- When selecting a folder/file the …

Update Amiberry to 5.5.1

---

scriptmodules/emulators/xroar.sh

The yearly XRoar update. The `--disable-kbd-translate` config option is no longer valid, so it has been removed from the build step.
Notable chanes since 1.0.9:
- version 1.1, Thu 21 Jul 2022
* New GDB monitor commands [by Tormod Volden]
* Support 1M or 2M in CoCo 3 [with Christopher Hawks]
* Support K7 cassette image files (read-only)
* Support UTF-8 block characters in -type for MC-10
* Type ASCII BASIC from file on MC-10
* NEW Matra & Hachette Alice support (keyboard layout, built-in profile)
* New meta-options -machine-opt and -cart-opt
* New ide-addr=address cart-opt
* 6801/6803: fix some illegal instruction timings [George Phillips]
* Fixed uppercase 'G', lowercase 'j' and 'w' glyphs for 6847T1 [Tim Lindner]
- version 1.2, Thu 27 Oct 2022
* Fixed comma, lowercase 'm', lowercase 'Ã¸' …

xroar: update to version 1.3

---

scriptmodules/libretrocores/lr-scummvm.sh

Recently, upstream re-organized the repository and changed the build process. This commit adapts the scriptmodule to the new structure:
- building is done directly from the main repo source
- data files neeed for the core is built with `make datafiles` and copied to our package
- ScummVM is upgraded to current stable (v2.6.1) in the process. NOTE: WIP engines are not built by default and are not included
- switched the theme the `scummremastered`, added in 2019 in ScummVM
- license changed to GPLv3 (same as the main ScummVM project)
Fixes: #3617

lr-scummvm: update build recipe, upgrade the core to v2.6.1

---

scriptmodules/libretrocores/lr-scummvm.sh

Fixes the creation of the `scummvm.zip` bundle file during building.

lr-scummvm: added `zip` as dependency

---

scriptmodules/supplementary/emulationstation.sh

Emulationstation does not run with -DUSE_GL21=On if gpu only supports GL <= 2.0. Fix OpenGL version check.

emulationstation: fix OpenGL version 2.1 check

---

scriptmodules/admin/wikidocs.sh

I noticed these error when running `sudo RetroPie-Setup/retropie_packages.sh wikidocs` on  a prisitine RetroPie installation (RetroPie-Setup commit 058f096c)
```
= = = = = = = = = = = = = = = = = = = = =
Installing dependencies for 'wikidocs' : Generate mkdocs documentation from wiki
= = = = = = = = = = = = = = = = = = = = =
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/cmitu/mkdocs-altlink-plugin
Cloning https://github.com/cmitu/mkdocs-altlink-plugin to /tmp/pip-req-build-wwu4cdtd
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
----------------------------------------
Command "python setup.py …
```

wikidocs scriptmodule: add missing dependencies

---

scriptmodules/supplementary/emulationstation.sh

If a Gnome/Wayland or Weston/Wayland session is started under Ubuntu 22.04, SDL2 falls back to x11 videodriver. There is ARM hardware which runs much faster, and without graphical glitches, if the SDL2 wayland video driver is used. To prevent SDL2 from using x11 video driver, export "SDL_VIDEODRIVER=wayland", if Wayland session is detected.

emulationstation: use SDL2 wayland videodriver if applicable

---

scriptmodules/supplementary/emulationstation.sh

gles can be used under x11, wayland, kms, dispmanx and fb. Respect gles platform flag and build emulationstation with gles renderer if requested.

emulationstation: allow gles for all platforms

---

scriptmodules/system.sh

-not officially supported.
-tested with NXP i.MX8M mini and i.MX6 dual lite with kernel 6.1 mainline and Ubuntu 22.04.   
-use mesa etnaviv driver if kernel uses etnaviv kernel driver.
-not tested with NXP gpu kernel module and driver blob vivante/galcore.

Add recognition of NXP imx socs i.MX6 dual lite, i.MX6 quad and i.MX8M mini 

---

scriptmodules/supplementary/raspbiantools.sh

PulseAudio is pulled by installing the desktop since [1] on `buster`. Changed the install procedure to disable it after adding the desktop and to replace the volume applet for `lxpanel` with the version that supports ALSA (otherwise `lxpanel` crashes, leaving the deskop unusable).
[1] https://www.raspberrypi.com/news/new-raspberry-pi-os-release-december-2020/

raspbiantools: disable PulseAudio on Buster after install

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/emulators/retroarch.sh
scriptmodules/libretrocores/lr-flycast.sh
scriptmodules/supplementary/sdl2.sh
scriptmodules/system.sh

Don't mix Vulkan with x86 and x11 platform flags. Vulkan can be used with other system platforms and wayland / drmkms / fb. Add a "vulkan" platform flag which can be used to enable it if applicable.

add platform flag vulkan

---

scriptmodules/emulators/yabasanshiro.sh

Debian >= 10 has no python-pip package. Use python3-pip instead.

yabasanshiro: remove missing python-pip package

---

scriptmodules/admin/setup.sh

Since a98c59597f1ae6e50a12b08f396e1bbd2dae7e93 we now need to check if a module is enabled.
This fixes incorrectly showing config modules like wifi on systems where it is not supported.

setup - only show enabled modules in config section

---

scriptmodules/libretrocores/lr-scummvm.sh

Modified the `unzip` command for the core system files to overwrite unconditionally the files, otherwise we get a prompt when upgrading.

lr-scummvm: fix interactive prompt from unzip

---

scriptmodules/supplementary/emulationstation.sh

I have done some tests running weston/wayland from CLI with a rpi4/raspbian-lite. After startup of weston $XDG_SESSION_TYPE is still "tty". If I start a weston/wayland session with graphical login (display manager sddm or gdm3) $XDG_SESSION_TYPE is "wayland". $WAYLAND_DISPLAY can be found in both constellations and seems to be more reliable. On a rpi4 $WAYLAND_DISPLAY=wayland-0. Just replace $XDG_SESSION_TYPE with $WAYLAND_DISPLAY.

emulationstation: modify wayland detection

---

scriptmodules/packages.sh

Added a fallback for getting the `modified_date` of a module if the module's file is not tracked by `git`. If the module is just copied in the `scriptmodules` folder or under `ext`, but not part of a `git` repo, use the modification date of the file. This avoids re-building the module when a mass update is run.
Noticed this in [this forum topic](https://retropie.org.uk/forum/topic/33922/need-help-with-openbor-retropie-extra-exarkuniv/15), seems like [RetroPie-Extra](https://github.com/Exarkuniv/RetroPie-Extra) copies selected module files under `ext`, while the main repository folder is kept separately.

packages: amend update detection for untracked modules

---

scriptmodules/helpers.sh
scriptmodules/supplementary/wifi.sh

If the OSK is installed it will be used for input, otherwise it will fall back to using dialog --inputbox
function takes 3 parameters:
The title of the dialog, the default text and a minimum number of characters to accept.
Adjusted wifi module to use the new inputBox. There is no need to redirect cmd output with 2>&1 >/dev/tty as the inputBox function does this.

helpers - added inputBox function that uses the OSK

---

scriptmodules/admin/joy2key/osk.py
scriptmodules/helpers.sh
scriptmodules/supplementary/retronetplay.sh

Replaced the `dialog` based inputboxes for host/nick/port in the netplay configuration prompts with the new `inputBox` helper, which uses the OSK (when installed).
Should make it easier to configure netplay without a keyboard.
Additional changes:
* the `osk.py` script was modified to accept an existing value instead of always starting with an empty input.
* modified the `inputBox` and added some notes on return value. Also changed the `dialog` based input prompt to be similar to how `osk.py` shows it (_Enter the `$value`_).

netplay: use the OSK to configure netplay options

---

scriptmodules/supplementary/samba.sh

Removed the `samba` service name, it's not used since _stretch_.
Thank you @gizmo for the reminder.
Should fix #3643

samba: update restart to remove old service name

---

scriptmodules/packages.sh

Allows proper update detection for modules with 7-character commit sha, such as some RetroPie-Extra modules.

packages.sh - function rp_hasNewerModule - variable length commit hash

---

scriptmodules/supplementary/sdl2.sh

Due to https://github.com/libsdl-org/SDL/issues/5399 which breaks darkplaces-quake in RetroPie we are keeping Buster at 2.0.10 until there is a resolution.
Added libsamplerate0-dev dependency to module.
Branch includes reworking the patch for kms modesetting via env variables, some minor changes to our Mali and RPI patches, and some removal of no longer needed changes.
It also includes removal of some debian/control build dependencies which were added to upstream to align with Debian's packaging. The additions caused dependencies like libwayland-dev and libpulse-dev to be required for all platforms. As we handle adding dependencies in our sdl module code, these have been removed in our retropie-2.0.16+ sdl2 branches.
Include fix for detection of videocore due to our renamed include …

sdl2 - updated to retropie-2.26.3 branch for bullseye

---

scriptmodules/emulators/hypseus.sh

Since SDL has been updated, make sure we don't encounter the performance issue reported on 2.0.16+ with RPI. After 2.0.16, using `SDL_TEXTUREACCESS_TARGET` for a `SDL_Texture` leads to an extra conversion inside SDL, so avoid it by telling `hypseus` to use `SDL_TEXTUREACCESS_STREAMING`.
Previous discussion and analysis of the performance impact:
* https://github.com/DirtBagXon/hypseus-singe/issues/66
* https://retropie.org.uk/forum/topic/18505/

hypseus: update runtime parameters for ARM

---

scriptmodules/emulators/dosbox-staging.sh

This fixes building on armv6 devices such as the RPI1.
The meson speexdsp script will test for neon support by building for armv7+neon. This will cause neon to be enabled when building for the RPI1, breaking compilation.
Fixes #3651

dosbox-staging - disable speexdsp simd support on armv6 devices

---

scriptmodules/emulators/mupen64plus.sh

GlideN64 overwrites settings if config version is to old. Current config version is 29. https://github.com/gonetz/GLideN64/blob/1f4d04f43b53739bc9b128ab5577d20e3d60ed6a/src/Config.h#L8

mupen64plus.sh: update GlideN64 config version

---

scriptmodules/emulators/mupen64plus.sh

Video output of rice plugin flickers or is black with ScreenUpdateSetting=1 with rpi mesa driver. ScreenUpdateSetting=7 fixes it. Fix issue #3138.

mupen64plus.sh: fix issue #3138

---

scriptmodules/libretrocores/lr-dosbox-pure.sh

This fixes building on Bullseye.
According to https://github.com/libretro/dosbox-pure/commit/603b1c7ae
>Switch to gcc 9 to avoid buggy assembly genetation [sic] of gcc 10
>On armv7l, gcc 10.2 with -O2 on the file core_dynrec.cpp generates assembly that wrongfully passes NULL to the runcode function
>resulting in a segfault crash. It can be observed by writing block->cache.start to stdout twice where it is NULL at first
>and then the actual value thereafter. This affects upstream SVN DOSBox as well as this core.
This may be needed for dosbox-svn also if this also affects that. That needs testing.

lr-dosbox-pure - install g++ v9 on arm if v10 is the system default

---

scriptmodules/emulators/dolphin.sh
scriptmodules/emulators/mame.sh
scriptmodules/emulators/openmsx.sh
scriptmodules/emulators/ti99sim.sh
scriptmodules/libretrocores/lr-bsnes.sh
scriptmodules/libretrocores/lr-mame.sh
scriptmodules/ports/dxx-rebirth.sh
scriptmodules/system.sh

gcc -dumpversion on GCC >= 7 seems to provide the major version but the documentation suggests this depends on how it's configured. We only need to test the major version so using compareVersions isn't required.
https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html states:
>Print the compiler version (for example, 3.0, 6.3.0 or 7)—and don’t do anything else. This is the compiler
>version used in filesystem paths and specs. Depending on how the compiler has been configured it can be
>just a single number (major version), two numbers separated by a dot (major and minor version) or three
>numbers separated by dots (major, minor and patchlevel version).
Ensure __gcc_version only contains the major version just in case in system.sh

Don't use compareVersions for GCC version comparisons

---

scriptmodules/emulators/minivmac.sh
scriptmodules/emulators/minivmac/gcc10_fix.diff

Move the SDL declarations from MYOSGLUE.h to MYOSGLUE.c This fixes building on GCC 10+ due to the MYOSGLUE.h header being included by every source file.
PR has been sent upstream https://github.com/vanfanel/minivmac_sdl2/pull/3

minivmac - include patch to fix building on gcc 10+

---

scriptmodules/emulators/ti99sim-sdl1.sh
scriptmodules/emulators/ti99sim-sdl1/missing_cstdio.diff
scriptmodules/emulators/ti99sim.sh
scriptmodules/emulators/ti99sim/missing_cstring.diff

ti99sim:
src/core/device-support.cpp was missing a cstring include which throws an error on recent g++
ti99sim-sdl1:
include/common.hpp was missing a cstdio include required for fclose

Fix building of ti99sim / ti99sim-sdl1 on recent g++

---

scriptmodules/system.sh

-Update Debian unstable version. Current Debian trixie/unstable has version 13. Debian bookworm/testing has version 12. 
-Add Ubuntu 22.10. Ubuntu >= 22.10 and Debian >= 12 have the package libsdl2-tests. Set __os_debian_ver="12" for Ubuntu versions >= 22.10.

Update OS versions

---

scriptmodules/libretrocores/lr-prboom.sh

Until [1] is resolved - one way or another - use a good known commit to build the PrBoom core. Upstream core is relatively static, so we're not loosing much for pinning the version.
[1] https://github.com/libretro/libretro-prboom/issues/181

lr-prboom: workaround a recent regression

---

scriptmodules/supplementary/emulationstation/configscripts/mupen64plus.sh
scriptmodules/supplementary/emulationstation/configscripts/openmsx.sh
scriptmodules/supplementary/emulationstation/configscripts/reicast.sh
scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh

This fixes a few of the EmulationStation controller configscripts to properly sanitize the `DEVICE_NAME` when it's used as part of filenames and `sed` / `grep` commands.
Earlier this year, a [change](https://github.com/paroj/xpad/commit/4a64f5caefb2e571d90240f9b1a2bbe1a8950a74) was made to `xpad` in which certain 8BitDo controller started to register with the system using the name "8BitDo Ultimate Wireless / Pro 2 Wired Controller".  When I attempted to set up this controller, a few of the configscripts were failing when they weren't with the prior name -- "8BitDo Ultimate Wireless Controller".
While working through the issue, I found that there was some existing code that applied sanitization to the `DEVICE_NAME` within the ES configscripts: …

Fix device name sanitization within ES controller configscripts

---

scriptmodules/emulators/openmsx/retropie-init.tcl

* fixed a typo in the joystick name cleanup instruction. When the joystick name contained the cleaned up characters, the auto-loading didn't work
* simplified the regex for both joystick and rom name cleanup instructions
* removed the 'osd' menu hiding from our code, since openMSX is now doing it itself (after a small delay). This prevents a warning message showed if the 'osd' menu cannot be found

openmsx: update the RetroPie initialization script

---

scriptmodules/emulators/dolphin.sh

Since upstream started requiring a C++20 capable compiler (gcc 10 min), update our build support based on the available gcc version:
* minimum gcc version is 8 (Ubuntu 18.04, Debian 10)
* current master can compile with gcc 10 (Debian 11, Ubuntu 22.04)
* allow building with gcc 9 (Ubuntu 20.04)
Upstream has transitioned and recommends using Qt6 for building, so use that when available (Ubuntu 22.04 for now, but Debian 'bookworkm' and 'bullseye-backports' also include it).
Dependencies updated to include `gettext` and `liblzma-dev`.

dolphin: update build requirements

---

scriptmodules/supplementary/retropiemenu.sh

Midnight Commander needs package p7zip to open 7z archives.

retropiemenu.sh: add mc 7zip support

---

scriptmodules/helpers.sh

On a multiarch system both amd64 and i386 versions of a package may be installed.
This would cause both to be returned by dpkg-query on a single line causing the extracting of version and install status to fail.
It now splits the output onto multiple lines and grabs the first line to workaround this.
Fixes #3679

helpers / hasPackage - fix package detection on a multiarch system

---

scriptmodules/supplementary/attractmode.sh

Added the Free fonts, since `attract` will not start without its default font (FreeSans).
The font search code has changed recently, triggering now an error without FreeSans being present.

attractmode: add default font dependency

---

scriptmodules/libretrocores/lr-prboom.sh

Reverts RetroPie/RetroPie-Setup#3668
Upstream has now fixed the issue.

Revert "lr-prboom: workaround a recent regression"

---

scriptmodules/supplementary/emulationstation.sh

The "X is running" test in emulationstation startup script is deprecated. X was replaced by Xorg a long time ago (pre Debian stretch and Ubuntu bionic). The test could be modified to support Xorg, but emulationstation runs quiet well under x11. Just remove it.

emulationstation.sh: remove deprecated "X is running" test

---

scriptmodules/ports/steamlink.sh

* removed the launcher through Xorg since Steam Link can now run with a desktop env on both RaspiOS 10 and 11, choosing between the DRM or MMAL drivers. Tested on a RPI 3 (RaspiOS 10) and RPI 4 (RaspiOS 11).
* adjusted the dependencies to remove xorg/matchbox/zenity since they're not strictly necessary and added a few packages which might not be automatically installed on RetroPie. The list of the packages that `steamlink` tries to install on first run in is `$XDG_DATA_HOME/SteamLink/steamlinkdeps.txt`, I just picked the ones that are not already part of existing dependencies (`vlc` will install most of them).
* disabled the package on 64bit, since is not available there (see https://steamcommunity.com/app/353380/discussions/0/1649917420735113143/)

steamlink: update dependencies and runtime config

---

scriptmodules/inifuncs.sh

As tabled here: https://retropie.org.uk/forum/topic/30714/inifuncs-sh-use-basic-regular-expression-match-in-iniset

inifuncs.sh: using basic RE to allow meta-chars in keys , eg. +()

---

scriptmodules/emulators/amiberry.sh
scriptmodules/emulators/amiberry/01_preserve_env.diff

Release notes - https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.0
Changelog for 5.6.0, with modifications added after 5.5.1:
* New features
- implemented On-Screen Virtual Keyboard
- added VKBD retroarch mapping support and VKBD default toggle key
- decrease mouse map sensitivity on joystick handling
- added new default options in amiberry.conf
- added Warp reset option in Misc Panel
- GUI improvements
- implemented turbo boot option
- added 1024x600 RTG resolution
- allow on-the-fly change of virtual mouse driver
- increased width of dropdowns in Input Panel
- automatically center GUI window when opening
- updated WHDLoad XML to latest version
- updated game controllers db to latest version
* Changes
- refactored input event handling to minimize latency
- rewrite Serial port …

amiberry: update to 5.6.0

---

scriptmodules/libretrocores/lr-caprice32.sh

Upstream uses a shallow submodule, but is tracking a rolling branch that changed since the submodule was added. Older `git` versions cannot fetch the ref registered in the parent repo and the recursive clone fails. It affects Debian _buster_ and Ubuntu 18.04, plus other downstream distros (Linux Mint 19.3).
Clone the repo temporarily and remove the submodule, since it's not used actively by the core. Issue was reporeted upstream in https://github.com/libretro/libretro-cap32/issues/116.

lr-caprice32: work around an upstream cloning issue

---

scriptmodules/supplementary/splashscreen/asplashscreen.sh

EmulationStation, when using the RPI videodrivers, displays at layer 10000. Increased the layer index for video/images in order to run above EmulationStation.

splashcreen: increase the DispmanX layer

---

scriptmodules/emulators/retroarch.sh

Updated the script for v1.15. Pull from https://github.com/cmitu/retroarch/tree/retropie-v1.15.0 into https://github.com/retropie/retroarch/ for our patches on-top of the lastest v1.15.
Changed a few options in the default config:
- removed some rarely used Quick Menu actions to shorten it by default. Rewind/Replay/Record have been toggled off.
- changed the default RGUI look & feel by configuring it to use the 'Tango Dark' theme, similar to the default RGUI theme.
- removed the core cache info file read/writing, since it's not useful for our configuration.
Biggest breaking change since v1.12 is the hotkey handling for keyboard inputs. Previously, when a gamepad was connected and keyboard didn't define any hotkey enable key, the hotkey action on the keyboard would trigger only when the …

retroarch: update to v1.15 & change a few defaults

---

scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
scriptmodules/supplementary/emulationstation/inputconfiguration.sh

* modified the input configuration script to export Vendor/Product IDs, if exported by EmulationStation.
* added vendor/product to RetroArch's script for generating joypad profile.
Fixes #3398

emulationstation: add vendor/product ids to input scripts

---

scriptmodules/supplementary/skyscraper.sh

By default, Skyscraper creates a composite image with screenshot, logo, and box art, and then saves this as a "screenshot" itself:
When the local `esgamelist` is then scraped after that, this already-processed "screenshot" (with logo and box art) has the logo and box art applied to it again, leading to a receding "hall of mirrors" effect. This effect is amplified with repeated scraping:
To prevent this, do not cache these already-processed screenshots when scraping the local `esgamelist` source.

skyscraper - prevent hall-of-mirrors effect

---

scriptmodules/libretrocores/lr-caprice32.sh

Reverts RetroPie/RetroPie-Setup#3698.
Upstream fixed the sub-module clone in https://github.com/libretro/libretro-cap32/pull/131.

Revert "lr-caprice32: work around an upstream cloning issue"

---

scriptmodules/emulators/openmsx.sh
scriptmodules/emulators/openmsx/retropie-init.tcl

Updated to the 18.0 release, which requires GCC 9 and it's installable on Debian 11 (bullseye)/Ubuntu 20.04+.
The input auto-loading script has been updated to use the joystick's SDL name, while previously was using the 'udev' device name. This fixes the issues when the joystick nane (SDL) is different than the 'udev' reported name and thus prevented the auto-loading.

openmsx: bump version to 18.0 and update input config

---

scriptmodules/ports/cgenius.sh

Changes in v3.3.0, from v3.2.0:
- Added Support for Keen 1 version 1.34
- Added Support for Keen 6 version 1.50

cgenius: update to v3.3.0

---

scriptmodules/supplementary/emulationstation.sh

The last runtime detection changes for the build instructions enable the GL21 renderer only on non-RPI platforms. The V3D Mesa driver supports OpenGL 2.1, so enable the GL21 renderer when it's used on a Raspberry Pi.
Without this change, the build will use the GL1.4 renderer.

emulationstation: use OpenGL2 for RPI+Mesa platform

---

scriptmodules/libretrocores/lr-scummvm.sh

libretro build files are now included in the upstream scummvm repository, and the libretro repo is a fork of that.
The `main` branch is now `master` and the libretro makefiles have moved to backends/platform/libretro.

lr-scummvm - fix building due to upstream changes

---

scriptmodules/libretrocores/lr-x1.sh

Changed the source repository to the libretro fork of the core, since it gets a bit of maintenance than the original repo (`r-type/xmil-libretro`) and I noticed a few more core options have been added over the time. The original core repository hasn't been updated since 2017.
Added the licence from the libretro fork.

lr-x1: switch to the libretro repository

---

scriptmodules/system.sh

Added basic support for detecting and building on the Rockchip 3588(s) SOC. The SOC is used in several ARM based SBC including Radxa Rock 5(A/B), Orange Pi 5(B), Khadas Edge 2. The CPU is an octocore package with 4x Cortex-A76 + 4x Cortex-A55 cores.
There are several distributions that support these systems, vendor provided images including a proprietary Mali blob with OpenGLES 3.2/OpenCL support or community provided images using either a Mesa fork for GLES/X11/Wayland support. For now, the platform has an `x11` flag to allow most of the emulators to be installed, but we might switch to dynamically detecting the desktop platform (i.e. `wayland` / `x11` depending on the system).

system: add support for the Rockchip 3588 platform

---

scriptmodules/emulators/dolphin.sh

Recently [1], Dolphin dropped support for Qt5.
For systems where Qt6 is not available (Debian 11 _bullseye_), use a commit from before the change to prevent the build from failing.
[1] https://github.com/dolphin-emu/dolphin/pull/11775

dolphin: fix build when qt6 is not availble

---

scriptmodules/emulators/amiberry.sh

Among others, fixes some input issues, one of them reported in the forums, and a Vero4k black screen during emulation. Full changelog at https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.1
Bugfixes:
- Hardfile properties were always set to default (fixes #1077)
- cycle exact was incorrect enabled sometimes (fixes #1075)
- Fix foreign disk image support when drive is standard Amiga 3.5" DD
- hsync events should be before misc events
- fixed uaegfx board parameters
- uaegfx board name is UAE, not uaegfx.card
- Fix helptext formatting in CPU panel (fixes #1088)
- use double-quotes to denote inches in GUI
- when using --autoload with a filename in the current path, Amiberry would crash (fixes #1091)
- fix build errors with GCC 13.1 (fixes #1100)
- savestate cmd line option would not …

amiberry: update to 5.6.1

---

scriptmodules/supplementary/configedit.sh

Can contain many thousands of '.png' images, if cheevos have been enabled.

configedit - exclude 'thumbnails' directory in manual edit

---

scriptmodules/supplementary/golang.sh

Fixes compilation for 'google.golang.org/protobuf', which needs 'math/bits', available in go 1.9 and later.

golang: upgrade to a newer version

---

scriptmodules/supplementary/audiosettings.sh

On RaspiOS (10/11), the ALSA configurations folder doesn't exist, so make sure we're creating it before saving/moving the ALSA configuration file we generate with the scriptmodule.

audiosettings: ensure ALSA configuration folder exists

---

scriptmodules/emulators/mame.sh

Forcing 'char' to be signed fixes crashing in some drivers, needed on ARM.
The default behavior for 'char' is arch/ISA specific, see: https://stackoverflow.com/questions/46463064

mame: force 'char' to be signed on ARM platforms

---

scriptmodules/libretrocores/lr-pcsx-rearmed.sh
scriptmodules/libretrocores/lr-snes9x.sh

Included `lr-snes9x` and `lr-pcsx-rearmed` in the main section when `aarch64` is detected, otherwise they won't be installed during a basic installation.

aarch64: add PS1 and SNES emulators to default installation

---

scriptmodules/emulators/scummvm.sh

Changes included: 
* updated the version to 2.7.1, released at the end of July. A short changelog is in the commit message, but it's mainly bugfixes.
* modified the startup script so `extrapath` is only set when the user hasn't configured it. It should fix the issue reported in #3748.

scummvm: update to 2.7.1 and tweak startup script

---

scriptmodules/emulators/dolphin.sh

Since May 2023, Qt6's SVG component is required, make sure we install the corresponding dependency.

dolphin: update dependencies for latest version

---

scriptmodules/emulators/dolphin.sh

Ubuntu seems to have different names for the QtSvg module, so try to install the available package depending on the distro release.
Fixes #3756.

dolphin: fix Qt6 Svg dependency for Ubuntu

---

scriptmodules/emulators/retroarch.sh

Upgraded RetroArch to current v1.16.0 version and added a new configuration option to disable creation of runtime logs (saved when the content is closed by the core).
Updated RetroArch source with our patches can be pulled into our repo from https://github.com/cmitu/RetroArch/tree/retropie-v1.16.0. Source is rebased over the latest 1.16.0 bugfix tag (1.16.0.3).
-----------------
Notable changes in v1.16.0, selected from the full release announcement (https://www.libretro.com/index.php/retroarch-1-16-0-release/):
General:
- Add new API for microphone support (no core supports this at the moment)
- Make cmd interface more useful for replay information
- Use refresh rate instead of core fps for frameskip timing
- Allow RETRO_ENVIRONMENT_SET_MEMORY_MAPS also after core startup. Change the …

retroarch: upgrade to v1.16.0

---

scriptmodules/supplementary/skyscraper.sh

- Update source repo to active fork: https://github.com/Gemba/skyscraper
- Scriptmodule enhancements and fixes (co-authored by @Gemba)
(Original first post follows):
> Upstream repository is currently not accepting pull requests, to focus on developing other projects. So I've made a couple of patches to update the source with one bug fix and one QOL improvement.
> 
> (BUG) Apple2 exts: normally, most roms are cached by hashing the file content. However, apple2 disk images are volatile and may change content. Patch `01_apple2_exts.patch` adds apple2 exts to list of exceptions, to be cached by file name instead.
> 
> (QOL) tg16 system: Many themes support an independent 'tg16' system folder. Patch `02_add_tg16_system.patch` adds tg16 alias for pcengine titles.

Skyscraper - update source repo and scriptmodule

---

scriptmodules/helpers.sh

The 'libfreetype6-dev' package has been replaced with `libfreetype-dev` since Debian 11 _bullseye_ [1]. It's not present in the current Debian testing (_trixie_) and Ubuntu 23.10 [2]
Added a mapping for the package, since it will help installing RetroPie on Ubuntu 23.10. When we stop supporting _buster_, we can remove the mapping and replace any `libfreetype6-dev` dependencies in the scriptmodules with the new package.
[1] https://packages.debian.org/bullseye/libfreetype6-dev - marked as 'transitional'
[2] https://packages.ubuntu.com/search?keywords=libfreetype6-dev - removed from Ubuntu 23.10

helpers: handle deprecation of 'libfreetype6-dev'

---

scriptmodules/helpers.sh

Starting with the Bookworm RaspiOS release, the Linux kernel package is no longer a monolithic package and it has been split in several packages, named after their build configuration, which in turn is dictated by the Pi model and architecture (`armhf`/`aarch64`).
This change adds support for the Linux kernel headers packages on the new OS release, which followed a similar split from the previously used `raspberrypi-kernel-headers` package.
NOTES:
* mixed kernel/userland archs are not supported. By default, an `armhf` RaspiOS installation will boot the Pi4/Pi5 with the 64bit kernel, but the corresponding headers package is not installable. While the Pi4 can still boot a 32bit kernel by adding `arm_64bit=0` to `/boot{/firmware}/config.txt`, the Pi5 does not have this capability.
* on the …

helpers: add support for the Bookworm Linux kernel header packages

---

scriptmodules/helpers.sh
scriptmodules/supplementary/raspbiantools.sh
scriptmodules/system.sh

Added support for detecting if running on a Armbian built system. Armbian is built on Debian/Ubuntu, so we're not changing the OS release/name.
* Added support for Armbian's Linux kernel package naming, in order to be able to install the kernel headers.
* Removed the ZRAM config from our own menu, Since Armbian has its own configuration tool (`armbian-config`) that handles it. ZRAM is configured and enabled by default on Armbian images.
NOTE: I'll probably add some changes later on to add `armbian-config` to the menu, replacing `raspi-config`. I just need to create a proper/usable icon for it.

systems: add support for Armbian

---

scriptmodules/supplementary/xboxdrv.sh

According to the Raspi docs, `dwc_otg.speed=1` sets the USB port to USB 1.0 speed (down from 2.0) and should be enabled only for debugging purposes. I don't think it's needed anymore, since the `xpad` kernel driver has replaced `xboxdrv` for supporting Xbox compatible gamepads.

xboxdrv: remove obsolete USB options

---

scriptmodules/emulators/atari800.sh

Updated to latest release tag. Use the `videocore` flag to activate the `rpi` target in the build configuration.
Notable changes in 5.0.0 (full changelog at https://github.com/atari800/atari800/releases/tag/ATARI800_5_0_0):
* AVI video recording (Alt+V hotkey) by Rob McMullen
* MP3 audio and other audio codecs for audio recording
* New cartridge types supported:
- 71: Super Cart 64 KB 5200 cartridge (32K banks)
- 72: Super Cart 128 KB 5200 cartridge (32K banks)
- 73: Super Cart 256 KB 5200 cartridge (32K banks)
- 74: Super Cart 512 KB 5200 cartridge (32K banks)
- 75: Atarimax 1 MB Flash cartridge (new) See DOC/cart.txt for details.
* support for remapping of all function keys (START, SELECT, OPTION etc)
* tool for creating cart files from ROM files
* video triple buffering changed to …

atari800: update to 5.0.0

---

scriptmodules/supplementary/raspbiantools.sh

Some changes prompted by the new RaspiOS Bookworm features:
- added Firefox as a browser, since it's supported now
- mimic the RaspiOS defaults and on Pi4/5 platforms add an additional entry for starting the Wayland based desktop, using the `wayfire` compositor.

raspbiantools: bookworm updates

---

scriptmodules/supplementary/samba.sh

[From: https://github.com/christgau/wsdd]
With Windows 10 version 1511, support for SMBv1 and thus NetBIOS device discovery was disabled by default. This causes hosts running Samba not to be listed in the Explorer's "Network (Neighborhood)" views. While there is no connectivity problem and Samba will still run fine, users might want to have their Samba hosts to be listed by Windows automatically.
This should fix the discoverability issues with recent Windows versions, especially since the SMBv1 client is not available anymore in Win11 (as some ill-advised instructions are trying to fix this problem).

samba: add a Web Service Discovery service

---

scriptmodules/libretrocores/lr-gpsp.sh

Removed obsolete installed file, since it was removed upstream.

lr-gpsp: fix installation due to missing file

---

scriptmodules/libretrocores/lr-mame2015.sh
scriptmodules/libretrocores/lr-mame2015/01-python3-irgen.diff
scriptmodules/libretrocores/lr-mame2016.sh
scriptmodules/libretrocores/lr-mame2016/01-python3-irgen.diff
scriptmodules/libretrocores/lr-mess2016.sh

Looks like some deprecation in python3.11 breaks building both cores due to some codegen including python scripts.
Upstream has a PR proposed in https://github.com/libretro/mame2015-libretro/pull/98, but not applied, so create one locally for each scriptmodule.

bookworm: fix Mame2015/Mame2016 not building. 

---

scriptmodules/emulators/mupen64plus.sh

This includes 2 commits:
- one to disable the VK API added for `mupen64-plus-core`, since it's built by default. We don't need that since we don't ship (for now) any video plugin or front-end that support Vulkan.
- the other removes some bitrot from `mupen64plus-video-gles2rice`, allowing it to compile on `armhf` with a newer g++ (like the one from Raspi OS 12 _bookworm_).

mupen64plus: buildfixes

---

scriptmodules/emulators/openmsx.sh

Bumped the repo version to the 19.1 tag, so it's available for Bullseye and later platforms.
A brief description of things added in 19.x (full changelog at https://raw.githubusercontent.com/openMSX/openMSX/RELEASE_19_1/doc/release-notes.txt):
- bugfixes for VDP and V9990 emulation
- many improvements on machine and extension descriptions
- added mapper for RetroHard MultiCart 31 in 1 cartridges
- implemented (more) I/O port mirroring for S-1985 and S-3527 based machines for PSG, VDP, PPI, RTC, printer)
- added mapper for Al Alamiah 30-in-1 cartridges
- added mapper for RetroHard MultiCart 31 in 1 cartridges
- improvements and additions to OSD Menu
- many bugfixes and improvements to the disk manipulator
- fixed SaI3xScaler
- added MIDI input support to ALSA
- added YM2151 recording to VGM …

openmsx: update to version 19.1

---

scriptmodules/admin/crosscomp.sh
scriptmodules/admin/crosscomp/asan_limits.diff
scriptmodules/admin/crosscomp/bullseye.diff

Split out header include fix from bullseye.diff into own patch file as it's also needed on gcc 12.x.
Apply patch for GCC versions greater than 10.

crosscomp - add support for building bookwork arm cross compiler

---

scriptmodules/libretrocores/lr-flycast-dev.sh

Added the libretro core from upstream flyinghead/flycast, it supercedes the current libretro/flycast repository used for the current `lr-flycast` core. The new core doesn't work correctly with the legacy VideoCore GLES drivers [1], so it will have to co-exist with the current `lr-flycast` until we drop support for older RaspiOS versions still using the VideoCore drivers.
Due to an internal compiler error, the enw core doesn't build on Buster with the included `gcc8`, but works on `gcc9` and later, which means it can be installed on Debian 11/Ubuntu 20.04 and later.
Tested on RaspiOS _bookworm_ with `vulkan`, `glcore` and `gl` RetroArch video drivers, on a Pi4.
[1] https://github.com/flyinghead/flycast/issues/559

lr-flycast-dev: add upstream libretro core

---

scriptmodules/ports/yquake2.sh

Released today, this includes [gyro aiming for Nintendo Switch controllers in RetroPie](https://retropie.org.uk/forum/topic/32772/quake-2-with-gyro-aiming-using-a-switch-controller), and cvars like `ogg_pausewithgame`, which pauses music when the game is paused, and `g_swap_speed`, cheat to speed up weapon switch animations.
Expansions / Mission Packs have been updated as well, mostly with bug fixes.
Once again, no performance lost from previous versions.

Update Yamagi Quake 2 to version 8.30

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/libretrocores/lr-ppsspp.sh

The 'ubershaders' introduced in v1.14 are not handled efficiently by the Mesa v3d driver, causing a performance regression [1]. Since the slowdown is not present in the Mesa version from Bullseye/Bookworm (which caused in part the version upgrade), install v1.13.2 just on Buster/RPI.
[1] https://github.com/hrydgard/ppsspp/issues/18388

ppsspp: revert to v1.13.2 for RPI and older Mesa

---

scriptmodules/supplementary/skyscraper.sh

Fixes gather and generate actions, which were broken with the new package version.
https://retropie.org.uk/forum/topic/34771/skyscraper-usage-script-doesn-t-work-after-package-update

skyscraper.sh function _get_ver_skyscraper - perform version check as $user, not as root

---

scriptmodules/supplementary/gamecondriver.sh

Use the generic KERNEL-HEADERS dependency instead of the pre-Bookworm package name, so the right package is correctly chosen.

gamecondriver: fix kernel headers package

---

scriptmodules/emulators/amiberry.sh

New version has Pi5 support, so we can enable it.
~~Not released yet, so we'll need to wait a bit.~~
Changes in 5.6.2 (complete changelog at https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.2):
Added:
* improved help text in DiskSwapper panel
* don't disable CD drive if no image path is specified
* if start_minimized is specified, do not show a window on startup
* hide the Linux hidden directories from dialogs
* added VSync option
* added missing help text in GUI->Priority
Fixed:
* fixed crash if Restart was pressed
* fixed crash on startup on x86_64 platform
* DiskSwapper slots should be 10
* Virtual Keyboard options were not saved correctly
* fixed several memory leaks from the GUI
Platforms:
* added Raspberry Pi5
* added RISC-V 64bit (no JIT)

amiberry: bump version and enable for Pi5

---

scriptmodules/libretrocores/lr-picodrive.sh

Upstream changed the README filename
Fixes #3801

lr-picodrive: fix building from source

---

scriptmodules/emulators/amiberry.sh

Changes since 5.6.2 (https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.3)
* Optionally keep a backup of existing file, when downloading updates
* Show SDL2 render thread option in the GUI
* Disable SDL2 render thread checkbox on KMSDRM
* Improved DMS support

amiberry: update to version 5.6.3

---

scriptmodules/supplementary/runcommand/runcommand.sh

This fixes games failing to launch when their filename contains multiple consecutive.  The fix is implemented by updating runcommand's `eval` to preserve all of the characters of `$COMMAND` by quoting the variable.
For one of my systems (tic-80), some of the games contain filenames that have multiple consecutive spaces in them.  For example: `C L A Y  P I G E O N.tlc`.  I'll admit, this is rare and unusual but this is done to match where I've sourced the game from.  When launching this game, it fails and returns to Emulationstation.
This *can* be fixed by simply removing the consecutive spaces and updating the gamelist, but my goal is to ensure that my game files match their source.  Fixing the root cause I hope might also solve similar issues others encounter in the future.
You can …

runcommand: Fix filenames with multiple consecutive spaces in them not loading

---

scriptmodules/supplementary/steamcontroller.sh

Changed to use the driver from https://github.com/Ryochan7/sc-controller since it offers a Python3 compatible version.
Module has been updatd updated/reworked:
- the driver repo is no longer cloned to $md_inst, so 'noinstclean' flag is not necessary
- installation is still done `virtualenv`, in Bookworm and later this becomes mandatory Note: the `--no-site-packages` was removed in the `virtualenv` call since it's ignored in v15 (version from Buster) and was removed in v20
- the `install` function is a mix of build/install, but since `install` cleans up $md_inst, it's necessary to have them there.
- added an update hook that removes the old driver start-up sequence in `/etc/rc.local`
- some minor re-wording of the text shown in the dialogs
Untested with a real controller, unfortunately, …

steamcontroller: switch to a different upstream source

---

scriptmodules/emulators/retroarch.sh

gfx/video_crt_switch.c doesn't currently build on videocore, due to definition of sr_state being in deps/switchres/switchres_wrapper.h which is not included on videocore.
I haven't used this functionality, so this is a quick workaround, rather than a proper fix. The fact that the code has ifdefs for videocore - I guess it did work, but will need to be looked at. But for now, just wanted to get RetroArch building again.

retroarch - use --disable-crtswitchres on videocore

---

scriptmodules/emulators/amiberry.sh

This should fix the regression from 5.6.2+ on DispmanX platforms.
Changelog (https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.4):
Fixes:
* Fixed problems writing parition tables to HDFs after latest updates
* Fixed crash in Add Harddrive dialog
* Quickstart did not select correct ROM for A4000T
* The default.uae could not be deleted
* GUI would not use default screenmode
* DMX targets would crash when opening the GUI
* CD images were not activated on Reset, only on Restart
* A3000 emulation didn't work
* Keyboard reset would not restore keys
New/Improved:
* increase size of text field in Create Hardfile dialog
* Use CD Image name as a fallback for screenshot filename, if no floppy was found
* Accept archive formats as disk images also (e.g. .zip, .lha, .7z)

amiberry: update to v5.6.4

---

scriptmodules/libretrocores/lr-pcsx-rearmed.sh

https://github.com/libretro/pcsx_rearmed/commit/4b2392bb1d5331466ecf29896103f157c1f8e05a forces BUILTIN_GPU to neon for all arm platforms, as ARCH_DETECTED gets set to "arm" which is a substring of "arm64".
Workaround this in our scriptmodule by setting BUILTIN_GPU=peops on non neon arm platforms (eg. armv6).

lr-pcsx-rearmed - rework parameters to fix building on armv6

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/emulators/ppsspp/gles2_fix.diff

GL_COMPRESSED_RGBA_ASTC_4x4_KHR isn't available in the videocore iv gles2 includes, and documentation suggests this is an opengles 3 extension.
Add ifdefs to not include this if it isn't defined.

ppsspp - fix building on Raspberry Pi with proprietary drivers

---

scriptmodules/emulators/ppsspp.sh

The fix has been included upstream for inclusion in v1.17.0 https://github.com/hrydgard/ppsspp/pull/18433

ppsspp - only apply gles2 patch on ppsspp v1.16.6

---

scriptmodules/supplementary/esthemes.sh
scriptmodules/supplementary/esthemes/patch-ruckage-famicom-mini.diff
scriptmodules/supplementary/esthemes/patch-ruckage-nes-mini.diff
scriptmodules/supplementary/esthemes/patch-ruckage-snes-mini.diff

Added the ability to patch themes locally to fix the gamelist layout bugs in themes, surfaced after EmulationStation's fixes for positioning, added a in 2.10.x. Mostly done to fix @ruckage's themes, which haven't been updated after the new EmulationStation version.
Fixes included:
* for the 'snes-mini' theme, based on https://github.com/ruckage/es-theme-snes-mini/pull/26, submitted by @makofee
* for the 'nes-mini' theme, started from https://github.com/ruckage/es-theme-nes-mini/pulls/13, submitted by @grosa1, which in turn is based on https://retropie.org.uk/forum/topic/12583/snes-mini-theme/929?_=1699852993853 (?). Followed by some testing and fixing for the other resolutions which are not covered by the initial changes.
* for the 'famicom-mini' theme, adapted from the previous patch …

esthemes: make it possible to patch themes locally

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/libretrocores/lr-ppsspp/v13-libretro_fix.diff

Core on v1.13.2 fails to run on Pi4 with the error:
...
[ERROR] Failed to open libretro core: "/opt/retropie/libretrocores/lr-ppsspp/ppsspp_libretro.so"
Error(s): /opt/retropie/libretrocores/lr-ppsspp/ppsspp_libretro.so: undefined symbol: hostAttemptBlockSize
This was fixed upstream with commits 1cd34f9d2bef6c92ed457c6aa85bf4d9b5111e90 and 7c5d36eca76c905a122c1, which are combined in the .diff file in this commit.

lr-ppsspp: fix libretro runtime missing symbol

---

scriptmodules/emulators/mupen64plus.sh
scriptmodules/supplementary/runcommand.sh

The `libraspberrypi-bin` package has been deprecated in RaspiOS's latest Bookworm release [1], being replaced with `raspi-utils`. We need this package for `tvservice`, but on KMS platforms this utility is obsolete and always returns an error.
The changes will:
- leave the `libraspberrypi-bin` dependency in `runcommand` just for RPI+DispmanX platforms (Buster and eariler Raspbian)
- replace the `mupen64plus` dependency with the correct one  (`libraspberrypi0`), since this is where the (E)GL(ES) VC drivers are located.
[1] RasPiOS 06.Dec.2023 release, list of included packages: https://downloads.raspberrypi.com/raspios_arm64/images/raspios_arm64-2023-12-06/2023-12-05-raspios-bookworm-arm64.info
Previous (and initial) Bookworm release contained the `libraspberrypi-bin` package: …

dependencies: handle obsolete `librasbperrypi-bin`

---

scriptmodules/ports/smw.sh

The fork from https://github.com/mmatyas/supermariowar is still active and it has the options to use SDL2 instead of SDL1. Switched the scriptmodule to it with updated dependencies and build instructions. New version also changed the configuration location, now in a dedicated folder.
Main changes since 1.8
* Experimental online mode, including an online lobby server
* Lots and lots and lots of bugfixes (seriously, there's at least 200)
* Added Web, ARM and (an experimental) Android ports, and improved support for Windows, Linux and OSX
* Improved music and sound quality
* Ported all parts of the game to SDL2, for hardware accelerated drawing and improved support for many platforms
* Major cleanup of the source code and the build system
NOTES: 
- I've updated the license to GPL2, since …

smw: switch to @mmatyas's fork; upgrade to 2.0

---

scriptmodules/supplementary/gamecondriver.sh
scriptmodules/supplementary/mkarcadejoystick.sh
scriptmodules/supplementary/snesdev.sh

The Pi5 uses a different architecture for the GPIO pins, which is not compatible with previous models. All GPIO functions are now handled by the RP1 [1] southbridge chip and the GPIO reading mechanism used in previous models doesn't work here.
Disabled drivers:
- gamecond and db9 (gamecondriver)
- mk_arcadejoystick_rpi
- snesdev
[1] https://www.raspberrypi.com/documentation/microcontrollers/rp1.html

drivers: disable GPIO kernel module drivers on Pi5

---

scriptmodules/system.sh

The 'Hardware' field has been removed from the output of '/proc/cpuinfo' after [1], so the setup script will not correctly identify it's running on a Raspberry PI. Use '/proc/device-tree/compatible' to check whether we're on a Raspberry Pi, the same method used for other SBCs.
Model calculation based on the Revision field from '/proc/cpuinfo' needs to be run in 2 places, so the code has been put in a separate function.
[1] https://github.com/pelwell/linux/commit/17804c20303c8295b05baf2ab9578432ac5c2735

system: fix RPI detection with recent RPI kernels

---

scriptmodules/supplementary/skyscraper.sh

Re: https://github.com/RetroPie/RetroPie-Setup/pull/3793#issuecomment-1803364524
@cmitu said:
> The version interrogation can also be shortened to just
> 
>     "$md_inst/Skyscraper --version | cut -d' ' -f 2
This no longer returns a coherent value.
In 3.9.2, the `--version` option returns:
```
pi@retropie:~ $ Skyscraper --version 
_______ __                                                     ___
|   _   |  |--.--.--.-----.----.----.---.-.-----.-----.----.   |"""|
|   1___|    <|  |  |__ --|  __|   _|  _  |  _  |  -__|   _|   |"""|
|____   |__|__|___  |_____|____|__| |___._|   __|_____|__|     |"""|
|:  1   |     |_____|                     |__|       3.9.2     |"""|
|::.. . |                                                      |"""|
`-------' by Lars Muldjord and contributors …
```

skyscraper.sh - use 'Skyscraper -h' for version interrogation. Require 'ge' match for version check.

---

scriptmodules/emulators/mame.sh
scriptmodules/emulators/mame/lzma_armv7_crc.diff

7zip/lzma assumes hardware crc support on arm, which breaks compilation on armv7.
Disable the check so it falls back to a software implementation.

mame - fix building 7zip/lzma on armv7 due to missing hardware crc

---

scriptmodules/supplementary/raspbiantools.sh

Upgrading via 'apt' the Bluez package with a the version from Debian updates will overwriten the RPT. This breaks pairing for some gamepads. Pin the package so it's always installed/updated from archive.raspberrypi.org on RaspiOS 10 'Buster'.
Added a couple of related changes to how 'apt' is run when updating:
* use 'full-upgrade' instead of 'dist-upgrade', since it will install new packages introduced by the upgrade.
* add '--allow-downgrades' to make sure that 'bluez' is retrieved from the RPI repos if it was already upgraded by an upstream update.

raspbiantools: pin Bluez to the RPI repos for Buster

---

scriptmodules/supplementary/emulationstation.sh

When running under Gnome/Wayland on Ubuntu 22.04 default configuration, the '--fullscreen-borderless' is not actually fullscreen. The top horizontal panel (?) is still visible and the EmulationStation window is actually pushed down.
Running with just '--fullscreen' is enough, but this is the default, thus there's no need to add any additional parameters when Gnome/Wayland is the current session. Tested on an updated Ubuntu 22.04, with the default Gnome session.

emulationstation: fix fullscreen launching params on Wayland/Gnome

---

scriptmodules/ports/micropolis.sh

Broken by my previuos PR.
Micropolis runs in a maximized window, but doesn't have any fullscreen option and it relies on the WM cursor to operate, so use the WM + Cursor option for it.

micropolis: fix path and display

---

scriptmodules/emulators/ppsspp.sh
scriptmodules/libretrocores/lr-ppsspp.sh

This fixes binary builds not triggering due to the changes being in ppsspp.

lr-ppsspp - split out lr-ppsspp specific patches

---

scriptmodules/supplementary/runcommand/runcommand.sh

Add the `xset` commands to disable the display powersave and screen blanking, since gamepad activity is ignored by Xorg and the display will go to sleep if no keyboard/mouse is active. 
I removed the script launchers ccbee7c05a, but the `xset` commands haven't been added `XINIT-WM` launchers.

runcommand: disable powersave when XINIT is used

---

scriptmodules/helpers.sh

The 'xorg' (meta)-package will install the necessary packages to run an Xorg server and to launch applications under an Xorg environment. We need to map 'xorg' for:
- Pi5 needs an additional package that provides configuration for Xorg, without it the server will not start. Unfortunately the package has no reverse dependency (for now), so it must be installed explicitely.
- One of the recommended packages installed is the 'xserver-xorg-legacy' package, which breaks our x11 apps launched from `runcommand`. We already uninstall it when the setup script starts (regardless of how it was installed), but let's not install it ourselves when 'xorg' is a dependency for one of our own scriptmodules. NOTE: `runcommand` breakage under `-legacy` is due to our redirection of STDIN/STDOUT. The `-legacy` …

helpers: map 'xorg' for Pi5 and for 'legacy' exclusion

---

scriptmodules/supplementary/bashwelcometweak.sh

On RasPI OS 11/12 (bullseye/bookworm) the `vcgencmd` command has moved to `/usr/bin`. Use the normal path first when running `vcgencmd measure_temp` to get the GPU temperature, otherwise nothing is shown.

bashwelcometweak: fix GPU temp reading

---

scriptmodules/admin/joy2key.sh

Modified the 'stop' action to use `start-stop-daemon` [1] instead of a simple `pkill`.
The advantage is that we don't need to use `sleep` to ensure the script is stopped, since `start-stop-daemon` monitors the process and will exit when is stopped. The `retry` action is to send a SIGKILL after 1 second, to ensure the process is stopped.
The modification will shorten the time it takes to 'stop' the joystick handling utility, since we don't have to wait - unconditionally - for 1 sec every stop. This will shorten the runtime of `runcommand` .
[1] https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html. Since it's part of `dpkg`, it's basically present on every Debian based system.

joy2key: refactor stop action

---

scriptmodules/emulators/mame.sh

Latest mame has an issue linking on Raspberry Pi OS Bullseye. It fails with
/usr/bin/ld: BFD (GNU Binutils for Raspbian) 2.35.2 assertion fail ../../bfd/elf32-arm.c:9876
Workaround this by using the gold linker.

Fix linking mame on Raspberry Pi OS bullseye

---

scriptmodules/emulators/amiberry.sh
scriptmodules/emulators/amiberry/01_preserve_env.diff

This bumps Amiberry from 5.6.4 -> 5.6.6.
Release notes:
https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.5
https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.6
Notably this changes the default vsync behaviour, which should fix https://github.com/BlitterStudio/amiberry/issues/1189  – render corruption when launching from EmulationStation on Pi5. (That was my own motivation, but I'm yet to confirm it has the desired outcome).
libportmidi-dev [has been added as a build dependency](https://github.com/BlitterStudio/amiberry/commit/e52bd6f44d776affc7017192b7ef691c496a3420).

Amiberry 5.6.6

---

scriptmodules/libretrocores/lr-dosbox.sh

Reported upstream, but not fixed. Workaround is to force C++11 as dialect, suggested in https://github.com/libretro/dosbox-libretro/issues/137

lr-dosbox: fix building with GCC 11+

---

scriptmodules/libretrocores/lr-gpsp.sh

Rename readme.txt to original_readme.txt and add README.md to install.

lr-gpsp - fix install and enable for non arm platforms

---

scriptmodules/ports/kodi.sh
scriptmodules/system.sh

Since Bullseye, `kodi` should be installed from the RPT repos, since it's built with the necessary patches/optimization directly by the RP folks.
However, the version in the repos don't always overrides the version present in the upstream Debian/Raspbian repositories [1] and installation fails.
Added a workaround to always prefer the Kodi packages originating from archive.raspberrypi.com/archive.raspberrypi.org and also fixed the Raspbian detection on Bookworm.
I think Bullseye and previous had 'archive.raspberrypi.org' for RP repositories, while Bookworm has switched to 'archive.raspberrypi.com', so we can't use the URL for pinning. Added a pin based on the 'l'(Location ?) field of the release from the repository.
[1] https://github.com/raspberrypi/bookworm-feedback/issues/144
NB: for …

kodi: fix installation on Bookworm/Bullseye

---

scriptmodules/ports/bombermaaan.sh

Upgraded to the latest version, which uses SDL2 and SDL2-Mixer.
I think we can now safely release the new RP version, since Bombermaaan finally works on Bullseye/Bookworm.

bombermaaan: update to version 2.x and switch to SDL2

---

scriptmodules/admin/builder.sh

[builder - allow automatic switching to different remote branch](https://github.com/RetroPie/RetroPie-Setup/commit/c44eb50a0da3af8834ec54aeabe0ad4aaca08110)
ENV variables __builder_repo && __builder_branch are used to switch to another repository/branch for building.
This is used to more easily build binaries before branches are merged into master. Primarily for SDL binaries, but simplifies testing for other modules.
[builder - remove old unused code](https://github.com/RetroPie/RetroPie-Setup/commit/3e1be9410523e3b492211767071f48a1edd2409e)

Builder fixes

---

scriptmodules/ports/bombermaaan.sh
scriptmodules/ports/bombermaaan/01-cmake-sdl-mixer.diff

Added a patch for CMake to fix generating/building Bombermaaan with older SDL2/SDL2_mixer:
- on Bullseye/Ubuntu 20.4, `sdl2_mixer-config.cmake` doesn't contain the target aliases in the `SDL2_mixer` namespace.
- on Buster, `sdl2-config.cmake` doesn't contain the target aliases in the `SDL2` namespace and the includes/libraries are not correctly added to the compilation and linkage options.

bombermaan: fix build for Buster/Bullseye

---

scriptmodules/admin/joy2key/joy2key_sdl.py

Besides the mappings parsed from RetroArch's auto-configuration profiles, there's a generic mapping used for gamepads that don't have a profile saved. Unfortunately this never worked, since the initialization of the mapping - in the `add_mappings` function - had the buttons and hats parameters switched. This changeset fixes this, creating a correct mapping.
The issue was reported in https://retropie.org.uk/forum/topic/35063/, `joy2key_sdl` would crash with a Python3 error since the (wrong) generic mapping would produce the incorrect data type and values for the `filter_active_events` method.

joy2key: fix generic mappings definition

---

scriptmodules/ports/gzdoom.sh

Add back GZDoom, the feature centric port for all Doom engine games, based on ZDoom. Since LZDoom is no longer developed, let's try to add back the few still active ZDoom projects.
Since it was removed, besides countless other features addded, it has gained a GLES2/OpenGL2 + Vulkan renderer. Unfortunately, 32bit support has been dropped entirely since 4.9, so 32bit platforms will have to use the 4.8.0 release.
Recent versions auto-detect the available video renderers and can switch to the less intesive GLES2/GL2 renderer automatically, but for old versions (32bit) the preferred renderer has to be set via `vid_preferbackend`.

ports: add GZDoom as a Doom source port

---

scriptmodules/ports/dsda-doom.sh

Added 'dsda-doom', a DOOM source port based on PrBoom+ with extra features geared for demo recording/playback, focused on speedrunning and quality of life. It has support for:
* Heretic, Hexen, MBF21, Doom-in-Hexen, UDMF, and MAPINFO support
* In-game console and scripting
* Full controller support
* Palette-based OpenGL renderer
* Debugging features for testing
* Strict mode for speedrunning
* Various quality of life improvements
* Advanced tools for TASing
* Rewind
It is meant to replace `lzdoom`, which is no longer developed, as a lightweight DOOM port. Can play most Boom based WADs without issues. Due to its popularity in the TAS community, a lot of BOOM compatible WADs are tested against `dsda-doom`, which should provide better compatiblity than other lightweight source ports …

ports: add 'dsda-doom', lightweight DOOM source port

---

scriptmodules/supplementary/xpadneo.sh

Upgrade to version 0.9.6, last maintenance release in the v0.9 series.
Main features:
* Add support for GuliKit KingKong2 PRO controllers
* Move paddles to range BTN_TRIGGER_HAPPY5
* Actually save rumble test values before we replace them
* Support GameSir T4 Cyclone models
* Fix documentation about Share button

xpadneo: upgrade to the latest v0.9.x version

---

scriptmodules/emulators/xroar.sh

New features in version 1.5:
*  Add ability to change Picture Area, seeing more or less border
*  New option -vo-picture
*  Respect -geometry dimensions in SDL-based UIs
*  Add optional 60Hz vertical scaling (on by default)
*  New option -no-vo-scale-60hz disables 60Hz scaling
*  Faster ROM intercept based printing on CoCo and MC-10
*  GIME: respect X offset and HVEN in COCO mode
*  MPI slot config moved from global to per-cart, included in -config-print
*  Add screenshot to PNG from menu or Control+Shift+S
*  Fix printing after switching machines [Jak Fearon]
*  Better rendering of paths in Windows dialogs
*  Fix some CoCo 3 cartridge behaviour [Christian Haitian]
*  GIME: reset video address later (fixes Androne) [Russ Le Blang]
*  GIME: fix various $FExx access problems

xroar: update to 1.5.3

---

scriptmodules/emulators/mame.sh

Made a few tweaks to optimize bulding MAME:
- bump the RAM requirements, to ensure there's enough memory to complete the build.
- don't build the MAME debugger on non-desktop platforms, since it would need a windowing environment to run anyway. This allows us to remove the QT dependencies and debugger compilation steps.
- use system's flac/zstd libraries (more could be added)
- tell the linker to remove debugging info, so the binaries don't need a 'strip' call afterwards
- synchronize the optimization level in MAME with RetroPie's optimization flags (-O2), to avoid extra optimization during compiling (MAME defaults to '-O3').

mame: modify build instructions and dependencies

---

scriptmodules/system.sh

omxplayer does not have a build available for aarch64 platform. So when building emulationstation from source on arm64 systems we need to skip this dependency, otherwise the dependency installation fails and we can't install emulationstation

Don't set dispmanx flag on arm64 systems

---

scriptmodules/inifuncs.sh

Use `#` instead of `/` for SED's substitution command separator. 
This makes the `iniGet` command work for key values containing `/` (like Dolphin's input configuration files). The `#` character is usually reserved for comment lines in an `.ini` file, so it should be relatively safe to use as separator; `sed` accepts any ccharacter besides `*` or newline for separator, so `#` should also be safe here.

initfuncs: change `sed` separator for `iniGet`

---

scriptmodules/emulators/dolphin.sh

Modified the module to update the dependencies and improve the initial configuration
* Build changes:
-  build dependencies modified to include SDL2. Latest version (as of Jan 2024) enable SDL2 by default on Linux and use it for input auto-configuration. Gamepads detected using SDL's GameController API are automatically configred based on their mappings.
- disable analytics and update support durign the build. Updates are handled by RetroPie-Setup and - unfortunately - analytics require a keyboard/mouse to get over the initial agreement pop-up that is presented to the user on the 1st run.
* Configuration updates:
- on KMS systems, start Dolphin via X11 by using the `XINIT-WM` launc prefix, which instructs `runcommand` to start a minimal desktop env.
- change the location of the …

dolphin: updates to build and configuration

---

scriptmodules/admin/setup.sh

Tell the user to save their configuration files if they intend to use any of RetroPie components after removal, i.e. if they previously had an emulator/port installed and they still want to use it after removing RetroPie.
Closes #3525

admin: expand the warning about config removals

---

scriptmodules/helpers.sh

Reverts RetroPie/RetroPie-Setup#3836

Revert "helpers: map 'xorg' for Pi5 and for 'legacy' exclusion"

---

scriptmodules/emulators/mame.sh

Version 0.263 introduced support for ZSTD compression for CHD files, but the version in Debian 10 Buster is not recent enough to compile MAME. Use the bundled source for `libzstd` instead of the system provided libraries for now.

mame: fix building latest version with old 'libzstd'

---

scriptmodules/system.sh

Pi5 needs an additional X11 configuration stanza for xorg-xserver to start properly. This configuration is handled by the `gldriver-test` package, which installs a couple of services that create the needed configuration files based on the displays connected to the board (HDMI/DSI/etc.). Technically, once the services have run the package can be removed IIF the type of display connection will not change (i.e. will always use HDMI or DSI, etc.)
Since this package is only installed with `raspberrrypi-ui-mods` (i.e. the RaspiOS desktop), let's install it by default on Pi5. The only dependency for the package is `raspi-config`, which is already present on any RaspiOS installation.

system: handle Pi5's xorg configuration

---

scriptmodules/libretrocores/lr-mame.sh

Update the build parameters so:
- optimization level matches RetroPie's compiler options (-O2)
- removed `PYTHON` pre-set since it's set now to `python3` by default
- disable PortAudio, not needed since audio is handled by RetroArch

lr-mame/lr-mess: modify build parameters

---

scriptmodules/emulators/dolphin.sh

Mentioned here (https://retropie.org.uk/forum/topic/35203/dolphin-gamecube-wiiware-wii-compatibility-on-pi-5/45?_=1710677064715), am I right in thinking the path will be set as /home/ username /RetroPie/roms/gc ?

Add multi disc functionality by default

---

scriptmodules/ports/love.sh

Love has switched over to cmake, so the scriptmodule was failing.
Their main branch is considered development, so switch to the last stable tag 11.5 (December 2023).
Their documentation still references the old build system so safer to stick with a stable release for this module. We can revisit this with the next release.

love - switch to 11.5 stable release

---

scriptmodules/emulators/advmame.sh

AdvanceMame is undergoing development and the current master branch fails on buster/bullseye.
May be due to older autoconf but better to stick with the last official release.

advmame - switch to last stable v3.10

---

scriptmodules/ports/gzdoom.sh
scriptmodules/ports/gzdoom/lzma_armv7_crc.diff

7zip/lzma assumes hardware crc support on arm, which breaks compilation on armv7.
Disable the check so it falls back to a software implementation.
Same fix as for mame with 508f3d1e64359fe4ebcd166eb27e87215bbbb524

gzdoom - fix building 7zip/lzma on armv7 due to missing hardware crc

---

scriptmodules/supplementary/xpad.sh

The `xpad` kernel module is patched locally in order for the 'triggers_to_buttons' option to work on any supported controller. During installation, the option is also enabled automatically. Historically, this has been used to work-around EmulationStation not detecting the analog shoulder triggers, but the detection works now and this extra option is not needed for EmulationStation.
Leaving the option enabled by default has the side effect of breaking SDL's Gamecontroller API DB mappings (no of buttons and axis are different then the upstream mapping). Since more and more applications/games/emulators/etc. are using this SDL sub-system, it's better we don't enable it anymore.
This change removes the module configuration handled by the scriptmodule - both installation and removal. Users can …

xpad: don't force the triggers-as-buttons option

---

scriptmodules/emulators/scummvm.sh

The 2.8.1 is a bugfix release and includes upgrades for the following engines: AGI, AGS, GRIM, SWORD2, MM (which is now enabled, it was skipped it in 2.8.0 by accident), mTropolis, NANCY, SCUMM, TWINE, Ultima, and V-Cruise.
Full changelog at https://downloads.scummvm.org/frs/scummvm/2.8.1/ReleaseNotes.html.

scummvm: update standalone emulator to 2.8.1

---

scriptmodules/libretrocores/lr-dirksimple.sh

This is an setup script to install the [DirkSimple](https://github.com/icculus/DirkSimple) libretro core.
DirkSimple is a laserdisc game player that implements specific titles from scratch, so it uses an arcade game's video content but not its roms. It takes game data in Ogg Theora format, so the "rom" that the core needs is a single .ogv file per game.
Currently, it plays [Dragon's Lair](https://en.wikipedia.org/wiki/Dragon%27s_Lair) and [Cliff Hanger](https://en.wikipedia.org/wiki/Cliff_Hanger_(video_game)), with other titles planned for the future. RetroArch ships DirkSimple as a standard core, including to their Steam builds. It offers a libretro option for playing some laserdisc titles, so you get all the consistent controller support, hotkeys and state serialization magic, in case …

Add lr-dirksimple setup script

---

scriptmodules/emulators/hatari.sh

The main repository and site (https://hatari.tuxfamily.org/) is currently not working. Switch to using the github mirror and also upgrade to v2.4.1 
Changes since the last version are: (Taken from https://raw.githubusercontent.com/hatari/hatari/v2.4.1/doc/release-notes.txt)
Version 2.4.1 (2022-08-03)
--------------------------
Emulation improvements:
- Sound:
- Much more precise function to convert CPU clocks to YM2149 clocks
in the case where YM2149 doesn't use the same source clock as the CPU
(fixes e.g. some STE sound glitches in BLSPLAY.TTP)
- Video:
- Fix regression in TT mode: Update video counter again on each HBL
(fixes e.g. Hextracker when run in TT mode)
Emulator improvements:
- DSP:
- Avoid small extra overhead on non-Falcon machines when DSP config
option is set
- Misc:
- Fix …

Switch to using the github mirror for Hatari and bump version to 2.4.1

---

scriptmodules/emulators/dosbox-staging.sh

Latest (0.81) version of Dosbox Staging doesn't go along with the legacy GPU VideoCore drivers, resulting in a SDL window initialization crash. Pin the 0.80.1 version for these devices, maybe a GLES2-only rendering path will be added later on, which would solve this issue.

dosbox-staging: pin version for videocore

---

scriptmodules/emulators/retroarch.sh

Upgraded RetroArch to version ~~1.17.0~~ 1.18.0. You can pull from https://github.com/cmitu/RetroArch/tree/retropie-v1.18.0, which contains 1.18.0 + our patches.
Notable changes, cherry-picked from:
- https://www.libretro.com/index.php/retroarch-1-17-0-release/
- https://github.com/libretro/RetroArch/commit/9e492f74c8378582bde6f115a8715ab08e945303
* Netplay
- expanded the protocol to allow multiplayer games running on separate consoles/computers.
Cores like 'Dosbox-Pure' or 'gPSP' support the new protocol.
- add support for joining MITM servers from command line
* Cheevos
- upgrade to v11.0
- don’t track disc changes when achievements are disabled
- inform user when server is unreachable
- fix crash on first load of game with achievements with threaded video
* Input
- fix ghost input when …

retroarch: upgrade to v1.18.0

---

scriptmodules/emulators/jzintv.sh
scriptmodules/emulators/mupen64plus.sh
scriptmodules/libretrocores/lr-picodrive.sh
scriptmodules/libretrocores/lr-snes9x.sh
scriptmodules/packages.sh
scriptmodules/system.sh

Only configure distcc variables if a module doesn't have the "nodistcc" flag.
Skip builder/setup modules to avoid having distcc changes propagate to modules built from them.
This allows easily disabling distcc for certain modules that are not compatible.
Remove DISTCC_HOSTS="" from mupen64plus, jzintv, and lr-snes9x and replace with the "nodistcc" flag
Add "nodistcc" to lr-picodrive, as on Raspberry PI OS Bullseye, the distcc wrapper fails at linking stage.

Distcc changes

---

scriptmodules/emulators/retroarch.sh

Previous commit removed the `retroarch.cfg` from upstream. While the configuration will set the right options in a new config file, we traditionally used the upstream's config as starting point, since it's largely commented and provides pointers for various configuration options.
Restore the previous behavior by including the upstream `retroarch.cfg` in `$md_inst`, since the makefile doesn't copy it during the install target.

retroarch: add back the commented config

---

scriptmodules/emulators/dolphin.sh

The initial config is missing the 'ISOPaths' option, without it the game paths added in the initial configuration are ignored by Dolphin.

dolphin: fix initial config

---

scriptmodules/emulators/dosbox-staging.sh

1. I've noticed that on newer version of Meson, dependendant packages like `iir` and `mt32emu` are no longer built and linked statically. Instead, they're created and then installed as dynamic libraries. The installation goes to `$md_inst/lib/<host-triplet>`, so the resulting binary doesn't work out-of-the-box, but the more important issue is that the `libmt32emu` library is not copied. As a result, `dosbox` will not be able to run on such a system.
The issue above doesn't seem to affect the RaspiOS (32/64bit) builds, but I had it happening on Debian Trixie (testing) and a recent Armbian Jammy 22.04 for OrangePi 5.
To make sure the above issue doesn't happen, link the `iir` and `mt32emu` libraries statically. They're always downloaded and built via Meson _wraps_, since there are no Debian …

dosbox-staging: update dependencies and build options

---

scriptmodules/supplementary/skyscraper.sh

This goes back to the forum discussion a while ago: Within the scriptmodule there can be options persisted (cf. `Skyscraper.cfg`) which then get applied to the command line, which overrun settings in Skyscraper's `config.ini`. 
To add more visibility about the applied options (and to avoid confusion about different behaviour of Skyscraper from scriptmodule vs. Skyscraper CLI usage) the user gets the actual command echoed before the scraping starts.
Tested it well on my side and did not notice a regression.
Also, for some reasons two already present scraping modules did not made it into the scriptmodule.

echo the applied command line options of Skyscraper; add two scrape modules

---

scriptmodules/emulators/mupen64plus.sh

Set HOST_CPU to armv8 when we have the armv8 flag set

mupen64plus - fix building on armv8 with 64bit kernel/32bit userland

---

scriptmodules/emulators/mame.sh
scriptmodules/libretrocores/lr-mame.sh
scriptmodules/libretrocores/lr-mess.sh

Starting with version 0.265 (April 2024), GCC 10.3 is required for building MAME. Enforce this requirement when building the emulator and libretro cores, Debian Buster will be getting 0.264 as the last version.

mame: add GCC requirements for version 0.265

---

scriptmodules/libretrocores/lr-mame.sh

We removed the `python3` parameter setup in commit 2a95dd076a00ea7975d14a0cde7f29eff5bb68f0, but the build parameters are also used by Mame/Mess 2016. Mame2016/Mess2016 have python2 still as default, so re-add the `PYTHON_EXECUTABLE` ~~configuration~~ parameter.

lr-mame: fix the build for 2016 repository

---

platforms.cfg

For certain CD ROM based games (e.g Policenauts), you need to create a .cmd so you can run the system disk, user disk and CD

Update platforms.cfg pc98 .cmd files

---

scriptmodules/supplementary/emulationstation.sh

self explanatory. the openGL version check as is only works on MESA drivers. `Extended renderer info` comes from the `GLX_MESA_query_renderer` extension

emulationstation: fix OpenGL version check

---

scriptmodules/emulators/yabasanshiro.sh

The previous build method on the Pi4 uses a CMake toolchain file which assumes a 32bit ARM system. To make it compile on ARM64, remove the toolchain file usage and add the appropriate defines/options from it to the CMake invocation.
NB: with these changes, we can probably try to install from the main/master branch (which doesn't have the Pi4 CMake toolchain file), but I'll not add it to this PR.

yabasanshiro: fix building on ARM64

---

scriptmodules/emulators/dolphin.sh
scriptmodules/emulators/mame.sh
scriptmodules/emulators/ti99sim.sh
scriptmodules/libretrocores/lr-bsnes.sh
scriptmodules/libretrocores/lr-flycast-dev.sh
scriptmodules/libretrocores/lr-mame.sh
scriptmodules/packages.sh
scriptmodules/ports/mysticmine.sh

rp_module_flags can now contain a variable comparison to enable or disable a scriptmodule.
The comparison should be in the format :\$var:cmp:val or !:\$var:cmp:val
eg. :\$__gcc_version:-lt:7 would be evaluated as [[ $__gcc_version -lt 7 ]]
This would enable a module if the comparison was true or disable if !:\$__gcc_version:-lt:7 was used.
Only global variables set before modules are loaded (eg via system.sh) are supported.
$ is escaped so variables are not evaluated when the module is sourced.
It works without, but provides less useful information in the setup menus as the variable name will not be visible.
Replace GCC version checks in depends_* functions with variable comparisons in flags.
The scriptmodule requires Python2 and python modules that are no longer packaged.
---
This is a …

Flag comparisons

---

scriptmodules/supplementary/autostart.sh
scriptmodules/supplementary/pegasus-fe-dev.sh
scriptmodules/supplementary/pegasus-fe.sh

Since the static binaries provided upstream are no longer working on newer RaspiOS or on 32bit ARM, create a standard scriptmodule to build Pegasus with `pegasus-fe-dev`. The new scriptmodule is meant to work similarly to the `es`/`es-dev` pair, only one can work at a time and they share a set of common functions. Note that due to the Qt5 version needed, the new scriptmodule is meant to be used on Debian 11/Ubuntu 22.04 and later.
Modified the original scriptmodule and added a theme download function, using @mmatyas's themes. More can be found at [2].
A 2nd commit adds `pegasus-fe` as an auto-start item, similar to Kodi/ES, while fixing the spelling of 'EmulationStation'.
Notes:
* the `pegasus-fe` launcher doesn't need the previous TTY set-up, it's now handled by `runcommand`.
* sometimes …

pegasus: add new module and small updates

---

scriptmodules/emulators/mupen64plus.sh

Upstream GlideN64 has a regression due to a recent shader related change, which breaks the video output on GLES devices/platforms. Until this issue is fixed in the upstream GlideN64, build the plugin from a commit before the changes that cause the regression.
The problem was reported in the forums [1] and I reported it upstream [2] and though there is a fix for it, it hasn't been added to the main GlidedN64 repository.
[1] https://retropie.org.uk/forum/topic/35444/
[2] https://github.com/gonetz/GLideN64/issues/2837

mupen64pluus: workaround the GLES GlideN64 regression

---

scriptmodules/libretrocores/lr-scummvm.sh

Upstream has added support for using an OpenGL(ES2) context for 3D games and HW rendering. The core will request a HW GL context from RetroArch when starting. Added the necessary parameters to the build to support the GL context for the platform where RetroArch is running.

lr-scummvm: build with OpenGL(ES) context support

---

scriptmodules/emulators/amiberry.sh
scriptmodules/emulators/amiberry/01_preserve_env.diff

Changes in 5.7.1 (https://github.com/BlitterStudio/amiberry/releases/tag/v5.7.1)
* Bugfixes (since 5.6.6):
- improve CD32 default mapping
- fix base color for Radiobuttons in SaveStates panel
- fix KMSDRM video regression
- fixed background color for SaveStates panel checkboxes
- when saving a new config in the GUI, it should be selected after the refresh
- when loading config from the command line and opening the GUI, the settings were reset to defaults
- always clear the text fields when deleting a config
- fullscreen toggle didn't quite work
- quickstart - enabling 2nd floppy drive did not refresh panel
- make guisan widgets active/inactive status more visible
- fixed textbox background color in Create hardfile dialog
- the floppy dropdown wasn't updated properly after a selection
- …

amiberry: update to 5.7.1

---

scriptmodules/emulators/amiberry.sh
scriptmodules/emulators/amiberry/02_fix_uae_config_load.diff
scriptmodules/emulators/amiberry/03_fix_crash_saving.diff

The 5.7.1 version has a couple of regresions (one is a crash), fixed in version 5.7.2. However, DispmanX support was dropped starting with 5.7.2 so just bumping the version would break Buster based Pi installation.
Therefore the module was changed so that:
- for DispmanX platforms cherry pick the post 5.7.2 fixes manually and lock the version to 5.7.1
- for every other platform build the 5.7.2 version

amiberry: upgrade to 5.7.2; handle dispmanx deprecation

---

scriptmodules/emulators/zesarux.sh

Full changelog at https://github.com/chernandezba/zesarux/releases/tag/ZEsarUX-11.0
Besides bug fixes, new and improved features:
* New additions:
- Added loading audio from external audio source
- Audio Spectrum Analyzer
- Added ZENG Online feature, which allows you to play to any emulated game on a multiplayer way using a central server
- Added ZENG support on all emulated machines
- Added save screenAdded ZENG support on curses driver
- Added save screen to .txt or .stl files
- Added save support for ZX80 & ZX81 .Z81 snapshots
- Added TempleOS GUI Style,  QNX GUI Style
- Added .zmenu type files to generate launcher menus
- Added more vintage Spectrum programs/games from me
- Added PCW Video mode 1 palette selector
- Added setting to force CHR$ 128 mode on ZX81
* Improvements
- Allow to …

zesarux: update to version 11

---

scriptmodules/ports/dxx-rebirth.sh

In https://github.com/RetroPie/RetroPie-Setup/commit/77bb4c16d8a4f74ec755541404dbe6c03fc6158b the code was locked to an older commit due to incompatibilities with Raspberry Pi OS Buster, but this version doesn't build with newer GCC.
Switch to using the latest code by default but lock to older versions for Buster and GCC 10 and lower
Tested to build correctly on Raspberry Pi OS Buster, Bullseye and Bookworm.
Newer dxx-rebirth uses a build/ subfolder.
The official site no longer hosts the files.

Dxx rebirth update

---

scriptmodules/ports/dxx-rebirth.sh

Don't download D2 shareware data if registered version files exist.
Ignore case - don't download D1/D2 shareware whether user-provided data files in **ALL CAPS** (DOS) or **lowercase** (Steam).
Shareware and add-on files no longer available from dxx-rebirth.com - switch to self-hosted files at `$__archive_url` (I don't know how to actually put them there, though. Someone else will have to do that part, or show me how.)

dxx-rebirth game data

---

scriptmodules/ports/gzdoom.sh

Fixed installation error due to ZMusic changing it's SO version. Upgraded GZDoom to 4.12.2. Changes in 4.12 (full changes at https://github.com/ZDoom/gzdoom/releases)
* 4.12.2
* network fixes, including prediction and interpolation
* added emulation of Final Doom's teleporter z glitch and activate it for Saturnia MAP10
* Reworked clientside lerping
* fix issues with GCC 14
* 4.12.1
* Added pistol start gameplay option
* Restored Windows 7 support
* 4.12
* set default backend to Vulkan, if Vulkan fails go GLES not OpenGL
* Update LZMA SDK to 23.01
* do not print all GL extensions to the log for the GLES renderer.
* fix map WAD check for savegame validation.
* Allow setting the colormap from mapinfo (dsda-doom)
* added per-sector sky UDMF properties.
* added DSDA's thrust properties for …

gzdoom: update to 4.12, fix installation

---

scriptmodules/emulators/supermodel3.sh

Just pushing this to see if there is any interest. Feel free to close if it's considered too problematic, I am aware it can require lots of tweaking per install.
This is the ARM optimised code, as used from Exarkuniv's "_RetroPie-Extra_", based on _mechafatnick_'s original arm mods.
This branch has received tweaking, from the _Sinden_ Pi guys, to _Supermodel.ini_ and _Games.xml_ for some time and is maintained.
It also has the following additions to the arm optimizations:
```
'Absolute' Mouse Input for light guns in Linux
Multiple Mouse Support : Allowing 2 players in lightgun games
Support for selecting a clone from within merged ROM set
Per game .commands file for individual game configuration
Log based Framerate Monitoring
Built-in Sinden border
```
The repo branch is here for …

Add Sega Model3: supermodel

---

scriptmodules/libretrocores/lr-prboom.sh

Changelog:
* General
- Improved vanilla compatibility.
- Boom features removed.
- Hall of mirrors greatly reduced.
- Visplane overflows fixed.
- Savegame buffer overflow errors remain.
* Levels
- New levels E1M9, E2M2, E2M3, E2M4, E2M7, E2M8, E3M5, MAP07, MAP21 and MAP27.
- Numerous vanilla fixes and aesthetic modernizations.
- Fixed and standardized secret exits.
* Monsters
- New minigunner
- The hatchling, which replaces the deadflare.
- The matribite, which replaces the summoner.
* Music
- Lots of new music including most of FreeDM music.
* Sounds
- New boss brain sounds.
* Visuals
- Colorblind-friendly keys and key indicators.
- Various revisions to sprites and textures.
- Improved kerning for menu text.
* Weapons
- Improved weapon sprites generally.
- SSG replacement restored to …

doom: update Freedoom to 0.13.0

---

scriptmodules/emulators/dolphin.sh

Adds a symlink to .local/share/dolphin-emu into /opt/configs/gc. The local share directory includes items like the memory card data, game specific configs, Wii Nand, Save states etc which users may want easier access to

Update dolphin.sh to include other settings

---

scriptmodules/emulators/amiberry.sh

Did a quick test and this seems to work, but there might be more changes you want to make.
I've only added `x86-64` as the platform, as there's no 32-bit version for x86 available.
I've also taken away the platform restrictions, but you know best on how to use those (perhaps just add that `x86` is permitted instead).

Add Amiberry for x86 platforms as well (fixes #3937)

---

scriptmodules/ports/solarus.sh

Fixed the licence link and removed the arm64 restriction.
The restriction was added in [1] for Odroid-C2, when `libluajit-5.1-dev` was not available. But that was in 2016 and I think the Ubuntu 20.04 image that's available now for C2 (or a current Armbian release based on Debian/Ubuntu) does have it [2].
[1] https://github.com/RetroPie/RetroPie-Setup/commit/acba46e0953ac74055a085b40e6e4f2b9eb67a65
[2] https://packages.ubuntu.com/noble/arm64/libluajit-5.1-dev/download

solarus: enable for arm64

---

scriptmodules/supplementary/dbar4gun.sh

**dbar4gun** is a Linux userspace driver  for the wiimote with [DolphinBar](https://www.mayflash.com/product/W010.html) support, specifically designed to be small and function as 4 light guns.
**Feature support**
- Bluetooth
- Only DolphinBar in mode 4
- N Mayflash Dolphinbar (recommended at the moment)
- 4 wiimote x Dolphinbar (slow with a single bar)
- wiimote with individual buttons
- multiplayer
- nunchuck
- calibration
- Standard configuration for Wii sensor
- dbar4gun supports maximum resolution and sensitivity without causing cursor jumps
- wiimote led -> index mouse (bin number)
- auto key
- Smoothed cursor
- works on linux
- works on retropie
- works on raspbian
repo: [https://github.com/lowlevel-1989/dbar4gun](https://github.com/lowlevel-1989/dbar4gun)

add dbar4gun support

---

scriptmodules/libretrocores/lr-atari800.sh
scriptmodules/libretrocores/lr-atari800/01_fix_audio_volume.diff

A buildfix patch [1] has been commited recently, but it introduced a regression [2]. Use the patch from [3] to replace the buildfix patch, since it has no side effects, until the libretro repository patches the issue.
[1] https://github.com/libretro/libretro-atari800/pull/92
[2] https://github.com/libretro/libretro-atari800/issues/96, https://retropie.org.uk/forum/topic/35513/
[3] https://github.com/libretro/libretro-atari800/pull/95

lr-atari800: patch sound regression locally

---

scriptmodules/emulators/mame.sh
scriptmodules/libretrocores/lr-mame.sh

* MAME specifically checks for GCC 10.3 so we need to compare with the full GCC version as bullseye has 10.2.
* lr-mame - Remove "master" branch from rp_module_repo so the _get_version tag is passed as a branch to checkout
* lr-mame - Simplify _get_version_lr-mame as the tagname variable was only used once

mame/lr-mame - fix building on bullseye

---

scriptmodules/ports/uqm.sh

As reported in #3483, the `uqm.sh` install script currently puts all content archives in the installed `.../content/packages/` directory, which seems eminently reasonable. However, despite the upstream project website and INSTALL guide having no obvious documentation to this effect, it is not correct: in fact only the `uqm-*-content.uqm` file goes here; `uqm-*-voice.uqm` and `uqm-*-3domusic.uqm` have to go in the `.../content/addons/` directory or the game won't find them.
This patch corrects the path when installing uqm from source, but the pre-compiled binary archive still contains all three files in the `packages/` directory and will have to be similarly updated.
I might also suggest adding the "remix" music packs to the installation, which are found at …

fix for uqm optional 3DO music and speech

---

scriptmodules/emulators/mupen64plus.sh

The mupen64plus package will contain an md5sum of all the mupen64plus repos last git commit.
As it will get a full hash for each repo, but the update check will compare using any hashes stored in the repos variable, it will mismatch and think there has been an update.

mupen64plus - use full commit hash for pinning GLideN64

---

scriptmodules/ports/tyrquake.sh

The upstream repo git://disenchant.net/tyrquake is currently not working. Cloning via https://disenchant.net/git/tyrquake.git works, but is slow.
Switch to the updated RetroPie mirror at https://github.com/RetroPie/tyrquake.git

tyrquake - switch to RetroPie github mirror

---

scriptmodules/packages.sh

This allows updating/reinstalling of modules with the nonet flag set (retropiemenu and runcommand) when no internet connection is available.
Incorrect variable was used in comparison ($id instead of $md_id), so the has_net wasn't forced to 1.

packages - fix install of modules with nonet flag when not connected

---

scriptmodules/libretrocores/lr-stella.sh

C++20 changes were added in 7a85faef which broke compatibility with GCC 8.
GCC 10 compatibility was removed a few commits later in a8a23f61
Fix to commit 2d57f9e0 (last building on GCC 8) on GCC < 11

lr-stella - fix building on GCC v8 (on buster)

---

scriptmodules/admin/image.sh

Using LZMA (xz) for compression instead LZ77 (gzip) reduces the image size by approx 30% more. Image writing utilities with compressed image support (RPI Imager, Balena Etcher) already support it and the RaspiOS or Armbian images are already distributed as `.xz` files.
Changed our image compression format from `.gz` to `.xz` and thus reduce the download size for all images.

image: switch to LZMA for compression

---

scriptmodules/ports/yquake2.sh

Released a few days ago, this version includes more practical weapon switching by repeteadly tapping "_next weapon_" or "_previous weapon_" buttons/keys, allowing you to skip over the list of guns. Also, cvars to set laser beams' transparency (`cl_laseralpha`) and show the player speed (`cl_showspeed`). Platforms that can use the GL1 renderer are the most benefitted, since there are a lot of optimizations for it.
Expansions / Mission Packs have been updated as well.

Update Yamagi Quake 2 to version 8.40

---

scriptmodules/emulators/supermodel3.sh

The folder contains the crosshairs bitmaps used in the `main` branch, installed only `x86`.
Should replace https://github.com/RetroPie/RetroPie-Setup/pull/3961.

supermodel3: add the Assets folder in x86

---

scriptmodules/ports/yquake2.sh

This is a hotfix release, intended to amend [a small bug introduced by yours truly](https://github.com/yquake2/yquake2/pull/1133); it only affects the GL1 renderer.
Also fixes a SDL sound bug in Windows.

Update Yamagi Quake 2 to version 8.41

---

scriptmodules/helpers.sh

allows stand-alone genesis system and romdir by user config

fn mkRomDir - create symlink only if 'genesis' not already exist

---

scriptmodules/supplementary/attractmode.sh

The Attractmode launcher still uses mesa-drm for modesetting for SFML. This PR switchs over to kmsxx.

Fix Attract-Mode Launcher

---

scriptmodules/libretrocores/lr-scummvm.sh

Due to the old EGL version implemented by the old BRCM GLES drivers, the core cannot obtain a (HW) GL context to be used for accelerated video output. Disable this feature on systems using the old/legacy GLES(2) driver.
See https://github.com/libretro/scummvm/issues/59 for context.

lr-scummvm: disable GL(ES) context creation with legacy drivers

---

scriptmodules/supplementary/splashscreen.sh
scriptmodules/supplementary/splashscreen/05-splash.sh
scriptmodules/supplementary/splashscreen/asplashscreen.sh
scriptmodules/supplementary/splashscreen/rp-vlc

Here is a possible solution for splashscreen support that works on bullseye.
omxiv / omxplayer only works on the Raspberry Pi legacy and fkms drivers.
This change switches to vlc for both utilities, as it supports mmal output on the Raspberry Pi legacy drivers, and drm output on KMS on Raspberry Pi OS (on bullseye).
This change includes stopping vlc before launching ES on kms as ES will fail to open the display otherwise. Maybe we should introduce an option to "wait" for vlc to finish before we start ES. May be useful for video splashes etc.
From my testing:
**Legacy Driver (default config)**
- omxiv - ES displays over splashscreen
- vlc - ES displays over splashscreen
**FKMS**
- omxiv - ES displays under splashscreen
- vlc - ES displays under splashscreen (mmal_vout)
**KMS**
- omxiv - no …

Switch to using VLC for splashscreen

---

scriptmodules/supplementary/xpad.sh
scriptmodules/supplementary/xpad/03_xpad_add_version.diff

DKMS in Bookworm has a bug[1] where the autoinstall function on kernel updates fails due to a miscalculated version comparison, thinking always that the kernel version is newer than the custom version and skipping the installation. The message shown during upgrades is:
xpad.ko.xz:
Running module version sanity check.
Module version  for xpad.ko.xz exactly matches what is already found in kernel
DKMS will not replace this module.
You may override by specifying --force.
Added a module version (copied from the `dkms.conf`'s package version) to have 'dkms' always install the out-of-tree version.
[1] https://github.com/dell/dkms/issues/296, fixed by https://github.com/dell/dkms/pull/297

xpad: force version on kernel module

---

scriptmodules/emulators/amiberry.sh

The 'capsimg.so' wasn't properly copied after build to the plugins folder, making Amiberry unable to load IPF files. Also fixes - apparently - a double free crash on the Pi4 build.

amiberry: fix 'campsimg' plugin installation

---

scriptmodules/supplementary/xpad.sh
scriptmodules/supplementary/xpad/04_fix_build_with_buster.diff

Due to a recent merge of upstream code, the module no longer builds on Linux kernel 5.10, included in Raspberry Pi OS 'buster'. The change needed to compile is minimal, it's caused by a missing event code from 'input-event-codes.h', part of the kernel's UAPI headers.
I've opened an issue at https://github.com/paroj/xpad/issues/291, but in the mean time we can add a small patch for older OSes to fix updating/building the module.

xpad: fix building on Buster kernels

---

scriptmodules/supplementary/splashscreen.sh

Don't install the 05-splash.sh script to kill vlc on Raspberry Pi Buster and below. VLC on Buster on RPI4 will output to MMAL which can overlay on top of EmulatioStation.
Remove 05-splash.sh if already present on Buster.

splashscreen - fix splashscreen ending early on rpi4 on Buster

---

scriptmodules/supplementary/sdl2.sh

Binaries for bullseye are available.
Replaces #3856

sdl2 - update to 2.30.8

---

scriptmodules/admin/joy2key.sh
scriptmodules/admin/joy2key/joy2key_sdl.py

Recent Linux kernels (6.2+) have the ability to disable the 'TIOCSTI' ioctl, thus rendering unusable the method of sending keyboard events to the controlling terminal via `fcntl.ioctl` [1]. Not all distributions have left it enabled currently, but Ubuntu 24.04 has it enabled, affecting the `runcommand` ability to generate keyboard events for a joystick.
Use the `python-uinput` module to create a virtual keyboard and send the proper events through it, without relying on the 'curses' or 'fcntl' modules. Now, since the new module doesn't know about Termios codes, which were used previously, I've added a translation table to accomodate scripts using those capability codes. The `python-uinput` uses the Linux event codes [2].
The new method needs the `uinput` Linux kernel module to be loaded …

joy2key: use 'uinput' for emitting keyboard events

---

scriptmodules/admin/joy2key.sh

On RaspiOS, the install user is part of the `input` group by default, but on Ubuntu is not. Add it during install so that `joy2key` can work as regular user (i.e. as part of `runcommand`).

joy2key: ensure the install user is part of 'input' group

---

scriptmodules/admin/joy2key.sh

Add an udev rule to give the `input` group write access to `/dev/uinput` in order for the python uinput device(s) can be created.
I didn't notice this since I had a similar rule added from the `steamcontroller` package installation on my systems and the `/dev/uinput` device had the correct (`root:input`) Uid/Gid.

joy2key: add udev rule for /dev/uinput permissions

---

scriptmodules/supplementary/gamecondriver.sh

Upstream has re-organized the repository with the new versions for DB9/Gamecondriver and removed the version suffix from the source folders. Modified the module to fix the symlink to `/usr/src` needed by `dkms` and also fix the license URL.

gamecondriver: update for newer version

---

scriptmodules/supplementary/retronetplay.sh

Ensure that we specify ipecho.net reports back an IP4v address, instead of IP6v. This way it's easier for the User to provide their Host IP Address to the Client player

Update retronetplay.sh with IP4v Address

---

scriptmodules/ports/gzdoom.sh

The new version has lots of bugfixes and adds support for the new Doom II add-on "Legacy of Rust" released by Bethesda with the Doom(+II) re-release.
New in version 4.13.0:
* Added pistol start gameplay option
* A few ID24 spec implementations, adds support for new Bethesda DOOM + DOOM II re-release and Legacy of Rust
* Several multiplayer network fixes, especially with prediction
* Some savegame fixes, should now be able to delete them on windows
* Add Extra Parameters to iwad selection box
* iwad selection box now always shows unless one of the following is true: it is disabled, -iwad is used from command line, or you load in a gameinfo that suggests an iwad
* Add mbf21 and mbf21 (strict) compatibility presets
* Particles and rollsprites are now square
* ZMusic update, allows selecting …

gzdoom: update to version 4.13.0

---

scriptmodules/supplementary/dbar4gun.sh

Now it can be configured from the RetroPie menu, and we have access to a debug gui.
Feature support
-----
- Standard configuration for Wii sensor
- Only DolphinBar in mode 4
- 4 wiimote x Dolphinbar (very fast with a single bar)
- Generic wiimote
- Bluetooth
- wiimote with individual buttons
- tilt correction
- calibration two points
- calibration three points
driver: https://github.com/lowlevel-1989/dbar4gun

added parameters and debug gui to dbar4gun

---

scriptmodules/admin/joy2key.sh
scriptmodules/supplementary/runcommand.sh
scriptmodules/supplementary/runcommand/runcommand.sh

There are 2 (uinput) related changes here:
* The SDL2/Uinput based Joy2Key is too slow for Pi1/0 devices, so allow the user to choose the older version. The older version is simpler since it doesn't need or load SDL2/Uinput, thus faster to load on those systems. By default, on ARMv6 devices the old version will be configured.
* The Uinput based event generation of keyboard events is not able to trigger the `runcommand` menu when launching images splash is done via `feh`, since the image display will get always have focus and thus the keybord events will not reach the `runcommand` terminal. So, in order for the `runcommand` menu to work after the splash image, make sure we stop `feh` before launch, just like `fbi` is stopped on non-desktop systems.

joy2key: allow selecting the non-SDL version

---

scriptmodules/emulators/xroar.sh

New in version 1.6:
*  New machine Dragon Professional (Alpha), 'dragonpro'
*  New machine Tandy Deluxe Colour Computer, 'deluxecoco'
*  New -ram-org option to specify RAM addressing
*  New -ram-init option to specify initial RAM state
*  6309 DIVD behaviour fixed against Tim Lindner’s fuzzing tool
*  6309 DIVD timing fixed according to David Banks’s behaviour notes
*  6309 DIVQ behaviour & timing adjusted similarly, though untested
*  More accurate observed NTSC CoCo 3 GIME composite video behaviour
*  New GTK+ 3 UI
*  New printer control dialog (GTK+ 3, Windows) or menu options (Mac OS X+)
*  More keyboard virtual joystick profiles included by default
*  All physical joysticks selectable from menus by default

xroar: update to 1.6.6

---

scriptmodules/emulators/mame.sh
scriptmodules/libretrocores/lr-mame.sh

Force PLATFORM=arm on arm systems. Without this mame builds for aarch64 and sets PTR64=1 erroring out with:
static_assert(sizeof(void *) == 8, "PTR64 flag enabled, but was compiled for 32-bit target\n");
This also fixes building of lr-mame2016

mame/lr-mame - fix building on aarch64 kernel with 32bit arm userland

---

scriptmodules/emulators/mupen64plus.sh
scriptmodules/emulators/mupen64plus/remove_fast_math.diff

These commits fix building on 32bit RPIOS Bookworm, with the RPI5. This patch may break if optimisation changes are made in the Makefiles. I was thinking to just "sed" them but can see how this goes. There may be a better fix also - but want to get this building for now. The de-duplication of the code is useful however.
**mupen64plus - de-duplicate make parameters** 
The make parameters are needed at the install stage and build stage so move them to a function.
Rename variable $source to $dir in the install loop - This matches the build function. An undefined variable $dir was used previously.
This also fixes some slight differences between them that were unnecessary:
* isPlatform "rpi1" && params+=("VFP=1" "VFP_HARD=1") was missing from the install stage
* install was missing isPlatform …

mupen64plus - fix building on rpi5 with aarch64 kernel + arm userland

---

scriptmodules/libretrocores/lr-flycast-dev.sh

There's no 'gles2' flag, use 'gles' to detect GLES2 only systems and add the GLES build options (e.g. Pi3). Added the project's README.md file to the installation.

lr-flycast-dev: fix build for GLES2 systems

---

scriptmodules/libretrocores/lr-mupen64plus-next.sh

**lr-mupen64plus-next - fix building on aarch64 kernel with arm userland**
**lr-mupen64plus-next - fix building on rpi5 on 32bit arm bookworm**
On the rpi5 on 32bit arm rpios bookworm, building failed with
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h:18284:34: error: unknown type name ‘float16x4_t’; did you mean ‘bfloat16x4_t’?
18284 | vfmlal_low_f16 (float32x2_t __r, float16x4_t __a, float16x4_t __b)
|                                  ^~~~~~~~~~~
|                                  bfloat16x4_t
Add the option -mfp16-format=ieee which fixes this.
Use an array add_clags to handle the additional CFLAGS changes and use for the linkage_arm.S workaround.

Fix building lr-mupen64plus-next on 32bit arm RPIOS Bookworm

---

scriptmodules/libretrocores/lr-mame.sh

This keeps the plugins directory and adds configuration to enable the highscores plugin.
This makes every game I tested's highscores work out of the box.
Tested on Debian 11 & 12, 32bit and 64bit ARM.

Enable Highscores for lr-mame

---

scriptmodules/emulators/mame.sh

Seems like setting `LDFLAGS` is not enough (anymore) to strip debugging info from the binaries. Use `ARCHOPTS` instead, as the build documentation recommends.

mame: fix linker flags for debug info removal

---

scriptmodules/supplementary/xpadneo.sh

Most likely the last v0.9.x release, followed by v0.10.x which will probably not use `dkms` for build/install.
Headlines:
* core, quirks: Add GameSir T4 Nova Lite support
* core, quirks: Add GuliKit KK3 MAX quirks
* core, quirks: Add heuristics to detect GameSir Nova controllers
* hid-xpadneo: Actually allow building with kernel 6.12
* hid-xpadneo: Allow building with kernel 6.12
* xpadneo, core: Add configuration for disabling Xbox logo shift-mode
* xpadneo, core: Fix coding style
* xpadneo, hidraw: Fixup previous commit to properly work with DKMS
* xpadneo, hidraw: Work around other software messing with our udev rules
* xpadneo, quirks: Let another Microsoft OUI bypass heuristics
* xpadneo, quirks: Prevent applying heuristics for some known vendors

xpadneo: update to v0.9.7

---

scriptmodules/supplementary/xpad.sh
scriptmodules/supplementary/xpad/04-revert-guard-usage.diff

The recent rebasing of the `xpad` driver onto the latest upstream version has added a new feature present only on 6.5+ kernels. Back out that change so that we can still use the driver on older kernels and also pin the source to a repo commit, just to prevent a build failure in case upstream reverts also the offending changes.
NB: This should be just a temporary workaround until upstream fixes the compatibility, which may take some time.

xpad: fix build for older kernels

---

scriptmodules/system.sh

The Ubuntu versioning is based on https://linuxmint.com/download_all.php. Debian versioning is kind of a guess, since there's a separate LMDE os release.

system: add support for Linux Mint 21/22

---

scriptmodules/emulators/amiberry.sh

A conf with `rom_path` defined (or `floppy_sounds_dir`) is required for program start. Create file on new install and `chown` to user/group.
https://retropie.org.uk/forum/post/301768

amiberry.sh - create conf when not exist and include rom_path value

---

scriptmodules/emulators/zesarux.sh

Highlights for the new 12.0 release (full changelog at https://github.com/chernandezba/zesarux/releases/tag/ZEsarUX-12.0):
* Added ZX Microdrive emulation on ZX Spectrum
* Added machines Czerweny CZ 1000, CZ 1500, CZ 1000 Plus, CZ 1500 Plus, CZ 2000, CZ Spectrum, CZ Spectrum Plus
* Added LEC memory extension emulation
* Added Memory Cheat feature: useful to find counters of energy, bombs, ammo or any other cheat in a game
* Added Quicksave screen function
* Added CPC Additional ROMS emulation
* Added setting "--simplemenus" to have a very simple main menu
* Added Visual Cassette Tape window
* Improved ZX Improved Spectrum Next emulation
* Various improvements to emulation and in specific areas (Hilow Datadrive emulation, Debugging, ZX Vision, ZX Desktop)
* Lots of fixes and QoL …

zesarux: update to version 12 - Bubble Bobble edition

---

scriptmodules/emulators/stella.sh

Full changelog is at https://stella-emu.github.io/changelog.html, some highlights:
* Added automatically enabled phosphor modes.
* Enhanced Game Properties dialog for multigame ROMs.
* Added 2nd UI theme and hotkey for toggling UI theme.
* Added bezel support (incl. Sinden Lightgun).
* Added optional type format detection based on colors used.
* Added Joy2B+ controller support.
* Added auto detection for QuadTari attached controllers.
* Enhanced Kid Vid support to play tape audio.
* Added port selection, used for controller default mapping.
* Added missing PlusROM support for E7 bankswitching.
* Enhanced movie cart (MVC) support.
* Accelerated emulation up to ~15% (ARM) (!!)
* Added limited GameLine Master Module bankswitching support.
* Added 03E0 bankswitching for Brazilian Parker Bros …

stella: upgrade to 7.0

---

platforms.cfg
scriptmodules/libretrocores/lr-ep128emu.sh

New system also added. Theme icon was recently submitted: https://github.com/RetroPie/es-theme-carbon-2021/pull/24
Added as experimental for now, but the libretro core has been in use since a while. Script based on lr-caprice32 and recent additions.
Tested on RPi 4, but core can be compiled for armv7, x86, x86_64 architectures so it is not restricted.

Enable Enterprise 128 emulation via ep128emu libretro core.

---

scriptmodules/supplementary/skyscraper.sh

In essence the `deepdiff_peas_jsonfiles.py` should be installed by the scriptmodule with the [release 3.15.0](https://github.com/Gemba/skyscraper/releases/tag/3.15.0) to ease the maintenance of [local changes](https://gemba.github.io/skyscraper/PLATFORMS/#step-1-transfer-platform-information-peas-to-local-file) to the platform configuration.
The change related to the topic in the forum: https://retropie.org.uk/forum/post/301718
I did not put python3-deepdiff to the scriptmodules dependencies as the platform configuration maintenance is an advanced use-case and not a base requirement to run/build Skyscraper.
The remainder of changes in here are cosmetic.
Thanks.

Update for Skyscraper v3.15.0

---

scriptmodules/emulators/mame.sh

**mame - fix rpi3 build on 32bit arm userland with aarch64 kernel** 
Workaround g++-12 compiler bug/compilation issue on 32bit arm userland with aarch64 kernel on the rpi3 (cortex-a53)
Disabling -ftree-slp-vectorize works around the issue:
{standard input}: Assembler messages:
{standard input}:4045: Error: co-processor offset out of range
make[2]: *** [skeleton.make:2727: obj/Release/src/mame/skeleton/scopus.o] Error 1
Add arch_opts_cxx array to handle adding additional parameters to ARCHOPTS_CXX.
**mame - disable distcc**
Mame doesn't work with distcc - add the nodistcc flag.

Fix building MAME on rpi3 with 32bit arm userland and aarch64 kernel 

---

scriptmodules/supplementary/dbar4gun.sh

On Buster, there's no `virtualenv` command in the `python3-virtualenv` package, so use an alternate syntax to create the virtual environment. On RaspiOS Buster the version of Python is 3.7, while the calibration code added in 0.14.0 needs 3.8, so choose an older version when Buster is detected.
@lowlevel-1989 - does this seem ok ?

dbar4gun: fix installation and add version selection

---

platforms.cfg

According to the docs:
> a `.bin` is a DragonDOS or RS-DOS binary file. XRoar will determine which type it is from the header and load it into RAM, then tell the CPU to jump to its start (EXEC) address.

coco/dragon32: add .bin extension

---

scriptmodules/emulators/xroar.sh

Added also the new `.bin` extension to the help text for the emulator.
New in version 1.8 (full change log at https://www.6809.org.uk/xroar/doc/ChangeLog):
* Fix mouse virtual joystick on resize in SDL builds
* New manual and automatic configuration saving from GUI
* Manage HD mounting from drive control dialog
* New MCX128 cartridge support for MC-10
* Fix some of the compatibility modes in GIME emulation
* Assert monitor detect line on CoCo 3 when RGB output selected
* Reduce write latency using Becker port
New in version 1.7:
* Avoid X11 keyboard init when SDL not build with X11 support
* SDL joystick module supports hotplug where possible
* Support reading a SDL gamepad DB file for non-SDL joystick modules
* New -joy-db-file option specifies SDL-compatible gamepad DB file
* New Linux …

xroar: update to version 1.8.x

---

scriptmodules/supplementary/emulationstation.sh
scriptmodules/supplementary/emulationstation/configscripts/sdl2.sh
scriptmodules/supplementary/runcommand/runcommand.sh

There are numerous emulators and ports that use the SDL2 libraries for gamepad/joystick input. Most of them have adopted the usage of the GameController SDL API in order to automatically configure the detected gamepads, based on either the built-in SDL mappings or an (additional) external mapping file. For instance, PPSSPP distributes a `gamecontrollerdb.txt` and Flycast automatically reads a `gamecontrollerdb.txt` for additional gamepad mappings.
This PR adds the ability to:
1. create a SDL compatible mapping for any gamepad configured in EmulationStation, using an input configuration script similar to RetroArch/Mupen64/etc.
2. make the mapping available to emulators/ports started from `runcommand` automatically, by using a SDL hint to point to the saved mappings
This should primarily …

Input auto-configuration for SDL2 gamepads

---

scriptmodules/emulators/mupen64plus.sh
scriptmodules/libretrocores/lr-mupen64plus-next.sh

* for the libretro core, removed a couple of packages which are not needed for the libretro core.
* for the standalone, removed `libglew` which is only used on Windows for one of the plugins and make the GLU libraries mandatory since the core doesn't build without it.

mupen64plus: adjust dependencies

---

scriptmodules/emulators/hypseus.sh

This addition allows the new multi-game (zip) ROM's to be used without the need for symlinking.
This will aide: **actionmax**, **captainpower** and _SEGA_ **videodriver** multi games, to now:
``` 
roms
|-- daphne
|    |
|    |-- cpower1.zlua (single line containing parent zipname "captainpower")
|    |
|    |-- captainpower
|    |    |
|    |    |-- captainpower.zip [Main zipped LUA package]
|    |    |-- cpower1.commands (Optional)
|    |    |-- cpower1.txt      [Video Framefiles]
|    |    |-- cpower2.txt
|    |    |-- ...
|    |    |-- video
|    |
|    |
|    |
|    |-- 38ambushalley.zlua (single line containing parent zipname "actionmax")
|    |
|    |-- actionmax
|    |    |
|    |    |-- actionmax.zip          [Main zipped LUA package]
|    |    |-- 38ambushalley.commands …
```

Hypseus: Simplify multigame zipped ROM +  add dependencies for (v2.11.4)

---

scriptmodules/supplementary/snesdev.sh
scriptmodules/supplementary/snesdev/001-wiringpi-static.diff

**NB**: should be merged after #4019.
New version of SNESDev needs WiringPi, but not the original version that got discontinued. There's an active fork of WiringPi which also provides `.deb` files, so check whether this new version is installed first before compiling locally a static version and using it.
Other modifications:
* modified the installation/build to use `$md_build` and handle the installation ourselves, instead of using the upstream `make` targets. This means the driver is copied to `/opt/retropie` (just like `xboxdrv`) instead of being located in `/usr/local`.
* added a `systemd` unit file to start the driver and don't rely on the upstream `rc.d` service scripts.

snesdev: update to new version

---

scriptmodules/supplementary/emulationstation/configscripts/sdl2.sh

Based on the feedback from @protocultor:
- add the correct Hat mapping value ('h' and not 'hat')
- don't add automatically direction signs for axis mappings since they're only necessary in certain configurations. However the info from the ES file is not enough to determine those configurations, though they seem to be an exception rather than the norm. One case where the signs are needed seems to be when the D-Pad is mapped using axis, so that was left implemented.

emulationstation: fixes for the SDL2 gamecontrollerdb

---

scriptmodules/ports/lzdoom.sh

LZDoom build fails using a recent GCC (14.x), due to C++ (new) dialect changes.
As a workaround, disable the GTK launcher from build to avoid the compilation errors. We don't use it and it's only built of GTK3 dev libraries are detected, but disable it so the compilation is not attempted even when the GTK3 dev libraries are installed.

lzdoom: fix building with newer GCC

---

scriptmodules/ports/eduke32.sh
scriptmodules/ports/eduke32/0006-e4m4-water-bug.patch

combined r8241 and r8247 to fix instant death when going underwater.
Forum post: https://retropie.org.uk/forum/topic/37010/patch-eduke32-e4l4-water-in-d-cup-ride-area-kills-duke-instantly

eduke32.sh - patch a gameplay bug in e4m4

---

scriptmodules/admin/joy2key/joy2key_sdl.py

When trying to match a RetroArch configuration profile to a detected joystick, try to use the Product/Vendor IDs in addition to Name and GUID. This covers the cases where the device naming changes between profile creation and `joy2key_sdl` runtime. We previously matched by the `input_device_name` found in the `.cfg` and GUID, but the GUID was actually not useful since it can't be read from the config profile `.cfg`.
Added also a few more debugging statements to show the configuration profiles loaded and to print the Product/Vendor IDs along the device name.

joy2key: match config by Product/Vendor IDs

---

scriptmodules/emulators/dosbox-sdl2.sh
scriptmodules/emulators/dosbox-sdl2/001-sd2.0-check-remove.diff

The configure script checks for SDL 2, but the test program run afterwards checks only for 2.0.x. Removed the check to allow compilation with any SDL2 version.
NB: while this fixes the compilation, the emulator gets stuck on exit on RaspiOS Bookworm and the SDL KMS video driver.
Fixes #4062

dosbox-sdl2: fix build with SDL 2.x

---

scriptmodules/ports/yquake2.sh
scriptmodules/ports/yquake2/hotkey_exit.diff
scriptmodules/ports/yquake2/sdl2_joylabels.diff
scriptmodules/ports/yquake2/yq2.cfg

Changelog: https://github.com/yquake2/yquake2/blob/QUAKE2_8_50/CHANGELOG
Most relevant addition for RetroPie is a new **OpenGL ES 1.0** renderer, which provides excellent performance under _Buster_ for basically all Pis that are supported in this OS.
Works on _Bullseye_, but requires a little fiddling to run the Legacy driver there:
https://github.com/yquake2/yquake2/pull/1128#issuecomment-2265372663 (point 2).
Note that, even if you don't use GLES1, its new options for optimization in mobile / embedded GPUs (`gl1_discardfb` and `gl1_lightmapcopies`)  are also available in GL1, so all SBCs and their OSs are benefitted from it.
This PR includes:
- A patch that enables the "_Exit shortcut_", RetroArch style, in YQ2. Meaning, _Hotkey_ + _Start_ immediately quits the game and returns to …

Yamagi Quake 2 version 8.50 overhaul

---

scriptmodules/ports/gzdoom.sh
scriptmodules/ports/gzdoom/armv8_gcc12_fix.diff

When compiling with armv8 with gcc12 and an aarch64 kernel, the build fails with
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h: In function ‘float16x8_t vmulq_n_f16(float16x8_t, float16_t)’:
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h:17784:14: error: conversion of scalar ‘float’ to vector ‘float16x8_t’ involves truncation
17784 |   return __a * __b;
|          ~~~~^~~~~
make[2]: *** [src/CMakeFiles/zdoom.dir/build.make:685: src/CMakeFiles/zdoom.dir/common/rendering/gles/gles_renderer.cpp.o] Error 1
Enabling -fmath-errno resolves the build error. This may be a gcc bug - not sure.

gzdoom - fix build with gcc 12 for armv8 on aarch64 kernel

---

scriptmodules/libretrocores/lr-bennugd.sh

This adds an experimental package for running games made with https://www.bennugd.org/ with my libretro core. I tested building from source on my Raspberry PI 3b with retropie 4.8. 
The most prominent game this runs is [Streets of Rage Remake](https://en.wikipedia.org/wiki/Streets_of_Rage_Remake) but others work too.

Add BennuGD_libretro

---

scriptmodules/ports/eduke32.sh

...so shareware version is not downloaded unnecessarily, in case user has old DOS files in ALL CAPS. Add `rename` dependency. Modeled after **wolf4sdl**.

eduke32: (QOL) ignore case when check for user game data

---

scriptmodules/ports/srb2.sh
scriptmodules/ports/srb2/001-cmake-libfind.diff

* changed the upstream Git repository from Github to their own server
* updated the SRB2 scripmodule to install the latest vesion (2.2.15)
* removed support for older Debian versions where OpenMPT had issues
* changed the build/installation to download the assets directly from the SRB2 releases and adjusted the included assets
* patched CMake detection for a couple of libraries due to a bug in CMake < 3.18 (i.e. Debian Buster)
EDIT: Supersedes #3497

srb2: update to 2.2.15

---

scriptmodules/emulators/atari800.sh
scriptmodules/emulators/retroarch.sh
scriptmodules/ports/cannonball.sh
scriptmodules/supplementary/controlblock.sh
scriptmodules/supplementary/moonlight.sh
scriptmodules/supplementary/powerblock.sh
scriptmodules/supplementary/raspbiantools.sh
scriptmodules/supplementary/sdl1.sh
scriptmodules/supplementary/sdl2.sh

Remove the dependency on `libraspberrypi` packages for new RaspiOS Bookworm installations, since they're not useful anymore. 
To do this, make the installation/usage in various scriptmodules depend on the `dispmanx` system flag instead of the `rpi` system flag. `dispmanx` is not set/used on RaspiOS Bookworm/Bullseye, but will still be set/used on Buster as before for Pi 0-4 platforms.

various: don't depend on 'libraspberrypi'
