- scriptmodules/emulators/dgen.sh
- scriptmodules/emulators/dosbox.sh
- scriptmodules/emulators/mame4all.sh
- scriptmodules/emulators/retroarch.sh
- scriptmodules/helpers.sh
- scriptmodules/libretrocores/mupen64libretro.sh
- scriptmodules/supplementary/dispmanx.sh
- scriptmodules/supplementary/emulationstation.sh
- scriptmodules/supplementary/gamecondriver.sh
- scriptmodules/supplementary/hotkey.sh
- scriptmodules/supplementary/setavoidsafemode.sh
- scriptmodules/supplementary/snesdev.sh
- scriptmodules/supplementary/xboxdrv.sh
Since the most common usage is to change a few configuration values at once, we now have a iniConfig function that sets up the delimiter type (such as "=" or " = "), the value quote character (often "" nothing or "\"" a single quote) and the filename. you can then just call "iniSet" or "iniUnset" with two parameters for key and value. A third parameter can be used in case you wish to use the current ini settings but on a different file. We should now easily be able to handle any key/value configs whilst keeping the code simple/compact
> reworked ini/config setting to reduce copy/paste and make the calling simpler

- scriptmodules/emulators/scummvm.sh
- scriptmodules/retropiesetup.sh
enabling:
* virtual / on screen keyboard
* keymapper gui for mapping keyboard etc
* newer build than debian repository (1.7.0)
rework the scummvm emulationstation config. we launch it from a script now (in roms/scummvm/) that will show up in emulation station too (and act
as a option to launch scummvm gui). Once launched, games can be added to scummvm. on exit, these are then added as files to rom/scummvm with the game id
as the name (.svm) which then show up in emulation station. this makes adding/launching games automatic.
idea for launching came from http://blog.petrockblock.com/forums/topic/guidescript-add-all-your-scummvm-games-to-emulationstation/#post-4814
> switch scummvm to build from source

- scriptmodules/emulators/gpsp.sh
GPSP seems to use GLES without SDL for rendering. So DISPMANX SDL has no effect. I just modified the gpsp source to get the same result as DISPMANX SDL. I also added a SELECT+START exit emulator combo.
https://github.com/gizmo98/gpsp/commits/master
> gpsp: Remove dispmanx flag and keep current resolution.

- scriptmodules/emulators/mupen64rpi.sh
-Store all config files under /opt/retropie/configs/n64.
-Start mupen64plus with --configdir and --datadir command line variables.
-Add an own rom folder so mupen64plus-libretro and mupen64plus can coexist.
-Set runcommand to 0.
> mupen64plus: minor improvements

- scriptmodules/emulators/mupen64rpi.sh
mupen64plus.cfg is build at the first run of mupen64plus. So we cannot change any mupen64plus.cfg related setting here. Mupen64plus runs without --osd and --windowed.
> mupen64plus: Revert some useless changes

- scriptmodules/supplementary/ps3controller.sh
The PS3 installation always fails at line 40. Should be fixed with the right sixpair path. See:
http://blog.petrockblock.com/forums/topic/possible-script-error-in-retropie/
> ps3controller: Fix sixpair path

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/libretrocores/mupen64libretro.sh
The module should be ready now (again). I renamed mupen64plus because we don't use the deprecated mupen64plus-rpi repo.
> Move MUPEN64Plus to source based installations.

- scriptmodules/emulators/retroarch.sh
To fix this issue: https://github.com/petrockblog/RetroPie-Setup/issues/623
> retroarch: Add SDL2 dependency

- scriptmodules/helpers.sh
- scriptmodules/retropiesetup.sh
- scriptmodules/supplementary/sdl1.sh
Emergency averted
https://github.com/raspberrypi/firmware/issues/354
memory allocation change in latest firmware caused a problem in SDL to be more apparent causing most programs to output a black screen. A clever fellow pssc had already fixed up sdl1.2 for the pi as part of a patchset for squeezeplay. This fixes the issue and sdl 1.x should be considerable more stable now - it has some other fixes also - see https://github.com/pssc/squeezeplay/commit/a86bc0b47223aceda3218b364f44654c3530985f. More info on the issue on the first link.
This pull requests adds a new module that downloads the source for sdl1, and packages it up. Binaries are ready to go. also includes a change so getDepends libsdl1.2-dev will install our provided packages rather than the debian provided ones. Hopefully in the …
> own packaged sdl1.2 for the pi

- scriptmodules/libretrocores/mupen64libretro.sh
I modified mupen64plus-libretro Makefile so we can use NEON assembler and ARMv7 instructions:https://github.com/gizmo98/mupen64plus-libretro/commit/a647345287912f2a06ec6e0f2165a6f98e836866
I have no PI2 atm. So this change is experimental.
> mupen64plus-libretro: Add experimental pi2 target

- scriptmodules/emulators/mupen64plus-testing.sh
Ricrpi has done a really nice job. But his fork is not updated as frequently as mainline repo. PRs and upstream fixes are not always merged. Mainline repo is working now with rpi. There is slight performance hit, but it is still much faster as mupen64plus-libretro. Moreover the mainline repo is not stripped down for ARMv6 and could run better with PI2. 
Rice is the default video plugin. I added a texture filtering fix to get rid of pixelated textures (shadows, water and so on) and enabled default 2x multisampling antialiasing.
> Add experimental mupen64plus (testing) mainline module.

- scriptmodules/emulators/mupen64plus-testing.sh
@joolswills @petrockblog 
Please add this fix. The module is not working if iniConfig is not set.
> mupen64plus-testing: Fix typo

- scriptmodules/libretrocores/genesislibretro.sh
Some users mentioned genesis core runs better as picodrive.
http://blog.petrockblock.com/forums/topic/has-anyone-gotten-phantasy-star-1-to-work/#post-86668
> genesis: Add genesis mastersystem emulator to emulationstation

- scriptmodules/emulators/mupen64plus-testing.sh
gles2n64 has two new options "multisampling" and "auto resolution". If "auto resolution" is enabled gles2n64 uses the current screen resolution. So it is only necessary to change the screen resolution with runcommand.sh. 
I also enabled zelda hack by default and added some comments.
> mupen64plus-testing: Use gles2n64 again

- scriptmodules/emulators/mupen64plus-testing.sh
It is no longer necessary to create config files. The files were merged in the appropriate plugin repository. I created rom dirs for gles2n64 and gles2rice. There will be always games running only with one of these plugins.
Other changes:
-Added two dependencies for audio plugins.
-Added make option -j2 for PI2. Compiles much faster with two threads. 
-Added experimental glide64 plugin. Runs but is really slow.
-Copy *.conf files as well.
> mupen64plus-testing: Cleanup and rework

- scriptmodules/helpers.sh
-add #include $configdir/all/retroarch.cfg to core specific retroarch.cfg if missing.
-set default core specific settings here.
This change is necessary if we remove --appendconfig. ensureSystemConfig did not overwrite old config files. So if we set default --config $configdir/"core"/retroarch.cfg and there is already a $configdir/"core"/retroarch.cfg $configdir/all/retroarch.cfg wouldn't be included.
> Modify ensureSystemConfig for old retroarch.cfgs

- retropie_packages.sh
- retropie_setup.sh
- scriptmodules/admin/setup.sh
Seemed logical since everything else is a module apart from init stuff, to make the retropie-setup a module too.
did a bit of code cleanup too.
no major differences doing it like this, apart from you can easily trigger any of the menus manually from retropie_packages - such as `./retropie_packages.sh setup binaries` to do a binary install (and later could be called directly from the retropie menu in emulationstation for doing an update etc)
> retropie-setup as a module

- scriptmodules/libretrocores/tyrquake.sh
Makefile.libretro was renamed. Use Makefile now.
> Fix tyrquake.sh

- scriptmodules/emulators/retroarch.sh
Get rid of this annoying search box joypad mapping until there is a real fix:
http://blog.petrockblock.com/forums/topic/controlle-issuesfreezing-when-accidentally-pushing-search-button/#post-90387
I have already done a PR but it was rejected. I have no interest hard boot my rpi every time i accidentally press x in RGUI so my SD card gets corrupted or something else.
> RetroArch: Disable search box until there is a fix

- scriptmodules/emulators/mupen64plus-testing.sh
Use vfp assembler if platform=rpi1.
> mupen64plus-testing: gles2n64 use VFP optimized code

- scriptmodules/emulators/mupen64plus.sh
Backport from testing. The user can select video plugin without editing mupen64plus.cfg.
> mupen64plus: add systems for both video plugins

- supplementary/platforms.cfg
This trivial change allows .32x and .32X files to be autodiscovered.
> lowercase .32x

- scriptmodules/supplementary/usbromservice.sh
- supplementary/01_retropie_copyroms
* always sync the roms folder - so latest rom folders are made available.
* use an array to map retropie / usb configs
* rsync without -a - just use -rt (recursive / preserve times). Avoids errors on fat32, and we will get away without preserving file permissions - files will be chowned to user when restored also
> Usbromservice

- scriptmodules/emulators/mupen64plus.sh
Don't compile OGL code because this flag is missing.
> mupen64plus: Install with VC=1

- supplementary/platforms.cfg
I have some roms with the .bin extension that work in the listed platforms. I tested with all emulators, for the respective platform.
I have also some .sg roms that i think they are Mega Drive roms, but not sure, could be SG-1000. They work with the 2 Mega Drive emulators so i added too.
> Add some supported formats to platforms.cfg

- scriptmodules/supplementary/limelight.sh
Based on this script:
https://github.com/stsfin/RetropieLimelightInstaller/blob/master/limelightconfig.sh
I cannot test this module finally because i have no geforce to connect to. Is it necessary to have an own section for limelight? Could put it under ports or somewhere else.
Also see: petrockblog#721
> Rewrite limelight setup script to a module

- scriptmodules/supplementary/ps3controller.sh
- scriptmodules/supplementary/ps3controllerpairing.sh
https://github.com/petrockblog/RetroPie-Setup/issues/654
-Add an own pairing module.
-Pair PS3 controller if controller is connected without retropie-setup. Use udev rules.
-Add hciconfig pscan to pair more than one controller.
> Add some sixad optimizations

- scriptmodules/supplementary/ps3controller.sh
Sixad adds the MAC address of a controller to the device name. Autoconfig detections like retroarch autoconfig files or mupen64plus rely on the exact device names. If there is any addition the detection is not working. This "fix" modifies sixad source code so MAC address will not be added anymore.
P.S. VID/PID detection does not work with sixad. Retroarch's udev driver does not check VID/PID for virtual or bluetooth devices. Furthermore according to udevadm the sixad joypad jsX has no VID/PID.
> Fix sixad controller autoconf detection issue

- scriptmodules/supplementary/limelight.sh
The limelight module installer pointed to the wrong rom directory and therefore could not find it's start scripts.
> fix rom path for limelight scripts

- scriptmodules/supplementary/ps3controller.sh
With led_n_auto set to 0, all controllers will show controller 1 LED, even if they are not the first controller.
> Show controller number

- scriptmodules/libretrocores/lr-nestopia.sh
- supplementary/platforms.cfg
Because it is a own system like a SEGA CD or SEGA 32.
http://blog.petrockblock.com/forums/topic/specify-an-emulator-in-runcommand-sh/
> Add famicom disk system as an own system

- scriptmodules/supplementary/ps3controller.sh
Use libusb 1.0 instead of libusb 0.1 so ps3 controller kernel driver can be reattached after sixpair has done the job.
> sixad: Use newer sixpair sources

- scriptmodules/ports/dxx-rebirth.sh
Add script to build DXX-Rebirth from current source.  Add Descent and
Descent 2 to the Ports system.  The build method compiles both d1x-rebirth and d2x-rebirth, therefore, they'll both be installed to a single dxx-rebirth folder, with separate execution scripts.
> Add DXX-Rebirth Port

- scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh
- scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
- scriptmodules/supplementary/emulationstation/inputconfiguration.sh
… xmlstarlet to parse the input xml in one go and load it into an associative array.
Previously the code run xmlstartlet 5 times for every button, for every inputconfig module.
We also skip checking whether the xml contains a button, as rather than hardcoding them, we get
them directly from the xml.
This brings processing time on a rpi1 from 27 seconds to under 5.
> rework and speed up processing of the input configuration

- scriptmodules/ports/Super Mario War.sh
script module to install super mario war to ports from the experimental
menu in the RetroPie Setup script.
> Add Super Mario War to Ports

- scriptmodules/supplementary/virtualgamepad.sh
script that installs a virtual gamepad from Miroof (https://github.com/miroof/node-virtual-gamepads) with node.js that enables people to use their smartphone as a gamepad. The code is probably not the most standardised but it was the only way I was able to figure out how to get it to work. if you have any suggestions for improvement I'm all ears.
> Add Miroof's Virtual Gamepad

- scriptmodules/admin/setup.sh
These changes will make it slightly more convenient when updating the setup script so that people don't have to exit out and then go back in again each time they update the setup script.
> Reload Setup Script after update automatically.

- scriptmodules/supplementary/retronetplay.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
Coded it so that people can have names with spaces.  The nickname is
really an optional aesthetic thing but I think it's a nice touch. 
One more setting to note is "netplay_client_swap_input" it's a simple true false perametre (default
would be true) that allows users to both use player one controls on
their respective devices even if they are player two in the game (but only for each
user which means you can't both be playing the same player one- just
using player one joypad controls) 
If it isn't already on by default, it should be- it probably isn't necessary to add to the module
> Add Nickname to netplay module

- scriptmodules/supplementary/splashscreen.sh
- scriptmodules/supplementary/splashscreen/asplashscreen
and fixed the update-rc.d to match the runlevel in asplashcreen
tested it on RPi 2 and RPi 1- I had to up the sleep perameter to 5 before omxplayer for the rpi 1 because of the slower boot time, you can get away with making it a 3 for the RPi2 if you want the video to boot faster. if you want the video to play all the way through without emulationstation cutting it off you can change `do-start &` to `do-start` in asplashscreen
> Add omxplayer video splashscreen

- scriptmodules/ports/smw.sh
I created a new repo with a more complete commit history as well as
reprogrammed the splashscreens to be raspberry pi specific and also
fixed the paths so all game files are installed into
/opt/retropie/ports/smw
> Fixed paths of Super Mario War for RetroPie

- supplementary/platforms.cfg
verified here:
http://blog.petrockblock.com/forums/topic/vice-issues-with-prg-files-and-drive-sound-emulation/
> Add .prg to Commodore 64

- scriptmodules/emulators/gpsp.sh
I couldnt figure out how to get gpsp to not overwrite the romdir.txt
created so for the time being this PR just enables savestates but they
are all currently saved in /opt/retropie/emulators/gpsp. If people wish
for their configs to be saved they need to exit from the F10 menu rather
than pressing escape.
> revert permissions back to user pi to enable savestates in GPSP

- scriptmodules/emulators/mupen64plus-testing.sh
Runs best with 640x480 and RPI2 OC. C++11 code needs gcc-4.8 or higher.
> mupen64plus-testing: add GLideN64 video plugin

- scriptmodules/emulators/mupen64plus-testing.sh
- scriptmodules/emulators/mupen64plus.sh
Add default gcc version check. If default version is 4.7 (whezzy)
install and use gcc-4.8. Else use default gcc version (jessie=4.9).
> mupen64plus: raspbian jessie compatibility

- scriptmodules/supplementary/ps3controller.sh
@joolswills please take a look if everything is fine. I tested these changes on a fresh RP3.1 installation and with two controllers. Rebooted five times. Disabled and enabled controllers at runtime. Controllers always paired. Issue https://github.com/RetroPie/RetroPie-Setup/issues/654 should be solved now.
ps3helper.sh and ps3pair.sh could be merged somehow because they share 90% code.
1. Workaround second controller pairing issue. Bluetooth dongle is no
longer discoverable after first controller is paired. Reenable pscan
with a udev rule (if virtual input device bt controller shows up
reenable pscan).
2. Cleanup module from old stuff which is no longer necessary because
udev rules manage everything.
3. Add some checks to ps3pair.sh. Check if sixad is running and enable
bluetooth dongle …
> ps3controller: fix two controller issue

- scriptmodules/emulators/xroar.sh
Further to our discussion in https://github.com/osmc/osmc/issues/219. A package is now in the official OSMC APT repository.
> Use rbp-userland-src-osmc package instead of 'hello_pi' tarball to satisfy xroar dependency

- scriptmodules/ports/supertux.sh
So I was thinking, there are quite a few games that can be installed directly with apt-get from the raspbian repositories- would there be any merit to a dynamic menu/script of sorts that builds the games based solely on the repo name as most games scripts will look virtually identical to this one?
That is of course unless you want them to be built from source/ want to be more picky  about what we include with retropie (as some games only work with an x server, some just aren't worth playing, some only require a keyboard etc.)
Just some thoughts anyhow, if you want supertux compiled from source instead of a repo/ don't think its up to snuff then feel free to reject it- just posted it as an option just in case people were interested.
> Add SuperTux to ports

- scriptmodules/emulators/retroarch.sh
-remove old search box fix because it does not work and is not necessary anymore
-default use analog sticks as dpads
> retroarch fixes

- scriptmodules/supplementary/retroarchinput.sh
retroarch-joyconfig is deprecated and no longer part of retroarch
https://github.com/libretro/RetroArch/issues/2388
> retroarchinput.sh: remove retroarch-joyconfig

- scriptmodules/ports/wolf4sdl.sh
I have written a script module to install wolf4sdl. The wolf4sdl source code builds a distinct binary, wolf3d, on the Pi depending upon the game data to be used. Binaries are not compatible with different versions of the game. For example, the shareware binary will not work with the 3D Realms game data.
The script module will first present a menu to let a user select which game data they wish to use. The script currently supports the following versions:
* Shareware version v1.4
* 3D Realms retail version (Apogee v1.4)
* Steam retail version (GT/ID/Activision)
Depending on the user selection, the script module (lines 29 to 40) will then clone the source code and delete the appropriate line(s) in [version.h](https://github.com/mozzwald/wolf4sdl/blob/master/version.h). I'm not sure whether …
> Add wolf4sdl to ports

- scriptmodules/supplementary/emulationstation/configscripts/mupen64plus.sh
- scriptmodules/supplementary/emulationstation/inputconfiguration.sh
-add mupen64plus.sh. Modify InputAutoConfig.ini
-inputconfiguration.sh: add iniGet and iniDel 
Herbfargus and i tested this script with four controllers. 
https://github.com/RetroPie/RetroPie-Setup/issues/729#issuecomment-15829
2871
This script is not intended to setup hotkeys. Another script is necessary to modify mupen64plus.cfg.
--> https://github.com/gizmo98/mupen64plus-retropie-hotkeys
> inputconfig: add mupen64plus script

- scriptmodules/supplementary/scraper.sh
from http://blog.petrockblock.com/forums/topic/scraper-little-details-to-solve/#post-110776
Unless you feel there is a better programmatic way to automate killing of processes when people start the setup script from within emulationstation
> add warning to kill emulationstation before using sselph's scraper

- platforms.cfg
- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/libretrocores/lr-mupen64plus.sh
-switch default emulator from lr-mupen64plus/rice to mupen64plus/rice.
Don’t use glesn64 or GLideN64 because glesn64 does crash with certain
roms and GLideN64 is to slow at HD resolutions.
-remove zip file extension because mupen64plus does not support zip
files.
> n64: use mupen64plus as default emulator

- scriptmodules/supplementary/scraper.sh
Set the scrapper to scrape using 4 different worker threads by default, massively speeding up scraping. Perhaps add a menu allowing the user to select the number of worker threads to use in the future.
> Scrape with 4 worker threads for speed.

- scriptmodules/emulators/reicast.sh
- scriptmodules/emulators/reicast/reicast.sh
- scriptmodules/supplementary/emulationstation/configscripts/reicast.sh
-use reicast upstream repo
-remove or replace cpu related flags
-use system libs instead of precompiled libs
-link emu.cfg and mappings dir into /opt/retropie/configs/dreamcast/
-update input script. create controller config files under
/opt/retropie/configs/dreamcast/mappings
-reicast does not have a dynamic setup. The current event device and
mapping file muste be stored in emu.cfg.
-add startup script. Startup script sets the current /dev/input/event*
device and related mapping file in
/opt/retropie/configs/dreamcast/emu.cfg.
> Add reicast upstream repo

- scriptmodules/supplementary/splashscreen/asplashscreen
this should resolve https://github.com/RetroPie/RetroPie-Setup/issues/135. For those who want a splash and audio together should either just make a video for better syncing or manually sort the two files themselves with multiple instances of omxplayer or equivalent. 
Boot music can be added in the same way that one would add a custom splashscreen
https://github.com/RetroPie/RetroPie-Setup/wiki/splashscreen
> Add audio options for those who want only music on boot

- scriptmodules/emulators/retroarch.sh
Contrary to retroarch's wiki retroarch's sdl2 joypad driver supports hotplugging as well.
https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-withou
t-Xorg#joypads
Switch to sdl2 so there is no button mismatch between emulationstation
generated controller configs and retroarch’s udev driver.
> retroarch: use sdl2 as input_joypad_driver

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
- scriptmodules/emulators/reicast.sh
- scriptmodules/emulators/reicast/reicast.sh
- scriptmodules/inifuncs.sh
-use /configs/all/autoconf.cfg to enable/disable autoconf functionality.
-add two new functions to add set read config file content.
-add functions to mupen64plus and reicast modules.
https://github.com/RetroPie/RetroPie-Setup/issues/1113
> Add Opt Out autoconf functionality

- .gitignore
Both the tmp and logs folders located in the root are generated, and should be ignored.
> Add logs and tmp folders in the root to gitignore

- scriptmodules/supplementary/emulationstation/configscripts/reicast.sh
- scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
-reicast: add workaround for xbox controller button mismatch. Button
numbers have an offset of 15.
-retroarch (udev): add workaround for 8Bitdo controller button mismatch.
Button numbers have an offset of 11.
-retroarch: remove keyboard hotkeys if there is no input_enable_hotkey.
-retroarch: write the current configured joypad input driver into
config file.
> input scripts: add workarounds for some controllers

- scriptmodules/supplementary/runcommand/runcommand.sh
a-Z depends on LC_COLLATE or LC_ALL and can produce weird bugs if user
have set there something other than what we're using by default.
a-zA-Z should work just everywhere.
Fixes #1166 and mcobit/retrosmc#14
> Use safer range expression in get_save_vars

- scriptmodules/supplementary/xboxdrv.sh
Added new menu items to the xboxdrv.sh scriptmodule:
* Number of controllers to attempt to enable (default: 2)
* Size of analog deadzone to use for all controllers (default: 4000)
> [xboxdrv.sh] Added user-configurable analog deadzones and number of controllers to enable.

- scriptmodules/supplementary/xboxdrv.sh
Updating to point to a new xboxdrv repo that integrates the following pull requests from the original xboxdrv repo:
137 - Fix zero-length rumble packets causing infinite rumble on some controllers.
169 - Add support for MadCatz Xbox 360 Marvel vs Capcom Tournament Edition Fightstick.
173 - Fix minor typo.
174 - Fix USB read error causing controller to be unusable until xboxdrv is restarted manually. (Happens somewhat frequently to me, personally.)
175 - Add support for Xbox One controllers (rumble and LED lights not functional yet).
> [xboxdrv] Switch to xboxdrv repo with pending pull requests/fixes

- platforms.cfg
- scriptmodules/emulators/coolcv.sh
Of course we'd first need to add the binary to the archive url
Binary is here (6.2):
http://atariage.com/forums/topic/240800-coolcv-emulator-for-mac-os-x-linux-windows-and-raspberry/page-1
I'm also not super sure on the bios for it and if I'd need to symlink
that to the bios folder.
Don't know if we want to wait until nanochess releases 6.3 for the
Pi with a potential configurable keyboard. Having the source code would make it a bit easier.
> Add CoolCV

- scriptmodules/emulators/coolcv.sh
The first time CoolCV runs a controller mapping file is created here: `/home/pi/coolcv_mapping.txt`  F7 should show key codes for each button press but currently isn't working. Hopefully will be fixed in next CoolCV release.
> Symlink CoolCV Controller Mappings

- scriptmodules/emulators/frotz.sh
- scriptmodules/supplementary/runcommand.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
This has been requested on a few occasions - making the launching less verbose and slightly prettier.
changes are:
Dialog when launching by default.
stdout/stderr logged to /tmp/runcommand.log unless a console app is used like frotz
can switch on use_art for runcommand to show ES artwork before launch - configurable from the runcommand config in retropie-setup
> Clean launch

- scriptmodules/helpers.sh
Preliminary support for direct launch through emulationstation as a result of https://github.com/RetroPie/EmulationStation/pull/1
For example in implementation with kodi: The direct launch path and system name are really only needed and then you indicate a 'true' at the end to enable directlaunch :
```
setESSystem 'Kodi' 'kodi' '' '' '/opt/retropie/supplementary/runcommand/runcommand.sh 0 "kodi-standalone" "kodi"' '' '' 'true'
```
Kodi seems to crash on exit when using directlaunch which may be a separate bug or some conflict with runcommand which may need to be further investigated. I have not tested with other systems and am unsure if it is specific to kodi or if it will happen with all systems.
> Add Direct Launch to Helper Script (set essystem function)

- scriptmodules/libretrocores/lr-beetle-lynx.sh
There are some caveats, lynxboot.img bios is needed in the roms folder and doesn't quite yet launch from emulationstation for some reason. Was hoping that it would address https://github.com/RetroPie/RetroPie-Setup/issues/823 but there might be some upstream things that need to be addressed as it pertains to system directory stuff (particulary with the mednafen emulators it would seem: https://github.com/RetroPie/RetroPie-Setup/issues/1162). 
For reference I have linked the verbose output when launching from the terminal (note the 4096 error is just due to me lacking the BIOS file) 
http://pastebin.com/tXXreyfy
> Add Libretro Beetle Lynx

- scriptmodules/supplementary/scraper.sh
Now that Retropie supports having a merged arcade folder in Retropie 3.5, add support for scraping the arcade folder as MAME.
> Add support for scraping Arcade system as MAME for sselph scraper.

- scriptmodules/libretrocores/lr-beetle-psx.sh
Rubbish performance even on the pi2, mostly for x86 really.  Has the
PlayStation Splashscreen, requires scph5500.bin scph5501.bin
schp5502.bin. see here for more details
http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX same issues
with bios and save directory as other mednafen systems.
> Add Beetle PSX emulator

- scriptmodules/libretrocores/lr-quicknes.sh
Added the QuickNES core to RetroPie. It only supports the NES and not the Famicom Disk System. It is currently the only NES core that supports RetroAchievements as supported by Retroarch.
> Add QuickNES core to Experimental

- scriptmodules/admin/setup.sh
Note it only shows the version of your setup script, not necessarily the
version of software installed.
Should address https://github.com/RetroPie/RetroPie-Setup/issues/949
> Add Version Info to Setup Script

- scriptmodules/supplementary/runcommand/runcommand.sh
If overscan is enabled `fb_res_h = display_res_h - overscan_r
-overscan_l` and `fb_res_v = display_res_v - overscan_t -overscan_b`.
It is false to use display resolution. Just store original fb
resolution and use this value for restore_fb().
> runcommand.sh: fix wrong fb_res restore

- scriptmodules/libretrocores/lr-mess.sh
Added libretro core for latest MESS pulled from git, currently 0.171.
Some additional symlinks or folders may need to be created for systems to work properly.
Documentation on how to set up MESS using this core will be coming in the future to the RetroPie wiki and has yet to be written.
Systems that have been set up for use with this MESS core are only those found to work approximately 100% speed. These include the following: Nintendo Gameboy (uses "gameboy" directory instead of "gb"), Nintendo Entertainment System and Colecovision with more added in the future as they get tested.
Systems that have been tested and that are not up to speed and therefore disabled at the moment include the following (as tested by a Raspberry Pi 2 overclocked to 1067mhz):
Amstrad GX4000 (60% speed)
Atari 2600 …
> Added libretro core for latest MESS.

- scriptmodules/libretrocores/lr-mess.sh
The hashes were being placed into $biosdir/mame instead of $biosdir/mame/hash.
> Fix MESS BIOS hashes incorrect placement.

- scriptmodules/emulators/residualvm.sh
Using pretty much the exact same setup as SCUMMVM with the exception of one particular configure flag. Tested with Grim Fandango in software mode on an overclocked Raspberry Pi 2, working well aside from laggy movies as far as I've seen to this point. OpenGL crashes the program entirely. Disabled "Fullscreen" to get full screen, ironically. Recognized joystick controls on its own without issue. Loading games directly from emulationstation works however it appears that the settings used in the ResidualVM GUI are ignored when launched in this manner. Might have to take a look and see if SCUMMVM has similar behavior. 
(I appeared to be unable to squash this for whatever reason.)
> Added experimental script for ResidualVM

- scriptmodules/ports/gemrb.sh
Tested with Baldur’s Gate and Baldurs Gate 2. Based on:
https://github.com/amigagamer/gemrb-retropie/blob/master/gemrb.sh
https://github.com/RetroPie/RetroPie-Setup/issues/794
The content of the windows installation folder of one of these games must be copied to $romdir/ports/$gamename.
> Add gemrb - open source implementation of infinity engine

- scriptmodules/libretrocores/lr-mess.sh
Added the Emerson Arcadia 2001 console to the lr-mess script.
Notes: Runs 100% on Pi 2. No BIOS required. MAME software list ROMs in $romdir/arcadia.
> Add Emerson Arcadia 2001 console to lr-mess script.

- scriptmodules/libretrocores/lr-mess.sh
Add CreatiVision to libretro MESS core.
Runs 100% or close to it depending on the game played. MAME software list ROMs are required to be in $romdir/crvision. BIOS is required at $romdir/crvision.zip
> Add CreatiVision to libretro MESS core.

- scriptmodules/ports/solarus.sh
Download games compatible with Solarus 1.4 rather than the latest ones
> Use stable URLs to download Solarus games

- scriptmodules/libretrocores/lr-fba-next.sh
Now, if Retropad Start button is held, the game's diagnostic menu appears, allowing various dipswitch settings to add free play and offer effects to FBA and Neogeo games. These settings are saved in the /roms/<system>/ folder as .fs files, and are automatically loaded on game load.
> Added core option defaults to lr-fba-next.

- scriptmodules/emulators/stratagus.sh
This adds the Stratagus engine that can be used to play Warcraft I + II and Starcraft (the latter in a more limited fashion). Extracting the game data into the Stratagus format is not part of the engine. The data has to be extracted from the original media (can be done by using the installers for https://github.com/Wargus/wargus, https://github.com/Wargus/war1gus,  https://github.com/Wargus/stargus on Windows, their debian packages, or their OS X bundles). The extracted folders must then be placed in the roms directory with the folder name ending in `.data`.
I don't know how to get OpenGL mode to work (it doesn't launch for me in that case), I suspect there needs to be work in the engine to support the Raspberry Pi. However, this is a simple 2d strategy engine and software mode works just …
> Add Stratagus

- scriptmodules/emulators/scummvm.sh
The only thing I'm thinking of changing is a few of the parameters which are set when building for the RPI. The savegame timestamps are switched off - this was because the RPI doesn't have a battery backed up clock, but internet connected RPI do have the correct time, so we might want this.
Also the hq scalers are switched off. Sure for performance we don't want them, but some people may want to run in a higher res with a scaler to get a "better image". so It might be worth including them. The event recorder is also switched off, but i dont personally think it will cause any sd card wear to worry about (no more than the system logging etc).
> updated scummvm to 1.8 - use github directly for source, and enable sdl2

- scriptmodules/emulators/retroarch.sh
- scriptmodules/helpers.sh
- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
- scriptmodules/supplementary/configedit.sh
- scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
- scriptmodules/supplementary/retroarchinput.sh
Switching to use quoted values for retroarch.cfg - when retroarch saves the configs itself it uses quotes, since we were not, it broke the config editor - so we might as well just use quotes (even though their skeleton config file does not.
> Config editor

- scriptmodules/inifuncs.sh
This affected [scriptmodules/emulators/mupen64plus/mupen64plus.sh](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/mupen64plus/mupen64plus.sh) in case the retroarch configuration file has spaces in the file name.
> Added missing quotes around file variable

- scriptmodules/emulators/scummvm.sh
Running ./configure results in the following error:
ERROR: The keymapper and the event recorder cannot be enabled simultaneously currently, please disable one of the two
As keymapper is explicitly enabled already, disable eventrecorder.
> fix compiling scummvm from source

- scriptmodules/supplementary/configedit.sh
All scraped images are loaded into the configuration editor list, so depending on how many games are scraped, it can get impractical to navigate.
> Exclude downloaded_images from configedit

- scriptmodules/libretrocores/lr-mame2003.sh
Binaries will subsequently need to be rebuilt to avoid a similar error from installing from old binaries, I presume.
Samples now a core option, rather than hard-coded, so added that, even though they default to enabled. Cheats and sample rates are a core option, but I think these should remain user-preferences.
This is all following https://github.com/libretro/mame2003-libretro/pull/29
Should this PR be extended so the script moves the old paths to the new ones? I believe that should be possible, but may end up making this all a bit messy. I could just update the [wiki](https://github.com/RetroPie/RetroPie-Setup/wiki/lr-mame2003) with a warning?
> Filename change. Avoids script error when rebuilding from source.

- scriptmodules/supplementary/reicastinput.sh
If retropie controller configuration fails this module can be used to setup controller.
> Add reicast input setup module

- scriptmodules/emulators/reicast.sh
- scriptmodules/emulators/reicast/reicast.sh
-fix controller setup under ubuntu 15.10/16.04 (gcc 5.x issue).
-prepare startup script for multiplayer setup. Controller count = player count.
-enable fullscreen for x11 targets.
Tested with Raspbian Jessie and Ubuntu 16.04 x86.
> Reicast optimizations

- scriptmodules/libretrocores/lr-reicast.sh
The current source code cannot be used for rpi. But x86 build works quite well.
> Add lr-reicast for platfom x86

- scriptmodules/emulators/mupen64plus.sh
> mupen64plus: enable audio autoconf for rpi only

- scriptmodules/libretrocores/lr-fba-next.sh
Wiki has been updated. Last remaining reference to the old version!
> libretro-fba is now 0.2.97.38.

- scriptmodules/supplementary/splashscreen.sh
- scriptmodules/supplementary/splashscreen/asplashscreen
* Changed from a directory search to a file search to allow for future restructuring in the splashscreen github to not require files in directories.
* Added an append option to make up for the lost ability to select a directory and append all contained files to the splashscreen.list.
* Added Preview options for images and videos.
* Restructured menus to have toggle options.
* Added a randomizer option that won't show up until an updated asplashscreen has been copied over to /etc/init.d/ during the splashscreen update.
> Updated splashscreen.sh and asplashscreen

- scriptmodules/inifuncs.sh
- scriptmodules/supplementary/splashscreen.sh
- scriptmodules/supplementary/splashscreen/asplashscreen
* addresses some of the points from https://github.com/RetroPie/RetroPie-Setup/pull/1480#issuecomment-219145076
* make functions more standalone and simplify logic - eg choose_splashscreen just returns a splashscreen - setting / preview etc is handled in their own functions
* put extensions into functions
* paths for splashscreen locations is now handled in own function
this needs some testing
> splashscreen:

- scriptmodules/supplementary/bluetooth.sh
- scriptmodules/supplementary/ps3controller.sh
After installation of newest pi-bluetooth package bluetooth is broken. Add necessary package rapberrypi-sys-mods.
@joolswills I don't know if this should be already merged. If raspberrypi-sys-mods will be installed there is a risk users will be asked if an udev rule should be changed.
> bluetooth: fix connection problems

- scriptmodules/emulators/sdltrs.sh
I have tested this and it works, I'm still not super sure about running any from model3 and up but supposedly they should be supported, I just havent really tested it all that much as I couldnt seem to locate an image for those models.
Feel free to tweak as needed
I also wasnt sure if you wanted to keep the source on the retropie organisation instead of on my repo
> add sdltrs trs-80 emulator

- scriptmodules/emulators/ti99sim.sh
tested on both the pc and pi and it seems to be working. I didnt symlink the bios cause it only works in the rom folder but I'm sure we can tweak it as needed after more testing. Thanks to @zerojay for the module
Should address https://github.com/RetroPie/RetroPie-Setup/issues/1435
> add ti-99/4A

- scriptmodules/libretrocores/lr-fceumm.sh
from the forum: https://retropie.org.uk/forum/topic/1981/famicom-disk-system-fds-and-lr-fceumm
I'm also not sure if I got the numbers right on the addSystem function. couldnt remember which was default.
> add fds support for lr-fceumm

- scriptmodules/emulators/retroarch.sh
* manage shaders/overlays from a retroarch gui function, so they can be updated separately from retroarch.
* only install shaders by default (to save on space).
this solves the issue that retroarch binaries are huge by default due to all the overlays, and the fact that people can't easily just update the shaders etc. Once this is in, I will rebuild the binaries to not include the shaders/overlays.
> retroarch changes

- scriptmodules/supplementary/configedit.sh
Reduces need for text editor/terminal use to do this: https://github.com/retropie/retropie-setup/wiki/playstation-1#multitap-3-8-player
Came up in https://retropie.org.uk/forum/topic/2115/dunce-question
> Added game_specific_options to config editor advanced options.

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-Default render resolution is 320x240 for best performance. Use dispmanx to upscale video.
-Use GlideN64 as default video plugin.
-Enable GlideN64 optimizations (NEON assembler).
-Update GlideN64 configVersion.
-Disable GlideN64 FBEmulation. I don't know why but games like MK64 and Castlevania have visual glitches since this morning. Mupen64plus-Core repo was updated today. There could be a correlation. @loganmc10 do you have visual issues with the newest Mupen64plus-Core as well?
> Optimize mupen64plus

- scriptmodules/emulators/mupen64plus.sh
-Use bilinear filtering standard mode to fix super smash brothers and
mario kart texture corruption. https://github.com/RetroPie/RetroPie-Setup/pull/1563#issuecomment-231420842
-Disable audio OMX audio output auto configuration. We use SDL audio
now.
-Disable FBEmulation for now. Conker BFD, Bomberman, Castlevania, Banjo
Kazooie, Super Smash Brothers, Goldeneye and Rayman 2 have extreme visual corruptions if this feature is
enabled. Need to find a way to enable it for Zelda games and Star Wars - SOTE. 
-Use native resolution if FBEmulation is enabled.
> Update mupen64plus Pt.4

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-Enable some GLideN64 optimizations again. 
-Use audio-omx as default audio plugin. Games run much faster if audio-omx is used.
-Switch audio plugin if internal rpi audio device is not used.
-Add GLideN64 FBEmulation enable switch for certain games (Zelda,
Rayman, Pokemon, Diddy Kong Racing etc.).
-Add GLideN64 Rice fallback for majora's mask.
-Make mupen64plus.cfg editing more secure. Add section if section does not exists.
-Take care ScreenshotPath, SaveStatePath and SaveSRAMPath stay the same even if you delete mupen64plus.cfg.
-Fix startup script for other platforms (x86, odroid).
> Update mupen64plus Pt.5

- scriptmodules/emulators/mame4all.sh
- scriptmodules/emulators/pifba.sh
- scriptmodules/emulators/pisnes.sh
- scriptmodules/emulators/retroarch.sh
- scriptmodules/emulators/vice.sh
- scriptmodules/emulators/zesarux.sh
- scriptmodules/helpers.sh
Previously things like retroarch.rp-dist files were always created, even if there were no customisations to the retroarch.cfg files. Now it works a bit more like debian, so these files are only changed if the new default config is different from the existing config (we still don't overwrite users configs).
It does this via a new function, copyDefaultConfig which also allows us to simplify some code, and it should be quicker to implement creation of a rp-dist file for other modules now without code duplication.
> Config defaults

- scriptmodules/emulators/retroarch.sh
- scriptmodules/helpers.sh
- scriptmodules/inifuncs.sh
- scriptmodules/supplementary/bluetooth.sh
- scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
* add autoconf.cfg parameter 8bitdo_hack (default 1) to decide whether to add the offset to the inputs for retroarch - which is required on the older firmware
* make sure autoconf.cfg is owned by $user - it would be created as root previously
* add setAutoConf function
* cleanup retroarch config generation code
> 8bitdo mapping improvements

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-enable legacy blending if possible (speed). 
-enable FBEmulation for killer instinct and jet force gemini
-push config version to 12
@dankcushions 
Could you do a short test again?
> mupen64plus: add legacy blending

- scriptmodules/emulators/dosbox.sh
When launching DOSBox, the mount of the C drive is visible which looks messy, and it doesn't change to C: drive automatically which is inconvenient.
Use @ to hide the commands from the user, and automatically change to the mounted C: drive.
The MOUNT command message displays the mounted path so there is no loss of information about where DOSBox has gotten the C drive from.
> [dosbox] hide commands and change to c:

- scriptmodules/system.sh
Added detection and compiler flags for Freescale i.MX6 platforms such as Udoo
> Suport for i.MX6 platforms

- scriptmodules/supplementary/runcommand/runcommand.sh
Same logic as in `helpers.sh`.
Since the `runcommand-onstart.sh` was implemented, the user can define another joystick device to use with joy2key.
> user can define __joy2key_dev

- scriptmodules/emulators/mupen64plus/mupen64plus.sh
de-duplicated getBinds
added workaround for 8bitdo controllers that need +11 hack (or -11 in this case)
> Mupen64plus

- scriptmodules/libretrocores/lr-glupen64.sh
Optional module for now. Better alternative for lr-mupen64plus.
> Add GLupen64 N64 libretro core

- scriptmodules/supplementary/emulationstation/configscripts/mupen64plus.sh
If controller has left thumb and right thumb add expansion pak enable bindings:
leftthumb = mempak
rightthumb = rumblepak
> mupen64plus: add expansion pak switching

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
@gizmo98 
saw this thread https://retropie.org.uk/forum/topic/3100/4-0-rc1-nintendo-64-high-resolution-and-the-conflict-with-320x240/4 and though maybe something like this?
> mupen64plus - add resolution parameter and highres emulator options

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/gonetz/GLideN64/pull/1087/files
@joolswills 
Mupen64plus needs to be updated. Old gliden64 plugins will not work properly with configVersion 13.
> mupen64plus: Update gliden64 configVersion

- scriptmodules/supplementary/runcommand/joy2key.py
Ignore axis higher than 8 to prevent accelerometer from causing
unintentional movements in curses GUI. Such as happens with DS4
controllers.
> Ignore accelerometer in runcommand

- platforms.cfg
- scriptmodules/emulators/dolphin.sh
-x86 only.
-no hotkeys. (dolphin seems to have no hotkey support?!)
-runs zelda ww with 15-30fps on a Pentium N3050 (Atom based) which is
real good for such a low end platform.
-only system wide installation atm.
-build time > 1h on a Pentium N3050.
-you need a mouse to get emulator window in front.
https://github.com/RetroPie/RetroPie-Setup/issues/1633
> Add experimental gc/wii emulator dolphin

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
common:
-use „-flto“. All mupen64plus plugins use OPTFLAGS = -flto. We
overwrite OPTFLAGS with our CFLAGS until now.
x86:
-add CXD4 and Z64 RSP LLE plugins
-add GLideN64 LLE mode. Allows for example SW Rogue Squadron to start
up.
-add GLideN64 Intel OGL3.3 graphics workaround. This workaround should
be obsolete when Ubuntu 16.04.2 arrives (new mesa 12.1 with OGL4.3
support). There are glitches because OGL3.3 does not support all necessary features.
-enable SSSE3 optimizations. Even ten year old CPUs support SSSE3.
> m64p: some modifications

- scriptmodules/libretrocores/lr-gambatte.sh
Makefile location changed:
https://github.com/libretro/gambatte-libretro/commit/4e4fb2b4a6a4e86242a
9b63c6fc235ef25303d06
https://retropie.org.uk/forum/topic/3789/gambatte-fails-to-install-from-
source-4-0-2-x86
> Fix lr-gambatte

- scriptmodules/emulators/retroarch.sh
As reported by @RetroResolution [in the forum](https://retropie.org.uk/forum/topic/3728/playstation-ffmpeg-recording-causes-seg-fault-in-retropie-4-0-2-recording-megadrive-vcs-etc-still-fine/), the default `menu_driver` for RetroArch on raspi3 is xmb (raspi3 owners can reproduce it after reinstall RetroArch from source and don't explicit set anything for `menu_driver` in retroarch.cfg).
@dankcushions said [here](https://retropie.org.uk/forum/post/23421) that he checked with libretro guys and "apparently it's defaulted differently on different systems". I checked here that raspi3 defaults to `xmb` and raspi2 and 1 defaults to `rgui`. For the sake of uniformity, it's better to explicitly set `menu_driver = "rgui"`, otherwise raspi3 users will get confused by the `xmb`.
> explicit use of rgui as the menu_driver

- scriptmodules/system.sh
Use -march=armv8-a+crc so CRC extensions can be used.
https://github.com/gizmo98/GLideN64/commit/4f74a0d6598b6ed4b29e26ffe59bd4e8ff2eeee4
> Better rpi3 cflags

- scriptmodules/emulators/mupen64plus.sh
https://github.com/gonetz/GLideN64/commit/a471b130e79c71de1791c624ece068
468e89b615
> m64p-rpi3: use armv8 crc

- scriptmodules/supplementary/retropie-manager.sh
RetroPie-Manager is a Django project to manage a Retropie from a web interface.
It is a fork mod of recalbox-manager.
The repository is https://github.com/botolo78/retropie-manager
The forum thread is https://retropie.org.uk/forum/topic/2303/retropie-manager-web-app-recalbox-manager-fork-mod
This scriptmodule was started by @HerbFargus and I just finished.
> add RetroPie-Manager as an experimental package

- scriptmodules/supplementary/retropie-manager.sh
I saw you ( @joolswills ) did it in `install` function, and thought it would be OK to do it in `remove` function too.
I didn't know this trick... :-)
> using "$datadir" instead of "$home/RetroPie" in remove function

- scriptmodules/supplementary/resetromdirs.sh
People end up with bad permissions for a variety of reasons. This script
module currently just resets ownership, it makes no changes to
permissions, even though it claims to.
Add `chmod -R ug+rwX` to fix permissions.
Signed-off-by: Jamie Bainbridge <jamie.bainbridge@gmail.com>
> resetromdirs: Actually fix permissions

- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand/joy2key.py
- scriptmodules/supplementary/runcommand/runcommand.sh
- scriptmodules/supplementary/wikiview.sh
Removed hardcoded escape sequences (cursor keys etc.) and replaced by terminal-independent curses calls that uses terminfo to map to sequences working for the actual terminal.
The problem was that on x86 Lubuntu the DPad of my X360 Gamepad was not working in runcommand because the hardcoded escape sequences were not working for my terminal:
https://retropie.org.uk/forum/topic/4115/xbox360-dpad-not-working-in-runcommand-menu
Is this ok for you? Please do not merge yet, I did not test it yet for RPi but I would like to ask before if you would support this PR.
> replaced terminal-dependent escape sequences by curses mappings

- scriptmodules/libretrocores/lr-glupen64.sh
This core has received a fair amount of testing now on Linux, Windows, Android, and the Raspberry Pi. It is stable and matches the features of mupen64plus+GLideN64.
It's performance is probably still slightly worse than standalone mupen64plus, but that is because of the RetroArch rendering pipeline (the extra work it does to support custom shaders and whatnot), so there is not much that can be done at this point.
Framebuffer Emulation is disabled by default still for the Raspberry Pi since there are still hardware specific bugs present with it (same with standalone mupen64plus)
> Allow glupen64 to rise from the shadows

- scriptmodules/ports/minecraft.sh
- scriptmodules/ports/minecraftpi.sh
I have updated the Minecraft Pi module to be more convenient and relevant.
:)
> Update the Minecraft Pi module

- scriptmodules/emulators/residualvm.sh
This forces ResidualVM to compile with SDL2 and GLES2 support. GLES acceleration gives about 6x the framerate for me on a RPi2 playing Escape from Monkey Island. It is unstable with some games, though, so I added a copy of the launcher script to force software mode.
> Update ResidualVM installation script

- scriptmodules/archivefuncs.sh
- scriptmodules/emulators/vice.sh
- scriptmodules/helpers.sh
Out of the box VICE can load ZIP files but only uses the first disk from the ZIP. This PR should make it possible to put all the disks belonging to a game into one ZIP. Upon startup the ZIP will be extracted into a temp directory and VICE will be started to autoload the first disk from that directory.
The temp directory (containing all unzipped disks) will be passed to VICE as working directory so when the user uses the disk swap functions in VICE he will see the (temp) directory containing all the relevant disks.
This is pretty much just a proof of concept. If you like it I will polish it a bit and test it more. Also I would like to put the unzip functions into a common shell script because I would also like to use it for emulators that do not support ZIP natively (fs-uae currently).
> VICE multi-disk ZIP support

- platforms.cfg
- scriptmodules/emulators/fs-uae.sh
- scriptmodules/emulators/fs-uae/fs-uae.sh
So, me again ;)
Another try on integrating fs-uae into ES. Now taking the ZIP functions into account (so no multi-disk-discovery needed anymore).
Some explanations on some points (does not make them necessarily good decisions ofc):
-  I thought about adding Amiga to platforms.cfg and to store the supported extensions there. But the extensions are depending on the emulator. So fs-uae supports IPF, ADF etc. (and now ZIP) while uae4all seems to be ADF only. I don't know if platforms.cfg is supposed to handle this so I added the extensions as a variable to the emulator script. Actually I wanted to have it (FSUAE_EXTS) readonly but when I declare it readonly it is always empty later in the configure function. I could not find out why.
- I changed the config directory symbolic link from …
> fs-uae - added integration into emulationstation. Supporting ZIPs containing multiple disks

- platforms.cfg
- scriptmodules/emulators/fs-uae.sh
- scriptmodules/emulators/vice.sh
- scriptmodules/helpers.sh
Before a user could have a `configs/all/platform.cfg` file which would be used if it existed. It needed to contain all the information from the retropie distributed platforms.cfg though - which isn't too useful to keep up to date with customisations.
Now it will just override anything in the retropie platforms.cfg - if a key isn't in the user platforms.cfg the system one will be used.
In addition you can now force themes per platform.. eg for North American users - they can create a `configs/all/platforms.cfg` containing
```
megadrive_fullname="Sega Genesis"
megadrive_theme="genesis"
```
and then update any megadrive/genesis emulator and ES will use the above name and theme.
> Platform.cfg changes / customise system theme

- scriptmodules/helpers.sh
- scriptmodules/supplementary/attractmode.sh
- scriptmodules/supplementary/emulationstation.sh
- scriptmodules/supplementary/retropiemenu.sh
* call a _add_rom_module function for each setting
* add _add_rom_emulationstation function for managing gamelists
* add _add_rom_attractmode function for managing attractmode romlists
* rename _addsystem_module to _add_system_module
> retropiemenu - rework retropie menu to support multiple frontends

- scriptmodules/emulators/hatari.sh
I would like to propose these config changes for hatari:
- disable statusbar (permanently visible otherwise)
- disable quit confirmation (needs an extra click otherwise to quit the emu. Other emulators also quit instantly on SIGTERM)
- added fullscreen option for x11
> hatari - disable quit confirmation, disable statusbar. use fullscreen or x11

- scriptmodules/emulators/ti99sim.sh
see also:
https://retropie.org.uk/forum/topic/3033/getting-ti99-emulator-to-work
https://retropie.org.uk/forum/topic/5649/ti-99-emulator-not-working
https://retropie.org.uk/forum/topic/4299/unable-to-locate-console-roms-on-ti99sim
there is also a 1.4 update as of June http://www.mrousseau.org/programs/ti99sim/archives/ not sure if we want to update to that as well and perhaps incorporate some platform specific building with armhf etc. also not sure how much of a priority this system is ;)
> fix ti99 paths so bios actually goes in bios folder

- scriptmodules/supplementary/usbromservice.sh
- scriptmodules/supplementary/usbromservice/01_retropie_copyroms
- scriptmodules/supplementary/usbromservice/10_retropie_mount
* add a new mount.d script to allow mounting of a usb stick directly over ~/RetroPie
* script will check for existance of a retropie-mount folder in the root. If it exists and is empty, the existing ~/RetroPie folder will be copied to it. Then it will be mounted.
Thought I would go for a simple option for allowing users to have their ~/RetroPie folder on a usb stick using the existing usbromservice module.
as mentioned above - you just need a folder in the root called "retropie-mount" and then that folder will be automatically mounted over `~/RetroPie/`
can add some simple gui later to save people having to do this by having a "prep usb stick" function or so, but simple enough to do this on a pc.
Only possible issue is if for some reason ES loads before it is mounted, but it didn't in my …
> usbromservice - support mounting of usb stick over ~/RetroPie

- scriptmodules/supplementary/runcommand/runcommand.sh
When running under X and showing the launching image with `feh`, if the user "press a button" to access the runcommand menu, the image stays in front of the terminal. This change kills the `feh` if the user "press a button".
> kill "feh" when invoking runcommand menu

- platforms.cfg
- scriptmodules/emulators/atari800.sh
.car files are Atari 8-bit cart images created from .bin files by the
Atari800 Emulator itself. They add a metadata header telling Atari800
what type of cart it is and saving the user from entering it manually.
TOSEC managed to scramble some carts by just renaming the .car files to
.bin in a lot of cases, not realising there was a difference. In
retropie, using a .car file in preference to a .bin file will save a
step for the user.
> Add .car files to Atari800

- scriptmodules/libretrocores/lr-mupen64plus.sh
This fix builds lr-mupen64plus properly on ODROID-C1. I have a C2 on the way, and it looks like the fix will be the same for it. If there's a better way to fix this, please let me know and I'll roll it properly, then submit another pull request.
> Hook ODROID-C1 into lr-mupen64plus.sh properly

- scriptmodules/emulators/drastic.sh
The person who did the RPI port recently put out the link to the test port on [this forum post](https://pyra-handheld.com/boards/threads/drastic-nintendo-ds-emulator.73431/page-83#post-1403469), and it's actually playable!
Tested:
- using a Pi 3
- using the Super Mario 64 DS (USA version) ROM
- using the Pokémon HeartGold (USA version) ROM
Results:
- Game speed is usually around 100%
- Smooth, continuous sound
Bugs:
- After you exit the emulator, you can't start anymore applications or else the Pi freezes... The only way around this (at least right now) is to restart the Pi.
> Add DraStic DS Emulator

- scriptmodules/supplementary/bluetooth/bluez-test-device
Currently, enumerating devices with non-ascii characters results in a UnicodeEncodeError.
Simply ignore non-ascii characters to ensure devices can be listed.
> Fix UnicodeEncodeError when enumerating devices

- scriptmodules/supplementary/bluetooth/bluez-test-device
The latest fix made to bluez-test-device did not respect the existing tabs styling present in the file. This commit uses tabs where necessary.
> [bluez-test-device] Fix indent style

- scriptmodules/supplementary/powerblock.sh
@petrockblog made some changes to match this up against other code. Please can you check it still works for you ok. more details in commit messages.
It didn't seem to work for me building / copying to md_inst then trying to install from there - because the previous location was saved in the cmake cache I believe. In this case for something where we need to keep the files around for enabling/disabling/uninstalling, it's best just to checkout to md_inst.
you will need to remove and reinstall though since the install location is now the git checkout.
> Powerblock

- scriptmodules/admin/apidocs.sh
- scriptmodules/admin/wikidocs.sh
Renamed existing docs module to apidocs.
Added this one as wikidocs.
```
sudo ./retropie_packages.sh wikidocs
```
to generate
```
sudo ./retropie_packages.sh wikidocs upload
```
to push to the site (requires your ssh public key in retropie account on our server - we can sort that if you want to test).
docs end up here
https://retropie.org.uk/wikidocs/
thanks for your work on this
> Incorporate Herb's mkdocs work into a module

- scriptmodules/libretrocores/lr-puae.sh
Initial pull request for code review, notes:
- No directory setup for kickstart or rom folders, I set that up with RetroPie assistant template and I can share that too if wanted
- Adding .uae extension (which can also be done by retropieassistant)
- Not verified with other arhitecture hence the restriction
- Save states doesn't work for me (Need to check with upstream maybe)
> Add lr-puae #1871

- scriptmodules/helpers.sh
I was having problems when using loadModuleConfig and the variable's value has spaces.
Example: when using `loading_text="NOW LOADING"`, loadModuleConfig was getting `key=loading_text` and `value=NOW`. After this change it's getting `value="NOW LOADING"`.
I've tested `scraper.sh` with this change to make sure it don't break anything and everything runs fine.
**Note**: the use of quotes on variable definitions should be avoided (maybe prohibited?), like this: `loading_text=NOW LOADING`.
If using `loading_text="NOW LOADING"` it will save this in the ini file:
```
loading_text = ""NOW LOADING""
```
And this excess of quotes symbols with `eval` (in scriptmodules) are a dangerous combination.
> loadModuleConfig's value can have spaces

- scriptmodules/helpers.sh
- scriptmodules/supplementary/controlblock.sh
I have added support for Git repository that use Git submodules. Also, I have added a driver module for the ControlBlock hardware, which is similar to the PowerBlock module.
> Support for Git repositories that use Submodules, drivers module for ControlBlock

- scriptmodules/supplementary/runcommand/runcommand.sh
This error is preventing netplay from working in recent release. --check-frames is new sort of similar(but not the same) option but isn't necessary to be adjusted if it works with default values.
> --frames isn't used by retroarch anymore

- scriptmodules/supplementary/raspbiantools.sh
should fix the whole wastebasket not showing up, mounts, etc.
post for reference:
https://retropie.org.uk/forum/topic/7538/installing-pixel/10
> add gvfs to pixel desktop

- scriptmodules/supplementary/emulationstation.sh
Should be $name instead of $system. There is no $system.
> Fix _del_system_emulationstation

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
Use version 15 until we can use upstream again.
https://github.com/joolswills/GLideN64/blob/flicker_fix/src/Config.h#L7
> mupen64plus: use config version of branch "flicker fix"

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-remove graphics plugin videocore.
-change some GlideN64 settings which produced glitches.
-enable FB emulationen for all games. Increases compatibility. May be a little bit slower but solves misalignment problems for now.
-use GlideN64 upstream again.
> mupen64plus: cleanup and add GlideN64 upstream again

- scriptmodules/inifuncs.sh
The test `[[ "$file" =~ retroarch\.cfg$ ]]` in the end of iniProcess was making the function always return a non-zero (fail) when not editing a retroarch.cfg file, even if everything was fine in iniProcess.
This change makes iniProcess return zero after that test.
> iniProcess returns 0 if not editing retroarch.cfg

- scriptmodules/emulators/retroarch.sh
- scriptmodules/helpers.sh
- scriptmodules/system.sh
* only force gcc version to 4.9 on debian/raspbian 8
* use libpng-dev for debian 9+
* set debian version to 9 for ubuntu 16.10 and above (for libpng naming).
> debian stretch support

- scriptmodules/supplementary/runcommand/joy2key.py
- scriptmodules/system.sh
Here we go with another attempt to implement custom button mappings on joy2key...
- ~~**IMPORTANT:** this change on joy2key does **NOT** change the current behavior of `joy2keyStart()` in helpers.sh and `start_joy2key()` in runcommand.sh (I've submitted this PR to let you review the code).~~
- ~~this `joy2key.py` only gets the custom configs from retroarch-joypads files if it's called **without those hexadecimal codes for buttons**~~
- ~~i.e. in order to make `retropie_setup.sh` and `runcommand.sh` take advantage of the custom button mappings, we need to delete those hexadecimal codes for buttons on joy2key starters (`runcommand.sh` and `helpers.sh`).~~
- the package `python-pyudev` is a dependency. Needed to get `/dev/input/jsX` names. But I'm not sure where to `getDepends` for this …
> joy2key can get button maps from retroarch configs

- scriptmodules/emulators/retroarch.sh
This causes choppy scrolling performance even on a RPi3, so disable it by
default to benefit users who manually switch to the xmb menu driver.
> retroarch: disable xmb menu icon shadows

- scriptmodules/emulators/retroarch.sh
- scriptmodules/supplementary/emulationstation.sh
When configuring "Swap A/B buttons in ES", users will most likely
need to enable the equivalent option (menu_swap_ok_cancel_buttons)
in RetroArch. Do this automatically to minimize user confusion.
> emulationstation: sync A/B swap configuration to retroarch config

- scriptmodules/emulators/mupen64plus.sh
-There was a build error if mupen64plus was build with `sudo __platform=rpi1 ./RetroPie-Setup`. -DARMv5_ONLY will be only used if HOST_CPU is armv5 or armv6.
-Don't mix neon and videocore options. Only rpi platforms need VC=1.
> Mupen64plus: fix target rpi1

- scriptmodules/ports/cdogs-sdl.sh
addresses https://github.com/RetroPie/RetroPie-Setup/issues/1947
not too bad of a game.
> add C-Dogs SDL

- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-fix bomberman 64: disable legacy blending.
-fix resident evil 2: use AUDIO-SDL. AUDIO-OMX crashs emulator at startup.
-fix pokemon stadium 2: use AUDIO-SDL. AUDIO-OMX crashs emulator at startup.
> Mupen64plus improvements

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
New default option "mupen64plus-auto" sets video plugins and resolution
automatically to get best performance and visual quality.
> mupen64plus: add default AUTO option

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-GLideN64: make fps counter grey so it is less noticeable
-add defaut keyboard config if InputAutoCfg.ini is missing
-replace platform rpi1 with armv6
> Mupen64plus more opts

- scriptmodules/supplementary/esthemes.sh
I would like to request the addition of ComicBook_SE Themes for both the 16:9 and 4:3 versions of the theme.  This allows users with Marquee/Wheelart to display them above the video instead of the standard logos.  Due to the current ES restrictions, it is not possible to allow this to happen and still function for users without wheelart/marqueed scraped.
> Request to Add ComicBook_SE Themes

- scriptmodules/supplementary/esthemes.sh
The first commit is just removing rendundant tests.
The second one adds the option to update all installed ES themes, as [requested in the forums](https://retropie.org.uk/forum/topic/11319/updating-all-installed-themes).
> added option to update all installed ES themes

- scriptmodules/libretrocores/lr-bluemsx.sh
* document msx/colecovision bios / rom locations
* added to coleco system
* use a separate retroarch-core-options.cfg so as to force the colecovision system
This needs some testing. I think the retroarch input configuration might need switching/changing to work also with this.
> lr-bluemsx - added colecovision support - fixes #2032

- scriptmodules/supplementary/runcommand/joy2key.py
Fix for PlayStation DS4 controller lagging in runcommand due to a badly placed time.sleep in joy2key and thus long time of processing large number of accelerometer events.
Tested and confirmed working/fixed on my Raspberry Pi3 setup.
Forum post:
https://retropie.org.uk/forum/topic/10315/ds4-in-textmode-menus
> fix for PlayStation DS4 controller lagging

- scriptmodules/emulators/uae4all.sh
- scriptmodules/emulators/uae4arm.sh
Applies to uae4all, uae4arm & amiberry scripts.
> Amiga: remove emulator ROM scripts correctly on uninstall

- scriptmodules/supplementary/bluetooth.sh
Re-enable bluetoooth stack in Bluetooth dialog menu, and restart
sixad daemon upon exit.
This allows standard BT device pair/unpair management with DS3
controller fully working in-menu. The only drawback is that
your PS3 controller will turn off upon exiting the menu due to the
daemon restart.
> Bluetooth: enhance sixad compatibility

- scriptmodules/supplementary/esthemes.sh
These themes, from @rxbrad, are useful for small screens.
Forum topic:
https://retropie.org.uk/forum/topic/6383/gbz-3-5-theme
Repositories:
https://github.com/rxbrad/es-theme-gbz35
https://github.com/rxbrad/es-theme-gbz35-dark
> esthemes: added gbz35 and gbz35-dark themes

- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand/joy2key.py
* Allow dpad control in addition to axis for cursor keys
* Verify existence of keys before mapping
The cursor keys will now be mapped to both the axis and dpad, but if
the dpad is not present, only the axis mappings will be used.
This should also make it possible to add default mappings for X/Y
buttons without having to worry about pad compatibility.
> joy2key: implement key verification & dpad support

- scriptmodules/libretrocores/lr-tyrquake.sh
hipnotic and rogue folders should be parallel to id1, not subfolders.
Fixes #2006
> lr-tyrquake: correct mission pack paths

- scriptmodules/supplementary/runcommand/joy2key.py
* Do verification on copy of default_button_codes for each device
(so missing buttons on one device are not pruned from all others)
* Add exception handling for a/b swap to avoid missing buttons blocking
script execution
> joy2key: fix key verification for multiple devices

- scriptmodules/libretrocores/lr-tyrquake.sh
Will be recognized when dopa is located in roms/ports/quake/dopa/pak0.pak
Note: this contradicts the current information on the wiki (telling you to rename to pak2.pak and copy shareware/registered paks). All episodes seem to work in all quake clients with the files in the following locations:
ports/quake/hipnotic/pak0.pak
ports/quake/dopa/pak0.pak (dopa itself)
ports/quake/rogue/pak0.pak
ports/quake/id1/pak1.pak (registered)
ports/quake/id1/pak0.pak (shareware)
> lr-tyrquake: enable episode 5 (dopa) support

- scriptmodules/ports/cgenius.sh
Version 1.9.9.2 might be beta but it is usable enough and has great features and bug fixes.
> Updated Commander Genius

- scriptmodules/libretrocores/lr-mame2000.sh
imame4all is the old name. This is the only remaining reference to it. As well as removing it, I adjusted the wording to read similarly to https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-mame2003.sh
> Removed references to imame4all, and re-worded

- scriptmodules/emulators/retroarch.sh
common: hide online/core updater menu options
xmb: prune history, music, image & import content menu tabs
> retroarch: prune unnecessary menu options

- scriptmodules/emulators/mupen64plus/mupen64plus.sh
Could not chnage directory for savegames, screenshots,... in cfg because on each startup the script replace them again.
Add a fix for this with the auto configuration.
> Could not change save path for save game to own directory

- scriptmodules/supplementary/pegasus-fe.sh
This patch adds initial/experimental support for the [pegasus-frontend](http://github.com/mmatyas/pegasus-frontend). The script downloads and extracts the [latest automatic build](https://github.com/mmatyas/pegasus-frontend/releases/tag/continuous) for the current platform (there are RPi and X11 builds). At the moment it uses the ES2 config files, so probably no additional configuration steps are necessary.
> Add initial support for Pegasus frontend

- scriptmodules/supplementary/runcommand/runcommand.sh
This allows a token to be reused more than once in an emulator command, e.g. attaching a disk image and a snapshot in VICE:
```
vice-x64-snap-disk = "/opt/retropie/emulators/vice/bin/x86 -8 %ROM%.d64 %ROM%"
```
Where there are a pair of files in the ROM directory:
```
romname.vsf
romname.vsf.d64
```
> Allow multiple instances of the same token in an emulator command.

- scriptmodules/ports/cgenius.sh
As discussed in #2074 and #2099, building Commander Genius using the stock Debian GCC currently fails due to an internal compiler error. As a workaround, this patch installs and uses Clang 3.9 to build the program. The bug doesn't seem to occur with later GCC releases, so these changes can be rolled out after the upgrade to Stretch.
> Workaround for cgenius build error

- scriptmodules/supplementary/bluetooth.sh
- scriptmodules/supplementary/ps3controller.sh
* Remove obsolete information that driver breaks Bluetooth and replace
with warning that Bluetooth pairing works in RetroPie menu, but cannot
be guaranteed elsewhere.
* Add notice after exiting Bluetooth menu (only when sixad is running)
informing users to re-pair controller, to hopefully reduce confusion.
> ps3controller: clarify Bluetooth stack compatibility

- scriptmodules/emulators/mupen64plus.sh
There is no SSSE3 code optimization anymore. Use SSE2 optimized code.
> mupen64plus: cxd4 x86 use SSE2

- scriptmodules/supplementary/consolefont.sh
Allows convenient configuration of certain preset font type/sizes
appropriate for viewing on large screens.
> Add console font scriptmodule

- scriptmodules/supplementary/runcommand/runcommand.sh
When a system's default emulator is not yet selected, the automatic invocation of choose_emulator function can be erratic (most notably with the joy2key process exiting prematurely). Avoid this issue by disabling the cancel button when invoked in this way.
> runcommand: fix default emulator dialog behaviour

- scriptmodules/emulators/mupen64plus.sh
GLideN64 needs libpng16-dev. Mupen64plus-core needs freetype and
ubuntu’s freetype needs libpng12-dev. libpng16-dev removes libpng12.
Fix: Use GLideN64 libpng16 libs and headers.
> mupen64plus: fix ubuntu 16.04

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
Fix ubuntu >= 16.10 audio issue (no sound) and remove old emulator entries.
> Mupen64plus x86 cleanup

- scriptmodules/supplementary/bashwelcometweak.sh
Use awk to print the last column of first line of ip route. Fixes IP address on stretch without breaking jessie.
> bashwelcometweak: fix IP address for stretch

- scriptmodules/supplementary/splashscreen.sh
- scriptmodules/supplementary/splashscreen/asplashscreen.sh
* Switch to systemd service to allow finer control of start sequence
* Add insserv to depends (not installed in Raspbian stretch lite image).
> splashscreen: convert to systemd service

- pkgconfig/bcm_host.pc
- pkgconfig/brcmegl.pc
- pkgconfig/brcmglesv2.pc
- pkgconfig/brcmvg.pc
- pkgconfig/mmal.pc
- pkgconfig/vcsm.pc
- scriptmodules/admin/setup.sh
- scriptmodules/system.sh
* Add "mesa kms" flags when vc4 module is inserted.
* Add "dispmanx" flag if /sys/bus/platform/devices/*.firmwarekms is enumerated (fake kms).
* Fallback to "videocore dispmanx" if neither is detected.
* Put a hard block on script execution if VC4 driver is enabled.
* Set environment variable for PKGCONFIG (coming in next stretch firmware).
* Use fallback copy of pkgconfig if needed; useful for current stretch firmware that lacks pkgconfig & legacy jessie compatibility. Separate commit so that it can be cleanly reverted in future.
> Add platform flags & pkgconfig

- scriptmodules/supplementary/ps3controller.sh
This is not present on the default stretch lite installation, leading
to the service not being enabled correctly.
(Let me know if you want me to convert to a systemd service... however, the service does autostart correctly as long as insserv is installed, unlike asplashscreen).
> ps3controller: add insserv to depends

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/packages.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
- scriptmodules/supplementary/sdl2.sh
@psyke83 this is how I would like to handle it - should help with most cases, and fixes mupen64plus for now (plus we get the new sdl library)
We still may need to handle RetroArch manually, but are there any affected modules apart from lr-ppsspp ? as we control that, we can just do it at the same time as RetroArch update.
> Newbcrmlibs

- scriptmodules/helpers.sh
Under certain scenarios, joy2key.py does not receive the INT signal
which leads to the process staying resident. Avoid this situation by
sending the signal repeatedly until a successful exit code is received.
>  helpers: joy2keyStop: wait for successful SIGINT

- scriptmodules/helpers.sh
Reverts RetroPie/RetroPie-Setup#2148
causes `Exception OSError: (9, 'Bad file descriptor') in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored` to be thrown by joy2key.
> Revert " helpers: joy2keyStop: wait for successful SIGINT"

- scriptmodules/supplementary/bluetooth.sh
It's necessary to read more characters per line to match the "[bluetooth]" string due to commit:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=6fd2662dc96ccf5fc194c53d5c6f90431ba9f8a5
Fixes bluetooth on stretch.
> bluetooth: fix bluez 5.43 compatibility

- platforms.cfg
Including hard disk image support (hdf).
> Add more common filetypes for Sharp X68000

- scriptmodules/ports/dxx-rebirth.sh
The unification/master branch is no longer recommended by upstream,
and the master branch has support for the new vendor libraries (as
well as the experimental Mesa driver).
> dxx-rebirth: use master branch

- scriptmodules/emulators/fs-uae/fs-uae.sh
- scriptmodules/emulators/reicast/reicast.sh
- scriptmodules/helpers.sh
- scriptmodules/libretrocores/lr-nxengine.sh
- scriptmodules/supplementary/runcommand/joy2key.py
- scriptmodules/supplementary/runcommand/runcommand.sh
Although you've re-arranged the start/stop invocations to avoid the process remaining in most cases, I thought you might want to consider switching to the USR1 signal to solve the orphaned process issue fully.
Additionally, I identified a few cases in which scripts will display a dialog without joy2key running, leaving users without a keyboard stuck. I considered adapting the scripts like so:
```
scriptdir=$scriptdir (needed for joy2keyStart to function; actual name should be replaced by sed or through substitution when creating new files)
source "$scriptdir/scriptmodules/helpers.sh"
joy2keyStart
dialog [...]
joy2keyStop
```
...but I think it might be a bit overkill, so I figured that changing these to pause dialogs with a 15 second timeout might work better.
Edit: the reicast warning is …
> Joy2Key-related fixes

- scriptmodules/supplementary/sdl1.sh
Use different source versions for jessie/stretch, and automatically
bump package version with rpiX and os codename appended.
ex:
* 1.2.15-10 will bump to 1.2.15-11~rpi1~jessie
* 1.2.15+dfsg1-4 will bump to 1.2.15+dfsg1-5~rpi1~stretch
> sdl1: allow building against distro-specific sources

- scriptmodules/supplementary/ps3controller.sh
The systemd package will automatically cleanup damage from the old package and enable/start the new system service, so remove it from here.
> ps3controller: update for new systemd package

- platforms.cfg
Like described in https://dolphin-emu.org/docs/faq/#what-dump-formats-are-supported-dolphin. I didn't include `.wbfs` for Gamecube because I believe it's a Wii only format (while not specified in the Wiki).
> Updating Dolphin extensions for GC and Wii

- scriptmodules/libretrocores/lr-mame.sh
- scriptmodules/ports/cgenius.sh
- scriptmodules/system.sh
* use __gcc_version to avoid calling gcc -dumpversion multiple times in the code
> system - remove default gcc functions which were needed for Raspbian Wheezy

- scriptmodules/emulators/dosbox.sh
* Configure DOSbox to use TiMidity/FluidSynth ALSA port for MIDI if a running
service is detected during installation or if the target is a Pi.
* On Pi, explicitly spawn/kill a TiMidity daemon - but only if an existing
TiMidity/FluidSynth instance is not already running.
Using timidity is safe on the Pi, as the bcm2835 audio codec supports hardware
mixing on up to 8 substreams. It may be usable on other targets, but we
need to ensure that either hardware mixing or dmix (ALSA software mixer)
is available to avoid sound blocking.
Alternative resolution to #2051.
> dosbox: implement software MIDI synth support

- scriptmodules/supplementary/retropiemenu.sh
P.S. The small interval between start/stop should no longer matter now that the python is killed before script processing completes, via the USR1 signal. I've tested several times and never saw an orphaned process before exiting retroarch, but even so, the second invocation of joy2keyStop after exiting retroarch would probably catch it.
> retropiemenu: quit joy2key for RetroArch case

- scriptmodules/emulators/retroarch.sh
- scriptmodules/libretrocores/lr-mupen64plus.sh
- scriptmodules/libretrocores/lr-mupen64plus/01_new_lib_names.diff
- scriptmodules/libretrocores/lr-parallel-n64.sh
* include patches for lr-mupen64plus and lr-parallel-n64 until upstream accepts the PRs - https://github.com/libretro/mupen64plus-libretro/pull/39 / https://github.com/libretro/parallel-n64/pull/469
@psyke83 tagging you for review.
> retroarch - update to new version including modules that require new brcm library names - #2091

- platforms.cfg
- scriptmodules/emulators/ags.sh
Add Adventure Game Studio to platforms configuration and fetch
recommended GUS patch from http://liballeg.org/digmid.html.
Fixes MIDI playback on devices with no hardware MIDI support (such as
Raspberry Pi).
--
It's not easy to determine which games use MIDI sound, so to help test this PR, I recommend downloading this: http://www.g4g.it/2009/11/30/fullyramblomatic-special-editions-pack/. I can confirm that "5 Days Special Edition" plays midi sound on the title menu.
If you'd like to mirror the GUS patch file, let me know and I can update the PR once you've uploaded the file to the retropie server. The current "digmid.dat" file is actually bz2 compressed, which is why "downloadAndExtract" is not possible unless we mirror a properly compressed & named archive.
> ags: add to platforms & enable DIGMID support

- scriptmodules/emulators/dosbox.sh
This allows users to override the default dosbox configuration,
but the most likely use is to configure the autoexec, such as:
[autoexec]
MOUNT C /home/pi/RetroPie/roms/pc
C:
CD PROGRAM/
LAUNCH.EXE
EXIT
This is the recommend way to configure content, and should also
work with lr-dosbox.
> dosbox: implement support for launching via .conf files

- scriptmodules/supplementary/splashscreen.sh
If /etc/splashscreen.list is not present during enable, default will
not be set correctly due to typo in function called.
> splashscreen: ensure splash is set to default if needed

- scriptmodules/supplementary/controlblock.sh
- scriptmodules/supplementary/powerblock.sh
With this pull request the services are not enabled with the installation anymore. This addresses the reboot issue as discussed at #2156.
> Do not enable PowerBlock and ControlBlock service with installation

- scriptmodules/emulators/coolcv.sh
- scriptmodules/emulators/drastic.sh
- scriptmodules/emulators/rpix86.sh
- scriptmodules/helpers.sh
- scriptmodules/ports/giana.sh
Hi @joolswills,
This seems like the ideal solution for our legacy/binary only items. I've confirmed that giana, rpix86 and coolcv work perfectly on stretch after patching with this PR.
This PR can be expanded to all other binary packages. Can you let me know what other binary-only software is distributed by the script and thus may potentially need patching?
Should help towards resolving #2091.
> RPi stretch binary-only compatibility patching

- scriptmodules/emulators/dosbox-sdl2.sh
- scriptmodules/emulators/dosbox.sh
Testing a newer revision of the SDL2 patch as discussed previously: https://github.com/RetroPie/RetroPie-Setup/issues/1350
The new revision of vanilla DOSbox seems to work OK. I decided to update it so that we have an equal baseline for comparison with the SDL2 version. I also added some minor cleanups and a fix to ensure that the midi synth is launched for .sh script content.
I've done some testing of the SDL2 build - performance is almost identical, but there is a noticeable reduction in screen tearing, better scaling to fit the entire screen, and mapper colours are OK. The splash screen, windowed mode and the mapper doesn't scale to the full screen properly, and while SDL_VIDEO_RPI_SCALE_MODE=1 does scale the window, the mouse cursor's bounding appears limited to the unscaled …
> Update dosbox & add experimental sdl2-only version

- scriptmodules/system.sh
As Deepin is now based in Debian, is just needed a little entry in the system.sh script to support the last version of this distribution without problems.
https://www.deepin.org/es/
Testing environment:
OS:  Deepin 15.5 Desktop
Processor: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Ram: 16GB
Kernel: 4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux
> Add Deepin to supported OS

- scriptmodules/supplementary/customhidsony.sh
Implement custom hid-sony driver patched to fix the
eternal vibrate bug with third-party Shanwan controllers. Currently
compatible with Raspberry Pi only.
Uses the following patch: https://github.com/raspberrypi/linux/commit/492ca83c3d19fba1622164f07cd7b775596a7db2
This module could also be useful if we can fix the Bluetooth idle timeout
not being respected. That would make the official BlueZ plugin a viable
replacement for the sixad wrapper for official and third-party controllers
alike.
---
Please don't merge - this is untested except to confirm successful build & dkms installation. Feedback from anyone with a Shanwan third-party controller that has the vibration bug would be appreciated. The patched modules probably still requires the use of the ps3controller driver for BT pairing, and …
> customhidsony: add custom hid-sony dkms driver module

- scriptmodules/ports/wolf4sdl.sh
The previous wolf4sdl-spear default to mission 3 when executed with
no arguments. Fix and add ports for the other two missions.
Fixes #1507.
> wolf4sdl: fix spear of destiny mission support

- scriptmodules/emulators/mupen64plus.sh
Needed by GlideN64: https://github.com/gonetz/GLideN64/blob/dfada113d35ebea131a13fa629512dc8852b0ad5/src/TextDrawer.cpp#L207
> Add missing fonts-freefont-ttf dependency

- scriptmodules/emulators/capricerpi.sh
- scriptmodules/emulators/pcsx-rearmed.sh
- scriptmodules/emulators/pisnes.sh
- scriptmodules/emulators/ppsspp.sh
- scriptmodules/emulators/ppsspp/01_egl_name.diff
- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
- scriptmodules/system.sh
This PR adds some additional stretch support -
* Enables running retropie_setup on Stretch
* Enables binaries (Almost all binaries are now built)
* Fixes a few packages for Stretch
lr-armsnes does not currently build on gcc 6.0 , due to some inline asm. I believe it should be a simple fix, but I am considering removing this module. It's no longer developed upstream, and had very few optimisations over pocketsnes really.
I'm currently rebuilding all packages again to make sure there are no issues with the CPU flags changes for the rpi1.
> Stretch changes

- scriptmodules/emulators/retroarch.sh
- scriptmodules/libretrocores/lr-beetle-psx.sh
- scriptmodules/supplementary/configedit.sh
Tagging @movisman - please test this PR and verify that the hw core builds & runs as expected.
As Jools has stated on the forum, it needs to be confirmed as working by someone in the project before being included. I currently don't have an x86 Linux installation available, and Jools is busy, so you'll need to be patient until I can sort out a testing environment.
Are you absolutely certain that Vulkan works? I would imagine that RetroArch itself needs to be built with Vulkan support enabled -  and we don't take any special steps to enable vulkan there.
> lr-beetle-psx: include hw core

- scriptmodules/supplementary/retropiemenu.sh
- scriptmodules/supplementary/wifi.sh
* Use ifconfig invocations instead of ifup/ifdown
* Ensure wlan0 is up before initiating scan
* Fix display of IP address & only show wlan0 interface address
Also fix IP address display in retropiemenu.
> wifi: fixes for stretch

- platforms.cfg
- scriptmodules/libretrocores/lr-mess.sh
Mostly to silence EmulationStation warnings printed in framebuffer during startup.
Note that lr-mess is currently a total... mess. The core doesn't load correctly as it seems to expect the driver name to be specified as the first argument:
```
[libretro INFO] Starting game from command line:/home/pi/RetroPie/roms/gb/Bionic Commando (USA).zip
[libretro INFO] ARGUV[0]=/home/pi/RetroPie/roms/gb/Bionic
[libretro WARN] Driver /home/pi/RetroPie/roms/gb/Bionic not found -1
[libretro WARN] Game not found: (USA)
[libretro INFO] RES:-2
```
After poking around a bit with strace and specifying the driver, the core will only load the bios from ```gameboy/dmg_boot.bin``` relative to the current path, so it won't read the bios files in the roms or bios folders. I don't have a desktop Linux installation …
> Misc platform fixes

- scriptmodules/supplementary/virtualgamepad.sh
It seems that Raspbian stretch splits npm into it's own package of the same name, but installing it would break libssl-dev:
```
The following additional packages will be installed:
gyp javascript-common libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libssl1.0-dev libuv1-dev node-abbrev node-ansi node-ansi-color-table node-archy
node-async node-balanced-match node-block-stream node-brace-expansion node-builtin-modules node-combined-stream node-concat-map node-cookie-jar node-delayed-stream
node-forever-agent node-form-data node-fs.realpath node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-gyp
node-hosted-git-info node-inflight node-inherits node-ini node-is-builtin-module node-isexe node-json-stringify-safe node-lockfile node-lru-cache …
```
> virtualgamepad: use nodesource if npm is not in distribution package

- scriptmodules/ports/openblok.sh
The portable installation flag was slightly incorrect, which produced a warning during the build and set up a different directory structure (the game otherwise worked fine). This patch makes the program truly portable.
> Fix OpenBlok build warning

- scriptmodules/libretrocores/lr-mame2010.sh
I updated the mame2010 readme and switched to markdown to enjoy some formatting. This creates an error as reported by @mediamogul here: https://retropie.org.uk/forum/post/133826
Pending the approval of my next PR ( https://github.com/libretro/mame2010-libretro/pull/94 ) mame2010 will autogenerate a mame.ini file if there isn't one -- therefore I'm suggesting that `mame.ini` from this script be removed as well.
In this PR I have also omitted the original mame 0.139 "whatsnew" file which seems out of place. No offense if you reject this change.
> resolve error + one other update to mame2010 build

- scriptmodules/libretrocores/lr-desmume2015.sh
Fix build for new upstream rebase, and split off old version into
lr-desmume2015 scriptmodule to correspond to its new name.
Fixes #2314.
N.B. The new fork of upstream (now "lr-desmume") will not build correctly until this is merged: https://github.com/libretro/desmume/pull/4. The new version seems to launch OK, but it's still slow on Pi 3.
> Update lr-desmume and split 2015 version

- scriptmodules/emulators/residualvm.sh
This change makes the script write the full game descrption (e.g. "Grim Fandango (Windows/English)") into the .rvm files that ES uses to generate the gamelist. The intent is to give .rvm files unique hashes that can be used by scrapers. Exactly the same as recent PR to scummvm.sh.
> Full game description in .rvm for scraper to hash

- scriptmodules/libretrocores/lr-prboom.sh
- scriptmodules/ports/zdoom.sh
Requires the following wads:
* Hexen: ```hexen.wad```
* Hexen Deathkings: ```hexen.wad``` & ```hexdd.wad```
* Heretic: ```heretic.wad```
Additionally, the scriptmodule will automatically rename supported wad
files to lowercase if necessary.
Tested and confirmed as working after ripping the necessary .wad files from my Steam installation.
Just a note on the added invocation of pushd/popd: the Hexen Deathkings file is actually a pwad that depends on ```hexen.wad``` to be present in order to launch correctly. If zdoom doesn't find hexen.wad in the current directory, the expansion won't be able to launch unless its location is specified via the additional argument ```-file /path/to/hexdd.wad``` -  but that must be invoked with ```-iwad /path/to/hexen.wad```. If you prefer to make a wrapper …
> zdoom: add support for Hexen 1 Series & Heretic

- scriptmodules/libretrocores/lr-prboom.sh
* lr-pboom does not support Hexen/Heretic/Strife/Chex, so isolate these
to zdoom's configuration instance.
* Omit Chex 1/2, as Chex 2 requires special arguments to load chex.wad, and
Chex 3 (freeware) includes remastered versions of the previous two episodes.
--
This should cover zdoom's list of supported commercial ports (keeping in mind that Chex 3 is a remaster, but includes the originals).
> zdoom: extend support to Strife, Chex 3 & isolate supported ports

- scriptmodules/supplementary/raspbiantools.sh
- scriptmodules/system.sh
* remove package if installed when running retropie-setup for existing installs
* install xorg without recommendations from raspbiantools so it wont be installed when installing the desktop
> make sure xserver-xorg-legacy is not installed - fixes #2299

- scriptmodules/supplementary/runcommand/joy2key.py
The location of the name, id/vendor & id/product descriptors are not
consistent with udev's DEVPATH for every kernel driver.
Fix this by properly normalizing the path correctly, then shift to the parent
directory if the "name" file does not exist.
Fixes the hid_sony driver.
> joy2key: normalize device path & check parent directory

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/0001-GLideN64-use-emplace.patch
Crash seems reproducible only on gcc 6.3.0 via Rasbian stretch, but the
workaround should not negatively impact other systems.
See: https://github.com/gonetz/GLideN64/issues/1665
> mupen64plus: workaround GLideN64 shader cache crash

- scriptmodules/supplementary/customhidsony.sh
The script depends on the Raspberry Pi properly tagging firmware releases,
but they have neglected to do so for 1.20180313-1. Work around this by
using the rpi-4.9.y branch instead.
> customhidsony: fix build on new Pi firmware

- scriptmodules/emulators/mupen64plus.sh
https://github.com/gonetz/GLideN64/commit/09a508ae114dad5a5067c5a1c411c24ec55b5d44
> mupen64plus: fix GLideN64 plugin path

- scriptmodules/admin/builder.sh
- scriptmodules/admin/crosscomp.sh
- scriptmodules/admin/image.sh
This code is added primarily to reduce the number of external scripts I have for maintenance, and to incorporate some of the admin functionality into the main RetroPie-Setup code (as was done for image building).
With these changes it is easier to install an arm targetting cross compiler set-up to be used with distcc. This is then used when building packages in an emulated chroot for faster compilation.
Am still doing a bit of final testing on it before merging.
> Cross compiler

- scriptmodules/libretrocores/lr-mame2003-plus.sh
The initial dash is gone from the URL now.
> update github URL for mame2003-plus-libretro

- scriptmodules/emulators/mupen64plus/mupen64plus.sh
-use default "Video-Rice" for Conker and Zelda games. These game have problems if GLideN64 is used (translucent and missing textures).
-remove Gauntlet Legends from blacklist
-use better Audio-SDL resampler (less crackle)
-fix Perfect Dark highres autosetting
> Add some mupen64plus optimizations

- scriptmodules/ports/abuse.sh
This updated version of abuse works properly without X (in contrast to dead upstream)
> add Abuse to experimental

- scriptmodules/libretrocores/lr-mame2003.sh
Based on @grant2258 's research into Run and Gun I created this tiny .nvram memory patch to that gets `rungun` past it's stalling point. It was added to mame2003-libretro here https://github.com/libretro/mame2003-libretro/pull/346 . 
In brief: This is a cruder implementation of what mame2010 and later do.
At some point we could BUILD_BIN2C this into the mame2003 binary like the builtin hiscore.dat, but I digress. Maybe one day.
This PR should make the game start fine for RetroPie users in the meantime. I don't have a RetroPie environment to test on, however.
> use mame2003 rungun memory patch to bypass stalling point

- scriptmodules/supplementary/bluetooth.sh
- scriptmodules/supplementary/customhidsony.sh
- scriptmodules/supplementary/customhidsony/0001-hidsony-nomotionsensors.diff
Due to the new kernel 4.14, we now have different button maps for the DS3's USB connection (via hid-sony) compared to both the 4.9 kernel version's driver as well as the current ps3controller driver. In order to at least maintain consistency with the native driver, I've split the sixaxis PR into two. 
This "groundwork" PR does two things: 
* bring the ```customhidsony``` driver into sync with the default 4.14 kernel driver so it has the same new mappings; the only difference between rpi-4.14.y and rpi-4.15.y version of hid_sony will be the Shanwan vibration fix (as well as my change to disable motion sensors).
* add basic bluetooth pairing support.
Neither of these changes will break ps3controller, but will allow people the option to use the native driver via Bluetooth (as long as they …
> Sixaxis groundwork

- scriptmodules/libretrocores/lr-mgba.sh
As mentioned in #2295, `lr-mgba` is mature enough now to support GB/GBC/SGB as well as GBA.
I've been using it for several weeks now and all works fine. The emulator detects the system type automatically and can use all BIOSes available, even Super Gameboy.
The emulation speed in my standard-configured RPI3 is very satisfactory too.
This is for the `master` upstream repository of `lr-mgba`, used when you install it from source.
I strongly suggest the binary version in RetroPie is updated too to make all work out-of-the-box.
The following BIOS files were used for testing each system type:
a860e8c0b6d573d191e4ec7db1b1e4f6  gba_bios.bin
32fbbd84168d3482956eb3c5051637f5  gb_bios.bin
dbfce9db9deaa2567f6a84fde55f9680  gbc_bios.bin
d574d4f9c12f305074798f54c091a8b4  sgb_bios.bin
I kept the …
> lr-mgba.sh: enable lr-mgba for GB and GBC (SGB also supported)

- scriptmodules/ports/cgenius.sh
Use stable branch instead of a version
> Commander Genius now uses the stable branch instead of a fixed tag

- scriptmodules/emulators/ppsspp.sh
- scriptmodules/emulators/ppsspp/02_tinker_options.diff
- scriptmodules/emulators/ppsspp/tinker.armv7.cmake
- scriptmodules/emulators/reicast.sh
- scriptmodules/libretrocores/lr-mupen64plus.sh
- scriptmodules/libretrocores/lr-parallel-n64.sh
- scriptmodules/system.sh
Hello,
The changes made make it possible to have a support on the emulators concerned. We are working on an image based on Armbian Stretch with the supplied 4.4.120-rockchip kernel. The changes also work on the ISO TinkerOS provided by ASUS.
If you want to do the tests on an armbian image we have a script that automates all the part of the dependencies etc.
https://github.com/Tinkerpie/Armbian-Setup
> Add support for tinker for few emulator

- platforms.cfg
- scriptmodules/libretrocores/lr-fbalpha.sh
* fbalpha now has neogeo cd support - see https://github.com/libretro/fbalpha/issues/4
> fbalpha - enable neocd subsystem / add .cue and .iso extensions

- scriptmodules/libretrocores/lr-81.sh
I noticed this core sitting in the RetroArch repository, and decided to try compiling it on the Pi and seeing how well it works.  Since it ended up working more-or-less perfectly from the look of things, and because the ZX81 isn't available at all in RetroPie yet, I decided to write a script module for it.
Due to some control-related issues (specifically having to set player 2's controller type to "Sinclair Keyboard" in order to get inputs to work), I put the core in the Experimental section.  The RetroArch page also didn't mention whether or not .zip or .7z files work, so I excluded them for the time being.
I should also note that some colorized ROM files are present within the repository's `colorized` folder for use with the core's Chroma feature.  However, the author of the ROMs appear …
> Add lr-81: libretro core for Sinclair ZX81

- scriptmodules/supplementary/esthemes.sh
This theme is designed to be used with your screen rotated to landscape. You will need to add a line of code to the boot/config.txt file. 'display_rotate=3' (or =1 depending on which way you want to rotate). The theme only covers mame/arcade and relevant collections like capcom, data east etc. No consoles, PC or handhelds are covered.
> Updated esthemes.sh with a new vertical only ES theme for mame roms

- platforms.cfg
- scriptmodules/libretrocores/lr-pokemini.sh
Title pretty much says it all.  I decided to take this opportunity to edit platforms.cfg to add Pokemon Mini platform definitions, since that seems to be how es_systems determines what file types to use.  (I might also submit a PR for the ZX81, as that script appears to not place file extensions otherwise, thus requiring the user to edit es_systems manually to add the extensions.)
I could just be misunderstanding how scriptmodules work, so feel free to change as you see fit.
> Add lr-pokemini: experimental libretro core for Pokemon Mini

- scriptmodules/ports/love-0.10.2.sh
Many games for Love are incompatible with the latest version (v11). For example, the bundled game [Mari0](http://stabyourself.net/mari0/) requires v0.10.2, and the amazing game [Not Tetris](http://stabyourself.net/nottetris2/) requires 0.7.2.
With this PR, I am trying to add the option to install versions 0.10.2 and 0.7.2 as additional emulators for the system "love". I looked at advmame-x.xx as examples how this might work.
The goal is to allow users to use the runcommand menu to choose the version of Love on a per-game basis, similar to how it works with Advmame. The choices should be love (latest version, currently v11.1, the default), love-0.10.2, or love-0.7.2.
I am pretty sure I probably forgot something in this PR. I just copy-pasted from love.sh and made the obvious adjustments. …
> love - allow installation of v0.10.2 in addition to latest version

- scriptmodules/supplementary/configedit.sh
Fix the mis-spelling of the **alsathread** audio driver in RetroArch Config. Reported in https://retropie.org.uk/forum/topic/18430/lr-armsnes-and-retropie-4-4/30.
> Fix threaded ALSA audio driver selection

- scriptmodules/emulators/advmame.sh
* get the package source from the github.com repository so it's not taken from the SF download page and uploaded on the RetroPie files server.
* run `autoreconf.sh` before configuring the build (needed to produce the `configure` script).
* update the build function to check for success using `$md_ret_files`
Started by https://retropie.org.uk/forum/topic/18473/update-of-advancemame-did-not-work
> Update for the advmame scriptmodule.

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand.sh
While working on a bare-minimum version of Raspbian Stretch with RetroPie, I discovered dependencies missing in runcommand and mupen64plus that are assumed to be installed: `fbset` and `libraspberrypi-bin`. I also slightly enhanced ensureFBMode() in helpers to account for a potentially non-existing `/etc/fb.modes`, e.g. for the case `fbset` is not installed beforehand. All details are in the commits.
* mupen64plus - add libraspberrypi-bin as dependency
* runcommand - add fbset and libraspberrypi-bin as dependencies
* helpers - ensureFBMode(): no-op if /etc/fb.modes doesn't exist
> dependency fixes to helpers, runcommand and mupen64plus

- platforms.cfg
The `lr-mupen64plus` retroarch core does support zip files, add them as supported files for Nintendo 64.
Tested and working.
> add .zip extension to n64 platform for lr-mupen64plus

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand.sh
Reverts RetroPie/RetroPie-Setup#2455
Reverting due to OSMC dependency issue - no raspberrypi-bin on OSMC.
> Revert "dependency fixes to helpers, runcommand and mupen64plus"

- scriptmodules/supplementary/runcommand/runcommand.sh
Another small fix:
* The `VIDEO_CONF` variable is initialised at the beginning of the script with the appropiate file path. However, the `default_mode()` function does not use it and instead hard-codes the file path.
> runcommand - use existing VIDEO_CONF variable

- scriptmodules/helpers.sh
In the case that /etc/fb.modes doesn't already exists,
ensureFBMode() will create an empty file only containing the
custom RetroPie video mode entry.
The above is problematic for example when `fbset` is not installed
beforehand. The package installation will detect the modified
version of /etc/fb.modes as user-customised and will prompt the user
what to do with the conflict, e.g. use the maintainer's version
(that doesn't include the RetroPie video mode entry) or keep the
modified version (that doesn't include the stock entries).
The safest solution is for ensureFBMode() to simply do nothing if
/etc/fb.modes doesn't exist already. After installing `fbset`, the
file will exist and ensureFBMode() will add the custom video mode
alongside the stock entries as expected.
> helpers - ensureFBMode(): no-op if /etc/fb.modes doesn't exist

- scriptmodules/supplementary/runcommand.sh
The runcommand script uses the `fbset` binary and in some
systems this package might not be installed by default.
> runcommand - add fbset as dependency

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand.sh
As discussed in PR #2461 , there was a problem with `libraspberrypi-bin` changing name in different OSs (OSMC and Xbian). This revised PR handles the issue similarly to how it is already handled for `librasperrypi-dev`. With this, we can now safely add `libraspberrypi-bin` as dependency for mupen64plus and runcommand.
Again, sorry for the previous broken PR, hopefully this one is trouble-free.
> properly add libraspberrypi-bin depedency handling

- scriptmodules/emulators/atari800.sh
- scriptmodules/emulators/atari800/01_rpi_fixes.diff
- scriptmodules/emulators/fuse.sh
- scriptmodules/emulators/fuse/01_disable_cursor.diff
- scriptmodules/emulators/scummvm-sdl1.sh
- scriptmodules/emulators/scummvm-sdl1/01_rpi_sdl1.diff
- scriptmodules/emulators/scummvm.sh
- scriptmodules/emulators/scummvm/01_rpi_enable_scalers.diff
- scriptmodules/emulators/uae4all.sh
- scriptmodules/emulators/uae4all/01_guichan.diff
- scriptmodules/helpers.sh
- scriptmodules/libretrocores/lr-nxengine.sh
- scriptmodules/ports/darkplaces-quake.sh
- scriptmodules/ports/darkplaces-quake/01_rpi_fixes.diff
- scriptmodules/supplementary/xpad.sh
- scriptmodules/supplementary/xpad/01_enable_leds_and_trigmapping.diff
As discussed in #2467, deprecate stdin usage in `applyPatch` / `addPort`.
This is a somewhat big PR, so I will summarise the commits here:
* a367202 and 9534c17 remove stdin functionality from `applyPatch` and `addPort`.
* 67cdb4f to a89c3f5 moves and rebases the in-line patches into files for affected modules.
* 4c3146c updates the only module using stdin with `addPort` to use new approach.
In the case of `applyPatch`, I did the following:
* Tested patching in every affected module and in every supported platform (see below).
* Rebased the patches so they apply cleanly into current source code. Some patches didn't even apply anymore due to being outdated, this is now fixed too.
In the case of `addPort`, I did the following:
* Changed the signature of the function to accept a custom …
> Deprecate stdin usage (fixes #2467)

- scriptmodules/libretrocores/lr-parallel-n64.sh
Hi, I wanted to test the lr-parallel-n64 core on my TinkerBoard (with Armbian 5.59, kern 4.14) but was unable to get it to build.  I was able to build it with these changes.
When building with platform="kms" the makefile exits immediately. 
I'm guessing eventually the lr-parallel-n64 Makefile will understand "kms" ?
The arguments inside the params array also need their quoting fixed, so that the variables in the makefile get set correctly when the array is expanded.
> Fix lr-parallel-n64 build from source on tinker platform

- platforms.cfg
- scriptmodules/libretrocores/lr-x1.sh
Yet another obscure Japanese home computer!  This one requires two BIOS files in `/home/pi/RetroPie/BIOS/xmil`, named IPLROM.X1 [CRC32 7B28D9DE] and IPLROM.X1T [CRC32 2E8B767C].  Tested and works full-speed on a Raspberry Pi 3B without overclocking.
Since the makefile is within the `libretro` folder, rather than at the root of the source files, I added `/libretro/` wherever needed.  Little bit hacky, but it works well enough and doesn't seem to cause any issues [I'm not sure if this is the preferred way to handle this however].
This commit also modifies `platforms.cfg` to add a name and extensions for the X1.
> Add lr-x1 - Sharp X1 libretro core

- scriptmodules/system.sh
We need to set `__os_debian_ver="9"` as KDE Neon is now based on Ubuntu 18.04
LTS and we need the little libpng-dev trick.
Old KDE Neon use Ubuntu 16.04 LTS.
> KDE Neon is now based on Ubuntu 18.04 LTS.

- scriptmodules/libretrocores/lr-fbalpha.sh
Fix for neon platforms not recognized by lr-fbalpha makefile.
See Issue: https://github.com/libretro/fbalpha/issues/249
> Fix lr-fbalpha build on unrecognized neon platforms

- scriptmodules/libretrocores/lr-nestopia.sh
I just found out that the `lr-nestopia` scriptmodule installs the Nestopia database file without changing the ownership back to the running user:
pi@retropie:~$ ls -la ~/RetroPie/BIOS/NstDatabase.xml
-rw-r--r-- 1 root root 1009534 Oct 19 17:53 /home/pi/RetroPie/BIOS/NstDatabase.xml
I adopted the approach of running `chown` from other scriptmodules in this PR, and now the file is installed properly:
pi@retropie:~$ ls -la ~/RetroPie/BIOS/NstDatabase.xml
-rw-r--r-- 1 pi pi 1009534 Oct 19 19:07 /home/pi/RetroPie/BIOS/NstDatabase.xml
> lr-nestopia - change ownership of installed database to $user:$user

- scriptmodules/supplementary/skyscraper.sh
* the configure phase needed the build folder, breaking binary installs.
Fix this by adding the necessary files to the binary install folder and making configure look there.
* added a few more samples for the 'import' and 'dbs' folders. 
* fixed a scraping problem because of a stray space in the sudo scraping command
* default config enables 'wheels' download and scraping and removes the maxFails
~~* added 'unpack' by default. This should alleviate the need to add --unpack from cli when
scraping zipped ROMs from screenscraper.~~
> Fix the install from a binary package and a scraping error

- scriptmodules/system.sh
My images are based on Armbian next.
Linux kernel is 4.14
Mali drivers r8p1 fbdev
If approved i will share image for supported devices with official RetroPie Setup script
> Add Allwinner H3 and H5 devices

- platforms.cfg
Assists with launching CD32 images from ES.
> Add .cue support to Commodore Amiga

- scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh
I've in a different on PR https://github.com/RetroPie/EmulationStation/pull/499 to make EmulationStation work with both digital and analogue directionals, but the `/opt/retropie/supplementary/emulationstation/configscripts/emulationstation.sh` script actually remove analogues from final configuration.
So this PR is about to keep analogues directionals.
> Don't remove analogues on EmulationStation post config

- platforms.cfg
- scriptmodules/libretrocores/lr-beetle-saturn.sh
`lr-beetle-saturn` supports `.chd` images, so adding it to the list of supported files.
> Adding .chd to Saturn supported extensions

- scriptmodules/admin/setup.sh
* use setsid for tee / gzip so they always complete
* https://github.com/RetroPie/RetroPie-Setup/issues/2524
My commit message is a bit crap but here's a proposed fix based on the discussion. Only difference is I put it in a function to avoid duplication.
> setup - stop ctrl+c signal from reaching tee / gzip and exiting retropie-setup - #2524

- scriptmodules/ports/steamlink.sh
The steamlink client will refuse to launch when overscan is enabled
(which is enabled by default on our RetroPie image), but an override
is supported.
(they added this overscan detection to their scripts after I submitted the initial PR)
> steamlink: add overscan override

- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
helpers / addEmulator - adjust the logic for automatic RA cmd generation
* match against any cmd parameter that is an .so in $md_inst
runcommand - detect retroarch by emulator id not command string
@hhromic - hopefully this will help https://github.com/RetroPie/RetroPie-Setup/pull/2551
> addEmulator / Runcommand RetroArch commandline detection

- scriptmodules/libretrocores/lr-scummvm.sh
- scriptmodules/libretrocores/lr-scummvm/01_fix_quit.diff
Finally I think I'm happy for this scriptmodule to be merged in RetroPie.
It has been tested for a while by various users in the forum and everyone seems happy with it.
**Useful Links**
* Forum Thread: <https://retropie.org.uk/forum/topic/19693/lr-scummvm-request-for-comments-and-testing>
* Libretro Docs for Scummvm: <https://docs.libretro.com/library/scummvm/>
* Default Joypad Mapping (I will add this info to the RetroPie wiki after merging): <https://docs.libretro.com/library/scummvm/#joypad>
* An evolving RetroArch-specific compatibility list (a lot of games are working fine) is being maintained in: <https://docs.google.com/spreadsheets/d/1a87BnQJc7_fTD5zF55JXcm79d5_l_d1ghDxtiubTnDE>
**Module Features**
* The scriptmodule enables MT-32 emulation during compilation.
* The scriptmodule …
> add ScummVM port for libretro (lr-scummvm) to experimental

- scriptmodules/libretrocores/lr-mame2003.sh
This PR pertains to a feature of mame2003-plus which had bugs and had thought I would give up on: backdrop artwork. However, the bugs with artwork unexpectedly were solved by an unrelated fix, and now backdrops can be displayed.
@joolswills would you please review this PR? I do not have a RetroPie setup to test it on.
My intentions are to:
1. Correctly locate the artwork folder within the mame2003-plus SYSTEM folder instead of the SAVE folder
2. Using the `hiscore.dat` and `cheat.dat` as a model, copy and chown the backdrop artwork files to the right place
In case you are wondering: at the moment there is just one artwork file in the repository folder, but there may be as many as a dozen or two files eventually. Not all that many games have backdrop art to begin with.
> correct mame2003-plus artwork path & copy artwork sources

- scriptmodules/libretrocores/lr-mame2003.sh
The correct function to use is `mkUserDir()` instead of `mkRomDir()`.
Also did some minor code cosmetic clean-up.
As reported in the forum posts:
* https://retropie.org.uk/forum/post/171213
* https://retropie.org.uk/forum/post/171515
> lr-mame2003-plus: fix installation of artwork in $biosrom instead of $romdir

- scriptmodules/ports/steamlink.sh
* Add missing xorg dependency
* Replace matchbox with matchbox-window-manager to eliminate unnecessary
desktop/gtk dependencies.
> steamlink: update xorg dependency & reduce matchbox install

- scriptmodules/supplementary/esthemes.sh
I noticed that the esthemes menu displays *(not installed)* for every non-installed theme:
Which makes the menu look a bit cluttered/convoluted. A better approach is what is currently done in the **RetroPie packages menus**, where only the installed packages are marked as *(installed)*:
This PR helps reduce visual clutter in the **esthemes menu** using the same approach as the package managing menus. Example:
> esthemes - do not append `(not installed)` if a theme is not installed

- scriptmodules/ports/splitwolf.sh
- scriptmodules/ports/wolf4sdl.sh
Based on the same setup script as Wolf4SDL, this PR adds [_Splitwolf_ from Team Raycast](https://bitbucket.org/linuxwolf6/splitwolf/wiki/Home), 2-4 player splitscreen Wolfenstein 3D with new game modes and full gamepad support!
That's right, you can frag Nazis with up to 4 of your friends on the big screen!
* Modern FPS gamepad controls (strafe/move with left stick, rotate with right stick)
* Smooth gamepad controls let you strafe, turn, and creep up slowly behind your enemies
* Classic co-op and 9 new game modes (Instagib, Nazi Zombies, Carry the Flag, Melee Rampage, Defuse the Bomb, and more)
* Graphic, zoomable minimap with all player locations
* Deployable MG42 machine gun
* Armored vehicle equipped with a mounted gatling gun spawns in areas with lots of enemies
* Gib animations when …
> Add Splitwolf: Splitscreen Wolfenstein 3D

- scriptmodules/supplementary/skyscraper.sh
This should fix version checking using `compareVersions` fix (discussed [here](https://github.com/RetroPie/RetroPie-Setup/pull/2584#commitcomment-32040176)) - thanks @hhromic for spotting the 2nd missing check.
It also fixes a spelling mistake after gathering using selecting systems and properly set the scrape source when the user has previously scraped with a source that was removed in v3 (i.e. 'localdb' or 'igdb').
On the issue of `compareVersions` - this could possibly be optimized to use `sort -V` instead of calling `dpkg --compare-versions` - see https://stackoverflow.com/questions/16989598/. Might be worth looking into it to replace it in the helper.
> Skyscraper - properly check version numbers this time (amend previous module change)

- scriptmodules/helpers.sh
* Minor Bug: the `git branch -D $commit` command should run in `$dir`, otherwise it fails if `$dir` is different than `$PWD`, for example:
function sources_module() {
gitPullOrClone "/other" https://github.com/user/repo branch commit
}
* Enhancement: print the status (branch/commit) of HEAD after any operation. It is useful to know exactly at which branch/commit the pull/clone operation left the requested repository, specially on calls without branch/commit arguments where this information is not directly visible.
Tested checking-out the sources of a number of scriptmodules and all is working fine on my side.
> helpers / gitPullOrClone - ensure git branch command runs in $dir and print HEAD status

- scriptmodules/libretrocores/lr-dolphin.sh
Upstream changed the build commands, so adding `-DLIBRETRO_STATIC=1` is the preferred way to build with GCC. 
References:
* https://github.com/libretro/libretro-super/pull/946/files (changes to the build used by the Libretro buildbot)
* https://github.com/libretro/dolphin/commit/ce4833fc5b15773bfa64b9b1702f3d6d3f557cae - upstream commit.
Started by https://retropie.org.uk/forum/topic/21080/
> Add Libretro Dolphin build changes

- scriptmodules/supplementary/configedit.sh
Certain hid drivers that enumerate multiple nodes (such as hid-sony)
may not advertise the device name in the parent node of udev DEVPATH.
Fix this by using a more reliable method to query the device name
through the /sys/class userspace IO.
Fixes erroneous "not connected" message on DualShock 3/4 controllers
when using the hid-sony driver.
> configedit: improve joystick detection

- scriptmodules/supplementary/skyscraper.sh
Make `find` follow symlinks, just in case one of the system folders is a symlink; reported in 
https://retropie.org.uk/forum/topic/21057. 
Simplify the systems listing - don't search for files, just the top non-empty folders.
> Skyscraper: fixed listing of systems when using symlinks.

- scriptmodules/helpers.sh
- scriptmodules/supplementary/customhidsony.sh
- scriptmodules/supplementary/mkarcadejoystick.sh
- scriptmodules/supplementary/xpad.sh
Introduce new DKMS helper function to consolidate DKMS management in
the relevant scriptmodules (customhidsony, mkarcadejoystick and xpad).
The helper will properly remove old versions of DKMS modules to prevent
"dkms.conf not found" errors occurring when removing a related scriptmodule
but an older DKMS module version was present.
Also fix the update hooks and ensure proper module reload when needed.
> helpers: add dkmsManager helper function

- scriptmodules/libretrocores/lr-hatari.sh
- scriptmodules/libretrocores/lr-hatari/01_libcapsimage.diff
* Use better linker flags instead of patching Makefile to find libcapsimage
Forum: https://retropie.org.uk/forum/topic/21127/lr-harari-error-installing-from-source/
> lr-hatari - fix build after recent changes upstream

- scriptmodules/helpers.sh
Reference: https://retropie.org.uk/forum/topic/21139/error-and-gui-terminates-back-to-es-when-launching-retropie-setup-direct-on-machine-libudev-but-ssh-is-ok
> joy2keyStart: add delay to work around launch issue

- scriptmodules/ports/kodi.sh
In Kodi 18, some components where split from the Kodi binary, the kodi-vfs-* binary addons. For people to use, for example, the integrated nfs, sftp, etc, filesystems and open compressed archives, they need to have them installed.
"kodi-standalone" can now be used instead of "kodi", it doesn't crash on exit anymore.
> Add kodi virtual filesystems | Use kodi-standalone instead

- scriptmodules/libretrocores/lr-superflappybirds.sh
Super Flappy Birds is an original-ish game created by me, specifically with retropie in mind. The game and screenshots are [here](https://github.com/IgniparousTempest/libretro-superflappybirds).
It is written as a libretro core, hence why the script is under the `libretrocores` folder, but it installs to the ports folder on retropie. This pattern seems odd, but it is what Dinothawr does, see [here](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-dinothawr.sh).
> added SuperFlappyBirds scriptmodule to libretrocores

- scriptmodules/ports/cgenius.sh
The `stable` upstream branch has made some changes that require a newer (3.12) CMake - but the Stretch version is still at 3.7. 
Upstream has fixed the issue, but it's not in the `stable` branch yet, but we can use the latest tagged branch and then switch to `stable` again when the fix is added there.
Reported in https://retropie.org.uk/forum/topic/21149/.
Fixed (upstream) in https://gitlab.com/Dringgstein/Commander-Genius/issues/355.
> cgenius - fixed building with Raspbian Strech "cmake"

- scriptmodules/helpers.sh
"dkms status" uses different formatting for modules that are "added"
compared to installed modules.
> helpers: fix dkmsManager remove for "added" modules

- scriptmodules/helpers.sh
Without an explicit `return` command, functions in bash default to returning the exit value of the last command executed.
The current implementation of `printMsgs()` uses `[[..]]` tests for deciding on the output type (dialog, heading, console), however if the last test (for heading) is false, then this will be the final exit value to be returned from `printMsgs()`. In other words, for all cases except "heading", it always will return `1` (false).
This can be solved by using if-elif-else blocks or, more elegantly, a switch-case block as in this patch. A correct return value is obtained by returning after dialog/echo on error.
---
Example/Tests:
```
$ source scriptmodules/helpers.sh
$ printMsgs "console" "Hello World" && echo OK
Hello World
$ source scriptmodules/helpers.sh
$ printMsgs …
```
> helpers - fix printMsgs() return value

- scriptmodules/supplementary/scraper.sh
The default mame settings are set **after** the other options. The result is that the "prefer screenshots" option is overridden. Moved the default settings before the custom options and reworked the params to prevent duplicates.
> fix prefer screenshots when using mame downloader

- scriptmodules/supplementary/pegasus-fe.sh
[Similarly to ES](https://github.com/RetroPie/RetroPie-Setup/blob/34426d09db82e3d59941db0b7a47d67a681a2cd9/scriptmodules/supplementary/emulationstation.sh#L217), the [X11 permission workaround](https://github.com/RetroPie/RetroPie-Setup/issues/1805#issuecomment-269387535) is also necessary for Pegasus to properly launch X11 applications. Based on the ES package code, this patch creates a similar launcher script on install to set up the TTY before launch.
> pegasus-fe: Fixed launching X11 applications

- scriptmodules/supplementary/skyscraper.sh
Small improvements and additions, based on the 3.x version and the feedback from the forum.
* removed the _Gather for all platforms_ entry from the menu, which should be now simpler. The gather action should now be similar to the gamelist generation. 
* added a warning before starting the actual online scraping, so it doesn't surprise the user(s). Mentioned the `Ctrl+C` shortcut to stop the scraping.
* added the _Vacuum_ action to the cache operations and modified the _Purge_ operations to use Skyscraper's options now.
* replaced all _system_ verbiage with _platform_, to be more consistent with Skyscraper's docs.
This version requires the 3.x version (released back on 23 Jan 2019). I'll update the wiki after the PR gets accepted.
> skyscraper: small improvements to the UI

- scriptmodules/ports/jumpnbump.sh
- scriptmodules/ports/jumpnbump/jumpnbump.sh
I found this little game recently and decided to make a scriptmodule for RetroPie.
It's a very simple but fun multiplayer game, ideal for kids -- and not so kids too :)
About the Game:
https://en.wikipedia.org/wiki/Jump_%27n_Bump
Also found it was previously requested in the RetroPie Forum:
https://retropie.org.uk/forum/topic/12370/jump-n-bump-as-a-port
Scriptmodule Features:
* Installs extra levels from https://wiki.debian.org/Games/Jumpnbump
* Creates a launcher for selecting levels and starting net play
* Configurable options such as "nogore" (no blood for kids)
* Installs tools for creating own levels (gobpack, jnbpack, jnbunpack)
Considerations:
* When waiting for network players or connecting to a server, the game can't be killed (CTRL+C). This is not a runcommand nor RetroPie …
> Add "Jump 'n Bump" port to experimental

- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand/joy2key.py
- scriptmodules/supplementary/runcommand/runcommand.sh
The sys.exit() function actually calls an exception (SystemExit), but our
script handles naked exceptions which can result in the script not terminating
properly. Fix by ensuring that all exceptions specify the relevant exception type only.
This seems to resolve the issue of the leftover process on my Pi and Ubuntu 18.10, but perhaps wait before merging until it's confirmed by others.
> joy2key: fix sys.exit() by avoiding naked exceptions

- scriptmodules/emulators/reicast/reicast.sh
Changed grep pipe so that it parses the last match for the controller mapping file. In the case where xbox userspace controllers were found, there was a userspace #2 which was matching for the first and second controller. This led to only the second controller being recognized.
> fixing edge case where multiplayer is broken for dreamcast

- scriptmodules/supplementary/runcommand/joy2key.py
Various IndexError or KeyError exception could occur if 'a', 'b', 'x' or 'y'
mappings were not available due to arrays accessing unexpected elements.
> joy2key: protect against IndexError and KeyError exceptions

- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
* After upstream commit b26afb9 the build broke because of the configure script incorrectly trying to always build `gpu_unai.so`
* Instead use the libretro makefile directly and set `platform` as done in other cores in RetroPie
* For non-RPI2/3 devices, use `arm` and `neon` flags to set platform
* For none of the above, use `unix` as fallback platform
* The built core is now correctly named: `pcsx_rearmed_libretro.so`
I tested the PR on an RPI3B+ using `__platform` set to `rpi1`, `rpi2` and `rpi3` to ensure it builds for all these variants. For other platforms it should use the correct parameters, but can't test myself. I also tested playing some games, all seems okay on my side.
> lr-pcsx-rearmed - fix build by using the libretro makefile directly

- scriptmodules/supplementary/skyscraper.sh
Purge and Vacuum actions should not be runa as 'root' - but as the RetroPie user.
> skyscraper: fix user errors on vacuum/purge actions

- scriptmodules/helpers.sh
- scriptmodules/supplementary/runcommand/joy2key.py
- scriptmodules/supplementary/runcommand/runcommand.sh
joy2key:
* Protect signal_handler from concurrent calls via multiple kill requests
* Daemonize to background as soon as signal handlers are registered;
guarantees that joy2keyStart/start_joy2key returns only when the script
is in a functional state (and thus the stop calls can't run too early).
* Ensure tty_fd is also closed on exit.
helper/runcommand:
* Don't run script in background
* Remove parent pid check (no longer needed)
* Remove joy2key PID upon kill to avoid unbalanced stop calls (although
the script now protects from this via signal_handler)
> joy2key: daemonize to prevent early-init related errors

- scriptmodules/emulators/mupen64plus/mupen64plus.sh
> Blacklist indiana jones n64 in a way that picks a config that runs

- scriptmodules/libretrocores/lr-reicast.sh
* redirect stdin from </dev/null to avoid segfault on RPI
* keep disabled for kms / mali targets for now
* ref: https://retropie.org.uk/forum/topic/20042/reicast-vs-lr-reicast-perfomance
> lr-reicast - enable for RPI

- scriptmodules/admin/builder.sh
- scriptmodules/helpers.sh
- scriptmodules/supplementary/retropiemenu.sh
- scriptmodules/supplementary/wifi.sh
I created a cleaner version of the snippet proposed before.
* the function obtains an externally routable source IP address for the machine
* an IPv4 route is tried first and, if not found, then an IPv6 route is tried
* the function also handles queries for specific devices (used in `wifi.sh`)
* replace all instances of `ip route (...)` with new `getIPAddress` function
I also found one more usage of `ip route (...)` in the `bashwelcometweak.sh` scriptmodule, however it is used from within the installed `.bashrc` snippet, therefore it does not have access to the helpers library.
(( btw, that `.bashrc` snippet does not seem to use any scriptmodule variable, perhaps it is better to move it outside the scriptmodule into `$md_data` for a cleaner code? ))
I tested the function in different …
> helpers - add getIPAddress() function

- scriptmodules/emulators/fuse.sh
- scriptmodules/emulators/fuse/02_sdl_fix.diff
* include patch to avoid segfault when using dispmanx sdl driver
* ref: https://sourceforge.net/p/fuse-emulator/bugs/449/
> fuse - update to v1.5.7

- scriptmodules/emulators/jzintv.sh
* repack source archive so it unpacks to jzintv not jzintv-20181225-src and remove dlls from bin subfolder
* remove now unneeded subMakefile changes
* override CC/CXX in Makefile to use just gcc rather than hardcoded version
* clear WARNXX to avoid incompatibility with -Wc++1z-compat and older g++
> jzintv - update to 20181225 version

- scriptmodules/libretrocores/lr-mame2003.sh
The `mame2003` and `mame2003-plus` core options are now better aligned with the other cores by prefixing the options with `<core_name>_` instead of `<core_name>-`.
* mame2003-libtetro - https://github.com/libretro/mame2003-libretro/blob/2961cbd34383f6a0d4d8a3362bb79911607158f6/src/mame2003/mame2003.c#L182-L220
* mame2003-plus-libretro : https://github.com/libretro/mame2003-plus-libretro/blob/927c5578dd5daa161b880876119444e0a414bdb4/src/mame2003/mame2003.c#L185-L223
This issue came up recently in the forums (https://retropie.org.uk/forum/topic/21828) - so I updated the Wiki, the PR also updates the core options on installation.
> lr-mame2003(-plus): update core options suffix

- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
* Pass `platform` parameter also for the clean target, otherwise there are files left uncleaned because of the configuration set by the platform parameter itself.
* Removed unnecessary default setting for platform as well (as noted before)
This is a very small and inoffensive fix. Most of the time the core is built from a freshly cloned directory, therefore the built core is exactly the same as before. The cleaning operation now works properly for cases such as debugging and building multiple times from the same directory.
> lr-pcsx-rearmed - use correct make invocation for cleaning

- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
The libretro Makefile does not select appropriate cpu/gpu flags.
Therefore, set ARCH, HAVE_NEON, BUILTIN_GPU and USE_DYNAREC manually.
Was:
> The libretro Makefile does not override an empty platform parameter, therefore we must at least start with "unix" for non-RPI2/3 devices that are not ARM nor NEON-enabled, i.e. "generic-x11" machines.
Turns out the previous check was actually necessary for passing "unix" as default when platform is left empty. The libretro makefile does not override an empty platform parameter as we thought (mpff).
> 
> Sorry I didn't catch this in the previous PR. The "generic-x11" platform is the only affected one and not many people use it there in favour of beetle psx.
> lr-pcsx-rearmed - set make parameters manually according to platform

- scriptmodules/libretrocores/lr-snes9x.sh
* using `platform=armv` is now sufficient for the build to use `-DARM`
- fixed since a while here: https://github.com/libretro/snes9x/pull/62
* adding `neon` to `platform` has no effect on the built binary of this core
- there is no NEON-specific code in the core
* also pass `platform` parameter for the clean target as well (I know you plan to remove cleaning during build, but for now at least let's keep it consistent)
Currently, `-DARM` is repeated twice because of the workaround in the scriptmodule:
g++ -I../libretro -I.. -I../apu/ -I../apu/bapu   -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -DARM -DGIT_VERSION=\"" dad0ae5"\" -flto -DARM -O3 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter -fPIC …
> lr-snes9x - update and simplify scriptmodule

- scriptmodules/emulators/vice.sh
Upstream recently dropped the **x64** target from their default build and intends to deprecate it, replacing it with **x64sc**. References:
* https://sourceforge.net/p/vice-emu/code/36182/
* https://sourceforge.net/p/vice-emu/mailman/message/36654013/
To allow building from source, this change explicitely adds `--enable-x64` (as per the last ref). The scriptmodule should probably be modified to use **x64sc** as `md_ret_require` and make **x64sc** as default emulator.
> vice: enable 'x64' to be built with recent Vice 3, fixes building from source.

- scriptmodules/helpers.sh
- scriptmodules/supplementary/sdl2.sh
* resolves issues with recent Ubuntu packages having dependencies on a specific sdl2 version - eg libavdevice58
> helpers - don't use our custom sdl2 by default on x11 target

- scriptmodules/libretrocores/lr-mame2016.sh
- scriptmodules/libretrocores/lr-mame2016/01_disable_bgfx.diff
* disable bgfx (fails on neon with recent GCC due to outdated SIMD instrinsics)
* see https://github.com/libretro/mame2016-libretro/pull/25
> lr-mame2016 - fix building on neon platforms by disabling bgfx

- scriptmodules/ports/sdlpop.sh
The game attempts to write some files to its working directory but they aren't
writable and so they're being redirected to the /opt/retropie/conf directory
> sdlpop - fix quicksave and in-game settings saving

- scriptmodules/libretrocores/lr-mupen64plus-next.sh
This scriptmodule has been under testing in the forum since Feb/2019 without major problems. Features:
* This core uses up-to-date GLideN64 plugin
* Scriptmodule sets a different namespace (`mupen64plus-next-`) for the core options to avoid clashing with the older `lr-mupen64plus` core options, i.e. they both can co-exist.
Forum Topic: https://retropie.org.uk/forum/topic/21093/
Upstream: https://github.com/libretro/mupen64plus-libretro-nx
> add mupen64plus "next" for libretro to experimental

- platforms.cfg
`lr-pcsx-rearmed` has support for CHD (https://github.com/libretro/pcsx_rearmed/pull/280) now.
This change adds the `.chd` extension to the list of `psx` supported extensions.
> psx: add support for CHD files

- scriptmodules/libretrocores/lr-quasi88.sh
I've tested this core and can confirm that it runs games properly.  As this core is still a WIP according to [the README.md in the repository](https://raw.githubusercontent.com/libretro/quasi88-libretro/master/README.md) and missing features like tape support and games that use more than two disks, I have marked it as experimental.
Note for testing: the filenames for the BIOS files are case sensitive at the moment, so `N88.ROM` will not be detected, but `n88.rom` will.
> Add lr-quasi88 - NEC PC-8801 emulator for libretro

- scriptmodules/emulators/mame4all.sh
- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/pifba.sh
- scriptmodules/system.sh
Changes:
1. Build armv7 binaries from now on.  This is harmless enough and may iron out a few quirks in Reicast.  It definitely resolves the mystery dynarec bug in Mupen64plus triggered by the addition of 64 Disk Drive support .  I have a [PR out there to optionally disable 64 Disk Drive support](https://github.com/mupen64plus/mupen64plus-core/pull/649) in builds that are affected, but it hasn't had any attention.  That is beyond our control, but this is not.
2. There are only 2 modules in "main" that are totally toxic to the Vero4k. Excluding these means users can safely perform a the bulk "basic install" without breaking their systems #2738 .
Many thanks,
> Exclude modules harmful to Vero4k and build for armv7

- scriptmodules/supplementary/pegasus-fe.sh
Qt applications on the Pi, like Pegasus, tend to have less detailed color gradients due to some framebuffer format related reasons. A kind user pointed out these banding issues can be fixed by defining an env var before launching Pegasus (mmatyas/pegasus-frontend#467).
> pegasus-fe: Fix gradient banding

- scriptmodules/admin/setup.sh
- scriptmodules/emulators/retroarch.sh
- scriptmodules/supplementary/emulationstation.sh
* Use the GL driver for EmulationStation; can be switched to GLESv2 after support is implemented
* Disable dispmanx on retroarch for mesa targets; should be possible to be enabled after upstream changes, but disable for now to avoid build error.
* Remove hard block on f/kms detection (don't even print error for RPI4)
* Requires SDL2 built with OpenGL support.
Should allow basic bringup for with fkms driver (default for rpi4).
> Fkms initial support

- scriptmodules/libretrocores/lr-mupen64plus-next.sh
- scriptmodules/libretrocores/lr-mupen64plus.sh
m4xw kindly asked me to make sure we include the LICENSE files in the installed mupen cores
EDIT: also use the correct license (GPL3 -> GPL2)
> lr-mupen64plus{-next} - install LICENSE files from upstream

- platforms.cfg
- scriptmodules/libretrocores/lr-flycast.sh
Add `.zip` as valid Dreamcast system extension, for Naomi/Atomiswave ROM support.
Naomi/Atomiswave ROM can be run with `lr-flycast`.
> Add .zip ROM extension support for Dreamcast

- scriptmodules/supplementary/customhidsony.sh
- scriptmodules/supplementary/customhidsony/0001-hidsony-gasiafix.diff
Stretch and buster are now on 4.19 kernel, so keep in sync.
> customhidsony: update for 4.19 kernel

- scriptmodules/libretrocores/lr-mupen64plus.sh
- scriptmodules/libretrocores/lr-mupen64plus/0001-eliminate-conflicting-typedefs.patch
Tested on RPI against fkms and legacy driver.
Legacy driver seems same as stretch, and the fkms version seems to run at similar speed - but there seems to be some tearing, as though vsync is not working correctly.
The mesa workaround may not be suitable for upstream submission due to it having potential to break on older distributions, so it's patched only for newer versions that have the different typedef definition.
> lr-mupen64plus: buster & fkms support

- scriptmodules/supplementary/bashwelcometweak.sh
In Buster, IPv6 seems to be enabled by default, therefore the `bashwelcometweak` displays the IPv6 localhost instead of preferring IPv4 as done in the more recent function implemented in `helpers.sh` in 1e849710 .
For now, just copy the newer function from `helpers.sh` in the `bashwelcometweak`. However, in the future, code duplication can be avoided by deploying a public library with RetroPie utilities.
> bashwelcometweak - add getIPAddress() function

- scriptmodules/admin/setup.sh
- scriptmodules/supplementary/raspbiantools.sh
proposed solution to get a newer kernel onto Stretch with the Sony BT fix.
if a new kernel/firmware is released for Stretch soon this won't be needed.
> image - install newer kernel from buster repos onto stretch to fix sony bt issues

- scriptmodules/system.sh
Current version of ZorinOS 15 is based on Ubuntu 18.04 It should be compatible with previous 16.04 based version as well.
Zorin OS is a similar flavor to Pop!_OS in that it is geared somewhat toward gamers, comes with nVidia drivers pre-installed and makes other aspects of linux gaming easier
> Added support for Zorin OS (script flag check)

- scriptmodules/admin/setup.sh
- scriptmodules/system.sh
Update dialog to state that the minimum Ubuntu is 16.04 (upon which Linux Mint 18 [is based](https://en.wikipedia.org/wiki/Linux_Mint_version_history)), and set the [Debian version](https://askubuntu.com/a/445496) to 9 for Ubuntu 16 & 17 / Mint 18 and 10 for Ubuntu 18 & 19 / Mint 19.
This fixes the issue I encountered where the installer would attempt to install ES 2.7.6 instead of stable on Mint 18.3 and Ubuntu 16.04, and fail due to missing Boost libraries.
> Fix version number requirements

- scriptmodules/emulators/dosbox-sdl2.sh
- scriptmodules/emulators/dosbox.sh
- scriptmodules/emulators/retroarch.sh
- scriptmodules/helpers.sh
* DOSBox:  update to r4252 & add fkms support
* DOSBox-sdl2: unblock & confirm fkms support.
* retroarch: add missing GLESv2 mesa headers.
* helpers: don't install custom SDL1 build for fkms targets
> DOSbox FKMS support & FKMS-related fixes

- scriptmodules/libretrocores/lr-mupen64plus-next.sh
- scriptmodules/libretrocores/lr-mupen64plus-next/0001-force-egl.patch
EGL detection needs to be forced for RPI3 via FKMS, otherwise the
core will segfault.
Seems to work well, apart from graphical tearing.
> lr-mupen64plus-next: buster & fkms support

- scriptmodules/emulators/retroarch.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
runcommand: fix server argument appending when parsing retroarch emulator entries
retroarch: build with X11 support on fkms targets to extend desktop coexistence and potentially work around vsync issues with certain cores using kmsdrm driver.
> runcommand & retroarch X11-related fixes

- scriptmodules/emulators/ppsspp.sh
* Implement fkms support (treated as a generic GLES2 target)
* Update build dependencies to enable additional emulator features
Observations on rpi3 via fkms:
* performance seems roughly on par with the legacy driver
* the core and standalone version have tearing; this may be an issue unique to rpi3's fkms overlay and not rpi4, but I can't be sure until someone tests. Same issue observed with `lr-pcsx-rearmed` and `lr-mupen64plus`.
* load & save of save states now appears to be stable in `lr-ppsspp`; building against the most recent tag, `v1.8.0`, causes the instability to return.
~~* sound is currently not working in `lr-ppsspp`, but it's a known issue and unrelated to this PR: https://github.com/libretro/ppsspp/issues/36~~
> ppsspp: buster & fkms support

- scriptmodules/supplementary/samba.sh
* force DEBIAN_FRONTEND=noninteractive for getDepends, as samba-common
will otherwise force user interaction despite the "-y" argument
being passed to apt-get.
* The service name is now "smbd"; try to restart if "samba" fails to
keep compatibility with older releases.
* Ensure service restart is performed when RetroPie shares are removed.
> samba: fixes for buster release

- scriptmodules/emulators/vice.sh
`checkinstall` is not available on Buster and it's not used by the scriptmodule, so it can be removed.
> vice: don't depend on 'checkinstall'

- scriptmodules/ports/dxx-rebirth.sh
* Update dependencies
* Enable OpenGL + SDL2 build for non-gles targets
* Enable fkms/mesa target, also using SDL2+GL (due to upstream
source requiring changes to support GLESv2 builds)
> dxx-rebirth: update for fkms and buster

- scriptmodules/emulators/openmsx.sh
Newer OpenMSX versions use SDL2 and SDL2-TTF, pull the correct dependencies. The memory used during build increased for a couple of files so bump the required amount of memory (tested on Raspbian Stretch, Pi 3B+).
The new versions also have SDLGL support, so it might be a good candidate for removing the `!kms` flag for Raspbian Buster. However, I couldn't get it to compile under Buster due to memory constraints (seems it requires more than 1Gb and it locked on my 3B+ test system during compilation so I couldn't get a working version).  I can re-try on Buster to test under `(f)kms`, but it might take a bit.
> openmsx - fix building with new versions requiring SDL2

- scriptmodules/admin/image.sh
The recommendation for Buster (Pi4 related probably) is for a larger boot partition:
* https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/#comment-1510398
Upstream `pi-gen` has been updated also with the new size:
* https://github.com/RPi-Distro/pi-gen/commit/0308e92705bc9a22b7574ab5acaa7623e9050b8f
> image: boot partition should be 256Mb for Buster

- scriptmodules/supplementary/mkarcadejoystick.sh
- scriptmodules/supplementary/mkarcadejoystick/01_kernel_timers_api.diff
Similar to https://github.com/RetroPie/RetroPie-Setup/pull/2725, the driver fails buiding on 4.15+ Linux kernels.
I've submitted the patch to the - closest - upstream I could find, in the [Recalbox](https://gitlab.com/recalbox/mk_arcade_joystick_rpi/merge_requests/71) repository for the driver, but there's no response so far.
Reported in https://retropie.org.uk/forum/topic/22859, tested by the reporting user.
> mkarcadejoystick: update the scriptmodule for kernels 4.15+ 

- scriptmodules/ports/ioquake3.sh
* Built against upstream ioquake3 source
* Suitable for Mesa (RPI3/4) and X11 targets
* Mesa targets use GL1 rendering - this works reasonably well, but
has occasional rendering errors for some models (on RPI3).
* KMS (incl. Mesa) targets are configure to run at the display resolution.
> Introduce ioquake3 scriptmodule

- scriptmodules/libretrocores/lr-caprice32.sh
the default combokey is SELECT
this key collides with RETROARCH and the combination START+SELECT to activate the virtual keyboard will terminate the emulator.
Therefore setup to Y and now START+Y activates virtual keyboard
The retroarch shortcuts like START+SELECT, SELECT+B .... are not affected
> lr-caprice32: Set combokey default to Y-Button

- scriptmodules/system.sh
Add detection for the Vero4k+. This is a minor hardware revision of the Vero4k which upgrades Ethernet to Gigabit and improves onboard flash performance. In other regards it is the same and should be treated as a minor revision of the same platform for the purposes of RetroPie and emulators.
This patch prevents it being reported as an unknown platform when trying to use retropie_setup.sh.
> Add detection for Vero4k+

- scriptmodules/emulators/vice.sh
Using the RPI `(f)kms` video driver, the emulator window is not fullscreen, but setting the`VICIIFullscreen` resource will make it start in fullscreen.
> vice: add fullscreen parameter for the (f)kms

- scriptmodules/emulators/reicast.sh
- scriptmodules/helpers.sh
**1st commit:**
Reicast have restructured their branches.
Presently we pull the default branch which was `master`.  It is now `alpha` (and for a short time was `develop`) and breaks the build with new paths and renaming.
Recommendation [here](https://github.com/reicast/reicast-emulator/issues/1669) is to adopt the `beta` branch until further notice.
---
**2nd commit**
Builds fail on Vero4K/OSMC/Debian at the installation of the python `evdev` dependancy:
> Collecting evdev
>   Downloading https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
> Building wheels for collected packages: evdev
>   Running setup.py bdist_wheel for evdev ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, …
> Fix 2x build errors, 1x gitPullOrClone bug 

- scriptmodules/emulators/xroar.sh
The latest version will add an unwanted dependency on X11 if compiled without `--disable-kbd-translation` and fails to run on a Pi system. Reported in:
* https://retropie.org.uk/forum/topic/22623/gpi-case-xroar-emulator-crashes-solved/11
* (possibly also affects) https://retropie.org.uk/forum/topic/23084/
Other changes:
* SDL2 support is added and picked up if present by `configure`, so add the explicit dependency for `libsdl2-dev`.
* correct the typo in the start command line (`-ccr` vs `--ccr`).
I've also tested on a `(f)kms` enabled system and it looks fine, but we can remove the `!kms` flag later. In the 1st topic, the poster said the SDL2 version was slower, a `-sdl1` version can also be added if desired.
> xroar: disable any X11 dependency for non-X11 platforms

- scriptmodules/emulators/mupen64plus.sh
Better performance. You can benchmark by changing the launch string in `/opt/retropie/emulators/mupen64plus/bin/mupen64plus.sh` to:
` SDL_VIDEO_RPI_SCALE_MODE=1 "$rootdir/emulators/mupen64plus/bin/mupen64plus" --noosd --nospeedlimit --windowed $RES --rsp ${RSP_PLUGIN}.so --gfx ${VIDEO_PLUGIN}.so --audio dummy --configdir "$configdir/n64" --datadir "$configdir/n64" "$ROM"`
but note that it won't be able to go faster than vsync (ie, you won't see an improvement) unless you have https://github.com/gonetz/GLideN64/pull/2070
True:
mario64 title screen: 95-105 VI/S
False:
mario64 title screen: 72-85 VI/S
See https://github.com/gonetz/GLideN64/pull/2014 for details on the change.
> ThreadedVideo = True for GLiden64

- scriptmodules/emulators/mupen64plus.sh
iniSet permits this if you put it all in the first parameter. this, in conjunction with https://github.com/ricrpi/mupen64plus-video-gles2n64/pull/28 (now accepted) will allow gles2n64 to run at low resolution scaled to screen, as was the intention (rather than full resolution of display, as it currently is)
> gles2n64.conf does not not like spaces around the '='

- platforms.cfg
- scriptmodules/ports/solarus.sh
General changes:
* Use the official repositories that are now in GitLab
* Use latest HEAD for OpenGL ES support and other required features
* Build with RPATH-replacement for proper dynamic library linking
* Moved Solarus from `ports` to `emulators` to be used as a system
* Added official theme assets to Carbon and Simple ES themes
* Configuration is symlinked to `$md_conf_root/solarus`
* Added a shell script launcher to assist with runtime options
Added scriptmodule GUI:
* Option to configure joypad axis deadzone
* Option to configure joypad buttons combo for quitting
Solarus quests (games) changes:
* Quests (games) no longer need to be "built"
* Do not ship games/quests anymore as the contain copyrighted material
* Users just have to download and place `.solarus` files in …
> solarus - update and modernise scriptmodule

- scriptmodules/libretrocores/lr-mupen64plus-next.sh
New git repository branching model entered in effect upstream.
Ref: https://github.com/libretro/mupen64plus-libretro-nx/issues/76
Commit in `libretro-super`: https://github.com/libretro/libretro-super/commit/476d2e4e662eea4337013af0a43c4a14a540b963
> lr-mupen64plus-next - update for new repo branching model upstream

- scriptmodules/supplementary/esthemes.sh
Added with author's permission - https://retropie.org.uk/forum/topic/22621.
The theme is designed for small screens (like the one present in the RetroFlag's GPICase)
> esthemes: add MiniJawn theme

- .github/FUNDING.yml
* Adds a "sponsors" button in Github
You might need to check if funding links are enabled on the repository settings.
> Add FUNDING Github metadata

- scriptmodules/ports/splitwolf.sh
The upstream repository doesn't have the `master` branch available, the default one is `scrubbed` (see https://bitbucket.org/linuxwolf6/splitwolf/). Fixes building from source (https://github.com/RetroPie/RetroPie-Setup/issues/2826) on Raspbian Stretch.
> splitwolf - fix building by pulling the correct Git repo branch

- scriptmodules/libretrocores/lr-nestopia.sh
Seems like the upstream repository was re-created as a standalone repository (instead of a fork) and some re-organization has taken place. The files no longer in the repository have been removed from `md_ret_files` to allow installation from source of the core.
> lr-nestopia - fix build after upstream repository changes

- scriptmodules/ports/solarus.sh
Minor improvements, does not change behaviour but adds safety checks.
* From acba46e0: "disable on aarch64 (only armhf libluajit-5.1-dev currently available in odroid-c2 repo)"
* Previously forgot to use `md_ret_require` to validate that the build phase generates the binary correctly.
> solarus - minor improvements to scriptmodule

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/0002-GLideN64-force-egl.patch
- scriptmodules/emulators/mupen64plus/0003-core-vsync-670.patch
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
Note: fkms targets uses the GLideN64 video plugins only, as the older
plugins are much less accurate and not as well-maintained. Additionally,
these targets will build the omx plugin, but will not be used by default
due to the better compatibility offered by the SDL audio plugin.
* apply armv8 optimization based on platform flag (rpi3/4)
* remove kms blocking flag and add initial fkms build support
* consolidate launcher script execution arguments
* skip "emplace" patch for fkms targets (no crash observed)
> mupen64plus: debian buster & initial fkms support

- scriptmodules/admin/image.sh
The Pi4 Buster recommendation is actually 256MiB but the script was creating
a much smaller boot partition (240MiB)  because of two bugs:
- parted mkpart units defaults to MB not MiB for input (256MiB is 268MB)
- parted's parameters are `start` `end` not `start` `size`. We need to specify
260 as an end because the start is 4
I changed the default unit to MiB because while explicitly specifying 260MiB
is possible, specifying units on mkpart disables parted's helpful range of
sloppiness.
> image: really set boot partition to 256MiB

- scriptmodules/emulators/dosbox-sdl2.sh
- scriptmodules/ports/darkplaces-quake.sh
- scriptmodules/ports/dxx-rebirth.sh
- scriptmodules/ports/ioquake3.sh
- scriptmodules/ports/lzdoom.sh
- scriptmodules/ports/lzdoom/0001-kmsdrm-fix-atexit-segfault.patch
- scriptmodules/ports/tyrquake.sh
- scriptmodules/ports/tyrquake/0001-force-vsync.patch
- scriptmodules/ports/yquake2.sh
The RPI legacy driver seems to default to vsync on, but the Mesa driver of RPI3, RPI4 (and Intel i965) via KMS does not. Enabling vsync per-application greatly improves video smoothness and eliminates tearing.
Additional changes:
* lzdoom: resolve segfault on exit via KMS and avoid FluidSynth (due to excessive memory/CPU usage).
> Enforce vsync for KMS targets (1)

- scriptmodules/libretrocores/lr-flycast.sh
The generic "rpi" platform string requires a "mesa" override to indicate it's a generic GLES build.
Fixes building against fkms overlay for RPI3.
> lr-flycast: improve fkms detection for older revisions

- scriptmodules/emulators/drastic.sh
Permission for new release has been granted; see: https://drastic-ds.com/viewtopic.php?f=5&t=5610
Please note that while RPI4 (and RPI3/fkms) has been confirmed as working by me,
the developers have not explicitly advertised this release as supporting
RPI4; it works only because it is built as a generic arm binary that is
not dependent on the proprietary Broadcom GLES libraries.
Please keep the above in mind if reporting any bugs upstream.
Closes https://github.com/RetroPie/RetroPie-Setup/issues/2669
> drastic: update to 2.5.0.4 with RPI4 compatibility

- scriptmodules/ports/cgenius.sh
As per cgenius recommendation at https://github.com/gerstrong/Commander-Genius/issues/309#issuecomment-358072833
Update the cgenius `cmake` command to include `-DNOTYPESAVE=on` by default.
> cgenius.sh: Update to allow joystick game saving

- scriptmodules/ports/kodi.sh
As of version 2:18.4-4~buster, pipplware's Kodi package ships with
kodi-rbpi_v8 built to target Mesa/KMS for RPI4, but also works on
RPI3 in fkms mode.
The v7 binary is still present, so the packages will work for older
board revisions with the legacy graphics drivers.
Thanks to Rascas for providing the packages & updating the launcher
script to support RPI3 in fkms mode, and popcornmix (built from his
leia_pi4 Kodi branch).
> kodi: unblock installation for fkms (buster)

- scriptmodules/supplementary/powerblock.sh
Addresses issue #2860.
This PR includes changes for the powerblock module to reflect recent changes in the PowerBLock driver: The installation and deinstallation fo the driver is now only based on the exception of two bash scripts (install.sh and uninstallation, respectively). Nothing needs to be compiled anymore.
I did not have the chance to test these changes for now on the current RetroPie installation. It should work, though.
> Changed module according to recent changes in the PowerBlock driver (#2860)

- scriptmodules/supplementary/pegasus-fe.sh
Pegasus is now functional on the Pi 4, and the build should work there too. There's also a second commit that adds SDL2 as a dependency, which is used for gamepad handling on Pi 0-3 (not on Pi 4 yet, but will be there too eventually).
> pegasus-fe: Raspberry Pi 4 support

- scriptmodules/emulators/scummvm.sh
- scriptmodules/emulators/scummvm/01_rpi_enable_scalers.diff
User in the forum tested new version with different games and all seems to be working fine.
Ref: https://retropie.org.uk/forum/topic/23778/scummvm-2-1-0
@joolswills once this is merged I would suggest to rebuild the binary with the updated version as well, considering how long it takes to build from source. Thanks!
> scummvm - bump version to latest stable (2.1)

- scriptmodules/emulators/mupen64plus.sh
Small performance boost:
mario64 title screen (with --nospeedlimit)
**bufferswapmode=0**
78-98 VI/sec (mainly around low 80s) 
**bufferswapmode=1**
85-97 (mainly around low-high 80s)
**bufferswapmode=2**
86-96 (mainly around mid-high 80s) 
This is the value that mupen64plus-fz (android port of mupen64plus that targets similar hardware) uses: https://github.com/fzurita/mupen64plus-ae/blob/master/app/src/main/java/paulscode/android/mupen64plusae/persistent/GLideN64Prefs.java#L194
> BufferSwapMode=2 (On buffer update) is most performant.

- scriptmodules/system.sh
These files (which can be installed via rpi-update) will cause build conflicts
when targeting Mesa for Pi 4B or FKMS.
> get_rpi_video: clean up legacy pkgconfig

- scriptmodules/emulators/pcsx2.sh
Actually the Debian/Ubuntu PCSX2 packages are really outdated. I'm changing the script to build the emulator using the fresh code from github.
I'm using the same configuration folders used to build the Ubuntu package.
If the user never installed PCSX2, the first run will display the configuration dialog. If it's installed using the system package, it'll run using existing configurations.
> Generate pcsx2 from source

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
See https://github.com/gonetz/GLideN64/issues/1688#issuecomment-545045823
If this eventually gets fixed (I doubt there is much appetite to fix GLES2/videocore bugs, though), the FPS hack may become relevant again, but there are apparently even more issues with Zelda*, hence it is in the GLideN64 blacklist.
I suggest we retire this FPS Counter hack (which affects all games ran in GLideN64) for now, as it does nothing.
> N64: GLideN64: FPS Counter hack no-longer works, and redundant since zelda* is in the GLideN64 blacklist

- scriptmodules/supplementary/bashwelcometweak.sh
I often log in as root to my retropie box (via ssh with a pubkey). Since the account doesn't have colours in its PS1, the last one used stays on the prompt, which is white and not very readable on my light terminal background. This is a quick fix for that problem.
> Fix colour sticking at white if you're logged in as root

- scriptmodules/emulators/residualvm.sh
- scriptmodules/emulators/xroar.sh
* Xroar already uses SDL2 and works fine under `fkms`
* ResidualVM also uss SDL2, it just needs to be linked to the Mesa GLESv2 library under the `fkms` platform.
> fkms: enable residualvm and xroar

- scriptmodules/admin/image.sh
The RPI VC4/VC6 drivers use the kernel CMA heap allocation for GPU memory
(which defaults to 256MB on 1GB+ targets) instead of the gpu_mem allocation.
Although the gpu_mem allocation is still used, it's needed only for camera and
hardware decoders, but the default allocation (~64-76MB) is sufficient.
Without this change, we are losing ~192MB of user-addressible kernel memory
for no reason.
> image: don't set custom gpu_mem allocation for mesa targets

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
The recommended value is 3/4 VRAM, so let's calculate it 👍 I don't see any performance change, but it was fun to do anyway!
Also done a little cleanup with the FBEmulation setting. I think unless we're using that setting in a blacklist, there's no need to force it to enabled at launch. Users should have the ability to play with these settings after install if they so wish.
> N64: GLideN64: set Texture Cache to 128MB for Pi 2+, 64MB for Pi 1/0 (RPI)

- scriptmodules/emulators/reicast.sh
- scriptmodules/emulators/reicast/0001-enable-rpi4-sdl2-target.patch
- scriptmodules/emulators/reicast/0002-enable-vsync.patch
- scriptmodules/emulators/reicast/0003-fix-sdl2-sighandler-conflict.patch
- scriptmodules/emulators/reicast/reicast.sh
reicast: update for rpi4 & generic kms
* Add support for RPI4 and generic KMS targets
* Allow configuration of rpi3 platform in favour of rpi2 platform
* Move build configuration into separate function to avoid duplication between
build and install functions.
* avoid duplication of addEmulator definitions due to audio backend options
* Set alsa as default audio backend for mesa (omx doesn't work, and oss backend via
aoss causes emulator stuttering).
Patch details (may be removed after upstream is fixed):
* Add SDL/gles2 sub-platform for rpi4 to allow kmsdrm compatibility
* Ensure vsync is enforced for SDL, otherwise KMSDRM will run at unlocked framerate.
* Fix signal handler conflict by disabling SDL2's exit signal handler, and ensuring that
reicast gracefully cleans up by stopping …
> reicast: update for rpi4 & generic kms

- scriptmodules/emulators/scummvm.sh
- scriptmodules/emulators/scummvm/01_rpi_enable_scalers.diff
* Use official tags as requested by upstream developers
* Do not enable experimental engines as requested by upstream developers
* Re-organised long lines
* Rebased patches
Tested on Raspberry Pi 3B+ with latest stable RetroPie.
Tested building with `__platform=rpi1` as well.
EDIT: I started the PR as draft for allowing testing from the originating forum member. Once confirmed working as expected I'll undraft the PR.
> scummvm - pull using stable tag and disable experimental engines

- scriptmodules/emulators/mupen64plus.sh
As per https://github.com/RetroPie/RetroPie-Setup/commit/96e1d73217678cc0f38bae57c312ce9396d444e8#diff-fe35047c4f73377c42592c2271157752
Small miss from the rebase. You might want to do it as a rebase rather than as a new commit, just highlighting it here :)
> FPS hack is no longer needed

- scriptmodules/emulators/dolphin.sh
Since [May, 2018](https://dolphin-emu.org/blog/2018/05/02/legend-dolphin-lens-between-worlds/#epilogue-tldr) Dolphin switched to a QT UI only.
So, I changed the `depends` to include GTK dependency only if the build is using the old 5 branch.
I tested this on Ubuntu 18.04 with GCC7 and it worked properly.
> Update dolphin depends

- scriptmodules/emulators/ppsspp.sh
CMakeLists.txt uses CMAKE_SYSTEM_PROCESSOR and adjusts flags based on this
however if building on rpi2/3 or in a chroot with __platform=rpi1 this will
still return armv7l as it uses "uname". This causes armv7/neon code to be included
which causes building to fail. We can override this by setting -DFORCED_CPU=armv6
which fixes building for the rpi1
> ppsspp - fix building for rpi1 target on rpi2/3 or chroot

- scriptmodules/emulators/pcsx2.sh
After #2872, installing `pcsx2` on 64 bit is no longer possible on Ubuntu, due to `libsdl2-dev:i386` installation conflicts (see https://bugs.launchpad.net/ubuntu/+source/mir/+bug/1808060). 
So will use the PPA maintained by the upstream team (from https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily) and add back the SDL2 downgrade option.
Tested on 18.04, should work on newer versions since the PPA builds up-to-date packages for 19.04 and 19.10 also. Should fix https://retropie.org.uk/forum/topic/23992.
> pcsx2: use upstream PPA for the latest version

- scriptmodules/emulators/pcsx2.sh
Previous PR (#2894) didn't modify the emulator path; fix the path so the correct configuration is produced.
> pcsx2: fix emulator path with PPA install

- scriptmodules/emulators/pcsx2.sh
Amends #2894 once more to re-enable installation on Debian. 
Current stable (Buster) includes `pcsx2` 1.5, while Debian Stretch has still 1.4.
> pcsx2: enable installation on Debian

- scriptmodules/supplementary/skyscraper.sh
Skyscraper can prioritise between different scraping sources when generating the frontend-end metadata and this is set through the `priorities.xml` file present in the `cache` folder.
Add the upstream sample for the `priorities.xml` during installation, it will be automatically used by Skyscraper instead of using a timestamp based prioritisation (i.e. last scraped resources wins). Users can then edit the file to change the order/priority when using multiple scraping sources.
See: https://retropie.org.uk/forum/topic/11826/versatile-c-game-scraper-skyscraper/1261.
> skyscraper: add priorities.xml sample when installing

- scriptmodules/emulators/retroarch.sh
`libgles2-mesa-dev` is unneeded on this platform and pulls in an awful lot of extra packages.  Some of these appear to break the GPU drivers.
Many Thanks.
> Mesa unneeded for Vero4K GLES and appears to be harmful.

- scriptmodules/libretrocores/lr-parallel-n64.sh
* remove a typedef conflict - may need to upstream a proper fix for this
* change logic from "tinker" to "kms" for make parameters to make it more general
* rollback code for "neon" rather than "arm" platforms
I've not tested this at all apart from building on rpi2 and rpi4. Need to check the typedef change on tinkerboard. Probably should be upstreamed but upstream master is broken on arm which also needs fixing.
> Lr-parallel-64 - fix building on rpi4/kms

- scriptmodules/libretrocores/lr-dosbox.sh
This one was missing the "GPL2" label.
> Fix the licence string of lr-dosbox

- scriptmodules/admin/builder.sh
- scriptmodules/system.sh
* use $__builder_dists instead of $__dists for distribution
* switch platform var name from $sys to $platform
* allow target platform configuration via __builder_platform env var
* simplify distcc configuration to use DISTCC_HOSTS rather than editing config
* allow manual setting of DISTCC_HOSTS for chroot building via __builder_distcc_hosts
* install distcc as a dependency is DISTCC_HOSTS is set
* allow setting of MAKEFLAGS for chroot building via __builder_makeflags
* add /usr/lib/distcc to PATH/MAKEFLAGS if set
> builder - variable / parameter changes

- scriptmodules/admin/stats.sh
- scriptmodules/admin/stats/licences/app.js
- scriptmodules/admin/stats/pkgflags/app.js
Continuing from #2921, this merges the licence and pkgflag CSVs into one, which are deployed under `stats/`.
> Use a common data file on the stat pages

- scriptmodules/supplementary/raspbiantools.sh
* will now unhold the kernel packages on buster to allow upgrade - eg in the case someone upgraded from stretch to buster
* split up the package download and install stages and make safer in the case it's interrupted
* run function before package upgrades again
* fixed bug where the kernel wouldn't be held if already installed when run before - will be held even if already installed (just the install stage skipped)
> raspbiantools - rework stretch kernel downgrade / holding logic

- scriptmodules/libretrocores/lr-atari800.sh
* use $config_root/atari800/lr-atari800.cfg to avoid conflict with standalone atari800 emulator
> lr-atari800 - rename config file used by core

- scriptmodules/emulators/zesarux.sh
Adds support for using SDL2 on KMS targets. Other changes
* explicitely `--enable-ssl` for build configuration, otherwise it seems SSL support is not [enabled by default](https://github.com/chernandezba/zesarux/blob/89b077721f30157e825cd2d76a00bd81a97f8493/src/Changelog#L434). 
~~* for PI0/1, run with the `--spectrum-reduced-core` parameter for performance. This disables the following: _Debug t-states, Char detection, +3 Disk, Save to tape, Divide, Divmmc, RZX, Raster interrupts, Audio DAC, Video out to file_~~
> zesarux: use SDL2 for KMS targets

- scriptmodules/supplementary/skyscraper.sh
Simplify the licence abbreviation, make it similar to what's already used by other scriptmodules.
> skyscraper: fix licence abbrev

- scriptmodules/supplementary/pegasus-fe.sh
The license abbreviation of this module should be `GPL3` for consistency.
@mmatyas is this okay for you?
Btw this discrepancy was found using your recent license viewer tool :)
> pegasus-fe: fix license abbrev

- scriptmodules/ports/ioquake3.sh
Fix the wrong licence link added in https://github.com/RetroPie/RetroPie-Setup/commit/16c9075eed90054aeec608d2e5af919563bd4935.
> ioquake3: fix license link

- scriptmodules/supplementary/emulationstation.sh
On the PI4 system, the `omxplayer` and the additional audio devices don't get enabled automatically since it's not using the legacy GLES library. Use the parameter added in https://github.com/RetroPie/EmulationStation/pull/573 to enable them.
Added an explicit dependency on `omxplayer`, it wasn't needed before since it got installed with the `splashscreen` scriptmodule.
EDIT: forgot to mention, this needs https://github.com/RetroPie/EmulationStation/pull/573 to be cherry-picked to the ES stable branch.
> emulationstation: enable the PI bits on supported platforms

- scriptmodules/supplementary/sdl2.sh
without --disable-video-opengl SDL2 when building with mali driver SDL2 will try and
use opengl driver first and fail due to driver ordering in SDL_video.c
@psyke83 - rpi doesn't need this for kms target - I assume other kms targets will be ok or ?
> sdl2 - mali targets require opengl driver disabled

- scriptmodules/emulators/ppsspp.sh
upstream are now doing a check for rpi model based on sysfs file which breaks when building in a chroot or on other non rpi hardware (but targetting the rpi)
@psyke83 we don't use this file for rpi4, but maybe it's worth checking if we need to adjust anything for our rpi4 target.
Personally I think upstream should just have cmake flags and not include checks like this. Or at least skip them if flags are already set.
Hopefully this doesn't break anything but I have to merge as I need to complete my buster binaries.
> ppsspp - fix building on rpi2/3 in chroot

- scriptmodules/emulators/ags.sh
- scriptmodules/emulators/retroarch.sh
- scriptmodules/ports/lincity-ng.sh
- scriptmodules/ports/micropolis.sh
- scriptmodules/ports/minecraft.sh
- scriptmodules/ports/steamlink.sh
- scriptmodules/ports/uqm.sh
- scriptmodules/supplementary/mesa-drm.sh
- scriptmodules/supplementary/raspbiantools.sh
- scriptmodules/supplementary/runcommand.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
- scriptmodules/supplementary/sdl2.sh
This is a possible implementation of modesetting for KMS and X11 targets. Tested as working on `rpi3` (fkms), `rpi4` and `x86` (though for the latter, my laptop's i965 driver shows only the native panel resolution in KMS mode, so it's not very useful in my particular case).
The SDL2 patch can be considered temporary, as @cmitu is working on a more fleshed-out version. I do think that it may be a good idea to provide a means to select by the mode index rather than (or in addition to) SDL2 internally matching a string like `XRESxYRES@REFRESH`, because the Pi has multiple modes with identical main timings, but different subtimings.
KMS modesetting currently works only with retroarch and SDL2 applications (but that accounts for virtually everything that runs in KMS mode). I don't think it's …
> KMS & X11 modesetting support

- scriptmodules/supplementary/runcommand.sh
* use rp_installModule so we will install from binary rather than source if a binary is available
@psyke83 @cmitu 
Binaries are built and should be ok but I've not tested.
> runcommand - use binary install for mesa-drm if available

- scriptmodules/ports/srb2.sh
New version 2.2 was released last December, with a lot of updates and bugfixes.
The assets have also changed and the module doesn't install anymore because of that and because the (build) binary name changed.
The changes include:
* updated binary name to fix the install
* updated dependencies (`libgme` and `libopenmpt`). Even though the project's page lists `libupnp` also, I don't see any reference to it, though it bundles a copy of the `miniupnpc` library so it might use that.
* updated assets names and location as they're checked during the configuration from `cmake`.
NOTE: I tested with the assets from http://ppa.launchpad.net/stjr/srb2/ubuntu/pool/main/s/srb2-data/srb2-data_2.2.0-20191207191146.tar.xz (the SRB2 Ubuntu PPA). These would need to be updated on the RetroPie's server also …
> srb2: update to version 2.2

- scriptmodules/supplementary/emulationstation.sh
EmulationStation version `2.7.6`, installed on older Debian platforms, doesn't have the `resources` folder. Selectively add it just for newer releases of EmulationStation and Debian (Stretch or newer).
(reported in the forums in https://retropie.org.uk/forum/topic/24483/v/17)
> emulationstation: fix installation on Raspbian Jessie

- scriptmodules/supplementary/mesa-drm.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
Not sure if you'll be bothered with the wildcard to pull in the libkms library & symlinks (currently: `libkms.so  libkms.so.1  libkms.so.1.0.0`). I can change it to explicitly name the files if you want.
An earlier version of my modesetting PR was using the `modeprint` tool from mesa-drm, but it wasn't possible to install `libkms.so` in the same directory as `modeprint`, as the binary would not resolve the library in the same folder. This isn't a problem with `modetest`, so we can cut down on the extraneous files now.
If this is merged, please trigger a rebuild of the mesa-drm binaries so that runcommand doesn't break for users (due to the path change compared to the current binary package).
> mesa-drm: switch to RetroPie repo & exclude extraneous files

- scriptmodules/emulators/mupen64plus.sh
After all the fun changing it in https://github.com/RetroPie/RetroPie-Setup/pull/2878, I've found out it was removed back in 2017 https://github.com/gonetz/GLideN64/commit/4e36fa07a2fc41ad0ba2ffc6fa0c8aba4c4ce72c#diff-ef42321f7e09f10e240c1d3cfd003e03 😒🥉 
Looks like GLideN64 now allocates from VRAM more smartly.
> CacheSize is no longer a parameter in GLideN64

- scriptmodules/emulators/retroarch.sh
- scriptmodules/emulators/retroarch/01_hotkey_hack.diff
- scriptmodules/emulators/retroarch/02_disable_search.diff
- scriptmodules/emulators/retroarch/03_shader_path_config_enable.diff
Only change is the rebased patches, it should fix the crashes reported in the `lr-atari800` core.
> retroarch: update to v1.8.4

- platforms.cfg
Verified that .cue file extensions work correctly.  Already listed as supported in the wiki.
> Add .cue extension to 3DO

- scriptmodules/emulators/frotz.sh
Since `frotz` has only a text interface (`ncurses` based), enable it for all platforms.
I don't have an Odroid to check if it's available in the repositories, but if they're using also upstream repositories, then it should be installable.
> frotz: remove module flags

- scriptmodules/supplementary/runcommand/runcommand.sh
Certain KMS systems may enumerate multiple CRTCs, some of which have
empty/invalid modes defined. If the first grepped entry happens to be such a
mode, modesetting will break. Fix by using a more accurate grep expression
to find an active CRTC with a valid mode that is marked with the "preferred"
flag.
Issue can be reproduced on Pi 3B with the vc4-kms-v3d overlay.
> runcommand: fix rare default kms mode detection problem

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
you can pass nativeResFactor=2 via a command line argument, so I have added that (and the ability to pass additional parameters to mupen64plus).
~~I think there's an argument that we shouldn't be using windowed mode with gliden64, as it demands you specify a resolution, but n64 resolutions aren't always factors of 320x240, so it's possible to get unwanted scaling/scaling artifacts. however, the alternative is to run fullscreen (letting gliden64 upscale from the true resolution) which removes the performance gain we get from our SDL upscaler. might be something to consider with the pi4...~~
ignore - gliden64 overrides the resolution when using `nativeResFactor`>0, so it doesn't matter what we send.
> N64: GLideN64: highres mode needs to be paired with a nativeResFactor=2 to work

- scriptmodules/supplementary/runcommand/runcommand.sh
It's possible for the booted mode to not be the "preferred" mode, so
simply grep for a working mode via the "driver" flag label instead.
> runcommand: fix kms default mode (again)

- scriptmodules/supplementary/omxiv.sh
- scriptmodules/supplementary/splashscreen.sh
- scriptmodules/supplementary/splashscreen/asplashscreen.sh
This commit changes the `splashscreen` from using `fbi` to [omxiv](https://github.com/HaarigerHarald/omxiv), an OpenMax image viewer for Raspberry PI that bypasses the KMS/DRM layer (similar to `omxplayer`). I added a separte module for it, using a modified version which adds a few `fbi`-compatible features (randomisation or images, exiting after a slideshow, reading the image list from a text file).
It's backwards compatible with non-KMS setups (I tested on a RPI3 using the _master_ RetroPie branch).
Notes:
- on `kms` enabled systems, there is a video mode initialisation done after boot, when the DRM module gets loaded, so I added an extra dependency for the `systemd` service on module loading. Otherwise, the splashscreen gets cut off after the DRM initialisation. This doesn't happen for …
> splashscreen: added KMS/RPI4 support (2)

- scriptmodules/emulators/mupen64plus.sh
- scriptmodules/emulators/mupen64plus/mupen64plus.sh
Because we only had one resolution for Mesa, we weren't able to traverse the resolutions loop properly to add the high resolution modes, so I did it another way.
~Also took the opportunity to retire every video plugin bar GLideN64 for pi4, since I doubt they offer any advantage now we have a GLES3 device with decent drivers. Kept them around for mesa on pi3 as its GLES2 pathway probably has some limitations.~
**Note**: only tested on pi4 (mesa). will test on pi3 for mesa and non-mesa once my new SD card arrives! non-mesa should be functionally identical to prev version, though.
> N64: Mesa: support high resolutions modes

- platforms.cfg
- scriptmodules/libretrocores/lr-neocd.sh
This was requested a while back. Tested working on RPI. Should be fine.
I used the neogeo system as we don't have support for a neogeocd system with default theme etc.
> lr-neocd - added libretro neocd core to experimental packages

- scriptmodules/emulators/daphne.sh
- scriptmodules/emulators/jzintv.sh
- scriptmodules/emulators/linapple.sh
- scriptmodules/emulators/scummvm-sdl1.sh
- scriptmodules/emulators/scummvm-sdl1/01_rpi_kms_sdl1.diff
- scriptmodules/emulators/ti99sim.sh
- scriptmodules/helpers.sh
- scriptmodules/ports/bombermaaan.sh
- scriptmodules/ports/cdogs-sdl.sh
- scriptmodules/ports/lincity-ng.sh
- scriptmodules/ports/micropolis.sh
- scriptmodules/ports/openttd.sh
- scriptmodules/ports/opentyrian.sh
- scriptmodules/ports/smw.sh
- scriptmodules/ports/supertux.sh
- scriptmodules/ports/xrick.sh
- scriptmodules/supplementary/dispmanx.sh
- scriptmodules/supplementary/runcommand/runcommand.sh
- scriptmodules/supplementary/sdl1.sh
This isn't everything but I have tested pretty much everything here - some of the sdl1 do not work with the dispmanx driver and have been left excluded.
for the sdl1 apps that work on dispmanx this will technically enable all the packages for other kms platforms (Only tinker board currently and this needs revisiting). The plan is to rework this so we can choose a backend based on platform and allow users to switch if needed - so for tinkerboard these would probably default to using X. 
In some cases I have enabled dispmanx by default where it wasn't before - but users on rpi1/2/3 can turn off via the dispmanx config. Some of them used X also and just needed the `!kms` removing.
> Enabling a variety of sdl1 applications for rpi4

- scriptmodules/ports/eduke32.sh
- scriptmodules/ports/eduke32/0004-recast-function.patch
Recast klabs function to integer to prevent compiler error on older gcc versions.
--
Only verified that it fixes compilation via chroot. If you can, please verify the build works on stretch before merging. Thanks.
> eduke32: fix build on gcc 6.3.x

- scriptmodules/system.sh
The previous logic only allowed it to be forced on. The variable should also be respected if set to 0
@psyke83
> system - allow forcing __has_kms to 0

- scriptmodules/emulators/advmame.sh
* use sdl2 on non videocore systems
* force sdl video / keyboard input on kms / mali
This is initial work to get this working on rpi4. Also enable now for mali.
Upstream has a recent commit related to rpi4 support but it looks as though it expects the old videocore driver enabled. As we use fkms, I've made it use sdl2 which lacks the programmable video stuff but works at least. The default config maybe could be improved. Primarily I had to force keyboard driver as default didn't work and set magnify to 1 to disable slow upscaling.
> advmame - enable for kms and mali systems

- scriptmodules/emulators/dosbox-sdl2.sh
Current master is failing due to libglew-dev being required
even if opengl is disabled. As a temporary measure, install
package to satisfy build (and raise the issue upstream later).
> dosbox-sdl2: add libglew-dev to depends

- scriptmodules/libretrocores/lr-parallel-n64.sh
- scriptmodules/libretrocores/lr-parallel-n64/01_revert_11c1ae33.diff
* fixes saving of core options as segfault prevented them from saving
* note: probably unrelated but still crashes on launch in some cases and seems to be intermittent (may work on a second launch)
> lr-parallel-n64 - revert 11c1ae33 to fix segfault on exit on arm

- scriptmodules/ports/srb2.sh
Since `libOpenMPT` is optional, disable it on Debian/Raspbian Stretch to prevent a build failure.
Ubuntu 18.04 includes a newer version and it builds fine with it.
> srb2: fix building on Stretch, disable libOpenMPT

- scriptmodules/libretrocores/lr-mupen64plus-next.sh
* the core is unable to obtain pointers to the GL functions from RetroArch when using the legacy drivers.
* the issue is under investigation but for now build from the last known commit for videocore.
> lr-mupen64plus-next - temporary workaround for crash using videocore platform

- scriptmodules/libretrocores/lr-pcsx-rearmed.sh
Lightrec crashes or is less performant at the moment.
Fixes https://retropie.org.uk/forum/topic/24895/pi4-lr-pcsx-rearmed-from-source-freezes-with-some-games
> PSX: Use previous ari64 dynarec for ARM targets, rather than experimental lightrec one

- scriptmodules/libretrocores/lr-flycast.sh
this option was originally added before the core was enabled on arm. it may not even be needed on x11/x86 anymore
@gizmo98 do you remember why this was added. I think you added this code originally
If it's not needed on x11/GL we can remove completely
> lr-flycast - only set video_shared_context for gl targets

- scriptmodules/emulators/np2pi.sh
- scriptmodules/ports/openbor.sh
* OpenBOR - without `dispmanx` it scales badly or duplicates the screen.
* NP2PI - the PC98 emulator, which - I think - uses a fixed resolution and needs the `dispmanx` scaling to get a compatible video mode.
> Enable a couple more SDL1 emulators on the Pi4

- scriptmodules/emulators/reicast.sh
- scriptmodules/emulators/reicast/reicast.sh
- scriptmodules/supplementary/emulationstation/configscripts/reicast.sh
Reicast input handling has been problematic for quite some time. It looks like it's the result of 2 commits:
- https://github.com/reicast/reicast-emulator/commit/8e4e2c67f2f2d00da7567d779fc734c68e676562,  which removed the input configuration performed from the CLI 
- https://github.com/reicast/reicast-emulator/commit/8b5c2a3fac54bb74e8e79ff17fe0890af9044273, which added SDL input support, but also changed the way the input `.cfg` files are named.
Instead of relying on the `input:evdev_...` CLI parameters, the configuration is loaded from the `api`_`<controller_filtered_name>` files, where `<controller_filtered_name>` is produced by [`make_mapping_filename`](https://github.com/reicast/reicast-emulator/blob/11a02e571b37144d205eebb1c2974404c4b338f6/libswirl/input/gamepad_device.cpp#L203). …
> reicast: change input mapping scripts and simplify launch script

- scriptmodules/libretrocores/lr-opera.sh
4DO Libretro repository changed the location and the name of the core in https://github.com/libretro/opera-libretro/commit/8d62f9e8d3cf6c425cc1cbc488a7bc6f1f7d6a7b.
Fixed the installation with the new libretro core name.
> lr-opera: replace lr-4do due to name and repository changes

- scriptmodules/supplementary/runcommand/runcommand.sh
Reported in https://retropie.org.uk/forum/topic/24822/, affecting the X11 video modes calculation.
When a locale where `.` is not a decimal separator, `printf` throws an error when trying to round the refresh rate:
```
pi@retropie $ _number=60.02 && LC_ALL=ru_RU.UTF-8 printf '%.0f\n' ${_number::-2}
-bash: printf: 60.: invalid number
```
Overriding the `LC_NUMERIC` locale for the `printf` call seems ok.
> runcommand: override locale settings for printf

- scriptmodules/emulators/reicast.sh
Should fix https://github.com/RetroPie/RetroPie-Setup/issues/2998.
> reicast: remove 'Start' link when emulator is removed

- scriptmodules/supplementary/sdl2.sh
Sorry, you'd closed the previous PR before I'd finished.  Found this straggler that yields a "malimali", which obviously breaks the binary download path (we host our own now)...
The only other optimisations I can see are to move a few `isPlatform "vero4k" && depends+=(vero3-userland-dev-osmc)` lines - that don't involve any other module specific packages - to helpers.sh. 
Those are in ScummVM, Reicast and PPSSPP.  I know there are similar lines for the RPi, but it's an option anyway.  Thoughts?
> Unneeded vero4k/mali reference

- scriptmodules/emulators/retroarch.sh
- scriptmodules/emulators/retroarch/04_fix_corrupted_widgets.diff
* backport https://github.com/libretro/RetroArch/pull/10246
> retroarch - backport menu widget corruption fix to our v1.8.4

- scriptmodules/supplementary/bashwelcometweak.sh
I added squigly brackets around the CPU Temp variables in the output string.  This is what made the display work correctly for me on my latest version of Raspian on a Raspberry Pi 4.  I suspect that BASH was trying to use the temperature symbol as part of the variable name.
> Added squiglies around CPU Temperature variables

- scriptmodules/emulators/advmame.sh
This happens on the PI4, where `sdl` is the only usable video/input driver.
The race seems to be happening when waiting for the video thread to stop [here](https://github.com/amadvance/advancemame/blob/d951cdd530c30d9b3129b0d215e0163e6b71ce27/advance/osd/video.c#L1006), but for some reason the video thread is not closing (?) and the `pthread_join` call yields a SIGSEGV signal.
> advmame: disable multithreading temporary to resolve a crash
