RetroPie/RetroPie-Setup

scriptmodules/emulators/retroarch.sh, scriptmodules/libretrocores/libretro-handy.sh
https://github.com/petrockblog/RetroPie-Setup/issues/548
=> Change Atari Lynx folder names from "lynx" to "atarilynx"

scriptmodules/libretrocores/tyrquake.sh
Compilation issues are solved. So move to source based installation. Good playable with 1GHz OC.
=> tyrquake: Move to source based installation

scriptmodules/libretrocores/libretro-vecx.sh
=> Add experimental vectrex libretrocore

scriptmodules/4do-libretro.sh
Compiles and runs but is much slower than mupen64plus-libretro. Needs optimization.
=> Add experimental 3DO libretrocore

scriptmodules/emulators/retroarch.sh, scriptmodules/libretrocores/libretro-vecx.sh
Tested with RPie SD card image 2.4.1 beta.
=> libretro-vecx: Move to source based installations and increase resolution.

supplementary/RetroArchConfigs/2Axes11KeysGamePad.cfg
After the hotkey issue was resolved for the autoconfig controllers I have updated this controller's config file with it's hotkeys.
=> 2Axes11KeysGamePad.cfg - Updated controller config

scriptmodules/ports/xbmc.sh
=> xbmc: Update application name

scriptmodules/libretrocores/prosystem.sh
Retroarch is running but there is still no picture and sound.
=> Prosystem: Fix typo and add bin files

scriptmodules/emulators/mupen64rpi.sh
-Align render resolution to display resolution (VGA)
-Force bilinear filtering (rice plugin)
=> mupen64plus: minor improvements

scriptmodules/libretrocores/o2em.sh
Compiles and runs if o2rom.bin BIOS file is present.
=> Add videopac libretrocore O2EM

retropie_packages.sh, scriptmodules/emulators/retroarch.sh, scriptmodules/helpers.sh, scriptmodules/libretrocores/doom.sh, scriptmodules/libretrocores/fmsx-libretro.sh, scriptmodules/libretrocores/libretro-vecx.sh, scriptmodules/libretrocores/mupen64libretro.sh, scriptmodules/libretrocores/prosystem.sh, scriptmodules/libretrocores/tyrquake.sh, scriptmodules/ports/darkplaces.sh, scriptmodules/ports/eduke32.sh, scriptmodules/supplementary/resetromdirs.sh
as discussed on #362 I have simplified the permissions. In addition I introduced a new global $biosdir to remove some duplication around the code, and make it simpler if we ever needed to change the location etc.
=> Rom permissions

scriptmodules/libretrocores/gpsp-libretro.sh
=> Add experimental gba libretrocore gpsp

scriptmodules/libretrocores/vba-next.sh
Builds and runs. But is even a little bit slow on a PI2 with default clock.
=> Add experimental gba libretrocore vba-next

scriptmodules/libretrocores/nestopia.sh
=> Add experimental nes libretrocore nestopia

retropie_packages.sh, scriptmodules/emulators/atari800.sh, scriptmodules/emulators/gngeopi.sh, scriptmodules/emulators/jzintv.sh, scriptmodules/emulators/zmachine.sh, scriptmodules/helpers.sh, scriptmodules/packages.sh, scriptmodules/ports/eduke32.sh, scriptmodules/retropiesetup.sh, scriptmodules/supplementary/emulationstation.sh, scriptmodules/supplementary/resetromdirs.sh, scriptmodules/supplementary/snesdev.sh, scriptmodules/supplementary/splashenable.sh, scriptmodules/supplementary/splashscreen.sh, scriptmodules/system.sh
A whole load of cleanups relating to error & info messages, and error logging/reporting.
also fixes a bug with duplicate errors being created.
=> Messages and info

scriptmodules/emulators/mupen64plus-testing.sh
-Added vanilla glide64mk2 from mupen64plus
-Use vanilla rice from mupen64plus
-Added default settings for rice and glide64mk2
-Added own video settings repo so it is easier to modify RiceVideoLinux.ini and gles2n64rom.conf.
-Use updated audio-omx and video-gles2n64 plugins from ricrpi.
=> mupen64plus-testing: Add glide64 and default settings

scriptmodules/libretrocores/genesislibretro.sh, scriptmodules/libretrocores/libretro_snes9x-next.sh, scriptmodules/libretrocores/snes9x-next.sh
Add snes9x-next and use genesis-plus-gx for megadrive/genesis emulation.
=> Snes9x and genesis plus gx

scriptmodules/supplementary/gamecondriver.sh
Updated the drivers to be compatible with RPi2.
=> update gamecon & db9 driver versions

scriptmodules/emulators/retroarch.sh
I have created a common-shaders repo now. Should be better as a bloated setup script. Feel free to fork or copy this repo because we should keep everything together.
=> RetroArch: Add common-shaders repo

supplementary/runcommand.sh
@gizmo98
The final piece ? As discussed on ticket #531 this now includes the ability to switch retroarch render resolution.
Options are
"320x240"
"640x480"
"960x720"
"1280x960"
"Use video output resolution"
"Use config file resolution"
it defaults to 640x480 - I thought about having a different default for pi2, but then I thought maybe best to err on the side of caution and go with best performance at a res that should be enough as a default. And of course it is easily switchable. But let me know what you think and if there is enough choice.
=> added options to launch menu to switch render resolution of retroarch #531

scriptmodules/supplementary/emulationstation_theme_simple.sh
Added missing themes for retropie and videopac. Can be removed if someone adds these systems to simple_latest.zip.
=> Add repo for missing system themes

scriptmodules/emulators/mupen64plus.sh
..default ScreenUpdateSetting=7 and set save state path.
=> mupen64plus: Add video settings repo from testing

scriptmodules/emulators/atari800.sh
Instead of giving "modify es_system.cfg" tips we should add atari5200:
https://github.com/petrockblog/RetroPie-Setup/wiki/Atari-800-and-5200
=> Add Atari 5200 system

scriptmodules/libretrocores/lr-genesis-plus-gx.sh, supplementary/platforms.cfg
and use genesis-plus-gx as a sega-cd system.
https://github.com/petrockblog/RetroPie-Setup/issues/749
=> Add Sega SG-1000 as a system

scriptmodules/emulators/mupen64plus.sh
Runs even better with zelda and other games (speed).
=> mupen64plus: Use old rice plugin.

supplementary/runcommand.sh
This pull request addresses the issue #766.
I am not very proficient in bash programming, but this is the solution I've been searching for. Even if this pull request is not merged it may provide a simple way to solve this problem for somebody.
=> enabled the option in the menu to edit custom config for each rom, if config exists it is added to appendconfig (only for retroarch)

scriptmodules/supplementary/gamecondriver.sh
Fixed and updated the script module for gamecon/db9.
=> updated gamecon script module.

scriptmodules/emulators/reicast.sh, scriptmodules/libretrocores/lr-beetle-vb.sh, scriptmodules/libretrocores/lr-mgba.sh, scriptmodules/libretrocores/lr-o2em.sh, scriptmodules/libretrocores/lr-virtualjaguar.sh, scriptmodules/libretrocores/lr-yabause.sh, supplementary/platforms.cfg
-Dreamcast emulator reicast. Only startable from console atm. No sound. Needs bios files.
-Atari Jaguar libretrocore. Is as slow as 3DO emulation.
-GBA libretrocore MGBA. Seems to run good.
-Virtual Boy libretrocore beetle-vb. Runs a bit laggy.
=> Add more experimental emus

scriptmodules/emulators/reicast.sh
=> reicast: fix startup from emulationstation

scriptmodules/emulators/reicast.sh
Without this fix only dreamcast menu shows up.
=> reicast: fix game start

scriptmodules/emulators/reicast.sh
I have forked reicast-emulator and added all changes from http://www.raspberrypi.org/forums/viewtopic.php?f=78&t=100076.
Audio is there but controller mapping is still a little bit strange with a PS3 controller.
=> Add reicast audio fix

scriptmodules/emulators/mupen64plus-testing.sh
AUDIO OMX: Enable extended options to increase audio buffer
=> Mupen64plus-testing: Audio buffer underun fix

scriptmodules/libretrocores/lr_mednafen_wswan.sh, supplementary/platforms.cfg
Add mednafen wonderswan emulator and update platforms.cfg.
=> Add Wonderswan

scriptmodules/libretrocores/lr_mednafen_ngp.sh, supplementary/platforms.cfg
Add Neo Geo Pocket Emulator and update platforms.cfg
=> Neo Geo Pocket (Color)

supplementary/moduledata/supplementary/emulationstation/configscripts/emulationstation.sh, supplementary/moduledata/supplementary/emulationstation/configscripts/retroarch.sh, supplementary/moduledata/supplementary/emulationstation/inputconfiguration.sh
This is still a WIP, but wanted to do the request so we don't collide. 
De-duplication and cleanups - the config file locations were duplicated in every function.
I'm thinking we can actually do this without so many functions - and have it so the submodules manage the logic themselves - should de-duplicate even more.
=> Input configuration

supplementary/platforms.cfg
verified by someone here  http://blog.petrockblock.com/forums/topic/reicast-games-format/
=> add .gdi extension to sega dreamcast

scriptmodules/libretrocores/lr-bluemsx.sh
It also has an option in the core settings to run colecovision- the colecovision
games run fine but they are currently not properly coded for input so
its basically useless for now.
=> Add lr-blueMSX primarily for MSX2

scriptmodules/supplementary/retropiemenu.sh, scriptmodules/supplementary/wifi.sh
@HerbFargus here you go - please try this
=> wifi configuration script - thanks to herbfargus for the initial work.

scriptmodules/helpers.sh, scriptmodules/supplementary/configedit.sh
@biscuits99 @HerbFargus 
Please check out this configuration module and let me know what you think.
=> new module for editing of configs, and setting of common retroarch options

scriptmodules/supplementary/splashscreen.sh, scriptmodules/supplementary/splashscreen/asplashscreen
@HerbFargus please try this - please run the script again, so it updates it, and then do enable.
This is the last thing to sort before the release...
=> remove delay from omxplayer start and fix up depdencies

scriptmodules/supplementary/esthemes.sh
published fixes on the central repo (https://github.com/RetroPie/es-theme-nbba/pull/1) and it can be now be added.
=> add nbba theme

supplementary/platforms.cfg
=> Add .zip to Wonderswan

scriptmodules/supplementary/scraper.sh
@HerbFargus please give this a go - no config options yet, but it can go in as a basic scraper and be improved later. i've only tested a little bit.
=> initial version of module to use Steven Selph's scraper #945

scriptmodules/emulators/frotz.sh
does zmachine need to be added to platforms.cfg?
=> add .z5 to frotz

scriptmodules/supplementary/esthemes.sh
There are few more tweaks I'll make on logos on and whatnot but it is
fully functional and runs over 50 systems on my rpi2 with default memory
splits.
=> add 3 more complete themes to the theme installer

scriptmodules/supplementary/esthemes.sh
gamelist on left, large boxart on right
=> add carbon-nometa variation

scriptmodules/supplementary/esthemes.sh
This theme is also fantastic as it also doesnt have the white screen of
death issue- plus who doesn't like turtles?
=> Add Omnija's Turtle Pi theme

platforms.cfg, scriptmodules/emulators/ppsspp.sh, scriptmodules/libretrocores/lr-ppsspp.sh
Please give it a go. Works here - testing with the excellent "Suicide Barbie" demo currently.
Performance probably could be a bit better as we are not building for arm7 due to current problems with ppsspp and arm7 target on the rpi.
=> added ppsspp experimental emulator

scriptmodules/emulators/retroarch.sh
Add a new disable searchbox fix.
=> retroarch: disable search box

scriptmodules/emulators/mupen64plus.sh
-All modifications were added upstream. Remove old fixes.
-Add raspbian jessie fix again.
=> Mupen64plus: cleanup module

scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
-remove duplicate onend_retroarch_joystick() function.
-add sanity check for controllers without select button.
=> retroarch config script tweaks

scriptmodules/supplementary/esthemes.sh
They look quite brilliant actually- a lot of customisability options with colour sets.
=> Add Eudora Themes from AmadhiX

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/RetroPie/RetroPie-Setup/issues/1061
=> mupen64plus: add hotkey remapping

scriptmodules/supplementary/configedit.sh
-create a string with all present shader presets
-add this string to common array
-increase x axis of dialog box because it was to small to show whole
file paths
=> configedit.sh: add shader selection

platforms.cfg, scriptmodules/libretrocores/lr-mednafen-ngp.sh, scriptmodules/libretrocores/lr-mednafen-wswan.sh
Would like Neogeo Pocket/Color and Wonderswan/Color as seperate folders.
1 for organization purposes and as well to maintain seperate folders for seperate systems.
=> Wonderswan and Neogeo Seperations

scriptmodules/supplementary/xboxdrv.sh
=> Minor typo fix.

scriptmodules/supplementary/esthemes.sh
Also reordered themes due to recentness/completeness
=> Add Pixel Theme (From Rookervik)

scriptmodules/supplementary/emulationstation.sh, scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh
https://github.com/RetroPie/RetroPie-Setup/pull/1161
=> emulationstation: add autoconf button swap option

platforms.cfg
tested here
http://blog.petrockblock.com/forums/topic/amstrad-cpc-tape-support-plz/
=> Add tape support for amstrad (.cdt)

scriptmodules/libretrocores/lr-gambatte.sh, scriptmodules/libretrocores/lr-gambatte/default.pal
http://blog.petrockblock.com/forums/topic/gameboy-overlay-settings-psd/
=> lr-gambatte: add default green yellow gb classic palette

platforms.cfg, scriptmodules/emulators/advmame.sh, scriptmodules/emulators/gngeopi.sh, scriptmodules/emulators/mame4all.sh, scriptmodules/emulators/pifba.sh, scriptmodules/libretrocores/lr-fba-next.sh, scriptmodules/libretrocores/lr-fba.sh, scriptmodules/libretrocores/lr-imame4all.sh, scriptmodules/libretrocores/lr-mame2003.sh, scriptmodules/libretrocores/lr-mame2010.sh
Still not completely sure of some of the configs (i.e. advmame, mame4all)
=> Add Arcade System

scriptmodules/libretrocores/lr-mame2003.sh
skip_disclaimer skips the nag screen
dcs-speedhack speeds up mk2/3
=> mame2003 core option defaults

scriptmodules/supplementary/scraper.sh
Add the option to allow users to select which scraper the sselph scraper should scrape from.
Updated menu items to make more sense.
=> Allow users to select the scraper to use with sselph's scraper.

scriptmodules/ports/solarus.sh
Added the Solarus open source Zelda LttP engine with 3 games made with it.
=> Added Solarus engine.

scriptmodules/emulators/retroarch.sh, scriptmodules/helpers.sh, scriptmodules/supplementary/configedit.sh
=> Config editor

scriptmodules/emulators/residualvm.sh
Pathname leftover from scummvm template
=> Corrected Path

scriptmodules/ports/solarus.sh
Add missing cmake dependency to Solarus.
=> Add missing cmake dependency to Solarus.

scriptmodules/ports/openbor.sh
Only current problem is the game selection menu requires keyboard at the moment.
=> Added OpenBOR port.

scriptmodules/emulators/mupen64plus.sh
tachiweasel's mupen64plus video plugin is a little bit faster but also less compatible as any other video plugin. 
https://github.com/tachiweasel/mupen64plus-video-videocore
=> mupen64plus: add videocore video plugin

scriptmodules/supplementary/esthemes.sh
A menu option for esthemes that handles cloning and displaying a sample image of all themes.
=> Added a theme gallery using fbi

scriptmodules/emulators/linapple.sh
supports autolaunching disks (still needs a reset to start a game though) but this will remove the need for a start script for the apple 2.
should address #1055 and #1212
=> Update linapple with dabone's changes

scriptmodules/emulators/reicast/reicast.sh
Use command line parameters instead of ini tweaks. This method is safer
and more reliable.
=> reicast.sh: use command line parameters

scriptmodules/supplementary/scraper.sh
I've seen this pop up in issues and emails so thought I'd
add the option to tweak these flags.
=> Add option to set -append and -use_nointro_name=false flags

scriptmodules/supplementary/scraper.sh
=> scraper: add option to use filenames as ROM name.

scriptmodules/admin/setup.sh, scriptmodules/emulators/atari800.sh, scriptmodules/emulators/gngeopi.sh, scriptmodules/emulators/jzintv.sh, scriptmodules/emulators/px68k.sh, scriptmodules/emulators/reicast.sh, scriptmodules/emulators/sdltrs.sh, scriptmodules/emulators/ti99sim.sh, scriptmodules/emulators/xroar.sh, scriptmodules/libretrocores/lr-4do.sh, scriptmodules/libretrocores/lr-nxengine.sh, scriptmodules/libretrocores/lr-o2em.sh, scriptmodules/packages.sh, scriptmodules/ports/alephone.sh, scriptmodules/ports/cannonball.sh, scriptmodules/ports/openbor.sh
* get rid of _INFMSGS and instead have a rp_module_help field with information in.
this can then be displayed in the setup menus, and not just after configuring.
=> help improvements

scriptmodules/supplementary/bluetooth.sh
* support connecting to devices in background
* use letters for main menu - saves renumbering etc
* cleanups / fixes
fixes #1526
=> bluetooth improvements

scriptmodules/admin/image.sh, scriptmodules/supplementary/autostart.sh
This is a WIP. Just for reference. Still untested.
=> initial integration of image building into retropie-setup

scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh, scriptmodules/supplementary/emulationstation/configscripts/mupen64plus.sh, scriptmodules/supplementary/emulationstation/configscripts/pifba.sh, scriptmodules/supplementary/emulationstation/configscripts/reicast.sh, scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh, scriptmodules/supplementary/emulationstation/inputconfiguration.sh
* rename buttons to avoid confusion (bottom -> shoulder / top -> trigger)
* as with https://github.com/RetroPie/EmulationStation/pull/54
=> input configuration button renames

scriptmodules/supplementary/raspbiantools.sh
=> More universal disable blanker

scriptmodules/libretrocores/lr-catsfc.sh, scriptmodules/libretrocores/lr-fba-next.sh, scriptmodules/libretrocores/lr-fba.sh, scriptmodules/libretrocores/lr-pocketsnes.sh, scriptmodules/libretrocores/lr-snes9x-next.sh, scriptmodules/libretrocores/lr-vecx.sh
Fixing stuff from here: https://github.com/RetroPie/RetroPie-Setup/issues/1614
=> Update libretro cores after renames + fix broken scripts

scriptmodules/supplementary/esthemes.sh
A new theme by mattrixk based off of the "Pixel" theme.
Announcement: https://retropie.org.uk/forum/topic/3085/metapixel-a-new-emulationstation-theme
Repository: https://github.com/mattrixk/metapixel
=> Add mattrixk's metapixel theme

scriptmodules/supplementary/emulationstation/configscripts/pifba.sh, scriptmodules/supplementary/emulationstation/configscripts/pisnes.sh
Tested with Logitech F710 (xpad) and iBuffalo SNES (usbhid)
Resolves https://github.com/RetroPie/RetroPie-Setup/issues/1609
Signed-off-by: Jamie Bainbridge <jamie.bainbridge@gmail.com>
=> pisnes - add input configuration script

scriptmodules/emulators/mupen64plus/mupen64plus.sh
Screen flickers if UseNativeResolutionFactor=1 is set
=> mupen64plus: fix majoras mask

scriptmodules/supplementary/esthemes.sh
[Here is the repository.](https://github.com/mattrixk/es-theme-spare)
[Here is the forum thread.](https://retropie.org.uk/forum/topic/3391/spare-a-new-emulationstation-theme)
=> Add mattrixk's Spare theme

platforms.cfg, scriptmodules/emulators/pcsx2.sh
Lazy implementation. Just use Ubuntu 16.04 pcsx2 package.
=> x86: add experimental ps2 emulator

scriptmodules/admin/docs.sh, scriptmodules/helpers.sh
sudo ./retropie_packages.sh docs
to build the documentation - will end up in "docs/" folder off the RetroPie-Setup folder.
=> added documentation builder module and api documentation for the main helpers.sh

scriptmodules/supplementary/sdl2.sh
Add armv64 and x64 platforms and platform flags. Some emulators have 32Bit or 64Bit optimizations which can be selected with separate flags.
=> Modify platforms

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/gonetz/GLideN64/commit/aab67261174f2df01da9a5326eaa23
197ca4cfdc
=> m64p: update config version

README.md, scriptmodules/admin/setup.sh, scriptmodules/emulators/ags.sh, scriptmodules/emulators/fs-uae.sh, scriptmodules/emulators/reicast.sh, scriptmodules/emulators/residualvm.sh, scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/scummvm.sh, scriptmodules/emulators/vice.sh, scriptmodules/helpers.sh, scriptmodules/inifuncs.sh, scriptmodules/packages.sh, scriptmodules/ports/eduke32.sh, scriptmodules/ports/love.sh, scriptmodules/ports/openpht.sh, scriptmodules/ports/zdoom.sh, scriptmodules/supplementary/autostart.sh, scriptmodules/supplementary/bluetooth.sh, scriptmodules/supplementary/ps3controller.sh, scriptmodules/supplementary/raspbiantools.sh, scriptmodules/supplementary/scraper.sh, scriptmodules/supplementary/sdl1.sh, scriptmodules/supplementary/sdl2.sh, scriptmodules/supplementary/usbromservice.sh, scriptmodules/system.sh
and map them to 
```
$__os_id
$__os_desc
$__os_release
$__os_codename
```
Update all the modules to use new variables.
WIP needs some more testing
=> use lsb_release for platform identification

scriptmodules/emulators/retroarch.sh
* move / symlink assets / shaders / overlays to configs/all/retroarch/*
along with https://github.com/RetroPie/RetroPie-Setup/commit/1d43c0f8253348e89973c9ff05d5d90daf18bf6e
this means that we are now using more of retroarch config structure in /opt/retropie/configs/all/retroarch and symlinking the old location.
With the new retroarch being able to save per core / per rom overrides, these will now get saved to /opt/retropie/configs/all/retroarch/config
also it has the advantage that shaders / overlays / can be backed up more easily if the user has added some of their own etc.
=> retroarch - move assets / shaders / overlays

scriptmodules/emulators/hatari.sh, scriptmodules/libretrocores/lr-hatari.sh
split out capsimage building in hatari.sh #1731
=> added lr-hatari to experimental section

scriptmodules/admin/docs.sh, scriptmodules/supplementary/runcommand/runcommand.sh
* make global vars uppercase - was getting confusing and will make it easier when refactoring / removing
* rework mode switching
* rework defaults loading/saving to remove globals
* readable keys in configs/all/videomodes.cfg and configs/all/emulators.cfg instead of md5hashes
=> Runcommand changes

scriptmodules/ports/sdlpop.sh
=> Fix make execution

scriptmodules/supplementary/emulationstation/configscripts/daphne.sh
from shmoopty - needs testing / feedback before merging - i made a few changes which will be squashed before merge also.
=> Daphne input

scriptmodules/helpers.sh, scriptmodules/supplementary/attractmode.sh, scriptmodules/supplementary/emulationstation.sh
This adds an attractmode module - should build on X11 and RPI.
Added support for multiple frontends when generating configs / moved ES config generation to ES script
Added initial configuration / romlist generation for attractmode
=> Attractmode

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/gonetz/GLideN64/blob/master/src/Config.h#L7
=> update gliden64 config version

scriptmodules/supplementary/mehstation.sh, scriptmodules/supplementary/retropiemenu.sh
Has a problem currently, in that mehstation loads etc, but once mehstation has scanned for roms, and saved back to the database, it will crash. Not sure the cause - bug in mehstation or something caused by the way we manually "set up" the db structure ourselves, so we can set up each system etc.
=> added mehstation to experimental

scriptmodules/ports/openpht.sh
=> bump to v1.7.1

scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/retroarch/01_hotkey_hack.diff
Anyone have time to test / confirm this works for them ? (eg on a game where insert coin doesn't work if the hotkey enable button is select)
=> retrarch - rework hotkey enable hack for upstream retroarch and re-enable patch - fixes #1772

scriptmodules/emulators/minivmac.sh
This is just a preliminary PR for review, 
So as a preface,from the minivmac [site](http://www.gryphel.com/c/minivmac/options.html#option_t):
By default, Mini vMac emulates a Macintosh Plus. But it also can be compiled to emulate a few other computers, with one of these lines:
-m 128K { Macintosh 128K }
-m 512Ke { Macintosh 512Ke }
-m Plus { (default) Macintosh Plus }
-m SE { Macintosh SE }
-m Classic { Macintosh Classic }
-m SEFDHD { Macintosh SE FDHD }
-m II { Macintosh II * }
This PR only handles the Macintosh Plus (some of the options available may also be emulated with Basilisk II)
There are some SDL issues with the mouse pointer with the default compile options through the main minivmac source but our good friend vanfanel has patched them up in his fork which this PR uses (though I …
=> Add Minivmac

scriptmodules/helpers.sh, scriptmodules/supplementary/runcommand/joy2key.py, scriptmodules/supplementary/runcommand/runcommand.sh
* if device parameter is /dev/input/jsX it will read from all joysticks
* if a joystick is removed or another reconnected it will be picked up
* default runcommand and helpers to use all joypads
if anyone has a chance to test this it would be appreciated. Thanks.
=> joy2key - support reading from multiple joysticks

scriptmodules/emulators/ppsspp.sh, scriptmodules/emulators/ppsspp/01_aarch64.diff, scriptmodules/emulators/retroarch.sh, scriptmodules/libretrocores/lr-armsnes.sh, scriptmodules/libretrocores/lr-beetle-supergrafx.sh, scriptmodules/libretrocores/lr-fbalpha.sh, scriptmodules/libretrocores/lr-gpsp.sh, scriptmodules/libretrocores/lr-ppsspp.sh, scriptmodules/libretrocores/lr-snes9x2002.sh, scriptmodules/ports/love.sh, scriptmodules/ports/solarus.sh, scriptmodules/supplementary/autostart.sh, scriptmodules/supplementary/splashscreen.sh, scriptmodules/system.sh
WIP - most stuff builds, but I haven't done much testing yet.
Also need to make the autostart module work on odroid c1/c2
=> Odroid c2 support

scriptmodules/admin/setup.sh, scriptmodules/emulators/ags.sh, scriptmodules/emulators/reicast.sh, scriptmodules/emulators/residualvm.sh, scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/scummvm.sh, scriptmodules/emulators/vice.sh, scriptmodules/helpers.sh, scriptmodules/ports/eduke32.sh, scriptmodules/ports/love.sh, scriptmodules/ports/openpht.sh, scriptmodules/ports/zdoom.sh, scriptmodules/supplementary/autostart.sh, scriptmodules/supplementary/bluetooth.sh, scriptmodules/supplementary/ps3controller.sh, scriptmodules/supplementary/raspbiantools.sh, scriptmodules/supplementary/scraper.sh, scriptmodules/supplementary/sdl1.sh, scriptmodules/supplementary/usbromservice.sh, scriptmodules/system.sh
Removed support for Wheezy and add elementary os / kde neon (recording upstream ubuntu version so we can handle versions / package renames etc)
@pl402 @VR51 @MrDiamond123
Please feel free to give this a spin!
=> Ubuntu based oses

scriptmodules/supplementary/emulationstation/configscripts/daphne.sh, scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh, scriptmodules/supplementary/emulationstation/configscripts/mupen64plus.sh, scriptmodules/supplementary/emulationstation/configscripts/pifba.sh, scriptmodules/supplementary/emulationstation/configscripts/reicast.sh, scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh, scriptmodules/supplementary/emulationstation/inputconfiguration.sh
* use globals for device name/type (no need to keep passing them to every function)
* add GUIDs to es_input.cfg - #1798
need to update documentation still
=> Inputconfig improvements

scriptmodules/supplementary/powerblock.sh
I have added a driver module for the power-switch hardware "PowerBlock".
=> Added PowerBlock driver module

scriptmodules/emulators/xm7.sh
Add XM7, Fujitsu FM-7 series emulator
cf.
https://github.com/nakatamaho/XM7-for-SDL
https://github.com/Artanejp/XM7-for-SDL
http://xm7.la.coocan.jp/xm7/xm7.html
=> Add XM7, Fujitsu FM-7 series emulator

scriptmodules/emulators/uae4arm.sh, scriptmodules/emulators/uae4arm/uae4arm.sh
* add default a500 / a1200 configs
* allow launching directly from adf/dms/zip
* support multiple disks in zip or if named *Disk1.adf *Disk2.adf as separate files
* choose a1200 config if filename contains AGA or CD32 else use a500 config
=> uae4arm - game launch script / enhancements

scriptmodules/supplementary/launchingimages.sh
Here is the scriptmodule we talked about [in the forum](https://retropie.org.uk/forum/topic/8029/where-s-the-retropie-setup-api-docs/3).
=> generate launching images based on ES themes

scriptmodules/emulators/advmame-0.94.sh, scriptmodules/emulators/advmame-1.4.sh, scriptmodules/emulators/advmame.sh, scriptmodules/emulators/advmame/01_rpi_framebuffer.diff
* rework patch code
* use 0.94 instead of 0.94.0
* make advmame always be the latest advmame version with advmame.rc as the config
* remove any old emulator.cfg entries
=> advmame - split advmame into multiple packages

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/gonetz/GLideN64/blob/master/src/Config.h
=> Mupen64Plus: Update config version

scriptmodules/ports/openblok.sh
This is an initial pass for OpenBlok coded by our good friend Fluffypillow aka @mmatyas. 
still needs a few tweaks, e.g. platform configs for x86
Open to suggestions for improvement
also there are a few known issues (particularly with xbox controllers using xpad) my logitech f310 controllers work swimmingly though. 
Gameplay as far as I can tell is stable including battle mode. Rookervik has also worked on some alternate themes (will have to be installed by the user manually though)
=> add openblok

scriptmodules/emulators/amiberry.sh, scriptmodules/emulators/uae4arm.sh, scriptmodules/emulators/uae4arm/uae4arm.sh
@ChoccyHobNob - i've tested this yet - but your PR at least motivated me to get this done :) (and actually did help, as I could see amiberry still used the same commandline parameters etc for now)
=> added amiberry - fixes #1880

scriptmodules/supplementary/launchingimages.sh
Some users reported problems in generating images and got solved after installing this lib.
=> added librsvg2-bin to launchingimages.sh dependencies

scriptmodules/supplementary/esthemes.sh
This is my first ever pull request to a repo that isn't my own; hope it works!
=> Add Futura themes (10px)

platforms.cfg, scriptmodules/admin/builder.sh
This needs some testing - I may have missed some also. Some cores do their own loading so I suspect 7zip wouldn't work for them.
=> platforms.cfg - added 7zip extensions to some systems that should support it via retroarch.

platforms.cfg, scriptmodules/emulators/minivmac.sh
@HerbFargus - does this look ok - just changed system and added dependency. Also removed !mali as sdl2 stuff should be fine on mali.
=> Minivmac changes

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/8894/fundamental-theme
=> Add G-rila's "Fundamental" theme

scriptmodules/supplementary/snesdev.sh
changed the 'make -C "$md_inst" make installservice' command and removed the additinal 'make' in the request.
=> service install not working

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh
https://github.com/RetroPie/RetroPie-Setup/issues/1925
=> GLideN64: store and load config version

scriptmodules/supplementary/esthemes.sh
see https://retropie.org.uk/forum/topic/8391/cardboard-mini-nes-nes-mini-and-famicom-mini-themes/400
=> Added @ruckage's nes-mini and famicom-mini emulationstation themes.

scriptmodules/supplementary/esthemes.sh
Seeing if it's possible to submit my themes to the official list.  They both currently support video previews and are in a stable state for use.
Details of both themes can be found here: https://retropie.org.uk/forum/topic/7022/new-theme-crt-with-support-for-video-preview.
=> Request to add anthonycaccese's crt themes

scriptmodules/admin/setup.sh, scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/retroarch/04_mali_struct.diff, scriptmodules/emulators/vice.sh, scriptmodules/libretrocores/lr-snes9x2002.sh, scriptmodules/system.sh
This is a WIP. Put here for those that want to test while it's being worked on (no bug reports yet please). 
What is currently working:
RetroArch / ES / SDL2 and most main emulators build.
=> Odroid XU support

scriptmodules/supplementary/esthemes.sh
I appologize for my early request to the main branch.  Herb suggested I start using the desktop gui for git and i made an error on proper modifications.  I do appologize.
=> Request to add es-theme-ComiBook and es-themeComicBook_4-3

scriptmodules/emulators/scummvm-sdl1.sh, scriptmodules/emulators/scummvm.sh
* scummvm built against sdl1 due to some issues with sdl2 built (mt-32 / joystick problems)
=> added scummvm-sdl1 module - fixes #1835

scriptmodules/supplementary/emulationstation/configscripts/retroarch.sh
* if es configuration has no hotkeyenable entry, use select for old behaviour and backward compatibility
* if es configuration has hotkeyenable set to a key with id 0, disable the hotkey enable button
* if es configuration has hotkeyenable set to anything else, use that for the hotkey
* this relies on https://github.com/RetroPie/EmulationStation/pull/74
=> inputconfiguration - allow configuration of hotkey enable button

scriptmodules/supplementary/scraper.sh
There is a potential issue with this PR. Only ScreenScraper and ArcadeItalia support video so people may expect it to work and it won't. Should I see if I can alert if they request video on a non-video source?
=> Add video and ArcadeItalia support for scraper

scriptmodules/emulators/retroarch.sh
@psyke83 please give this a go. It's much the same as your PR, but without using svn and just grabbing a tar.gz from our own server.
=> retroarch - install minimal assets by default

scriptmodules/supplementary/runcommand/runcommand.sh
* scripts must be called "name.sh" and live in /opt/retropie/configs/all/runcommand-menu
* scripts are passed the same parameters as onstart / onend ("$SYSTEM" "$EMULATOR" "$ROM" "$COMMAND")
* exit code of 0 returns to user menu, 1 exits without launching, and 2 exits and launches rom
@meleu despite saying I didn't want to implement the runcommand menu stuff yet, I decided to throw this together as it should provide the ability to do what you want but also allow scripts to be "dropped in" easily by users. It's had limited testing though and may have errors.
The other thing I thought was important was to handle what happens on exit - see the return codes above.
=> runcommand - add user menu

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/11012/new-theme-steampunk/14
=> Add Steampunk theme by dmmarti

scriptmodules/supplementary/esthemes.sh
Adding the awesome Retrorama theme from @lipebello.
Here is a demo:
https://www.youtube.com/watch?v=RN-Fzw5n8ws
**edit**:
his comment about adding this to RetroPie-Setup: https://www.youtube.com/watch?v=RN-Fzw5n8ws&lc=z13vjp3outitcrzxb04cddcx4rfygnjbkmc0k.1498405527867352
=> Added the awesome Retrorama theme to esthemes.sh

scriptmodules/supplementary/esthemes.sh
I neglected that index detail when implemented #2025 and the logic never was able to show the "update or uninstall" dialog.
Fixed.
=> esthemes bugfix

scriptmodules/supplementary/esthemes.sh
Hi @dmmarti , as promised! Have you posted this in the RP forums?
=> Add Dmmarti's "Maximus Pie" Theme

scriptmodules/supplementary/esthemes.sh
* add --default-item to remember position
* use G and U for first two options and numbered items for themes
* change order of code to be more logical
=> esthemes - rework menu logic

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/11723/new-theme-showcase-now-released
=> Add 'Showcase' by Dmmarti

scriptmodules/supplementary/esthemes.sh
new theme I been working on for a couple of months its a Mario theme based on hurstyblue
=> Add 'marioblue" by garaine

scriptmodules/libretrocores/lr-fbalpha.sh
Updating Final Burn Alpha version 0.2.97.40 to 0.2.97.42
Source: https://github.com/libretro/fbalpha/commit/ed1e7061cb4500ac57b3f7aa4245de66b28c26e9
=> Update FBA version

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/11933/new-theme-magazine-madness-released
=> Add RetroHursty69's Magazine Madness Theme

scriptmodules/supplementary/esthemes.sh
Art Book
Repository: https://github.com/anthonycaccese/es-theme-art-book
Forum Thread: https://retropie.org.uk/forum/topic/11728/new-theme-art-book
TFT (for small screens)
Repository: https://github.com/anthonycaccese/es-theme-tft
Forum Thread: https://retropie.org.uk/forum/topic/10793/new-theme-tft-a-theme-made-for-small-screens
Thank you!
=> Added anthonycaccese's art-book and tft themes

scriptmodules/supplementary/esthemes.sh
add playstation theme by lostless to main es theme list.
=> Add playstation theme

scriptmodules/emulators/mupen64plus/mupen64plus.sh
and blacklist battle of naboo and indiana jones and the infernal machine.
https://www.reddit.com/r/emulation/comments/6t002h/star_wars_rogue_squadron_hle_gliden64_build/
=> mupen64plus: remove rogue squadron from blacklist

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/12376/new-theme-stirling-in-development
=> Stirling theme by RetroHursty69

scriptmodules/supplementary/esthemes.sh
https://retropie.org.uk/forum/topic/12445/new-theme-kidz
=> Add dmmarti's "Kidz" theme

scriptmodules/supplementary/gamecondriver.sh
=> update gamecon_gpio_rpi and db9_gpio_rpi versions

scriptmodules/supplementary/esthemes.sh
Forum Thread:
https://retropie.org.uk/forum/topic/11728/theme-art-book
Repositories: 
https://github.com/anthonycaccese/es-theme-art-book-4-3
https://github.com/anthonycaccese/es-theme-art-book-pocket
Thank you
=> Request to add Art Book 4x3 and Art Book Pocket themes

scriptmodules/supplementary/usbromservice.sh
* update usbromservice scripts on retropie-setup upgrade
* move to main packages rather than config, as it requires the usbmount and this makes it easier to add/remove. previously it would be installed when choosing the usbromservice from config, even if you didn't want to use it.
=> usbromservice improvements -

scriptmodules/libretrocores/lr-mame2014.sh
Fixes #2120
Refs: 
https://github.com/libretro/mame2014-libretro/commit/869834c255e295885939def4ad1f09c0af32fe98
https://github.com/libretro/mame2014-libretro/commit/00d553dcee27ef8e6523fec3d056934a41ec7348
=> lr-mame2014: update location of README

scriptmodules/supplementary/runcommand/joy2key.py
This is a quick fix to issue #1798 for joy2key.py.
It could be improved if all the retroarch joypad *.cfg files include the vendor ID and the product ID.
It would be also nice to improve the retroarch joypad *.cfg file creation by including those IDs in the filename, like this:
<vendor_id>:<product_id>:<name>.cfg.
Since I have only few involvement with this project, I don't want to take the initiative to implement such a change. This is just an idea that might be helpful.
=> Fix for joy2key.py related to issue #1798.

scriptmodules/supplementary/esthemes.sh
retropie Emulationstation theme by coinjunkie
=> synthwave theme

scriptmodules/supplementary/esthemes.sh
Apparently Ive become the goto man for theme pull request..lol
=> 2 versions of Boxalloy by Dwayne Hurst and svc720 by Sara Thomas

scriptmodules/supplementary/sdl1.sh
Reverts RetroPie/RetroPie-Setup#2181
=> Revert "sdl1: allow building against distro-specific sources"

scriptmodules/supplementary/esthemes.sh
Add 3 new themes by Dwayne Hurst
Greenilicious
Retroroid
Merryxmas
=> Updated esthemes.sh

scriptmodules/supplementary/emulationstation/configscripts/emulationstation.sh, scriptmodules/supplementary/emulationstation/inputconfiguration.sh
This is needed for cec input to be stored in es_input.cfg
=> Support for cec input

scriptmodules/supplementary/attractmode.sh
Not ready to be merged until these PRs are accepted:
https://github.com/mickelson/attract/pull/387
https://github.com/mickelson/sfml-pi/pull/7
=> attractmode: Pi: update for new vendor graphics libraries

scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/mupen64plus/mupen64plus.sh, scriptmodules/emulators/mupen64plus/rpi-yuv.diff
May be reverted later - see: https://github.com/gonetz/GLideN64/issues/1665
=> mupen64plus: Pi: temporarily workaround texture rendering/segfault issue

scriptmodules/libretrocores/lr-gambatte.sh
=> lr-gambatte: update readme name

scriptmodules/supplementary/esthemes.sh
I have added 3 new ES themes. Tributes GoT, Tribute SWars and Tribute STrek.
=> Update to esthemes.sh have added 3 new ES themes

scriptmodules/emulators/amiberry.sh, scriptmodules/emulators/uae4arm.sh
Preparation for @midwan's SDL2 version of amiberry. Not ready for merging.
=> amiberry: update for new SDL2 release

scriptmodules/ports/alephone.sh, scriptmodules/ports/darkplaces-quake.sh, scriptmodules/ports/uqm.sh, scriptmodules/supplementary/raspbiantools.sh
=> More stretch fixes

scriptmodules/emulators/amiberry.sh
=> amiberry: drop -sdl2 postfix for xu4 target

scriptmodules/ports/digger.sh
screwed up previous pull request, recreating again with issues fixed
=> add Digger Remastered to experimental

scriptmodules/libretrocores/lr-mame2003-plus.sh
@arcadez thanks for pointing this out
=> fix mame2003-plus license link

platforms.cfg, scriptmodules/emulators/amiberry.sh, scriptmodules/emulators/uae4arm/uae4arm.sh
* add lha extension
* adjust launch script to use new -autowhdload parameter
* rework whdboot folder set-up
=> amiberry - add support for whdload auto-load - #2327

scriptmodules/supplementary/esthemes.sh
Namely:
- retrorama: https://www.youtube.com/watch?v=xZo3tmqqkhM
- strangerstuff: https://www.youtube.com/watch?v=Avtqd0lthMg
- spaceoddity: https://www.youtube.com/watch?v=HixjBvEzx7w
- swineapple: https://www.youtube.com/watch?v=inCWJwXr6B0
=> added some lipebello's themes

scriptmodules/ports/cgenius.sh
I hope it is okay this time. I hard synched my fork against your repo and now just one local commit. If that's not okay, let me know how you want to have it squash...
=> Version update

scriptmodules/supplementary/scraper.sh
This PR adds option to download screenshots instead of box art for
Steven Selph's scraper.
=> Steven Selph's scraper: prefer screenshots

scriptmodules/emulators/ppsspp.sh
=> PPSSPP - Fix typo on fullscreen option for tinker.

scriptmodules/libretrocores/lr-np2kai.sh
Follow-up to issue #2404.  Setup script for a modified version of Neko Project 2 ported to libretro.
=> Added lr-np2kai script.

scriptmodules/ports/bombermaaan.sh
I would like if you could add this port to retropie experimental for others to install and test.
=> Added bombermaaan.sh script.

scriptmodules/libretrocores/lr-redream.sh
=> added lr-redream dreamcast emulator to experimental

scriptmodules/libretrocores/lr-dolphin.sh
=> added lr-dolphin to experimental (for x86/x86_64)

scriptmodules/helpers.sh, scriptmodules/libretrocores/lr-nxengine.sh
@hhromic I was thinking to just to it like this - simplifies it I think.
=> addPort - remove script parameter and handle in scriptmodule

scriptmodules/supplementary/esthemes.sh
Added 1 ES theme called SuperSweet
=> Update esthemes.sh with new a theme

scriptmodules/supplementary/esthemes.sh
=> Update esthemes.sh with new Donkey Konkey Theme

scriptmodules/supplementary/emulationstation.sh
=> escape $ inside heredoc

scriptmodules/supplementary/esthemes.sh
A new ES theme called SnapBack
=> Update esthemes.sh with new SnapBack Theme

scriptmodules/supplementary/esthemes.sh
=> Update esthemes.sh with new He-Man Theme

scriptmodules/supplementary/skyscraper.sh
Based on the conversation on the previous `skyscraper` PR by @muldjord and @hhromic.
* Fix the editing in advanced configuration by providing STDOUT/STDIN for console editors (e.g nano/vim) and running the editor as `$user`.
* Disable output buffering during the scraping session (
* Use the Skyscraper shipped configuration file (config.ini.example) as a started config file.
* Add some optimizations suggested in the previous PR #2520 by @hhromic.
=> Fixes and optimizations for the Skyscraper scriptmodule

scriptmodules/libretrocores/lr-mupen64plus.sh, scriptmodules/libretrocores/lr-mupen64plus/01_new_lib_names.diff, scriptmodules/libretrocores/lr-mupen64plus/02_fix_build.diff
Tested and building fine now. Fixes #2544
=> lr-mupen64plus - add patch from @psyke83 to fix broken build and refresh existing patch

scriptmodules/supplementary/esthemes.sh
=> Update esthemes.sh with new Batman Theme

scriptmodules/ports/steamlink.sh
Currently for RPI 3+ only.
See: https://steamcommunity.com/app/353380/discussions/0/1743353164093954254/
=> Add steamlink to ports

scriptmodules/emulators/ppsspp.sh, scriptmodules/emulators/residualvm.sh, scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/scummvm.sh, scriptmodules/emulators/stella.sh, scriptmodules/helpers.sh, scriptmodules/ports/cdogs-sdl.sh, scriptmodules/ports/openblok.sh, scriptmodules/ports/openttd.sh, scriptmodules/ports/zdoom.sh, scriptmodules/supplementary/mehstation.sh
create ~/.config ~/.local ~/.local/share folder used by some modules @psyke83
=> Home folders

scriptmodules/ports/steamlink.sh
* update dependencies
* update directory locations for new version
=> steamlink: update script for 1.0.7

scriptmodules/ports/steamlink.sh
When steamlink is launched without a running Xorg server,
DualShock controllers erroneously act as both a gamepad and virtual
mouse, which causes major input conflicts in-game.
Launching from an Xorg session fixes this issue, but steamlink also
requires a window manager running in order to set the window focus
property (to allow joystick events to be processed).
Additional changes:
* switch to repository version of steamlink package
* update Help text to reflect new onscreen welcome message
* remove overscan override (issue fixed upstream).
=> steamlink: switch to xinit+matchbox session & misc updates

scriptmodules/supplementary/skyscraper.sh
Prepare for the 3.x verion of **Skyscraper**, which has some notable changes for scraping - most important one being that scrape/gather of resources (artwork, info) and gamelist generation are separate actions, so they need to be run separately.
I refactored the GUI to make sure that scraping and gamelist generation are 2 separate actions and moved back (to sub-menus) the options for scraping and game list generation. Overview of changes:
1. UI Refactoring and additions.
* Added sections for gathering and game list generations, each with actions and options
* Added a separate section for advanced options and moved them back from the main menu
* Added editing of the `aliasMap.csv` file (introduced in the 2.x series)
* Added an update action - similar to the one in the `scraper` module. …
=> Modifications for Skyscraper 3.x release; fix reported issued

scriptmodules/supplementary/bluetooth.sh
All changes are compatible with Raspbian stretch's default
BlueZ version.
bluez_cmd_bluetooth:
* enable default-agent during general scan
* fix compatibility with BlueZ 5.50-1 userspace tools
* improved reliability when sending multiple commands
sixaxis:
* ensure both authorization & trust is performed to account for
different BlueZ behaviour between versions
* force-disconnect Bluetooth connection upon first registration to
avoid controller hang caused by USB input claim conflict
general:
* increase scan time to 20 seconds
* silence sixad messages
=> bluetooth: improve BlueZ 5.50+ & sixaxis compatibility

platforms.cfg, scriptmodules/libretrocores/lr-freechaf.sh
=> add freechaf scriptmodule to libretrocores

scriptmodules/helpers.sh, scriptmodules/supplementary/custombluez.sh, scriptmodules/supplementary/customhidsony.sh
Small updates to resolve issues noticed on Ubuntu 18.10.
=> Ubuntu-related fixes

scriptmodules/helpers.sh, scriptmodules/supplementary/customhidsony.sh, scriptmodules/supplementary/mkarcadejoystick.sh, scriptmodules/supplementary/xpad.sh
This might cause issues due to unexpected module rebuilds on script update.
=> dkmsManager: remove update_hook

scriptmodules/supplementary/bashwelcometweak.sh
Just a small PR. Display the time in the locale of the retropie user.
=> Makes time display 12h/24h according to locale in motd greeter

scriptmodules/supplementary/bluetooth.sh
Ensure that bluetoothctl will never cause the script to hang due to
infinitely repeating status change messages.
Also reduce timeout to 15 seconds and clarify DualShock instructions;
the PS button needs to be pressed if the controller is still scanning
during cable connect to ensure it binds to the USB connection.
=> WIP: bluetooth: improve scan timeout functionality

scriptmodules/supplementary/pegasus-fe.sh
There is now a Raspberry Pi 3-optimized build of Pegasus, which might provide improved performance.
=> pegasus-fe: Added Raspberry Pi 3 release

scriptmodules/emulators/dosbox.sh, scriptmodules/emulators/dosbox/01-fully-bindable-joystick.diff
Patch via: https://www.vogons.org/viewtopic.php?f=32&t=27452&p=314840
Should resolve #2643.
=> dosbox: update to SVN 4194 with joystick patch

scriptmodules/emulators/xroar.sh
It should resolve retropie/retropie-setup#2657.
=> xroar: update to 0.35.4

scriptmodules/supplementary/gamecondriver.sh
As reported in [the forum](https://retropie.org.uk/forum/topic/22384/), the `gamecondriver` package doesn't build in Kernels 4.15+ due to the deprecation of the `setup_timer` function. This affects the new Linux Kernel included in Raspbian Stretch, which has been upgraded to the 4.19.x stable branch (and will likely be the base for the upcoming Raspbian Buster release).
I added a fix for both modules (a few lines) and submitted them upstream:
* https://github.com/marqs85/gamecon_gpio_rpi, accepted in https://github.com/marqs85/gamecon_gpio_rpi/pull/2
* https://github.com/marqs85/db9_gpio_rpi, accepted in https://github.com/marqs85/db9_gpio_rpi/pull/4
The modification to the `gamecondriver` change the source of the package to the Github repositories and - consequently - the …
=> gamecondriver: update the scriptmodule for kernels 4.15+

platforms.cfg
Fix slip-ul in `platforms.cfg`.
=> psx: really add CHD as extension

scriptmodules/supplementary/controlblock.sh, scriptmodules/supplementary/powerblock.sh
I have added the wiring package as dependency to the PowerBlock and ControlBlock modules. Their corresponding drivers have had an update recently.
=> Added wiringpo as dependency to controlblock and powerblock modules.

scriptmodules/supplementary/raspbiantools.sh
* there are additional issues with the newer kernel including overscan problems
* add option to pass parameter to apt-mark to hold/unhold and hold downgraded packages
=> raspbiantools - downgrade kernel/firmware instead for stretch bt fix

scriptmodules/ports/yquake2.sh, scriptmodules/supplementary/runcommand/runcommand.sh
* add variable replacement to pass framebuffer x/y res
* update yquake2 for fkms targets
=> runcommand KMS x/y res support & yquake2 update

scriptmodules/emulators/ags.sh, scriptmodules/emulators/zesarux.sh, scriptmodules/ports/cannonball.sh, scriptmodules/ports/darkplaces-quake.sh, scriptmodules/ports/steamlink.sh, scriptmodules/ports/tyrquake.sh, scriptmodules/ports/wolf4sdl.sh
Cannonball works fullspeed; tyrquake is not quite fullspeed (GL at native res), but it's not too bad.
=> More FKMS updates

scriptmodules/supplementary/esthemes.sh
(With permission), we'd like to add Super Retroboy theme by @KALEL1981 (Travis Willson).
For 4:3 aspect, small screen devices.  More info about the theme is here: https://retropie.org.uk/forum/topic/23116/retroflag-gpi-small-screen-super-retroboy-theme
=> Add Super Retroboy theme by Travis Willson

scriptmodules/supplementary/sdl2.sh
All targets now use a unified branch that builds for any target.
Branch:
* Based on 2.0.10 upstream
* All custom patches have been imported, but any changes to default build via
debian/rules have been removed.
* Includes fixes for RPI3 regression in SDL_EGL_ChooseConfig, segfault on joystick
disconnect, RPI + kmsdrm coexistence.
Scriptmodule:
* All driver selection is done via script
* Raspberry Pi: build with RPI and KMSDRM driver together
* X11 & GL support is enabled by default; useful for FKMS, and GLES2 targets
via gl4es translation library.
=> sdl2: consolidate branches and update to 2.0.10

scriptmodules/libretrocores/lr-flycast.sh
see https://github.com/libretro/flycast/blob/master/Makefile#L166
=> Flycast has different compile options for Raspberry Pi 4

scriptmodules/supplementary/retropie-manager.sh
=> retropie-manager: update rp_module_licence link

scriptmodules/libretrocores/lr-yabause.sh
This should fix building from source since the repository was re-organised.
=> lr-yabause - fix building with the new repository structure

scriptmodules/supplementary/esthemes.sh
'Meshy' and 'Magazine Madness 2'
=> Update esthemes.sh with 2 new themes

scriptmodules/emulators/xroar.sh, scriptmodules/helpers.sh
* use a depth of 0 for xroar to do a full depth clone as the repository doesn't support shallow cloning
=> helpers / gitPullOrClone - add a depth parameter and default to shallow cloning - #2678

scriptmodules/supplementary/esthemes.sh
=> Update esthemes.sh with 1 new theme

scriptmodules/ports/uqm.sh
* bump version to 0.6.2.dfsg-9.5 (build fix)
* enable kms support
=> uqm: buster build fix & kms support

scriptmodules/supplementary/esthemes.sh
New theme is called 'uniflyered'
=> Updated esthemes.sh with 1 new theme

platforms.cfg
title says all. i tested and worked with some stock .hdm files.
=> add .hdm for x68000

scriptmodules/supplementary/sdl2.sh
This should ensure that an installation of SDL2 from binary on a fresh
installation should not fail due to missing dependencies not being
installed by the debian packages themselves.
Certain board-specific packages that may cause distribution dependency
resolution issues are deliberately omitted, but they should already be
installed (if not, we can do so during script first-time run or basic
install).
Some dependencies have also been reordered to be more consistent with our
board flags; x11 depends are still a mess, but reordering them may
break vero4k.
=> sdl2: add dependencies to debian packages

scriptmodules/ports/cgenius.sh
Added libsdl2-ttf-dev
The library is required to be able to successfully compile it
=> cgenius - Fix Dependences

scriptmodules/supplementary/esthemes.sh
=> Update esthemes.sh with one new theme

scriptmodules/emulators/atari800.sh, scriptmodules/emulators/gngeopi.sh, scriptmodules/emulators/zesarux.sh, scriptmodules/libretrocores/lr-4do.sh, scriptmodules/libretrocores/lr-81.sh, scriptmodules/libretrocores/lr-fmsx.sh, scriptmodules/libretrocores/lr-mupen64plus-next.sh, scriptmodules/libretrocores/lr-np2kai.sh, scriptmodules/libretrocores/lr-puae.sh, scriptmodules/libretrocores/lr-quasi88.sh, scriptmodules/libretrocores/lr-quicknes.sh, scriptmodules/libretrocores/lr-snes9x.sh, scriptmodules/libretrocores/lr-vba-next.sh, scriptmodules/ports/bombermaaan.sh, scriptmodules/ports/giana.sh, scriptmodules/ports/ioquake3.sh, scriptmodules/ports/kodi.sh, scriptmodules/ports/openttd.sh, scriptmodules/ports/splitwolf.sh, scriptmodules/supplementary/controlblock.sh, scriptmodules/supplementary/golang.sh, scriptmodules/supplementary/xarcade2jstick.sh
Adds license for a few packages that didn't have it at all, updates the links to the 'raw' page of the licenses for Github bases repositories and corrected a few links that were not longer available.
=> licenses: update/add links for a few scriptmodules

scriptmodules/supplementary/esthemes.sh
added my theme, ran installer & installed my theme with it.  works like a charm.
form post: https://retropie.org.uk/forum/topic/24277/my-clean-simple-240p-es-theme-retrocrt?_=1576294475190
=> adding RetroCRT 240p theme

scriptmodules/supplementary/esthemes.sh
I've created a vertical version of my 240p theme
https://retropie.org.uk/forum/topic/24315/my-clean-simple-vertical-240p-theme-retrocrt-240p-vertical?_=1576606722076
=> Adding xovox/es-theme-RetroCRT-240p-Vertical

scriptmodules/admin/stats.sh, scriptmodules/packages.sh, scriptmodules/supplementary/resetromdirs.sh
Fixes the package coverage for the stats
@mmatyas
=> Stats fixes

scriptmodules/supplementary/bluetooth.sh
Before when looking for devices to pair with, previously registered devices could be shown
which can make it confusing with multiple gamepads with the same name as to which to add
=> bluetooth - only show unregistered devices when scanning to simplify use

scriptmodules/emulators/atari800.sh, scriptmodules/emulators/atari800/01_rpi_fixes.diff, scriptmodules/emulators/atari800/atari800.sh
* added automake dependency
* update patch - we only change the compiler name to gcc now
=> atari800 - switch to using github repo and update to v4.1.0

scriptmodules/emulators/atari800.sh, scriptmodules/emulators/gngeopi.sh, scriptmodules/emulators/zesarux.sh, scriptmodules/libretrocores/lr-4do.sh, scriptmodules/libretrocores/lr-81.sh, scriptmodules/libretrocores/lr-fmsx.sh, scriptmodules/libretrocores/lr-mupen64plus-next.sh, scriptmodules/libretrocores/lr-np2kai.sh, scriptmodules/libretrocores/lr-puae.sh, scriptmodules/libretrocores/lr-quasi88.sh, scriptmodules/libretrocores/lr-quicknes.sh, scriptmodules/libretrocores/lr-snes9x.sh, scriptmodules/libretrocores/lr-vba-next.sh, scriptmodules/ports/bombermaaan.sh, scriptmodules/ports/giana.sh, scriptmodules/ports/ioquake3.sh, scriptmodules/ports/kodi.sh, scriptmodules/ports/openttd.sh, scriptmodules/ports/splitwolf.sh, scriptmodules/supplementary/controlblock.sh, scriptmodules/supplementary/golang.sh, scriptmodules/supplementary/xarcade2jstick.sh
Reverts RetroPie/RetroPie-Setup#2916
This should have been done against master. Please feel free to do a new PR. Easier to revert and redo than cherry pick and fix conflicts merging back to master.
=> Revert "licenses: update/add links for a few scriptmodules"

scriptmodules/ports/vvvvvv.sh
A few sources take a long time to compile with -O2 btw. Limited testing but it works.
=> added VVVVVV to ports

scriptmodules/emulators/retroarch.sh, scriptmodules/libretrocores/lr-mupen64plus-next.sh, scriptmodules/libretrocores/lr-mupen64plus.sh, scriptmodules/libretrocores/lr-mupen64plus/0002-rpi-gles3.patch
Enabled gles3 for Ra / mupen64 plus libretro cores
Needs testing etc. Feedback welcome.
=> Rpi4 gles3

scriptmodules/libretrocores/lr-xrick.sh, scriptmodules/ports/xrick.sh
* rework xrick to work with libretro core
* remove data.zip from xrick due to licence uncertainty
* various module cleanups
=> lr-xrick - added libretro core

scriptmodules/libretrocores/lr-parallel-n64.sh
* use videocore in logic rather than rpi
* add -DARM_FIX to fix building on arm with arm dynarec
* switch to upstream master
=> lr-parallel-n64 - fix building from latest upstream code

scriptmodules/emulators/mupen64plus.sh, scriptmodules/libretrocores/lr-flycast.sh, scriptmodules/libretrocores/lr-genesis-plus-gx.sh, scriptmodules/libretrocores/lr-mupen64plus-next.sh, scriptmodules/libretrocores/lr-parallel-n64.sh, scriptmodules/libretrocores/lr-picodrive.sh, scriptmodules/libretrocores/lr-snes9x.sh, scriptmodules/libretrocores/lr-snes9x2010.sh, scriptmodules/ports/ioquake3.sh, scriptmodules/supplementary/skyscraper.sh
Some of these have been discussed in #2961 
Ive done it slightly differently but some of these are better defaults.
Im considering moving all n64 to optional also. Will make it easier for users to make a considered choice imho.
=> Package moves

platforms.cfg, scriptmodules/emulators/redream.sh
=> redream - added redream emulator to experimental packages

scriptmodules/admin/setup.sh
Minor change. Might as well have platform in here.
=> setup - show platform in main RetroPie-Setup menu header

scriptmodules/emulators/dosbox-sdl2.sh, scriptmodules/emulators/mupen64plus.sh, scriptmodules/emulators/reicast.sh, scriptmodules/helpers.sh, scriptmodules/system.sh
Addresses Issue #2943 more appropriately.
=> Advertise Vero4K as a Mali platform

scriptmodules/admin/builder.sh, scriptmodules/helpers.sh, scriptmodules/system.sh
Reorganisation of system splitting out some code into functions
__jobs var with a simple default based on memory and nproc
Set MAKEFLAGS -jX based on this
some memory var changes
Rework of all compiler flag logic
=> System reorg

scriptmodules/helpers.sh, scriptmodules/packages.sh
=> Get depends rework

scriptmodules/admin/setup.sh, scriptmodules/emulators/drastic.sh, scriptmodules/emulators/redream.sh, scriptmodules/packages.sh
Basic support for remembering how a package was installed to update in the same manner.
=> Initial pkg info

scriptmodules/supplementary/esthemes.sh
Add the Clean theme that I recently released: https://github.com/dionmunk/es-theme-clean
=> Add [Theme] Clean

scriptmodules/supplementary/esthemes.sh
=> Added theme EpicNoir

scriptmodules/supplementary/esthemes.sh
Should replace #3114. 
Theme added with author's permission (https://retropie.org.uk/forum/topic/25313/).
=> esthemes: new theme from @AndreaMav

scriptmodules/emulators/retroarch.sh, scriptmodules/emulators/retroarch/01_hotkey_hack.diff, scriptmodules/emulators/retroarch/02_disable_search.diff, scriptmodules/emulators/retroarch/03_shader_path_config_enable.diff
Tested on RPI3 Buster (Thanks @hhromic), and PC with Ubuntu 20.04
Will test on RPI4 and merge if all good (and update assets)
=> retroarch - update to v1.8.6 and rebase/rework patches

scriptmodules/helpers.sh, scriptmodules/ports/kodi.sh
Logic fixes for removing systems / ports
=> Del system fixes

scriptmodules/supplementary/xpadneo.sh
Threw this together. I've seen this driver mentioned on the forums a few times. Untested.
=> added xpadneo - linux driver for xbox one wireless gamepads

platforms.cfg, scriptmodules/emulators/hatari.sh, scriptmodules/libretrocores/lr-hatari.sh
* update module help to include bios information
It's tested working but perhaps our default config/launchers need to be revisited as a fair amount may have changed.
=> hatari - switch to git repository (v2.2.1) and symlink bios (tos.img)

scriptmodules/supplementary/skyscraper.sh
A user requested the '--flags onlymissing' option to be available in the RetroPie Skyscraper script. This PR adds it to the GATHER menu. Tested working.
=> Added '--onlymissing' option to GATHER options

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, README.md, scriptmodules/supplementary/retropiemenu.sh, scriptmodules/supplementary/wifi.sh
Fixed up some original GitHub wiki URLs to point at the new Docs site, plus a few grammar improvements.
=> Reword wiki references to docs site

scriptmodules/emulators/drastic.sh
_DraStic_ has input problems when running in a KMS context, reported a few times in the forums.
There is a workaround by running it a X11 session, with a minimal window manager (similar to Steam Link). 
Tested on a PI3 (Stretch) and PI4 (Buster), I don't know if the bug is present on Pi3 (Buster) with the legacy BRCM drivers
=> drastic: workaround faulty input handling in a KMS context

scriptmodules/supplementary/runcommand/runcommand.sh
Translate bash logic to one awk call
=> runcommand.sh: get_all_x11_modes speedup.

scriptmodules/supplementary/xpadneo.sh
=> xpadneo: bump version to v0.9

scriptmodules/supplementary/skyscraper.sh
remove two tabs
de-duplicate version dialog warning
remove updating (but leave in checking / reporting a new version)
=> Skyscraper tweaks

scriptmodules/libretrocores/lr-fbneo.sh
=> FBNeo 0.2.97.44 is no longer the latest version

scriptmodules/helpers.sh
Modified the `dkmsManager` function to account for cases when the running
kernel is replaced before the module installation, so `dkms` cannot build the module.
If the module cannot be built for the running kernel version, then instruct `dkms` to build
for the installed kernels that have a valid `build` folder/symlink present.
Installations performed under a 'chroot' are also handled with the new additions,
so there is no need for separate handling.
This covers situations when the user does an upgrade of the distro's packages and
RetroPie's drivers at the same time. Raspberry Pi OS replaces the current kernel
and the kernel headers for the running version are no longer found, so the driver(s) installed
are not updated from their scriptmodule by `dkmsManager`.
As a side note, Raspberry Pi …
=> helpers: improve DKMS module installation

platforms.cfg, scriptmodules/libretrocores/lr-dosbox-pure.sh
Have done limited testing. Put together quickly so need to do some more work (module based off lr-dosbox which was pretty basic).
=> Lr dosbox pure

scriptmodules/supplementary/esthemes.sh
=> esthemes: 2 more themes from @lipebello

scriptmodules/ports/cgenius.sh
* Bug fixes
* GUI, sound and controller improvements.
* Boost is no longer required, replaced with TinyXML2.
* Python scripting engine replaced with Lua (included).
=> cgenius: update to the latest stable version

scriptmodules/packages.sh
When the remote repository uses an annotated Git tag, the real commit is found
by looking for the "tag^{}" reference, since the the tag ref will point to the
tag object itself, instead of the tagged commit. See gitrevisions(7).
=> packages - handle git repositories with two tag references

scriptmodules/libretrocores/lr-xrick.sh
Fixed a typo :slightly_smiling_face:
=> fixed typo in description for lr-xrick

platforms.cfg, scriptmodules/libretrocores/lr-flycast.sh
See https://github.com/libretro/flycast/blob/master/core/libretro/libretro.cpp#L2257
=> dreamcast: Added .m3u support for lr-flycast

scriptmodules/system.sh
Also fix a bug with the generic-x11 platform not using an array for __platform_flags
=> system - split out platforms configuration to simplify code

scriptmodules/supplementary/esthemes.sh
https://github.com/cjonasw/raspixel-320-240
=> Add Raspixel 320x240 theme

scriptmodules/libretrocores/lr-duckstation.sh
~~**WIP**~~
Adding sensible defaults as users test this experimental core.
(testing seems to be have dried up for now - ready for review)
=> lr-duckstation: improve core option defaults

scriptmodules/libretrocores/lr-vice.sh
* added x64sc, x128, xpet, xplus4 and xvic on top of the default x64
=> lr-vice - added additional targets to lr-vice

scriptmodules/admin/setup.sh
Add inst menu, for managing of all installed packages in a single list
Add all menu, for managing of all packages in a single list
Wrote this a month ago and need to go over it. I was planning on some other menus too, but I'll leave this here - interested if additional ways to manage packages like this is useful.
=> setup - add additional packaging menus

platforms.cfg, scriptmodules/libretrocores/lr-retro8.sh
Here is my pull-request for adding PICO-8 to the RetroPie-Setup
=> Add libretro module script for pico8

scriptmodules/supplementary/esthemes.sh
New theme is called synthy16x9
=> Update esthemes.sh with new theme

scriptmodules/admin/joy2key/joy2key_sdl.py
* Added a local fix for a crash when using older Python and Py-SDL2 versions.
Upstream bug: https://github.com/marcusva/py-sdl2/issues/75.
Upstream fixed the issue, but older distros (Ubuntu 18.04 based) don't have an updated `python3-sdl2` package.
* It seems that initializing the video is not really required for the joystick subsystem to work.
On newer SDL versions (tested with 2.0.16), initialization will fail with video added if the video cannot be initialized.
This prevents starting `joy2key_sdl.py` if ES is already started or trying to run it headless (i.e. no KMS/X available).
While this is not a use case we're covering, it's better to remove the video initialization if it's not needed.
=> joy2key: fix crash on older pythons/py-sdl2 and init update

scriptmodules/supplementary/esthemes.sh
The theme is called NeonFantasy
=> Update esthemes.sh with 1x theme

scriptmodules/libretrocores/lr-tyrquake.sh
=> lr-tyrquake: update licensing file

scriptmodules/ports/srb2.sh
required to compile on Ubuntu 21.10
=> updated srb2 to latest release

scriptmodules/emulators/scummvm.sh
Changes in 2.5.1:
* Added scalers in OpenGL mode
* Fixed several bugs in The Lost Files of Sherlock Holmes
* Made the sound for Sam & Max more accurate
* Improved graphics for some Macintosh SCUMM games
* Implemented more renderers for The Longest Journey
* Many enhancements added to Little Big Adventure
* Fixed the dreaded bug on World of Xeen startup
=> scummvm: update to version 2.5.1

scriptmodules/emulators/yabasanshiro.sh
Setup script for YabaSanshiro SEGA Saturn emulator.
This is instruction video.
https://youtu.be/tgiJdss_sgQ
=> Yabasanshiro origin

scriptmodules/ports/wolf4sdl.sh
Additional mission 3 checksum for installation media: "Spear of Destiny - Super CD Pack"
=> wolf4sdl: (bug) additional checksum for registered version game data

scriptmodules/supplementary/esthemes.sh
Theme is called ShadowClean and is suited for 16:9 monitors
=> Update esthemes.sh with a new theme

scriptmodules/supplementary/esthemes.sh
=> Update to esthemes.sh with 1 new theme

scriptmodules/ports/supertux.sh
=> supertux.sh: (QOL) remove 171 MB game data

scriptmodules/supplementary/esthemes.sh
adding another of my themes, far prettier than the others <3
=> es-themes-RetroCRT-240p-Rainbow

scriptmodules/libretrocores/lr-puae2021.sh
A version from 2021 (v2.6.1), before the core was updated from upstream to v4.5.x which brought more accuracy, but slower performance.
=> Added lr-puae2021

scriptmodules/ports/alephone.sh
(Unless using old-version game engine, then use old-version data too.)
=> alephone (update): Use latest version game data.

scriptmodules/libretrocores/lr-flycast.sh
Ref: https://github.com/RetroPie/RetroPie-Setup/pull/3517
(Revisited for `defaultRAConfig`)
=> lr-flycast: (QOL) add to Arcade system (redux)

scriptmodules/supplementary/splashscreen.sh
Updated wording to remove ambiguity.
Slightly reworked randomizer function.
Added mode label (custom, etc.) to randomizer menu title.
Fixed path dialog on randomizer choices.
Disable randomizer upon selecting default splashscreen.
=> splashscreen.sh: (QOL) updated menu interface

scriptmodules/supplementary/xpadneo.sh
This is a maintenance release, fixing the Xbox button for SDL apps using the Gamecontroller API.
=> xpadneo: upgrade to v0.9.3

scriptmodules/emulators/simcoupe.sh
Updated the default branch, since upstream changed the project repository's default to 'main'.
Since the `cmake` requirements have been bumped to 3.14 some time ago, select the closest tag before the change in order to fix building on Ubuntu 18.04.
Note also that current code requires C++17 'filesystem' support, which is not present in Ubuntu 18.04.
As an aside, the reason for the `cmake` upgrade was the support for _FetchContent_. Dependencies are now downloaded at build time, so we'll be able to remove the `libspectrum-dev` dependency at some point, when removing support for older `cmake` versions.
=> simcoupe: update the branch selection to fix building

scriptmodules/libretrocores/lr-flycast.sh
Not sure if the similar Odroid-C2 would be needing this.  Unable to test.
=> Fix lr-flycast build on Vero4k

scriptmodules/supplementary/esthemes.sh
PopCom16x9 suited for 16:9 ratio screens. PopCom5x4 suited for 5:4 (or Arcade1UP) screens.
=> Updated esthemes.sh with 2 new themes

scriptmodules/supplementary/esthemes.sh
Adding theme: https://github.com/leochely/es-theme-Guilty-Gear
I posted some images of the theme in this post:  https://retropie.org.uk/forum/topic/32415/guilty-gear-es-theme/3
=> Adding Guilty Gear ES Theme

scriptmodules/supplementary/scraper.sh, scriptmodules/supplementary/scraper/00-fix-screenscraper-response-parsing-265.diff
Added the patch from @Torben2000 [1] which fixes scraping from the ScreenScraper source.
Can be removed when/if upstream (@sselph) accepts the changes in the main repository.
[1] https://github.com/sselph/scraper/pull/265
=> scraper: fix scraping from ScreenScraper.fr

scriptmodules/emulators/ppsspp.sh
Changelog:
* Version 1.13.2
- Crashfix on Android 12 when playing certain background music ([#15990])
- Fix Star Ocean battles in D3D backends (#[15889])
- Minor fixes that might fix some other crashes
* Version 1.13.1
- Confirmation dialog added before change of MAC address (#15738) 
- IR interpreter regression fixed (#15739) 
- Fix clearing of replacement texture cache (#15740) 
- Improved Portuguese-pt translation (#15734) - Fix graphical regression in Split/Second (#15733) - Couple of minor crash fixes
* Version 1.13
- Analog mapping for fast-forward (#15645)
- Major softgpu accuracy fixes and speedups, including a JIT (#15163, #15345, #15389, #15529, #15440, #15410, #15405, #15400) and many, many more - Fixed some NEON code paths (#15481) - Fix performance of texture uploads with …
=> ppsspp: update to 1.13.2

scriptmodules/system.sh
change logic to avoid running the sysfs tests in a chroot
=> system - use kms on bullseye or newer when building in chroot

scriptmodules/emulators/pcsx2.sh
* The Ubuntu PPA has 64bit packages for some time, now defaulting to 64bit only for recent 22.04 and newer. Modified the module to take this into account and install the 64bit package when available.
* The new PCSX2 versions have a QT UI by default and the PPA installs it automatically. The parameters and commands are different from the previous WXWidgets based versions, so configuration detects the version installed and sets the correct commands for both versions.
=> pcsx2: fix installation and configuration for recent 1.7 packages

scriptmodules/ports/cgenius.sh
Updated to the latest stable version (3.2.0), with mostly bugfixes and stability changes.
Scriptmodule changes:
* changed the build to be in a separate folder
* removed the install prefix since it's unused
* removed the `gcc` workaround since it's not needed anymore
* added a minimal config to configure the games location
* removed the gamesdir symlink, not needed with the above modifications. Should prevent copying errors when backing up the SMB folders since the `games` config sub-folder was a symlink outside the `config` share.
=> cgenius: upgrade to 3.2.0 & misc module improvements

scriptmodules/emulators/hypseus.sh
New feature added in https://github.com/DirtBagXon/hypseus-singe/commit/a71cfe7cb92e04b37bb2d9cc627f8456c0137809
Shown in: https://retropie.org.uk/forum/post/285690
=> hypseus: Add new bezels folder

scriptmodules/emulators/yabasanshiro.sh
Update from version 1.5.0 to version 1.9.0. Sonic R shows no glitches in the title screen anymore.
=> yabasanshiro: update to version 1.9.0

scriptmodules/supplementary/raspbiantools.sh
Add an option which enables ZRAM. ZRAM will which can hold up to 50% of the physical ram.
Compressed memory (ZRAM) can be used with low memory embedded devices. ZRAM has compression ratio of up to 4:1. 256MB of physical memory can store up to 1024MB. It is only used if free memory is getting low. It is much faster than disk swapping. It also prevents linux from using disk swap until ZRAM is full.
https://wiki.debian.org/ZRam
https://haydenjames.io/raspberry-pi-performance-add-zram-kernel-parameters/
Tested with a 2GB Raspberry Pi 4, emulationstation, some retroarch cores and some memory intensive source builds.
=> raspbiantools: Add option to enable compressed memory (ZRAM)

scriptmodules/emulators/vice.sh
Tested on RPI 4 with no issues found so far.
Sound issues mentioned in commit 81fc3a964b79d321285e4e3560a7eb80f3a35270 were not observed by myself so far with that version.
=> vice - switch to v3.7.1 release

scriptmodules/supplementary/runcommand/runcommand.sh
Fix https://github.com/RetroPie/RetroPie-Setup/issues/3563.
=> runcommand.sh: suppress framebuffer garbage

scriptmodules/admin/crosscomp.sh
Instead of switch_distcc to change the default distcc daemon to point to an installed cross compiler,
it now has a configure_distcc function that allows configuring additional distcc daemons on different ports.
$md_inst/bin is no longer used. Symlinks for cc/gcc/c++/g++ are now made in the $md_inst/$dist/bin folders where the cross compiler binaries are installed.
Example usage:
./retropie_packages.sh crosscomp configure_distcc buster 3633
Will configure a /etc/init.d/distcc-buster script (copied from /etc/init.d/distcc) on port 3633. The logging will be in /var/log/distcc-buster.log. The /etc/default/distcc config is still used by all daemons.
This is used to allow multiple daemons for RPI buster / bullseye cross compiling (Which I use for building the distribution binaries)
=> crosscomp - allow configuration of multiple distcc daemons

scriptmodules/libretrocores/lr-scummvm.sh
Upstream changed the Makefile variable, add it also here.
=> lr-scummvm: M32 emulation build change

scriptmodules/emulators/stella.sh
Fixes building on GCC 10+ (The configure script bailed out on GCC 10+ on 6.0.1 which is from 2019)
Changelog since 6.0.1 copied from https://stella-emu.github.io/changelog.html
Stella release 6.7 for Linux, macOS and Windows is now available.
* **IMPORTANT NOTES:**
* Because of fixes to JSON handling, all remappings will be reset to defaults; if you had custom mappings, they will need to be re-entered again.
* Because of internal changes, all state files are now invalid.
* Completely reworked the file launcher:
* Redesigned user interface
* Added tracking of user favorites, recently played and most popular games
* Added virtual directories for selecting tracked games
* Added quick path navigation
* Added navigation history
* Added icons for files and directories
* Added option to …
=> stella - update to version 6.7

scriptmodules/system.sh
=> system - enable binaries for Raspberry Pi OS 11 (bullseye)

scriptmodules/ports/ioquake3.sh
=> ioquake3: fix install target detection for aarch64

scriptmodules/emulators/ags.sh
As discussed in the forum: https://retropie.org.uk/forum/topic/33969/adventuregamestudio-ags-scriptmodule-updates
Maybe you should wait until AGS 3.6.0 is final before merging.
Again: Thanks for all the advise for the scriptmodule.
=> Updates for next AGS release (v3.6.0)

scriptmodules/supplementary/audiosettings.sh
Needed for configurations using the 'vc4-kms-v3d' overlay on Pi3/Pi4.
The names are (almost) similar, but the default order of the cards is different:
* (fkms) the order is HDMI 1[+2], Headphones
* (kms)  the order is Headphones, HDMI 0[1] (!)
We may have to add a function to set the HDMI0 port as default, let's wait for Bullseye to land and check then.
=> audiosettings: support the ARM-side HDMI driver

scriptmodules/admin/image.sh
Raspberry PI OS images have added a first-boot wizard to change the default username/password [1]. In order to skip this step and keep the (former) default username 'pi', add a 'userconf.txt' to preset the info needed for the default user.
[1] https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022
=> image: pre-set the default user on RPI OS (11)

scriptmodules/emulators/zesarux.sh
10 years aniversary edition !
*    Improvements in Network Gaming: Allow to connect more than two hosts (up to 16) and the flash state is sync between al instances. Keep in mind that this ZEsarUX feature allows to play any emulated game at the same time with many friends, every one at his house and connected to Internet. It works for all emulated games, you don't have to modify the games
*    Amstra PCW improvements: Added PCW colour modes (4 or 16 colours) and added PCW Joysticks support: Kempston, Cascade, DKTronics, OPQASpace
*    Text Adventure improvements: Use artificial intelligence (OpenAI) to get realistic images for location description text. Also, added GAC support on Adventure Map and Debug Adventure
*    AY Player improvements: Added playlist management, allow shuffle mode, …
=> zesaux: upgrade to version X (10.10)

scriptmodules/admin/builder.sh, scriptmodules/admin/image.sh, scriptmodules/admin/image/dists/rpios-stretch.ini
Builder/Image changes to align the builder module with the new image module changes
=> Chroot builder changes

scriptmodules/system.sh
Add __os_debian_ver="12" for LMDE6
=> LMDE6 Support

scriptmodules/supplementary/wifi.sh
Added support for NetworkManager and predictable network interface device names. NetworkManager is default on RaspiOS 12 and also on Armbian. Armbian doesn't disable the predictable ifnames, so the changes here will help adding support for configuring WiFi on it.
Changes included:
- interface name is not hardcoded to 'wlan0', but taken from `/sys/net/devices`. Most of the functions had to be modified and an extra parameter for ifname was added.
- config/remove wifi functions have been added for each management version (wpasupplicant/nm)
- tweaked the interface in a few places (colors, title, phrasing)
- the NetworkManager configuration methods will create a connection named 'RetroPie-WiFi'. This helps identifying the connection during removal, since I didn't find a way to add some …
=> wifi: add NetworkManager support and various tweaks

scriptmodules/supplementary/audiosettings.sh
Since PipeWire is the default sound server in RaspiOS 12 _bookworm_, make sure we account for its presence and we're able to choose a default card ('output sink') or disable/enable it.
At this time, PipeWire is using emulating a PulseAudio session manager through `pipewire-pulse`, while also running the native `wireplumber` session manager. Most of the clients still think they speak to PulseAudio using the PulseAudio client API, while the actual backend is PipeWire.
Changed:
- use `pactl` instead of `pacmd`, since the latter is not working through PipeWire's PulseAudio emulation
- use `pactl` to set the PipeWire defaul output, instead of using the native `pw-cli`
- added a toggle functions for PipeWire and PulseAudio, chosen based on the detected sound server
NOTE: although techically …
=> audiosettings: add PipeWire support

scriptmodules/emulators/ppsspp.sh, scriptmodules/libretrocores/lr-ppsspp.sh
Fixes building on Debian 12 Bookworm for the included `ffmpeg` project.
Changes since 13.x:
* ver 1.14.x (full list of changes - https://www.ppsspp.org/news/release-1.14)
* Graphics fixes in Burnout Dominator, Kurohyou, Ratchet & Clank, Outrun, Ridge Racer, Spongebob: Yellow Avenger, Cars: Race-o-Rama, Hunter x Hunter, many others
* Performance improvements: Killzone now runs at playable speed, Juiced 2 performance fixed, lighting ubershader optimization
* Many software renderer improvements, both performance and accuracy.
* Some input handling fixes, IR interpreter fixes, and so much more.
* MSAA antialiasing added to the Vulkan backend (desktop only)
* New API for plugins to access aspect ratio, scaling and fast-forward ([#16441]), other new APIs & improvements
* UI improvements
- New …
=> ppsspp: upgrade to version 1.16.6

scriptmodules/supplementary/audiosettings.sh
Pi5 has the same 2 mHDMI ports and 2 cards
=> audiosettings: add Pi5 along

scriptmodules/supplementary/skyscraper.sh
Changes for v3.9.0 in the scriptmodule
- new script files to be installed
- new config files (partially replacements)
- move files from install to config folder instead of copying (`/opt/retropie/supplementary/skyscraper` was crowded with files, which Skyscraper even does not read from there)
- some spaces and quotes corrected
Read about the Skyscraper 3.9.0 changes [here](https://github.com/Gemba/skyscraper/blob/dev_reloaded/README_Skyscraper_reloaded.md#tba-version-390).
Once this scriptmodule is merged I will tag the 3.9.0 version of Skyscraper.
=> for v3.9.0 release of Skyscraper

scriptmodules/supplementary/audiosettings.sh
Fixed Pi5 detection by checking for `vc4hdmi` cards when determining if audio is enabled. Since the Pi5 doesn't have the analog audio output (Headphones), the detection thinks there's no audio enabled (since `snd_bcm2835` module is not loaded), but it's wrong.
Also fixed a couple of things:
- the `pactl` listing parsing would enter an infinite loop if no audio was present
- when checking for Pulse/Pipewire use the `.service` instead of the `.socket`, since the socket can be disabled, but the service is always active.
=> audiosettings: fix Pi5 detection

platforms.cfg
Ref:
- pc98: https://github.com/libretro/libretro-core-info/blob/master/np2kai_libretro.info
- x68000: https://github.com/libretro/libretro-core-info/blob/master/px68k_libretro.info
- saturn: https://github.com/libretro/libretro-core-info/blob/master/mednafen_saturn_libretro.info
=> platform: add a few more extensions (PC98, X68k, Saturn)

scriptmodules/supplementary/esthemes.sh
Created 2 new themes for ES to suit 16:9. Called AIGEN and AIGEN_PLUS.
=> Update esthemes.sh 2x new themes

scriptmodules/emulators/mupen64plus/mupen64plus.sh
Since recent kernels don't have the BCM string in `/proc/cpuinfo`, update the Raspberry Pi detection to use the device tree.
Other updates:
* simplifed the selection of the OMX output plugin and port number. Applies only to Pi models 0-4, since Pi5 cannot use OMX
* disabled pre-setting the 'pulse' SDL audio driver for non-OMX/ALSA devices. SDL will try 'pulseaudio' ('pulse' is the SDL 1.2 name) then 'alsa' in this order, so there's no need to force it to 'pulseaudio'. Starting with 2.0.22, SDL supports a list of drivers in the AUDIODEVICE hint, but Buster based systems are not there yet.
=> mupen64plus: modify launch script for RPI detection

scriptmodules/emulators/px68k.sh
The original repository has long been abandoned, but several forks are still active. The (most ?) active one has added support for SDL2 (Renderer, Audio, GameController API) and MIDI (Fluidsynth) among other things and it even has some SDL3 support in the works. [1]
This commit switches the source of the emulator to [1] and adjusts the dependencies, build instructions and files included. When building with Fluidsynth, install a minimal soundfont. Generate a minimal configuration when none is found, setting up the ROM/Disk start folder and the menu language.
[1] https://github.com/TurtleBazooka/px68k, based on https://github.com/kenyahiro/px68k, original repository at https://github.com/hissorii/px68k.
Notable changes in this fork.
* Utilizes SDL2 Renderer (GPU), so "sdl-gfx" is …
=> px68: change upstream project, use SDL2

scriptmodules/supplementary/skyscraper.sh
I just released Skyscraper 3.10.0 which contains a bash completion file. 
This change deploys the completion file during installation.
=> Deployment of Skyscraper 3.10.0 bash completion file.

scriptmodules/ports/dsda-doom.sh
Forgot to add a few dependencies needed to build the port.
=> dsda-doom: fix some dependencies

scriptmodules/supplementary/skyscraper.sh
cf. https://retropie.org.uk/forum/post/295194
Also the fn remove_skyscraper() was present two times. Merged them together and added a prompt if skyscraper's cache should also be cleared.
=> Put programmable completion file to /etc/bash_comletion.d/

scriptmodules/libretrocores/lr-mame.sh, scriptmodules/libretrocores/lr-mess.sh
Added a bit more swap in order to be able to finish the compilation for both cores.
=> lr-mame/mess: bump memory requirements

scriptmodules/supplementary/skyscraper.sh
As mentioned here: https://github.com/RetroPie/RetroPie-Setup/pull/3875#issuecomment-1989100380
=> Replace dialog with info message for headless operation

platforms.cfg
Adding m3u format support for disc swapping in Dolphin
=> Add m3u to Gamecube and Wii

scriptmodules/supplementary/bluetooth.sh
Due to changes in BlueZ added to fix CVE-2023-45866, the PS3 controllers won't pair/work anymore with BlueZ. Since the path consist in only one change to default option (ClassicBondedOnly default changed, see [1]), it's been quickly added by all distros [2], [3]. This has already been reported in the forums and fixed (for Buster) by downgrading the `bluez` package. The same fix cannot be applied to current distros, so we can switch back the option to the way it works with PS3 controllers.
NOTE:
* while technically this makes BlueZ vulnerable to CVE-2023-45866, the exploit mentioned works IIF BlueZ is set to 'discoverable' mode. However, this mode is set only during discoveries, which in RetroPie means just the pairing dialog - I think the risk for a real break-in through the vulnerability …
=> bluetooth: fix PS3 pairing with recent BlueZ

platforms.cfg
* Amstrad: add more supported extensions
* Daphne: enable the OGV format supported by DirkSimple
=> platform: updates for amdstrad and daphne

scriptmodules/libretrocores/lr-picodrive.sh, scriptmodules/libretrocores/lr-snes9x.sh
Errors introduced in #3902 (oops!)
=> Move nodistcc flag out of module sections

scriptmodules/supplementary/steamcontroller.sh
* stop the SCC daemon when disabling the service
* fix typo for the here-doc label used in the udev rule file
=> steamcontroller: minor fixes

scriptmodules/supplementary/audiosettings.sh
Fixes:
- settings the default sink (audio output) with `pactl` doesn't work like `pacmd`. The index of the sink is ignored and it's sink's `object.id` that's accepted by `pactl set-default-sink <id>`. As such, previous version didn't correctly set the audio output for Pipewire/Pulseaudio so a separate hash map was added to translate from `index` to the `object.id` of the sink.
- running `alsamixer` doesn't work correctly as `root` when Pipewire/Wireplumber are started as user services. Thus, run it as the install user in the Pulseaudio context
Tweaks:
- use `card.name` for the name of the card when listed in the dialog. This makes the name of the HDMI outputs nicer, instead of using the `alsa.name` property which outputs `MAI PCM i2s-hifi-0` as the card name (not very user friendly). With …
=> audiosettings: improve Pipewire control

scriptmodules/emulators/amiberry.sh
Added a couple of changes to accomodate the upstream additions:
- externally loaded dynamic libraries are now loaded from `$md_inst/plugins`. Include both the CAPSImg / FloppyBridge libraries on installation.
- extra paths from which various media (floppies/LHA archives/disk or cdrom images) are now set to the `amiga` rom folder. They're useful when loading things from the Amiberry GUI, otherwise launching media from EmulationStation doesn't need these settings.
Also, don't apply the makefile patch on the x86 (preview) branch and fixed the tag name on the `preview` branch.
This is a follow-up on the things discussed during #3938.
=> amiberry: update build/configuration

scriptmodules/libretrocores/lr-stella.sh
=> lr-stella - lock to commit fd35ce62 for GCC 10

scriptmodules/emulators/dosbox-staging.sh, scriptmodules/libretrocores/lr-hatari.sh
dosbox-staging - fix removal comparison (should be $md_mode not $md_id)
lr-hatari - skip iniSetting on removal
=> dosbox-staging / lr-hatari - cleanup module removal

scriptmodules/supplementary/usbromservice.sh, scriptmodules/supplementary/usbromservice/01_retropie_copyroms, scriptmodules/supplementary/usbromservice/10_retropie_mount
=> usbromservice - Add group to usbmount scripts

scriptmodules/emulators/scummvm-sdl1.sh, scriptmodules/emulators/scummvm.sh
New release ScummVM 2.9.0 - "Close Encounters of the 2.9th Kind". Full changelog - https://downloads.scummvm.org/frs/scummvm/2.9.0/ReleaseNotes.html, below some highlights from the new release:
New games:
* The Adventures of the Good Soldier Schweik
* Backyard Basketball
* Castle Master
* Marvellous Mice Adventures: Meeting Sea Rat
* Marvellous Mice Adventures: Sea Rat's Birthday
* Mask Show
* Moonbase Commander
* Orion Burger
* Rise of the Dragon
* The Space Bar
* Thimbleweed Park (requires a platform that supports OpenGL with Shaders)
* Total Eclipse
* Total Eclipse 2
* Unrest
* Wait for it! Issue 3. Song for a Hare
Platform updates:
* The AGS engine has been brought up to version 3.6.1.30 from upstream
* Keymapper support was added to more than 20 engines, allowing customization of the …
=> scummvm: upgrade to version 2.9

scriptmodules/ports/vvvvvv.sh
Similar to Cave Story, add a check if data.zip exists in ~/RetroPie/roms/ports/vvvvvv/ if it doesn't display a warning message and exit
=> Add a missing file warning to vvvvvv.sh

scriptmodules/supplementary/skyscraper.sh
The changes are for the new GameBase scraper support.
=> Dependency and file update for Skyscraper 3.16

scriptmodules/emulators/supermodel3.sh
Fixed: https://github.com/RetroPie/RetroPie-Setup/pull/4049
Thanks.
=> Full Fat Supermodel no longer distributes Supermodel.ini #2

scriptmodules/emulators/supermodel3.sh
=> Update supermodel3.sh - More haste, less speed

platforms.cfg
Seems HDF/HDZ are supported by P-UAE and Amiberry.
=> platforms: more amiga extensions

scriptmodules/admin/joy2key/joy2key_sdl.py
Reverts RetroPie/RetroPie-Setup#4059
Seems there's an issue with older SDLs.
=> Revert "joy2key: match config by Product/Vendor IDs"

scriptmodules/emulators/hypseus.sh, scriptmodules/emulators/hypseus/hypinput.ini, scriptmodules/emulators/hypseus/hypinput_gamepad.ini
This will be a new location for Gamepad config `.ini` in next release, but can be safely added now in preparation.
=> Hypseus: New gamepad config ini location for next release.

scriptmodules/supplementary/skyscraper.sh
and a brief README for the helper scripts.
=> Changes to select Qt6/Qt5 depending on distro

COPYRIGHT.md
Greetings,
I came across something in `COPYRIGHT.md` while I was looking over the code base to familiarize myself with the structure of the project and the coding style, so I went ahead and fixed it:
* I assume we would want the copyright year updated to the present date
* I also added a bit more Markdown formatting to the file
=> Updated copyright year, added formatting

scriptmodules/emulators/scummvm-sdl1.sh, scriptmodules/emulators/scummvm.sh
It's mostly a maintenance release, but some new features:
* AGI:
- Added support for early version of Christmas Card 1986 with advertisements for Tandy hardware.
* AGS:
- Added official support for Old Skies and Rosewater
Full changelog - https://downloads.scummvm.org/frs/scummvm/2.9.1/ReleaseNotes.html
=> scummvm: update to 2.9.1

scriptmodules/emulators/hypseus.sh
Possibly time this moved out of "experimental" now?
=> Move Hypseus from exp to opt group
